In [2]:
import pandas as pd
import numpy as np
import pandas_gbq
import time
import itertools
import datetime
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import requests
import json
import plotly.graph_objects as go
project_id = "perceptive-ivy-290216"

In [3]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp1_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp1 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [3]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp2_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp2 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [4]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp3_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp3 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [4]:
race="Chinese Grand Prix"

In [5]:
# FP1

In [6]:
df_bq_fp1=df_bq2_fp1[(df_bq2_fp1["GP"]==race)&(df_bq2_fp1["Year"]==2025)]
GP_fp1=df_bq_fp1
GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)
GP_fp1=GP_fp1.sort_values(['Driver','LapNumber'])
GP_fp1["DriverNumber"]=GP_fp1["DriverNumber"].astype(int)
year=GP_fp1['Year'].iloc[0]
gp=GP_fp1['GP'].iloc[0]
GP_fp1.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_12559/1916111373.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
24655,0 days 00:18:13.266000,ALB,23,NaT,1,1.0,0 days 00:15:51.342000,NaT,NaT,0 days 00:00:34.226000,0 days 00:01:04.214000,NaT,0 days 00:17:09.177000,0 days 00:18:13.398000,266.0,258.0,255.0,276.0,False,MEDIUM,1.0,True,Williams,0 days 00:15:51.342000,2025-03-21 03:31:23.690,1,NaN,False,,False,False,2025,Chinese Grand Prix
24656,0 days 00:20:23.046000,ALB,23,0 days 00:02:09.780000,2,1.0,NaT,NaT,0 days 00:00:36.435000,0 days 00:00:41.893000,0 days 00:00:51.452000,0 days 00:18:49.701000,0 days 00:19:31.594000,0 days 00:20:23.046000,157.0,248.0,257.0,307.0,True,MEDIUM,2.0,True,Williams,0 days 00:18:13.266000,2025-03-21 03:33:45.614,1,NaN,False,,False,True,2025,Chinese Grand Prix
24657,0 days 00:21:58.876000,ALB,23,0 days 00:01:35.830000,3,1.0,NaT,NaT,0 days 00:00:25.500000,0 days 00:00:28.867000,0 days 00:00:41.463000,0 days 00:20:48.546000,0 days 00:21:17.413000,0 days 00:21:58.876000,274.0,269.0,266.0,325.0,True,MEDIUM,3.0,True,Williams,0 days 00:20:23.046000,2025-03-21 03:35:55.394,1,NaN,False,,False,True,2025,Chinese Grand Prix
24658,0 days 00:24:20.806000,ALB,23,0 days 00:02:21.930000,4,1.0,NaT,NaT,0 days 00:00:37.567000,0 days 00:00:44.439000,0 days 00:00:59.924000,0 days 00:22:36.443000,0 days 00:23:20.882000,0 days 00:24:20.806000,158.0,242.0,263.0,171.0,False,MEDIUM,4.0,True,Williams,0 days 00:21:58.876000,2025-03-21 03:37:31.224,1,NaN,False,,False,True,2025,Chinese Grand Prix
24659,0 days 00:25:55.409000,ALB,23,0 days 00:01:34.603000,5,1.0,NaT,NaT,0 days 00:00:25.119000,0 days 00:00:28.789000,0 days 00:00:40.695000,0 days 00:24:45.925000,0 days 00:25:14.714000,0 days 00:25:55.409000,271.0,265.0,268.0,332.0,True,MEDIUM,5.0,True,Williams,0 days 00:24:20.806000,2025-03-21 03:39:53.154,1,NaN,False,,False,True,2025,Chinese Grand Prix

In [7]:
#Assign Rank for each entry point
GP_fp1["RK"] = GP_fp1["LapTime"].rank(method="dense", ascending=True)
GP_fp1["RK"]= GP_fp1["RK"].astype(int)

In [ ]:
pole_lap = GP_fp1["LapTime"].min()
GP_fp1['LapTimeDelta']= pd.to_timedelta(GP_fp1["LapTime"]) - pd.to_timedelta(pole_lap)

GP_fp1["GAP"]=GP_fp1['LapTimeDelta']
GP_fp1.loc[:, "GAP (s)"] = GP_fp1["GAP"].dt.total_seconds()

GP_fp1['LapTimeDelta']=GP_fp1['LapTimeDelta'].astype(str)

for index, row in GP_fp1.iterrows():
  if GP_fp1.loc[index, 'LapTimeDelta']=='0 days 00:00:00':
    GP_fp1.loc[index, 'LapTimeDelta']='0 days 00:00:00.01'
GP_fp1['LapTimeDelta']=pd.to_timedelta(GP_fp1['LapTimeDelta'])


GP_fp1['LapTimeDelta'] = GP_fp1['LapTimeDelta'] + pd.to_datetime('1970/01/01')

GP_fp1['LapTimeDelta2']= pd.to_timedelta(GP_fp1["LapTime"]) - pd.to_timedelta(pole_lap)
GP_fp1['LapTimeDelta2']=GP_fp1['LapTimeDelta2'].astype(str)

GP_fp1["LapTimeDelta2"]=GP_fp1['LapTimeDelta2'].str.split('days ').str[1]

GP_fp1["LapTime"]=GP_fp1['LapTime'].str.split('days ').str[1]

GP_fp1=GP_fp1.fillna(0)
GP_fp1.head(10)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,RK,LapTimeDelta,GAP,GAP (s),LapTimeDelta2
24655,0 days 00:18:13.266000,ALB,23,0,1,1.0,0 days 00:15:51.342000,NaT,NaT,0 days 00:00:34.226000,0 days 00:01:04.214000,NaT,0 days 00:17:09.177000,0 days 00:18:13.398000,266.0,258.0,255.0,276.0,False,MEDIUM,1.0,True,Williams,0 days 00:15:51.342000,2025-03-21 03:31:23.690,1,0.0,False,,False,False,2025,Chinese Grand Prix,334,0,0,0.000,0
24656,0 days 00:20:23.046000,ALB,23,00:02:09.780000,2,1.0,NaT,NaT,0 days 00:00:36.435000,0 days 00:00:41.893000,0 days 00:00:51.452000,0 days 00:18:49.701000,0 days 00:19:31.594000,0 days 00:20:23.046000,157.0,248.0,257.0,307.0,True,MEDIUM,2.0,True,Williams,0 days 00:18:13.266000,2025-03-21 03:33:45.614,1,0.0,False,,False,True,2025,Chinese Grand Prix,270,1970-01-01 00:00:38.276000,0 days 00:00:38.276000,38.276,00:00:38.276000
24657,0 days 00:21:58.876000,ALB,23,00:01:35.830000,3,1.0,NaT,NaT,0 days 00:00:25.500000,0 days 00:00:28.867000,0 days 00:00:41.463000,0 days 00:20:48.546000,0 days 00:21:17.413000,0 days 00:21:58.876000,274.0,269.0,266.0,325.0,True,MEDIUM,3.0,True,Williams,0 days 00:20:23.046000,2025-03-21 03:35:55.394,1,0.0,False,,False,True,2025,Chinese Grand Prix,96,1970-01-01 00:00:04.326000,0 days 00:00:04.326000,4.326,00:00:04.326000
24658,0 days 00:24:20.806000,ALB,23,00:02:21.930000,4,1.0,NaT,NaT,0 days 00:00:37.567000,0 days 00:00:44.439000,0 days 00:00:59.924000,0 days 00:22:36.443000,0 days 00:23:20.882000,0 days 00:24:20.806000,158.0,242.0,263.0,171.0,False,MEDIUM,4.0,True,Williams,0 days 00:21:58.876000,2025-03-21 03:37:31.224,1,0.0,False,,False,True,2025,Chinese Grand Prix,301,1970-01-01 00:00:50.426000,0 days 00:00:50.426000,50.426,00:00:50.426000
24659,0 days 00:25:55.409000,ALB,23,00:01:34.603000,5,1.0,NaT,NaT,0 days 00:00:25.119000,0 days 00:00:28.789000,0 days 00:00:40.695000,0 days 00:24:45.925000,0 days 00:25:14.714000,0 days 00:25:55.409000,271.0,265.0,268.0,332.0,True,MEDIUM,5.0,True,Williams,0 days 00:24:20.806000,2025-03-21 03:39:53.154,1,0.0,False,,False,True,2025,Chinese Grand Prix,68,1970-01-01 00:00:03.099000,0 days 00:00:03.099000,3.099,00:00:03.099000

In [ ]:
GP_fp1=GP_fp1.sort_values(by='RK')
GP_fp1["Driver_Lap"]=GP_fp1["Driver"].astype(str)+ " " +"(Lap "+GP_fp1["LapNumber"].astype(str)+")"
GP_fp1=GP_fp1.head(10)

In [13]:
fig=px.bar(
    GP_fp1,
    y="Driver_Lap",
    x='LapTimeDelta',
    text='LapTimeDelta2',
    orientation='h',
    color='Driver',
    category_orders={'Category': GP_fp1['LapTime'].unique()},
    template="presentation",
    hover_data=['Team', 'Year', 'GP','LapTime', 'LapNumber','Sector1Time', 'Sector2Time', 'Sector3Time',
       'Compound', 'TyreLife', 'FreshTyre'],
    title="<b>FP1 Fastest Laps for the {} {}</b>".format(year,gp),
    height=800, 
    width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
                 }
)
fig.update_layout(
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),

    xaxis_title="<b>Delta</b>",
    yaxis_title="<b></b>",
    title_font_family="<b>PT Sans Narrow</b>",

)

fig.update_layout(xaxis_tickformat='%H:%M:%S.%f')

fig.update_traces(marker_line_width=1,marker_line_color="BLACK")

fig.update_layout(yaxis={'categoryorder':'total descending'})

fig.update_traces(textposition='auto')

for x,y,z in zip(GP_fp1.LapTimeDelta2, GP_fp1.Team, GP_fp1.Driver_Lap):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==y:
      image=str(png)
      fig.add_layout_image(
          x=x,
          y=z,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=2.5,
          sizey=2.5,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=18,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=100, r=5, t=50, b=60),
)

fig.update_layout(showlegend=False)

fig.show()

In [16]:
save_year=2025

In [17]:
fig_fp1.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP1/{}/{} {} FP1 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [35]:
# FP2

In [36]:
df_bq_fp2=df_bq2_fp2[(df_bq2_fp2["GP"]==race)&(df_bq2_fp2["Year"]==2025)]
GP_fp2=df_bq_fp2
GP_fp2["LapNumber"]=GP_fp2["LapNumber"].astype(int)
GP_fp2=GP_fp2.sort_values(['Driver','LapNumber'])
GP_fp2["DriverNumber"]=GP_fp2["DriverNumber"].astype(int)
year=GP_fp2['Year'].iloc[0]
gp=GP_fp2['GP'].iloc[0]
GP_fp2.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_73022/2277067741.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
10753,0 days 00:21:05.266000,ALB,23,0 days 00:01:54.309000,1,1.0,0 days 00:19:12.922000,NaT,0 days 00:00:40.034000,0 days 00:00:19.262000,0 days 00:00:55.013000,0 days 00:19:51.166000,0 days 00:20:10.479000,0 days 00:21:05.381000,270.0,296.0,302.0,186.0,False,MEDIUM,1.0,True,Williams,0 days 00:19:12.922000,2025-03-14 05:04:13.372,1,NaN,False,,False,False,2025,Australian Grand Prix
10754,0 days 00:22:24.505000,ALB,23,0 days 00:01:19.239000,2,1.0,NaT,NaT,0 days 00:00:27.539000,0 days 00:00:17.954000,0 days 00:00:33.746000,0 days 00:21:32.805000,0 days 00:21:50.759000,0 days 00:22:24.505000,282.0,315.0,305.0,320.0,True,MEDIUM,2.0,True,Williams,0 days 00:21:05.266000,2025-03-14 05:06:05.716,1,NaN,False,,False,True,2025,Australian Grand Prix
10755,0 days 00:24:27.534000,ALB,23,0 days 00:02:03.029000,3,1.0,NaT,NaT,0 days 00:00:41.429000,0 days 00:00:32.258000,0 days 00:00:49.342000,0 days 00:23:05.934000,0 days 00:23:38.192000,0 days 00:24:27.534000,163.0,177.0,305.0,241.0,False,MEDIUM,3.0,True,Williams,0 days 00:22:24.505000,2025-03-14 05:07:24.955,1,NaN,False,,False,True,2025,Australian Grand Prix
10756,0 days 00:25:45.182000,ALB,23,0 days 00:01:17.648000,4,1.0,NaT,NaT,0 days 00:00:26.974000,0 days 00:00:17.524000,0 days 00:00:33.150000,0 days 00:24:54.508000,0 days 00:25:12.032000,0 days 00:25:45.182000,287.0,319.0,307.0,323.0,True,MEDIUM,4.0,True,Williams,0 days 00:24:27.534000,2025-03-14 05:09:27.984,1,NaN,False,,False,True,2025,Australian Grand Prix
10757,0 days 00:27:57.255000,ALB,23,0 days 00:02:12.073000,5,1.0,NaT,NaT,0 days 00:00:46.633000,0 days 00:00:30.085000,0 days 00:00:55.355000,0 days 00:26:31.815000,0 days 00:27:01.900000,0 days 00:27:57.255000,186.0,182.0,272.0,266.0,False,MEDIUM,5.0,True,Williams,0 days 00:25:45.182000,2025-03-14 05:10:45.632,1,NaN,False,,False,True,2025,Australian Grand Prix

In [37]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp2['LapTime_TD']= pd.to_timedelta(GP_fp2["LapTime"])
GP_fp2["LapTime"]=GP_fp2['LapTime'].str.split('days ').str[1]
GP_fp2.loc[:, "LapTime (s)"] = GP_fp2["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [38]:
GP_fp2['s1_TD']= pd.to_timedelta(GP_fp2["Sector1Time"])
GP_fp2['s2_TD']= pd.to_timedelta(GP_fp2["Sector2Time"])
GP_fp2['s3_TD']= pd.to_timedelta(GP_fp2["Sector3Time"])

GP_fp2.loc[:, "Time S1 (s)"] = GP_fp2["s1_TD"].dt.total_seconds()
GP_fp2.loc[:, "Time S2 (s)"] = GP_fp2["s2_TD"].dt.total_seconds()
GP_fp2.loc[:, "Time S3 (s)"] = GP_fp2["s3_TD"].dt.total_seconds()

In [39]:
GP_fp2_Rk=GP_fp2[GP_fp2["LapTime"]!="NaT"]
GP_fp2_Rk["LAP_RK"] = GP_fp2_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S1_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S2_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S3_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["Race_RK"] = GP_fp2_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [40]:
GP_fp2_Sectors=GP_fp2_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp2_Sectors=GP_fp2_Sectors.fillna(0)
GP_fp2_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
10606,ANT,1,0.000,21.174,49.540,0,0.000,HARD,2025,Australian Grand Prix,0.0,0.0,16.0,13.0
10897,SAI,1,39.711,19.647,38.860,00:01:38.218000,98.218,MEDIUM,2025,Australian Grand Prix,1.0,1.0,8.0,1.0
10753,ALB,1,40.034,19.262,55.013,00:01:54.309000,114.309,MEDIUM,2025,Australian Grand Prix,7.0,2.0,4.0,17.0
10487,BOR,1,40.102,20.391,43.857,00:01:44.350000,104.350,MEDIUM,2025,Australian Grand Prix,3.0,3.0,12.0,8.0
10576,GAS,1,40.370,19.329,42.532,00:01:42.231000,102.231,MEDIUM,2025,Australian Grand Prix,2.0,4.0,6.0,5.0

In [41]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp2=GP_fp2_Sectors[GP_fp2_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp2.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp2.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp2.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp2.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp2=Fastest_Lap_fp2.merge(Fastest_sector1_fp2,on=['LapNumber']).merge(Fastest_sector2_fp2,on=['LapNumber']).merge(Fastest_sector3_fp2,on=['LapNumber'])
Fast_Laps_fp2=Fast_Laps_fp2[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp2=Fast_Laps_fp2.reset_index(drop=True)
Fast_Laps_fp2.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Australian Grand Prix,2025,1,00:01:38.218000,98.218,SAI,MEDIUM,39.711,SAI,MEDIUM,18.598,RUS,HARD,38.860,SAI,MEDIUM
1,Australian Grand Prix,2025,2,00:01:17.671000,77.671,NOR,MEDIUM,27.033,TSU,MEDIUM,17.548,GAS,MEDIUM,32.925,NOR,MEDIUM
2,Australian Grand Prix,2025,3,00:01:18.846000,78.846,HUL,MEDIUM,27.249,HUL,MEDIUM,17.956,HUL,MEDIUM,33.641,HUL,MEDIUM
3,Australian Grand Prix,2025,4,00:01:17.302000,77.302,SAI,MEDIUM,26.792,SAI,MEDIUM,17.479,GAS,MEDIUM,32.952,SAI,MEDIUM
4,Australian Grand Prix,2025,5,00:01:17.650000,77.650,TSU,MEDIUM,26.864,TSU,MEDIUM,17.695,TSU,MEDIUM,33.091,TSU,MEDIUM

In [42]:
Fast_Laps_fp2['color'] = Fast_Laps_fp2['Fastest Lap'].apply(driver_color)
Fast_Laps_fp2.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Australian Grand Prix,2025,1,00:01:38.218000,98.218,SAI,MEDIUM,39.711,SAI,MEDIUM,18.598,RUS,HARD,38.860,SAI,MEDIUM,#64C4FF
1,Australian Grand Prix,2025,2,00:01:17.671000,77.671,NOR,MEDIUM,27.033,TSU,MEDIUM,17.548,GAS,MEDIUM,32.925,NOR,MEDIUM,#FF8000
2,Australian Grand Prix,2025,3,00:01:18.846000,78.846,HUL,MEDIUM,27.249,HUL,MEDIUM,17.956,HUL,MEDIUM,33.641,HUL,MEDIUM,#52e252
3,Australian Grand Prix,2025,4,00:01:17.302000,77.302,SAI,MEDIUM,26.792,SAI,MEDIUM,17.479,GAS,MEDIUM,32.952,SAI,MEDIUM,#64C4FF
4,Australian Grand Prix,2025,5,00:01:17.650000,77.650,TSU,MEDIUM,26.864,TSU,MEDIUM,17.695,TSU,MEDIUM,33.091,TSU,MEDIUM,#6692FF

In [43]:
LapTime_fp2_ordered=Fast_Laps_fp2.sort_values(by=['LapTime (s)'])
LapTime_fp2_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
14,Australian Grand Prix,2025,15,00:01:16.439000,76.439,LEC,SOFT,26.477,LEC,SOFT,17.392,LEC,SOFT,32.567,PIA,SOFT,#E80020
11,Australian Grand Prix,2025,12,00:01:16.580000,76.580,NOR,SOFT,26.494,LEC,SOFT,17.399,NOR,SOFT,32.674,NOR,SOFT,#FF8000
7,Australian Grand Prix,2025,8,00:01:16.784000,76.784,TSU,SOFT,26.460,TSU,SOFT,17.315,DOO,MEDIUM,32.825,TSU,SOFT,#6692FF
8,Australian Grand Prix,2025,9,00:01:16.794000,76.794,LEC,MEDIUM,26.648,LEC,MEDIUM,17.492,LEC,MEDIUM,32.654,LEC,MEDIUM,#E80020
13,Australian Grand Prix,2025,14,00:01:16.859000,76.859,HAM,SOFT,26.528,HAM,SOFT,17.359,DOO,SOFT,32.724,HAM,SOFT,#E80020

In [44]:
import plotly.graph_objects as go
# colors = n_colors('rgb(255, 200, 200)', 'rgb(200, 0, 0)', 9, colortype='rgb')

fig_fp2 = go.Figure(go.Table
 (header={"values": LapTime_fp2_ordered.columns},
  cells=dict(
    values=LapTime_fp2_ordered.T.values,
    fill_color=[LapTime_fp2_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp2.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp2_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp2_ordered.loc[LapTime_fp2_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp2_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp2.update_layout(
    title="FP2 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp2.show()

In [45]:
fig_fp2.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP2/{}/{} {} FP2 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [18]:
# FP3

In [19]:
df_bq_fp3=df_bq2_fp3[(df_bq2_fp3["GP"]==race)&(df_bq2_fp3["Year"]==2025)]
GP_fp3=df_bq_fp3
GP_fp3["LapNumber"]=GP_fp3["LapNumber"].astype(int)
GP_fp3=GP_fp3.sort_values(['Driver','LapNumber'])
GP_fp3["DriverNumber"]=GP_fp3["DriverNumber"].astype(int)
year=GP_fp3['Year'].iloc[0]
gp=GP_fp3['GP'].iloc[0]
GP_fp3.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7879/2774860751.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
15252,0 days 00:32:33.265000,ALB,23,0 days 00:01:42.922000,1,1.0,0 days 00:30:52.377000,NaT,0 days 00:00:38.723000,0 days 00:00:20.954000,0 days 00:00:43.245000,0 days 00:31:29.313000,0 days 00:31:50.318000,0 days 00:32:33.413000,274.0,158.0,303.0,204.0,False,HARD,1.0,True,Williams,0 days 00:30:52.377000,2025-03-15 01:49:58.888,1,NaN,False,,False,False,2025,Australian Grand Prix
15253,0 days 00:33:51.872000,ALB,23,0 days 00:01:18.607000,2,1.0,NaT,NaT,0 days 00:00:27.513000,0 days 00:00:17.698000,0 days 00:00:33.396000,0 days 00:33:00.778000,0 days 00:33:18.476000,0 days 00:33:51.872000,283.0,319.0,303.0,322.0,True,HARD,2.0,True,Williams,0 days 00:32:33.265000,2025-03-15 01:51:39.776,1,NaN,False,,False,True,2025,Australian Grand Prix
15254,0 days 00:35:55.985000,ALB,23,0 days 00:02:04.113000,3,1.0,NaT,NaT,0 days 00:00:45.965000,0 days 00:00:25.396000,0 days 00:00:52.752000,0 days 00:34:37.837000,0 days 00:35:03.233000,0 days 00:35:55.985000,172.0,223.0,306.0,217.0,False,HARD,3.0,True,Williams,0 days 00:33:51.872000,2025-03-15 01:52:58.383,1,NaN,False,,False,True,2025,Australian Grand Prix
15255,0 days 00:37:13.966000,ALB,23,0 days 00:01:17.981000,4,1.0,NaT,NaT,0 days 00:00:26.995000,0 days 00:00:17.447000,0 days 00:00:33.539000,0 days 00:36:22.980000,0 days 00:36:40.427000,0 days 00:37:13.966000,285.0,323.0,302.0,325.0,True,HARD,4.0,True,Williams,0 days 00:35:55.985000,2025-03-15 01:55:02.496,1,NaN,False,,False,True,2025,Australian Grand Prix
15256,0 days 00:39:28.660000,ALB,23,0 days 00:02:14.694000,5,1.0,NaT,0 days 00:39:08.220000,0 days 00:00:41.786000,0 days 00:00:24.084000,0 days 00:01:08.824000,0 days 00:37:55.752000,0 days 00:38:19.836000,0 days 00:39:28.660000,166.0,216.0,NaN,238.0,False,HARD,5.0,True,Williams,0 days 00:37:13.966000,2025-03-15 01:56:20.477,1,NaN,False,,False,False,2025,Australian Grand Prix

In [20]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp3['LapTime_TD']= pd.to_timedelta(GP_fp3["LapTime"])
GP_fp3["LapTime"]=GP_fp3['LapTime'].str.split('days ').str[1]
GP_fp3.loc[:, "LapTime (s)"] = GP_fp3["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [21]:
GP_fp3['s1_TD']= pd.to_timedelta(GP_fp3["Sector1Time"])
GP_fp3['s2_TD']= pd.to_timedelta(GP_fp3["Sector2Time"])
GP_fp3['s3_TD']= pd.to_timedelta(GP_fp3["Sector3Time"])

GP_fp3.loc[:, "Time S1 (s)"] = GP_fp3["s1_TD"].dt.total_seconds()
GP_fp3.loc[:, "Time S2 (s)"] = GP_fp3["s2_TD"].dt.total_seconds()
GP_fp3.loc[:, "Time S3 (s)"] = GP_fp3["s3_TD"].dt.total_seconds()

In [22]:
GP_fp3_Rk=GP_fp3[GP_fp3["LapTime"]!="NaT"]
GP_fp3_Rk["LAP_RK"] = GP_fp3_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S1_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S2_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S3_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["Race_RK"] = GP_fp3_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [23]:
GP_fp3_Sectors=GP_fp3_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp3_Sectors=GP_fp3_Sectors.fillna(0)
GP_fp3_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
15385,BEA,1,0.000,20.958,38.308,0,0.000,MEDIUM,2025,Australian Grand Prix,0.0,0.0,9.0,1.0
15329,SAI,1,36.390,18.788,44.269,00:01:39.447000,99.447,HARD,2025,Australian Grand Prix,3.0,1.0,1.0,8.0
15127,GAS,1,36.784,18.909,43.183,00:01:38.876000,98.876,HARD,2025,Australian Grand Prix,2.0,2.0,2.0,6.0
15035,VER,1,37.991,19.905,40.142,00:01:38.038000,98.038,SOFT,2025,Australian Grand Prix,1.0,3.0,5.0,3.0
15252,ALB,1,38.723,20.954,43.245,00:01:42.922000,102.922,HARD,2025,Australian Grand Prix,4.0,4.0,8.0,7.0

In [24]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp3=GP_fp3_Sectors[GP_fp3_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp3.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp3.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp3.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp3.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp3=Fastest_Lap_fp3.merge(Fastest_sector1_fp3,on=['LapNumber']).merge(Fastest_sector2_fp3,on=['LapNumber']).merge(Fastest_sector3_fp3,on=['LapNumber'])
Fast_Laps_fp3=Fast_Laps_fp3[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp3=Fast_Laps_fp3.reset_index(drop=True)
Fast_Laps_fp3.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Australian Grand Prix,2025,1,00:01:38.038000,98.038,VER,SOFT,36.390,SAI,HARD,18.788,SAI,HARD,38.308,BEA,MEDIUM
1,Australian Grand Prix,2025,2,00:01:17.242000,77.242,RUS,SOFT,26.767,RUS,SOFT,17.521,VER,SOFT,32.868,RUS,SOFT
2,Australian Grand Prix,2025,3,00:01:17.298000,77.298,PIA,SOFT,26.971,PIA,SOFT,17.515,PIA,SOFT,32.812,PIA,SOFT
3,Australian Grand Prix,2025,4,00:01:17.981000,77.981,ALB,HARD,26.995,ALB,HARD,17.447,ALB,HARD,33.314,SAI,HARD
4,Australian Grand Prix,2025,5,00:01:16.646000,76.646,VER,SOFT,26.616,HUL,SOFT,17.161,VER,SOFT,32.678,ANT,SOFT

In [25]:
Fast_Laps_fp3['color'] = Fast_Laps_fp3['Fastest Lap'].apply(driver_color)
Fast_Laps_fp3.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Australian Grand Prix,2025,1,00:01:38.038000,98.038,VER,SOFT,36.390,SAI,HARD,18.788,SAI,HARD,38.308,BEA,MEDIUM,#3860C6
1,Australian Grand Prix,2025,2,00:01:17.242000,77.242,RUS,SOFT,26.767,RUS,SOFT,17.521,VER,SOFT,32.868,RUS,SOFT,#27F4D2
2,Australian Grand Prix,2025,3,00:01:17.298000,77.298,PIA,SOFT,26.971,PIA,SOFT,17.515,PIA,SOFT,32.812,PIA,SOFT,#FF8000
3,Australian Grand Prix,2025,4,00:01:17.981000,77.981,ALB,HARD,26.995,ALB,HARD,17.447,ALB,HARD,33.314,SAI,HARD,#64C4FF
4,Australian Grand Prix,2025,5,00:01:16.646000,76.646,VER,SOFT,26.616,HUL,SOFT,17.161,VER,SOFT,32.678,ANT,SOFT,#3860C6

In [26]:
LapTime_fp3_ordered=Fast_Laps_fp3.sort_values(by=['LapTime (s)'])
LapTime_fp3_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
11,Australian Grand Prix,2025,12,00:01:15.921000,75.921,PIA,SOFT,26.398,VER,SOFT,17.110,VER,SOFT,32.296,PIA,SOFT,#FF8000
12,Australian Grand Prix,2025,13,00:01:15.960000,75.960,RUS,SOFT,26.277,RUS,SOFT,17.150,NOR,SOFT,32.433,ANT,SOFT,#27F4D2
8,Australian Grand Prix,2025,9,00:01:16.077000,76.077,PIA,SOFT,26.358,PIA,SOFT,17.276,PIA,SOFT,32.443,PIA,SOFT,#FF8000
9,Australian Grand Prix,2025,10,00:01:16.173000,76.173,RUS,SOFT,26.355,RUS,SOFT,17.239,DOO,SOFT,32.563,RUS,SOFT,#27F4D2
16,Australian Grand Prix,2025,17,00:01:16.188000,76.188,LEC,SOFT,26.385,LEC,SOFT,17.249,LEC,SOFT,32.554,LEC,SOFT,#E80020

In [27]:
import plotly.graph_objects as go
# colors = n_colors('rgb(255, 200, 200)', 'rgb(200, 0, 0)', 9, colortype='rgb')

fig_fp3 = go.Figure(go.Table
 (header={"values": LapTime_fp3_ordered.columns},
  cells=dict(
    values=LapTime_fp3_ordered.T.values,
    fill_color=[LapTime_fp3_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp3.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp3_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp3_ordered.loc[LapTime_fp3_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp3_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp3.update_layout(
    title="FP3 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp3.show()

In [28]:
fig_fp3.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP3/{}/{} {} FP3 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [40]:
#Multi GP Plot FP1

In [41]:
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    else:
        return '#3860C6'

In [ ]:
save_year_multi=2023

In [42]:
#2024
race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
# 2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2024
for i in race_multi:
    df_bq_fp1=df_bq2_fp1[(df_bq2_fp1["GP"]==i)&(df_bq2_fp1["Year"]==year_multi)]
    GP_fp1=df_bq_fp1
    GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)
    GP_fp1=GP_fp1.sort_values(['Driver','LapNumber'])
    GP_fp1["DriverNumber"]=GP_fp1["DriverNumber"].astype(int)
    # year=GP_fp1['Year'].iloc[0]
    # gp=GP_fp1['GP'].iloc[0]
    GP_fp1['LapTime_TD']= pd.to_timedelta(GP_fp1["LapTime"])
    GP_fp1["LapTime"]=GP_fp1['LapTime'].str.split('days ').str[1]
    GP_fp1.loc[:, "LapTime (s)"] = GP_fp1["LapTime_TD"].dt.total_seconds()
    GP_fp1['s1_TD']= pd.to_timedelta(GP_fp1["Sector1Time"])
    GP_fp1['s2_TD']= pd.to_timedelta(GP_fp1["Sector2Time"])
    GP_fp1['s3_TD']= pd.to_timedelta(GP_fp1["Sector3Time"])

    GP_fp1.loc[:, "Time S1 (s)"] = GP_fp1["s1_TD"].dt.total_seconds()
    GP_fp1.loc[:, "Time S2 (s)"] = GP_fp1["s2_TD"].dt.total_seconds()
    GP_fp1.loc[:, "Time S3 (s)"] = GP_fp1["s3_TD"].dt.total_seconds()
    GP_fp1_Rk=GP_fp1[GP_fp1["LapTime"]!="NaT"]
    GP_fp1_Rk["LAP_RK"] = GP_fp1_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S1_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S2_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S3_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["Race_RK"] = GP_fp1_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)
    GP_fp1_Sectors=GP_fp1_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
    GP_fp1_Sectors=GP_fp1_Sectors.fillna(0)
    Fastest_Lap_fp1=GP_fp1_Sectors[GP_fp1_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_Lap_fp1.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
    Fastest_sector1_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector1_fp1.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
    Fastest_sector2_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector2_fp1.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
    Fastest_sector3_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector3_fp1.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
    Fast_Laps_fp1=Fastest_Lap_fp1.merge(Fastest_sector1_fp1,on=['LapNumber']).merge(Fastest_sector2_fp1,on=['LapNumber']).merge(Fastest_sector3_fp1,on=['LapNumber'])
    Fast_Laps_fp1=Fast_Laps_fp1[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
    Fast_Laps_fp1=Fast_Laps_fp1.reset_index(drop=True)
    Fast_Laps_fp1['color'] = Fast_Laps_fp1['Fastest Lap'].apply(driver_color)
    LapTime_fp1_ordered=Fast_Laps_fp1.sort_values(by=['LapTime (s)'])
    fig_fp1 = go.Figure(go.Table
    (header={"values": LapTime_fp1_ordered.columns},
    cells=dict(
        values=LapTime_fp1_ordered.T.values,
        fill_color=[LapTime_fp1_ordered.color],
        align='center', font=dict(color='white', size=11)
        ))
    )
    fig_fp1.update_layout(
        title="FP1 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi, i),
            title_x=0.5,
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=13,
            color="Black"
        ),
        height=780,
        width=1200,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig_fp1.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP1/{}/{} {} FP1 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi,year_multi, i),include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [43]:
#Multi GP Plot FP2

In [44]:
for i in race_multi:
    try:
        df_bq_fp2=df_bq2_fp2[(df_bq2_fp2["GP"]==i)&(df_bq2_fp2["Year"]==year_multi)]
        GP_fp2=df_bq_fp2
        GP_fp2["LapNumber"]=GP_fp2["LapNumber"].astype(int)
        GP_fp2=GP_fp2.sort_values(['Driver','LapNumber'])
        GP_fp2["DriverNumber"]=GP_fp2["DriverNumber"].astype(int)
        year=GP_fp2['Year'].iloc[0]
        gp=GP_fp2['GP'].iloc[0]
        #Convert LapTime to Time Delta for plotting on Y Axis
        GP_fp2['LapTime_TD']= pd.to_timedelta(GP_fp2["LapTime"])
        GP_fp2["LapTime"]=GP_fp2['LapTime'].str.split('days ').str[1]
        GP_fp2.loc[:, "LapTime (s)"] = GP_fp2["LapTime_TD"].dt.total_seconds()
        # Fastest Driver in each lap
        GP_fp2['s1_TD']= pd.to_timedelta(GP_fp2["Sector1Time"])
        GP_fp2['s2_TD']= pd.to_timedelta(GP_fp2["Sector2Time"])
        GP_fp2['s3_TD']= pd.to_timedelta(GP_fp2["Sector3Time"])

        GP_fp2.loc[:, "Time S1 (s)"] = GP_fp2["s1_TD"].dt.total_seconds()
        GP_fp2.loc[:, "Time S2 (s)"] = GP_fp2["s2_TD"].dt.total_seconds()
        GP_fp2.loc[:, "Time S3 (s)"] = GP_fp2["s3_TD"].dt.total_seconds()
        GP_fp2_Rk=GP_fp2[GP_fp2["LapTime"]!="NaT"]
        GP_fp2_Rk["LAP_RK"] = GP_fp2_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S1_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S2_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S3_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["Race_RK"] = GP_fp2_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

        GP_fp2_Sectors=GP_fp2_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
        GP_fp2_Sectors=GP_fp2_Sectors.fillna(0)
        GP_fp2_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()
        #get a combined view for fastest drivers in the entire lap, S1, S2, and S3
        Fastest_Lap_fp2=GP_fp2_Sectors[GP_fp2_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_Lap_fp2.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
        Fastest_sector1_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector1_fp2.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
        Fastest_sector2_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector2_fp2.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
        Fastest_sector3_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector3_fp2.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
        Fast_Laps_fp2=Fastest_Lap_fp2.merge(Fastest_sector1_fp2,on=['LapNumber']).merge(Fastest_sector2_fp2,on=['LapNumber']).merge(Fastest_sector3_fp2,on=['LapNumber'])
        Fast_Laps_fp2=Fast_Laps_fp2[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
        Fast_Laps_fp2=Fast_Laps_fp2.reset_index(drop=True)
        Fast_Laps_fp2['color'] = Fast_Laps_fp2['Fastest Lap'].apply(driver_color)
        LapTime_fp2_ordered=Fast_Laps_fp2.sort_values(by=['LapTime (s)'])
        fig_fp2 = go.Figure(go.Table
        (header={"values": LapTime_fp2_ordered.columns},
        cells=dict(
            values=LapTime_fp2_ordered.T.values,
            fill_color=[LapTime_fp2_ordered.color],
            align='center', font=dict(color='white', size=11)
            ))
        )
        fig_fp2.update_layout(
            title="FP2 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi,i),
                title_x=0.5,
            yaxis = dict(tickfont = dict(size=15)),
            xaxis = dict(tickfont = dict(size=15)),
            font=dict(
                family="PT Sans Narrow",
                size=13,
                color="Black"
            ),
            height=780,
            width=1200,
            title_font_family="PT Sans Narrow",
            margin=dict(l=5, r=5, t=35, b=5),
        )
        fig_fp2.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP2/{}/{} {} FP2 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi,year_multi,i),include_plotlyjs='cdn')
    except:
        continue

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [45]:
#Multi GP Plot FP3

In [46]:
for i in race_multi:
    try:
        df_bq_fp3=df_bq2_fp3[(df_bq2_fp3["GP"]==i)&(df_bq2_fp3["Year"]==year_multi)]
        GP_fp3=df_bq_fp3
        GP_fp3["LapNumber"]=GP_fp3["LapNumber"].astype(int)
        GP_fp3=GP_fp3.sort_values(['Driver','LapNumber'])
        GP_fp3["DriverNumber"]=GP_fp3["DriverNumber"].astype(int)
        year=GP_fp3['Year'].iloc[0]
        gp=GP_fp3['GP'].iloc[0]
        #Convert LapTime to Time Delta for plotting on Y Axis
        GP_fp3['LapTime_TD']= pd.to_timedelta(GP_fp3["LapTime"])
        GP_fp3["LapTime"]=GP_fp3['LapTime'].str.split('days ').str[1]
        GP_fp3.loc[:, "LapTime (s)"] = GP_fp3["LapTime_TD"].dt.total_seconds()
        # Fastest Driver in each lap
        GP_fp3['s1_TD']= pd.to_timedelta(GP_fp3["Sector1Time"])
        GP_fp3['s2_TD']= pd.to_timedelta(GP_fp3["Sector2Time"])
        GP_fp3['s3_TD']= pd.to_timedelta(GP_fp3["Sector3Time"])

        GP_fp3.loc[:, "Time S1 (s)"] = GP_fp3["s1_TD"].dt.total_seconds()
        GP_fp3.loc[:, "Time S2 (s)"] = GP_fp3["s2_TD"].dt.total_seconds()
        GP_fp3.loc[:, "Time S3 (s)"] = GP_fp3["s3_TD"].dt.total_seconds()
        GP_fp3_Rk=GP_fp3[GP_fp3["LapTime"]!="NaT"]
        GP_fp3_Rk["LAP_RK"] = GP_fp3_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S1_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S2_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S3_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["Race_RK"] = GP_fp3_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

        GP_fp3_Sectors=GP_fp3_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
        GP_fp3_Sectors=GP_fp3_Sectors.fillna(0)
        #get a combined view for fastest drivers in the entire lap, S1, S2, and S3
        Fastest_Lap_fp3=GP_fp3_Sectors[GP_fp3_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_Lap_fp3.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
        Fastest_sector1_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector1_fp3.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
        Fastest_sector2_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector2_fp3.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
        Fastest_sector3_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector3_fp3.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
        Fast_Laps_fp3=Fastest_Lap_fp3.merge(Fastest_sector1_fp3,on=['LapNumber']).merge(Fastest_sector2_fp3,on=['LapNumber']).merge(Fastest_sector3_fp3,on=['LapNumber'])
        Fast_Laps_fp3=Fast_Laps_fp3[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
        Fast_Laps_fp3=Fast_Laps_fp3.reset_index(drop=True)
        Fast_Laps_fp3['color'] = Fast_Laps_fp3['Fastest Lap'].apply(driver_color)
        LapTime_fp3_ordered=Fast_Laps_fp3.sort_values(by=['LapTime (s)'])

        fig_fp3 = go.Figure(go.Table
        (header={"values": LapTime_fp3_ordered.columns},
        cells=dict(
            values=LapTime_fp3_ordered.T.values,
            fill_color=[LapTime_fp3_ordered.color],
            align='center', font=dict(color='white', size=11)
            ))
        )
        fig_fp3.update_layout(
            title="FP3 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi, i),
                title_x=0.5,
            yaxis = dict(tickfont = dict(size=15)),
            xaxis = dict(tickfont = dict(size=15)),
            font=dict(
                family="PT Sans Narrow",
                size=13,
                color="Black"
            ),
            height=780,
            width=1200,
            title_font_family="PT Sans Narrow",
            margin=dict(l=5, r=5, t=35, b=5),
        )
        fig_fp3.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP3/{}/{} {} FP3 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi, year_multi, i),include_plotlyjs='cdn')
    except:
        continue

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy