In [1]:
import pandas as pd
import numpy as np
import pandas_gbq
import time
import itertools
import datetime
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import requests
import json
import plotly.graph_objects as go
project_id = "perceptive-ivy-290216"

In [2]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp1_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp1 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [3]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp2_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp2 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [4]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp3_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp3 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [5]:
race="Japanese Grand Prix"

In [6]:
# FP1

In [7]:
df_bq_fp1=df_bq2_fp1[(df_bq2_fp1["GP"]==race)&(df_bq2_fp1["Year"]==2025)]
GP_fp1=df_bq_fp1
GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)
GP_fp1=GP_fp1.sort_values(['Driver','LapNumber'])
GP_fp1["DriverNumber"]=GP_fp1["DriverNumber"].astype(int)
year=GP_fp1['Year'].iloc[0]
gp=GP_fp1['GP'].iloc[0]
GP_fp1.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_61214/1916111373.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
254,0 days 00:18:03.434000,ALB,23,NaT,1,1.0,0 days 00:16:07.469000,NaT,NaT,0 days 00:00:48.495000,0 days 00:00:23.364000,NaT,0 days 00:17:40.431000,0 days 00:18:03.537000,269.0,281.0,269.0,280.0,False,MEDIUM,1.0,True,Williams,0 days 00:16:07.469000,2025-04-04 02:31:09.953,1,NaN,False,,False,False,2025,Japanese Grand Prix
255,0 days 00:19:36.785000,ALB,23,0 days 00:01:33.351000,2,1.0,NaT,NaT,0 days 00:00:32.936000,0 days 00:00:42.407000,0 days 00:00:18.008000,0 days 00:18:36.370000,0 days 00:19:18.777000,0 days 00:19:36.785000,275.0,302.0,271.0,301.0,True,MEDIUM,2.0,True,Williams,0 days 00:18:03.434000,2025-04-04 02:33:05.918,1,NaN,False,,False,True,2025,Japanese Grand Prix
256,0 days 00:21:49.902000,ALB,23,0 days 00:02:13.117000,3,1.0,NaT,NaT,0 days 00:00:50.937000,0 days 00:00:58.438000,0 days 00:00:23.742000,0 days 00:20:27.722000,0 days 00:21:26.160000,0 days 00:21:49.902000,219.0,284.0,272.0,214.0,False,MEDIUM,3.0,True,Williams,0 days 00:19:36.785000,2025-04-04 02:34:39.269,1,NaN,False,,False,True,2025,Japanese Grand Prix
257,0 days 00:23:20.788000,ALB,23,0 days 00:01:30.886000,4,1.0,NaT,NaT,0 days 00:00:31.788000,0 days 00:00:41.376000,0 days 00:00:17.722000,0 days 00:22:21.690000,0 days 00:23:03.066000,0 days 00:23:20.788000,280.0,304.0,271.0,305.0,True,MEDIUM,4.0,True,Williams,0 days 00:21:49.902000,2025-04-04 02:36:52.386,1,NaN,False,,False,True,2025,Japanese Grand Prix
258,0 days 00:25:47.106000,ALB,23,0 days 00:02:26.318000,5,1.0,NaT,0 days 00:25:45.905000,0 days 00:00:52.068000,0 days 00:01:09.389000,0 days 00:00:24.861000,0 days 00:24:12.856000,0 days 00:25:22.245000,0 days 00:25:47.106000,176.0,240.0,NaN,239.0,False,MEDIUM,5.0,True,Williams,0 days 00:23:20.788000,2025-04-04 02:38:23.272,1,NaN,False,,False,False,2025,Japanese Grand Prix

In [8]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp1['LapTime_TD']= pd.to_timedelta(GP_fp1["LapTime"])
GP_fp1["LapTime"]=GP_fp1['LapTime'].str.split('days ').str[1]
GP_fp1.loc[:, "LapTime (s)"] = GP_fp1["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [9]:
GP_fp1['s1_TD']= pd.to_timedelta(GP_fp1["Sector1Time"])
GP_fp1['s2_TD']= pd.to_timedelta(GP_fp1["Sector2Time"])
GP_fp1['s3_TD']= pd.to_timedelta(GP_fp1["Sector3Time"])

GP_fp1.loc[:, "Time S1 (s)"] = GP_fp1["s1_TD"].dt.total_seconds()
GP_fp1.loc[:, "Time S2 (s)"] = GP_fp1["s2_TD"].dt.total_seconds()
GP_fp1.loc[:, "Time S3 (s)"] = GP_fp1["s3_TD"].dt.total_seconds()

In [10]:
GP_fp1_Rk=GP_fp1[GP_fp1["LapTime"]!="NaT"]
GP_fp1_Rk["LAP_RK"] = GP_fp1_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["S1_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["S2_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["S3_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["Race_RK"] = GP_fp1_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [11]:
GP_fp1_Sectors=GP_fp1_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp1_Sectors=GP_fp1_Sectors.fillna(0)
GP_fp1_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
254,ALB,1,0.0,48.495,23.364,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,4.0,11.0
152,ALO,1,0.0,50.249,22.032,0,0.0,HARD,2025,Japanese Grand Prix,0.0,0.0,9.0,9.0
124,ANT,1,0.0,55.171,19.749,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,19.0,2.0
480,BEA,1,0.0,53.758,25.931,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,16.0,17.0
47,BOR,1,0.0,49.611,21.879,0,0.0,HARD,2025,Japanese Grand Prix,0.0,0.0,7.0,8.0

In [14]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3860C6"
    elif driver =="TSU":
        return "#3860C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [15]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp1=GP_fp1_Sectors[GP_fp1_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp1.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp1.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp1.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp1.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp1=Fastest_Lap_fp1.merge(Fastest_sector1_fp1,on=['LapNumber']).merge(Fastest_sector2_fp1,on=['LapNumber']).merge(Fastest_sector3_fp1,on=['LapNumber'])
Fast_Laps_fp1=Fast_Laps_fp1[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp1=Fast_Laps_fp1.reset_index(drop=True)
Fast_Laps_fp1.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Japanese Grand Prix,2025,2,00:01:30.738000,90.738,VER,SOFT,31.570,VER,SOFT,41.229,RUS,MEDIUM,17.791,NOR,MEDIUM
1,Japanese Grand Prix,2025,3,00:01:32.092000,92.092,HAD,HARD,32.545,HAD,HARD,41.715,HAD,HARD,17.832,HAD,HARD
2,Japanese Grand Prix,2025,4,00:01:29.690000,89.690,VER,SOFT,31.066,VER,SOFT,40.755,RUS,MEDIUM,17.637,ALO,HARD
3,Japanese Grand Prix,2025,5,00:01:30.719000,90.719,TSU,SOFT,31.663,TSU,SOFT,41.323,HAD,HARD,17.635,TSU,SOFT
4,Japanese Grand Prix,2025,6,00:01:29.616000,89.616,RUS,MEDIUM,31.210,ALO,HARD,40.554,RUS,MEDIUM,17.597,ANT,MEDIUM

In [16]:
Fast_Laps_fp1['color'] = Fast_Laps_fp1['Fastest Lap'].apply(driver_color)
Fast_Laps_fp1.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Japanese Grand Prix,2025,2,00:01:30.738000,90.738,VER,SOFT,31.570,VER,SOFT,41.229,RUS,MEDIUM,17.791,NOR,MEDIUM,#3860C6
1,Japanese Grand Prix,2025,3,00:01:32.092000,92.092,HAD,HARD,32.545,HAD,HARD,41.715,HAD,HARD,17.832,HAD,HARD,#6692FF
2,Japanese Grand Prix,2025,4,00:01:29.690000,89.690,VER,SOFT,31.066,VER,SOFT,40.755,RUS,MEDIUM,17.637,ALO,HARD,#3860C6
3,Japanese Grand Prix,2025,5,00:01:30.719000,90.719,TSU,SOFT,31.663,TSU,SOFT,41.323,HAD,HARD,17.635,TSU,SOFT,#3860C6
4,Japanese Grand Prix,2025,6,00:01:29.616000,89.616,RUS,MEDIUM,31.210,ALO,HARD,40.554,RUS,MEDIUM,17.597,ANT,MEDIUM,#27F4D2

In [17]:
LapTime_fp1_ordered=Fast_Laps_fp1.sort_values(by=['LapTime (s)'])
LapTime_fp1_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
11,Japanese Grand Prix,2025,13,00:01:28.549000,88.549,NOR,SOFT,30.820,NOR,SOFT,40.108,NOR,SOFT,17.621,NOR,SOFT,#FF8000
12,Japanese Grand Prix,2025,14,00:01:28.712000,88.712,RUS,SOFT,30.902,RUS,SOFT,40.227,RUS,SOFT,17.393,ANT,SOFT,#27F4D2
9,Japanese Grand Prix,2025,11,00:01:28.809000,88.809,RUS,SOFT,30.932,ALO,HARD,40.141,RUS,SOFT,17.459,ANT,SOFT,#27F4D2
10,Japanese Grand Prix,2025,12,00:01:28.965000,88.965,LEC,SOFT,31.128,LEC,SOFT,40.275,LEC,SOFT,17.562,LEC,SOFT,#E80020
8,Japanese Grand Prix,2025,10,00:01:29.065000,89.065,VER,SOFT,30.950,VER,SOFT,40.619,VER,SOFT,17.496,VER,SOFT,#3860C6

In [18]:
LapTime_fp1_ordered.sort_values(by=['Time S1 (s)'])

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
11,Japanese Grand Prix,2025,13,00:01:28.549000,88.549,NOR,SOFT,30.820,NOR,SOFT,40.108,NOR,SOFT,17.621,NOR,SOFT,#FF8000
15,Japanese Grand Prix,2025,17,00:01:29.392000,89.392,ALB,SOFT,30.895,ALO,SOFT,40.499,ALB,SOFT,17.700,ALB,SOFT,#64C4FF
12,Japanese Grand Prix,2025,14,00:01:28.712000,88.712,RUS,SOFT,30.902,RUS,SOFT,40.227,RUS,SOFT,17.393,ANT,SOFT,#27F4D2
13,Japanese Grand Prix,2025,15,00:01:29.394000,89.394,HIR,SOFT,30.916,HIR,SOFT,40.489,LAW,SOFT,17.679,HIR,SOFT,#3860C6
9,Japanese Grand Prix,2025,11,00:01:28.809000,88.809,RUS,SOFT,30.932,ALO,HARD,40.141,RUS,SOFT,17.459,ANT,SOFT,#27F4D2
8,Japanese Grand Prix,2025,10,00:01:29.065000,89.065,VER,SOFT,30.950,VER,SOFT,40.619,VER,SOFT,17.496,VER,SOFT,#3860C6
6,Japanese Grand Prix,2025,8,00:01:29.176000,89.176,RUS,MEDIUM,30.986,RUS,MEDIUM,40.587,RUS,MEDIUM,17.603,RUS,MEDIUM,#27F4D2
16,Japanese Grand Prix,2025,18,00:01:29.225000,89.225,HAD,SOFT,31.009,HAD,SOFT,40.545,HAD,SOFT,17.671,HAD,SOFT,#6692FF
5,Japanese Grand Prix,2025,7,00:01:29.526000,89.526,VER,SOFT,31.060,VER,SOFT,40.766,VER,SOFT,17.650,ALB,HARD,#3860C6
2,Japanese Grand Prix,2025,4,00:01:29.690000,89.690,VER,SOFT,31.066,VER,SOFT,40.755,RUS,MEDIUM,17.637,ALO,HARD,#3860C6
10,Japanese Grand Prix,2025,12,00:01:28.965000,88.965,LEC,SOFT,31.128,LEC,SOFT,40.275,LEC,SOFT,17.562,LEC,SOFT,#E80020
17,Japanese Grand Prix,2025,19,00:01:29.333000,89.333,SAI,SOFT,31.130,SAI,SOFT,40.740,SAI,SOFT,17.463,SAI,SOFT,#64C4FF
7,Japanese Grand Prix,2025,9,00:01:29.840000,89.840,PIA,SOFT,31.177,NOR,MEDIUM,40.637,NOR,MEDIUM,17.544,PIA,SOFT,#FF8000
4,Japanese Grand Prix,2025,6,00:01:29.616000,89.616,RUS,MEDIUM,31.210,ALO,HARD,40.554,RUS,MEDIUM,17.597,ANT,MEDIUM,#27F4D2
14,Japanese Grand Prix,2025,16,00:01:29.450000,89.450,SAI,SOFT,31.305,SAI,SOFT,40.664,SAI,SOFT,17.481,SAI,SOFT,#64C4FF
0,Japanese Grand Prix,2025,2,00:01:30.738000,90.738,VER,SOFT,31.570,VER,SOFT,41.229,RUS,MEDIUM,17.791,NOR,MEDIUM,#3860C6
3,Japanese Grand Prix,2025,5,00:01:30.719000,90.719,TSU,SOFT,31.663,TSU,SOFT,41.323,HAD,HARD,17.635,TSU,SOFT,#3860C6
23,Japanese Grand Prix,2025,25,00:01:33.519000,93.519,RUS,MEDIUM,32.319,RUS,MEDIUM,42.614,SAI,SOFT,18.355,ANT,MEDIUM,#27F4D2
18,Japanese Grand Prix,2025,20,00:01:32.868000,92.868,NOR,MEDIUM,32.365,NOR,MEDIUM,42.278,RUS,MEDIUM,18.111,ALO,SOFT,#FF8000
21,Japanese Grand Prix,2025,23,00:01:32.935000,92.935,PIA,MEDIUM,32.371,LEC,MEDIUM,42.326,PIA,MEDIUM,18.163,SAI,SOFT,#FF8000
19,Japanese Grand Prix,2025,21,00:01:32.947000,92.947,RUS,MEDIUM,32.376,RUS,MEDIUM,42.254,RUS,MEDIUM,18.221,ALO,SOFT,#27F4D2
24,Japanese Grand Prix,2025,26,00:01:33.917000,93.917,RUS,MEDIUM,32.377,RUS,MEDIUM,42.724,ANT,MEDIUM,18.194,ANT,MEDIUM,#27F4D2
22,Japanese Grand Prix,2025,24,00:01:33.510000,93.510,RUS,MEDIUM,32.390,RUS,MEDIUM,42.768,RUS,MEDIUM,18.352,RUS,MEDIUM,#27F4D2
20,Japanese Grand Prix,2025,22,00:01:32.938000,92.938,RUS,MEDIUM,32.421,LEC,MEDIUM,42.152,RUS,MEDIUM,18.164,ALO,SOFT,#27F4D2
1,Japanese Grand Prix,2025,3,00:01:32.092000,92.092,HAD,HARD,32.545,HAD,HARD,41.715,HAD,HARD,17.832,HAD,HARD,#6692FF
25,Japanese Grand Prix,2025,27,00:01:50.418000,110.418,RUS,MEDIUM,34.688,RUS,MEDIUM,46.739,LEC,MEDIUM,22.091,LEC,MEDIUM,#27F4D2
26,Japanese Grand Prix,2025,28,00:02:20.671000,140.671,RUS,MEDIUM,48.840,RUS,MEDIUM,45.206,ANT,MEDIUM,22.928,ANT,MEDIUM,#27F4D2
27,Japanese Grand Prix,2025,29,00:02:27.716000,147.716,RUS,MEDIUM,73.810,RUS,MEDIUM,47.370,RUS,MEDIUM,26.536,RUS,MEDIUM,#27F4D2

In [19]:
LapTime_fp1_ordered.sort_values(by=['Time S2 (s)'])

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
11,Japanese Grand Prix,2025,13,00:01:28.549000,88.549,NOR,SOFT,30.820,NOR,SOFT,40.108,NOR,SOFT,17.621,NOR,SOFT,#FF8000
9,Japanese Grand Prix,2025,11,00:01:28.809000,88.809,RUS,SOFT,30.932,ALO,HARD,40.141,RUS,SOFT,17.459,ANT,SOFT,#27F4D2
12,Japanese Grand Prix,2025,14,00:01:28.712000,88.712,RUS,SOFT,30.902,RUS,SOFT,40.227,RUS,SOFT,17.393,ANT,SOFT,#27F4D2
10,Japanese Grand Prix,2025,12,00:01:28.965000,88.965,LEC,SOFT,31.128,LEC,SOFT,40.275,LEC,SOFT,17.562,LEC,SOFT,#E80020
13,Japanese Grand Prix,2025,15,00:01:29.394000,89.394,HIR,SOFT,30.916,HIR,SOFT,40.489,LAW,SOFT,17.679,HIR,SOFT,#3860C6
15,Japanese Grand Prix,2025,17,00:01:29.392000,89.392,ALB,SOFT,30.895,ALO,SOFT,40.499,ALB,SOFT,17.700,ALB,SOFT,#64C4FF
16,Japanese Grand Prix,2025,18,00:01:29.225000,89.225,HAD,SOFT,31.009,HAD,SOFT,40.545,HAD,SOFT,17.671,HAD,SOFT,#6692FF
4,Japanese Grand Prix,2025,6,00:01:29.616000,89.616,RUS,MEDIUM,31.210,ALO,HARD,40.554,RUS,MEDIUM,17.597,ANT,MEDIUM,#27F4D2
6,Japanese Grand Prix,2025,8,00:01:29.176000,89.176,RUS,MEDIUM,30.986,RUS,MEDIUM,40.587,RUS,MEDIUM,17.603,RUS,MEDIUM,#27F4D2
8,Japanese Grand Prix,2025,10,00:01:29.065000,89.065,VER,SOFT,30.950,VER,SOFT,40.619,VER,SOFT,17.496,VER,SOFT,#3860C6
7,Japanese Grand Prix,2025,9,00:01:29.840000,89.840,PIA,SOFT,31.177,NOR,MEDIUM,40.637,NOR,MEDIUM,17.544,PIA,SOFT,#FF8000
14,Japanese Grand Prix,2025,16,00:01:29.450000,89.450,SAI,SOFT,31.305,SAI,SOFT,40.664,SAI,SOFT,17.481,SAI,SOFT,#64C4FF
17,Japanese Grand Prix,2025,19,00:01:29.333000,89.333,SAI,SOFT,31.130,SAI,SOFT,40.740,SAI,SOFT,17.463,SAI,SOFT,#64C4FF
2,Japanese Grand Prix,2025,4,00:01:29.690000,89.690,VER,SOFT,31.066,VER,SOFT,40.755,RUS,MEDIUM,17.637,ALO,HARD,#3860C6
5,Japanese Grand Prix,2025,7,00:01:29.526000,89.526,VER,SOFT,31.060,VER,SOFT,40.766,VER,SOFT,17.650,ALB,HARD,#3860C6
0,Japanese Grand Prix,2025,2,00:01:30.738000,90.738,VER,SOFT,31.570,VER,SOFT,41.229,RUS,MEDIUM,17.791,NOR,MEDIUM,#3860C6
3,Japanese Grand Prix,2025,5,00:01:30.719000,90.719,TSU,SOFT,31.663,TSU,SOFT,41.323,HAD,HARD,17.635,TSU,SOFT,#3860C6
1,Japanese Grand Prix,2025,3,00:01:32.092000,92.092,HAD,HARD,32.545,HAD,HARD,41.715,HAD,HARD,17.832,HAD,HARD,#6692FF
20,Japanese Grand Prix,2025,22,00:01:32.938000,92.938,RUS,MEDIUM,32.421,LEC,MEDIUM,42.152,RUS,MEDIUM,18.164,ALO,SOFT,#27F4D2
19,Japanese Grand Prix,2025,21,00:01:32.947000,92.947,RUS,MEDIUM,32.376,RUS,MEDIUM,42.254,RUS,MEDIUM,18.221,ALO,SOFT,#27F4D2
18,Japanese Grand Prix,2025,20,00:01:32.868000,92.868,NOR,MEDIUM,32.365,NOR,MEDIUM,42.278,RUS,MEDIUM,18.111,ALO,SOFT,#FF8000
21,Japanese Grand Prix,2025,23,00:01:32.935000,92.935,PIA,MEDIUM,32.371,LEC,MEDIUM,42.326,PIA,MEDIUM,18.163,SAI,SOFT,#FF8000
23,Japanese Grand Prix,2025,25,00:01:33.519000,93.519,RUS,MEDIUM,32.319,RUS,MEDIUM,42.614,SAI,SOFT,18.355,ANT,MEDIUM,#27F4D2
24,Japanese Grand Prix,2025,26,00:01:33.917000,93.917,RUS,MEDIUM,32.377,RUS,MEDIUM,42.724,ANT,MEDIUM,18.194,ANT,MEDIUM,#27F4D2
22,Japanese Grand Prix,2025,24,00:01:33.510000,93.510,RUS,MEDIUM,32.390,RUS,MEDIUM,42.768,RUS,MEDIUM,18.352,RUS,MEDIUM,#27F4D2
26,Japanese Grand Prix,2025,28,00:02:20.671000,140.671,RUS,MEDIUM,48.840,RUS,MEDIUM,45.206,ANT,MEDIUM,22.928,ANT,MEDIUM,#27F4D2
25,Japanese Grand Prix,2025,27,00:01:50.418000,110.418,RUS,MEDIUM,34.688,RUS,MEDIUM,46.739,LEC,MEDIUM,22.091,LEC,MEDIUM,#27F4D2
27,Japanese Grand Prix,2025,29,00:02:27.716000,147.716,RUS,MEDIUM,73.810,RUS,MEDIUM,47.370,RUS,MEDIUM,26.536,RUS,MEDIUM,#27F4D2

In [20]:
LapTime_fp1_ordered.sort_values(by=['Time S3 (s)'])

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
12,Japanese Grand Prix,2025,14,00:01:28.712000,88.712,RUS,SOFT,30.902,RUS,SOFT,40.227,RUS,SOFT,17.393,ANT,SOFT,#27F4D2
9,Japanese Grand Prix,2025,11,00:01:28.809000,88.809,RUS,SOFT,30.932,ALO,HARD,40.141,RUS,SOFT,17.459,ANT,SOFT,#27F4D2
17,Japanese Grand Prix,2025,19,00:01:29.333000,89.333,SAI,SOFT,31.130,SAI,SOFT,40.740,SAI,SOFT,17.463,SAI,SOFT,#64C4FF
14,Japanese Grand Prix,2025,16,00:01:29.450000,89.450,SAI,SOFT,31.305,SAI,SOFT,40.664,SAI,SOFT,17.481,SAI,SOFT,#64C4FF
8,Japanese Grand Prix,2025,10,00:01:29.065000,89.065,VER,SOFT,30.950,VER,SOFT,40.619,VER,SOFT,17.496,VER,SOFT,#3860C6
7,Japanese Grand Prix,2025,9,00:01:29.840000,89.840,PIA,SOFT,31.177,NOR,MEDIUM,40.637,NOR,MEDIUM,17.544,PIA,SOFT,#FF8000
10,Japanese Grand Prix,2025,12,00:01:28.965000,88.965,LEC,SOFT,31.128,LEC,SOFT,40.275,LEC,SOFT,17.562,LEC,SOFT,#E80020
4,Japanese Grand Prix,2025,6,00:01:29.616000,89.616,RUS,MEDIUM,31.210,ALO,HARD,40.554,RUS,MEDIUM,17.597,ANT,MEDIUM,#27F4D2
6,Japanese Grand Prix,2025,8,00:01:29.176000,89.176,RUS,MEDIUM,30.986,RUS,MEDIUM,40.587,RUS,MEDIUM,17.603,RUS,MEDIUM,#27F4D2
11,Japanese Grand Prix,2025,13,00:01:28.549000,88.549,NOR,SOFT,30.820,NOR,SOFT,40.108,NOR,SOFT,17.621,NOR,SOFT,#FF8000
3,Japanese Grand Prix,2025,5,00:01:30.719000,90.719,TSU,SOFT,31.663,TSU,SOFT,41.323,HAD,HARD,17.635,TSU,SOFT,#3860C6
2,Japanese Grand Prix,2025,4,00:01:29.690000,89.690,VER,SOFT,31.066,VER,SOFT,40.755,RUS,MEDIUM,17.637,ALO,HARD,#3860C6
5,Japanese Grand Prix,2025,7,00:01:29.526000,89.526,VER,SOFT,31.060,VER,SOFT,40.766,VER,SOFT,17.650,ALB,HARD,#3860C6
16,Japanese Grand Prix,2025,18,00:01:29.225000,89.225,HAD,SOFT,31.009,HAD,SOFT,40.545,HAD,SOFT,17.671,HAD,SOFT,#6692FF
13,Japanese Grand Prix,2025,15,00:01:29.394000,89.394,HIR,SOFT,30.916,HIR,SOFT,40.489,LAW,SOFT,17.679,HIR,SOFT,#3860C6
15,Japanese Grand Prix,2025,17,00:01:29.392000,89.392,ALB,SOFT,30.895,ALO,SOFT,40.499,ALB,SOFT,17.700,ALB,SOFT,#64C4FF
0,Japanese Grand Prix,2025,2,00:01:30.738000,90.738,VER,SOFT,31.570,VER,SOFT,41.229,RUS,MEDIUM,17.791,NOR,MEDIUM,#3860C6
1,Japanese Grand Prix,2025,3,00:01:32.092000,92.092,HAD,HARD,32.545,HAD,HARD,41.715,HAD,HARD,17.832,HAD,HARD,#6692FF
18,Japanese Grand Prix,2025,20,00:01:32.868000,92.868,NOR,MEDIUM,32.365,NOR,MEDIUM,42.278,RUS,MEDIUM,18.111,ALO,SOFT,#FF8000
21,Japanese Grand Prix,2025,23,00:01:32.935000,92.935,PIA,MEDIUM,32.371,LEC,MEDIUM,42.326,PIA,MEDIUM,18.163,SAI,SOFT,#FF8000
20,Japanese Grand Prix,2025,22,00:01:32.938000,92.938,RUS,MEDIUM,32.421,LEC,MEDIUM,42.152,RUS,MEDIUM,18.164,ALO,SOFT,#27F4D2
24,Japanese Grand Prix,2025,26,00:01:33.917000,93.917,RUS,MEDIUM,32.377,RUS,MEDIUM,42.724,ANT,MEDIUM,18.194,ANT,MEDIUM,#27F4D2
19,Japanese Grand Prix,2025,21,00:01:32.947000,92.947,RUS,MEDIUM,32.376,RUS,MEDIUM,42.254,RUS,MEDIUM,18.221,ALO,SOFT,#27F4D2
22,Japanese Grand Prix,2025,24,00:01:33.510000,93.510,RUS,MEDIUM,32.390,RUS,MEDIUM,42.768,RUS,MEDIUM,18.352,RUS,MEDIUM,#27F4D2
23,Japanese Grand Prix,2025,25,00:01:33.519000,93.519,RUS,MEDIUM,32.319,RUS,MEDIUM,42.614,SAI,SOFT,18.355,ANT,MEDIUM,#27F4D2
25,Japanese Grand Prix,2025,27,00:01:50.418000,110.418,RUS,MEDIUM,34.688,RUS,MEDIUM,46.739,LEC,MEDIUM,22.091,LEC,MEDIUM,#27F4D2
26,Japanese Grand Prix,2025,28,00:02:20.671000,140.671,RUS,MEDIUM,48.840,RUS,MEDIUM,45.206,ANT,MEDIUM,22.928,ANT,MEDIUM,#27F4D2
27,Japanese Grand Prix,2025,29,00:02:27.716000,147.716,RUS,MEDIUM,73.810,RUS,MEDIUM,47.370,RUS,MEDIUM,26.536,RUS,MEDIUM,#27F4D2

In [21]:
import plotly.graph_objects as go

fig_fp1 = go.Figure(go.Table
 (header={"values": LapTime_fp1_ordered.columns},
  cells=dict(
    values=LapTime_fp1_ordered.T.values,
    fill_color=[LapTime_fp1_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp1.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp1_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp1_ordered.loc[LapTime_fp1_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp1_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp1.update_layout(
    title="FP1 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp1.show()

In [22]:
save_year=2025

In [23]:
fig_fp1.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP1/{}/{} {} FP1 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [24]:
# FP2

In [25]:
df_bq_fp2=df_bq2_fp2[(df_bq2_fp2["GP"]==race)&(df_bq2_fp2["Year"]==2025)]
GP_fp2=df_bq_fp2
GP_fp2["LapNumber"]=GP_fp2["LapNumber"].astype(int)
GP_fp2=GP_fp2.sort_values(['Driver','LapNumber'])
GP_fp2["DriverNumber"]=GP_fp2["DriverNumber"].astype(int)
year=GP_fp2['Year'].iloc[0]
gp=GP_fp2['GP'].iloc[0]
GP_fp2.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_61214/2277067741.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
23169,0 days 00:14:49.776000,ALB,23,NaT,1,1.0,0 days 00:13:02.761000,NaT,NaT,0 days 00:00:46.702000,0 days 00:00:22.186000,NaT,0 days 00:14:27.868000,0 days 00:14:49.947000,269.0,279.0,269.0,269.0,False,HARD,1.0,True,Williams,0 days 00:13:02.761000,2025-04-04 06:00:30.259,1,NaN,False,,False,False,2025,Japanese Grand Prix
23122,0 days 00:16:21.166000,ALB,23,0 days 00:01:31.390000,2,1.0,NaT,NaT,0 days 00:00:31.941000,0 days 00:00:41.560000,0 days 00:00:17.889000,0 days 00:15:21.717000,0 days 00:16:03.277000,0 days 00:16:21.166000,277.0,304.0,271.0,304.0,True,HARD,2.0,True,Williams,0 days 00:14:49.776000,2025-04-04 06:02:17.274,1,NaN,False,,False,True,2025,Japanese Grand Prix
23153,0 days 00:18:32.607000,ALB,23,0 days 00:02:11.441000,3,1.0,NaT,NaT,0 days 00:00:48.152000,0 days 00:00:54.952000,0 days 00:00:28.337000,0 days 00:17:09.318000,0 days 00:18:04.270000,0 days 00:18:32.607000,229.0,166.0,272.0,226.0,False,HARD,3.0,True,Williams,0 days 00:16:21.166000,2025-04-04 06:03:48.664,1,NaN,False,,False,True,2025,Japanese Grand Prix
23194,0 days 00:44:05.543000,ALB,23,NaT,4,1.0,NaT,0 days 00:20:14.296000,0 days 00:00:31.067000,0 days 00:00:40.855000,NaT,0 days 00:19:03.927000,0 days 00:19:44.827000,NaT,279.0,309.0,NaN,NaN,False,HARD,4.0,True,Williams,0 days 00:18:32.607000,2025-04-04 06:06:00.105,125,NaN,False,,False,False,2025,Japanese Grand Prix
23207,0 days 00:46:03.059000,ALB,23,NaT,5,2.0,0 days 00:44:05.543000,NaT,NaT,0 days 00:00:47.916000,0 days 00:00:21.203000,NaT,0 days 00:45:41.856000,0 days 00:46:03.059000,271.0,287.0,273.0,196.0,False,SOFT,1.0,True,Williams,0 days 00:44:05.543000,2025-04-04 06:31:33.041,1,NaN,False,,False,False,2025,Japanese Grand Prix

In [26]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp2['LapTime_TD']= pd.to_timedelta(GP_fp2["LapTime"])
GP_fp2["LapTime"]=GP_fp2['LapTime'].str.split('days ').str[1]
GP_fp2.loc[:, "LapTime (s)"] = GP_fp2["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [27]:
GP_fp2['s1_TD']= pd.to_timedelta(GP_fp2["Sector1Time"])
GP_fp2['s2_TD']= pd.to_timedelta(GP_fp2["Sector2Time"])
GP_fp2['s3_TD']= pd.to_timedelta(GP_fp2["Sector3Time"])

GP_fp2.loc[:, "Time S1 (s)"] = GP_fp2["s1_TD"].dt.total_seconds()
GP_fp2.loc[:, "Time S2 (s)"] = GP_fp2["s2_TD"].dt.total_seconds()
GP_fp2.loc[:, "Time S3 (s)"] = GP_fp2["s3_TD"].dt.total_seconds()

In [28]:
GP_fp2_Rk=GP_fp2[GP_fp2["LapTime"]!="NaT"]
GP_fp2_Rk["LAP_RK"] = GP_fp2_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S1_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S2_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S3_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["Race_RK"] = GP_fp2_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [29]:
GP_fp2_Sectors=GP_fp2_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp2_Sectors=GP_fp2_Sectors.fillna(0)
GP_fp2_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
23169,ALB,1,0.0,46.702,22.186,0,0.0,HARD,2025,Japanese Grand Prix,0.0,0.0,3.0,5.0
23178,ALO,1,0.0,53.205,34.761,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,17.0,16.0
23181,ANT,1,0.0,51.666,39.521,0,0.0,HARD,2025,Japanese Grand Prix,0.0,0.0,15.0,20.0
23179,BEA,1,0.0,57.029,37.573,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,20.0,17.0
23170,BOR,1,0.0,47.652,21.755,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,9.0,4.0

In [30]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp2=GP_fp2_Sectors[GP_fp2_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp2.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp2.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp2.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp2.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp2=Fastest_Lap_fp2.merge(Fastest_sector1_fp2,on=['LapNumber']).merge(Fastest_sector2_fp2,on=['LapNumber']).merge(Fastest_sector3_fp2,on=['LapNumber'])
Fast_Laps_fp2=Fast_Laps_fp2[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp2=Fast_Laps_fp2.reset_index(drop=True)
Fast_Laps_fp2.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Japanese Grand Prix,2025,2,00:01:29.666000,89.666,RUS,HARD,30.948,RUS,HARD,40.779,NOR,MEDIUM,17.707,ANT,HARD
1,Japanese Grand Prix,2025,3,00:02:11.441000,131.441,ALB,HARD,31.401,SAI,SOFT,43.226,NOR,MEDIUM,19.481,NOR,MEDIUM
2,Japanese Grand Prix,2025,4,00:01:36.044000,96.044,NOR,MEDIUM,31.067,ALB,HARD,40.814,NOR,MEDIUM,19.368,PIA,HARD
3,Japanese Grand Prix,2025,5,00:01:28.670000,88.670,VER,SOFT,30.653,ALO,SOFT,40.381,VER,SOFT,17.552,VER,SOFT
4,Japanese Grand Prix,2025,6,00:01:30.208000,90.208,LEC,HARD,30.815,HAM,HARD,40.321,HAM,HARD,18.491,LEC,HARD

In [31]:
Fast_Laps_fp2['color'] = Fast_Laps_fp2['Fastest Lap'].apply(driver_color)
Fast_Laps_fp2.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Japanese Grand Prix,2025,2,00:01:29.666000,89.666,RUS,HARD,30.948,RUS,HARD,40.779,NOR,MEDIUM,17.707,ANT,HARD,#27F4D2
1,Japanese Grand Prix,2025,3,00:02:11.441000,131.441,ALB,HARD,31.401,SAI,SOFT,43.226,NOR,MEDIUM,19.481,NOR,MEDIUM,#64C4FF
2,Japanese Grand Prix,2025,4,00:01:36.044000,96.044,NOR,MEDIUM,31.067,ALB,HARD,40.814,NOR,MEDIUM,19.368,PIA,HARD,#FF8000
3,Japanese Grand Prix,2025,5,00:01:28.670000,88.670,VER,SOFT,30.653,ALO,SOFT,40.381,VER,SOFT,17.552,VER,SOFT,#3860C6
4,Japanese Grand Prix,2025,6,00:01:30.208000,90.208,LEC,HARD,30.815,HAM,HARD,40.321,HAM,HARD,18.491,LEC,HARD,#E80020

In [32]:
LapTime_fp2_ordered=Fast_Laps_fp2.sort_values(by=['LapTime (s)'])
LapTime_fp2_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
9,Japanese Grand Prix,2025,11,00:01:28.114000,88.114,PIA,SOFT,30.713,PIA,SOFT,39.970,PIA,SOFT,17.431,PIA,SOFT,#FF8000
5,Japanese Grand Prix,2025,7,00:01:28.163000,88.163,NOR,SOFT,30.651,RUS,SOFT,40.165,NOR,SOFT,17.276,NOR,SOFT,#FF8000
8,Japanese Grand Prix,2025,10,00:01:28.231000,88.231,NOR,SOFT,30.692,NOR,SOFT,39.827,NOR,SOFT,17.712,NOR,SOFT,#FF8000
6,Japanese Grand Prix,2025,8,00:01:28.543000,88.543,PIA,SOFT,30.759,HAM,SOFT,40.037,PIA,SOFT,17.397,ANT,SOFT,#FF8000
10,Japanese Grand Prix,2025,12,00:01:28.586000,88.586,LEC,SOFT,30.774,LEC,SOFT,40.226,LEC,SOFT,17.586,LEC,SOFT,#E80020

In [33]:
import plotly.graph_objects as go
# colors = n_colors('rgb(255, 200, 200)', 'rgb(200, 0, 0)', 9, colortype='rgb')

fig_fp2 = go.Figure(go.Table
 (header={"values": LapTime_fp2_ordered.columns},
  cells=dict(
    values=LapTime_fp2_ordered.T.values,
    fill_color=[LapTime_fp2_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp2.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp2_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp2_ordered.loc[LapTime_fp2_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp2_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp2.update_layout(
    title="FP2 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp2.show()

In [34]:
fig_fp2.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP2/{}/{} {} FP2 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [35]:
# FP3

In [36]:
df_bq_fp3=df_bq2_fp3[(df_bq2_fp3["GP"]==race)&(df_bq2_fp3["Year"]==2025)]
GP_fp3=df_bq_fp3
GP_fp3["LapNumber"]=GP_fp3["LapNumber"].astype(int)
GP_fp3=GP_fp3.sort_values(['Driver','LapNumber'])
GP_fp3["DriverNumber"]=GP_fp3["DriverNumber"].astype(int)
year=GP_fp3['Year'].iloc[0]
gp=GP_fp3['GP'].iloc[0]
GP_fp3.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_61214/2774860751.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
176,0 days 00:30:06.798000,ALB,23,NaT,1,1.0,0 days 00:19:29.432000,0 days 00:21:31.308000,NaT,0 days 00:00:48.793000,NaT,NaT,0 days 00:21:01.198000,NaT,276.0,273.0,NaN,265.0,False,MEDIUM,1.0,True,Williams,0 days 00:19:29.432000,2025-04-05 02:34:30.458,15,NaN,False,,False,False,2025,Japanese Grand Prix
177,0 days 00:32:21.717000,ALB,23,NaT,2,2.0,0 days 00:30:06.798000,NaT,NaT,0 days 00:00:48.988000,0 days 00:00:19.570000,NaT,0 days 00:32:02.236000,0 days 00:32:21.752000,278.0,279.0,269.0,279.0,False,MEDIUM,1.0,False,Williams,0 days 00:30:06.798000,2025-04-05 02:45:07.824,1,NaN,False,,False,False,2025,Japanese Grand Prix
178,0 days 00:33:52.596000,ALB,23,0 days 00:01:30.879000,3,2.0,NaT,NaT,0 days 00:00:31.997000,0 days 00:00:41.057000,0 days 00:00:17.825000,0 days 00:32:53.714000,0 days 00:33:34.771000,0 days 00:33:52.596000,283.0,299.0,270.0,295.0,True,MEDIUM,2.0,False,Williams,0 days 00:32:21.717000,2025-04-05 02:47:22.743,1,NaN,False,,False,True,2025,Japanese Grand Prix
179,0 days 00:36:19.644000,ALB,23,0 days 00:02:27.048000,4,2.0,NaT,NaT,0 days 00:00:48.983000,0 days 00:01:03.644000,0 days 00:00:34.421000,0 days 00:34:41.579000,0 days 00:35:45.223000,0 days 00:36:19.644000,161.0,235.0,268.0,148.0,False,MEDIUM,3.0,False,Williams,0 days 00:33:52.596000,2025-04-05 02:48:53.622,1,NaN,False,,False,True,2025,Japanese Grand Prix
180,0 days 00:38:07.155000,ALB,23,0 days 00:01:47.511000,5,2.0,NaT,0 days 00:38:05.827000,0 days 00:00:33.511000,0 days 00:00:50.554000,0 days 00:00:23.446000,0 days 00:36:53.155000,0 days 00:37:43.709000,0 days 00:38:07.155000,203.0,281.0,NaN,238.0,False,MEDIUM,4.0,False,Williams,0 days 00:36:19.644000,2025-04-05 02:51:20.670,1,NaN,False,,False,False,2025,Japanese Grand Prix

In [37]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp3['LapTime_TD']= pd.to_timedelta(GP_fp3["LapTime"])
GP_fp3["LapTime"]=GP_fp3['LapTime'].str.split('days ').str[1]
GP_fp3.loc[:, "LapTime (s)"] = GP_fp3["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [38]:
GP_fp3['s1_TD']= pd.to_timedelta(GP_fp3["Sector1Time"])
GP_fp3['s2_TD']= pd.to_timedelta(GP_fp3["Sector2Time"])
GP_fp3['s3_TD']= pd.to_timedelta(GP_fp3["Sector3Time"])

GP_fp3.loc[:, "Time S1 (s)"] = GP_fp3["s1_TD"].dt.total_seconds()
GP_fp3.loc[:, "Time S2 (s)"] = GP_fp3["s2_TD"].dt.total_seconds()
GP_fp3.loc[:, "Time S3 (s)"] = GP_fp3["s3_TD"].dt.total_seconds()

In [39]:
GP_fp3_Rk=GP_fp3[GP_fp3["LapTime"]!="NaT"]
GP_fp3_Rk["LAP_RK"] = GP_fp3_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S1_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S2_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S3_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["Race_RK"] = GP_fp3_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [40]:
GP_fp3_Sectors=GP_fp3_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp3_Sectors=GP_fp3_Sectors.fillna(0)
GP_fp3_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
176,ALB,1,0.0,48.793,0.000,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,10.0,0.0
116,ALO,1,0.0,57.938,30.897,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,16.0,17.0
96,ANT,1,0.0,47.263,22.152,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,7.0,5.0
313,BEA,1,0.0,58.373,29.150,0,0.0,HARD,2025,Japanese Grand Prix,0.0,0.0,17.0,15.0
37,BOR,1,0.0,46.442,23.687,0,0.0,MEDIUM,2025,Japanese Grand Prix,0.0,0.0,4.0,9.0

In [41]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp3=GP_fp3_Sectors[GP_fp3_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp3.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp3.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp3.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp3.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp3=Fastest_Lap_fp3.merge(Fastest_sector1_fp3,on=['LapNumber']).merge(Fastest_sector2_fp3,on=['LapNumber']).merge(Fastest_sector3_fp3,on=['LapNumber'])
Fast_Laps_fp3=Fast_Laps_fp3[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp3=Fast_Laps_fp3.reset_index(drop=True)
Fast_Laps_fp3.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Japanese Grand Prix,2025,2,00:01:29.107000,89.107,LEC,SOFT,31.337,LEC,SOFT,40.263,LEC,SOFT,17.507,LEC,SOFT
1,Japanese Grand Prix,2025,3,00:01:29.272000,89.272,HAM,SOFT,31.145,HAM,SOFT,40.287,NOR,SOFT,17.624,PIA,SOFT
2,Japanese Grand Prix,2025,4,00:01:30.133000,90.133,GAS,MEDIUM,31.416,GAS,MEDIUM,40.830,HAD,MEDIUM,17.722,ALO,MEDIUM
3,Japanese Grand Prix,2025,5,00:01:28.768000,88.768,PIA,SOFT,30.875,LEC,SOFT,40.071,PIA,SOFT,17.606,PIA,SOFT
4,Japanese Grand Prix,2025,6,00:01:28.818000,88.818,NOR,SOFT,30.923,NOR,SOFT,40.242,NOR,SOFT,17.601,HAM,SOFT

In [42]:
Fast_Laps_fp3['color'] = Fast_Laps_fp3['Fastest Lap'].apply(driver_color)
Fast_Laps_fp3.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Japanese Grand Prix,2025,2,00:01:29.107000,89.107,LEC,SOFT,31.337,LEC,SOFT,40.263,LEC,SOFT,17.507,LEC,SOFT,#E80020
1,Japanese Grand Prix,2025,3,00:01:29.272000,89.272,HAM,SOFT,31.145,HAM,SOFT,40.287,NOR,SOFT,17.624,PIA,SOFT,#E80020
2,Japanese Grand Prix,2025,4,00:01:30.133000,90.133,GAS,MEDIUM,31.416,GAS,MEDIUM,40.830,HAD,MEDIUM,17.722,ALO,MEDIUM,#0093cc
3,Japanese Grand Prix,2025,5,00:01:28.768000,88.768,PIA,SOFT,30.875,LEC,SOFT,40.071,PIA,SOFT,17.606,PIA,SOFT,#FF8000
4,Japanese Grand Prix,2025,6,00:01:28.818000,88.818,NOR,SOFT,30.923,NOR,SOFT,40.242,NOR,SOFT,17.601,HAM,SOFT,#FF8000

In [43]:
LapTime_fp3_ordered=Fast_Laps_fp3.sort_values(by=['LapTime (s)'])
LapTime_fp3_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
14,Japanese Grand Prix,2025,16,00:01:27.965000,87.965,NOR,SOFT,30.501,NOR,SOFT,39.951,NOR,SOFT,17.442,PIA,SOFT,#FF8000
11,Japanese Grand Prix,2025,13,00:01:27.991000,87.991,PIA,SOFT,30.476,NOR,SOFT,39.971,PIA,SOFT,17.397,PIA,SOFT,#FF8000
10,Japanese Grand Prix,2025,12,00:01:28.077000,88.077,RUS,SOFT,30.687,RUS,SOFT,39.858,RUS,SOFT,17.504,HAM,SOFT,#27F4D2
7,Japanese Grand Prix,2025,9,00:01:28.385000,88.385,RUS,SOFT,30.677,HAM,SOFT,40.125,RUS,SOFT,17.558,RUS,SOFT,#27F4D2
6,Japanese Grand Prix,2025,8,00:01:28.414000,88.414,LEC,SOFT,30.632,LEC,SOFT,40.215,LEC,SOFT,17.567,LEC,SOFT,#E80020

In [44]:
import plotly.graph_objects as go
# colors = n_colors('rgb(255, 200, 200)', 'rgb(200, 0, 0)', 9, colortype='rgb')

fig_fp3 = go.Figure(go.Table
 (header={"values": LapTime_fp3_ordered.columns},
  cells=dict(
    values=LapTime_fp3_ordered.T.values,
    fill_color=[LapTime_fp3_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp3.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp3_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp3_ordered.loc[LapTime_fp3_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp3_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp3.update_layout(
    title="FP3 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp3.show()

In [45]:
fig_fp3.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP3/{}/{} {} FP3 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi GP Plot FP1

In [ ]:
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    else:
        return '#3860C6'

In [ ]:
save_year_multi=2023

In [42]:
#2024
race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
# 2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2024
for i in race_multi:
    df_bq_fp1=df_bq2_fp1[(df_bq2_fp1["GP"]==i)&(df_bq2_fp1["Year"]==year_multi)]
    GP_fp1=df_bq_fp1
    GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)
    GP_fp1=GP_fp1.sort_values(['Driver','LapNumber'])
    GP_fp1["DriverNumber"]=GP_fp1["DriverNumber"].astype(int)
    # year=GP_fp1['Year'].iloc[0]
    # gp=GP_fp1['GP'].iloc[0]
    GP_fp1['LapTime_TD']= pd.to_timedelta(GP_fp1["LapTime"])
    GP_fp1["LapTime"]=GP_fp1['LapTime'].str.split('days ').str[1]
    GP_fp1.loc[:, "LapTime (s)"] = GP_fp1["LapTime_TD"].dt.total_seconds()
    GP_fp1['s1_TD']= pd.to_timedelta(GP_fp1["Sector1Time"])
    GP_fp1['s2_TD']= pd.to_timedelta(GP_fp1["Sector2Time"])
    GP_fp1['s3_TD']= pd.to_timedelta(GP_fp1["Sector3Time"])

    GP_fp1.loc[:, "Time S1 (s)"] = GP_fp1["s1_TD"].dt.total_seconds()
    GP_fp1.loc[:, "Time S2 (s)"] = GP_fp1["s2_TD"].dt.total_seconds()
    GP_fp1.loc[:, "Time S3 (s)"] = GP_fp1["s3_TD"].dt.total_seconds()
    GP_fp1_Rk=GP_fp1[GP_fp1["LapTime"]!="NaT"]
    GP_fp1_Rk["LAP_RK"] = GP_fp1_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S1_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S2_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S3_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["Race_RK"] = GP_fp1_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)
    GP_fp1_Sectors=GP_fp1_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
    GP_fp1_Sectors=GP_fp1_Sectors.fillna(0)
    Fastest_Lap_fp1=GP_fp1_Sectors[GP_fp1_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_Lap_fp1.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
    Fastest_sector1_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector1_fp1.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
    Fastest_sector2_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector2_fp1.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
    Fastest_sector3_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector3_fp1.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
    Fast_Laps_fp1=Fastest_Lap_fp1.merge(Fastest_sector1_fp1,on=['LapNumber']).merge(Fastest_sector2_fp1,on=['LapNumber']).merge(Fastest_sector3_fp1,on=['LapNumber'])
    Fast_Laps_fp1=Fast_Laps_fp1[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
    Fast_Laps_fp1=Fast_Laps_fp1.reset_index(drop=True)
    Fast_Laps_fp1['color'] = Fast_Laps_fp1['Fastest Lap'].apply(driver_color)
    LapTime_fp1_ordered=Fast_Laps_fp1.sort_values(by=['LapTime (s)'])
    fig_fp1 = go.Figure(go.Table
    (header={"values": LapTime_fp1_ordered.columns},
    cells=dict(
        values=LapTime_fp1_ordered.T.values,
        fill_color=[LapTime_fp1_ordered.color],
        align='center', font=dict(color='white', size=11)
        ))
    )
    fig_fp1.update_layout(
        title="FP1 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi, i),
            title_x=0.5,
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=13,
            color="Black"
        ),
        height=780,
        width=1200,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig_fp1.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP1/{}/{} {} FP1 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi,year_multi, i),include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/1988034499.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [43]:
#Multi GP Plot FP2

In [44]:
for i in race_multi:
    try:
        df_bq_fp2=df_bq2_fp2[(df_bq2_fp2["GP"]==i)&(df_bq2_fp2["Year"]==year_multi)]
        GP_fp2=df_bq_fp2
        GP_fp2["LapNumber"]=GP_fp2["LapNumber"].astype(int)
        GP_fp2=GP_fp2.sort_values(['Driver','LapNumber'])
        GP_fp2["DriverNumber"]=GP_fp2["DriverNumber"].astype(int)
        year=GP_fp2['Year'].iloc[0]
        gp=GP_fp2['GP'].iloc[0]
        #Convert LapTime to Time Delta for plotting on Y Axis
        GP_fp2['LapTime_TD']= pd.to_timedelta(GP_fp2["LapTime"])
        GP_fp2["LapTime"]=GP_fp2['LapTime'].str.split('days ').str[1]
        GP_fp2.loc[:, "LapTime (s)"] = GP_fp2["LapTime_TD"].dt.total_seconds()
        # Fastest Driver in each lap
        GP_fp2['s1_TD']= pd.to_timedelta(GP_fp2["Sector1Time"])
        GP_fp2['s2_TD']= pd.to_timedelta(GP_fp2["Sector2Time"])
        GP_fp2['s3_TD']= pd.to_timedelta(GP_fp2["Sector3Time"])

        GP_fp2.loc[:, "Time S1 (s)"] = GP_fp2["s1_TD"].dt.total_seconds()
        GP_fp2.loc[:, "Time S2 (s)"] = GP_fp2["s2_TD"].dt.total_seconds()
        GP_fp2.loc[:, "Time S3 (s)"] = GP_fp2["s3_TD"].dt.total_seconds()
        GP_fp2_Rk=GP_fp2[GP_fp2["LapTime"]!="NaT"]
        GP_fp2_Rk["LAP_RK"] = GP_fp2_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S1_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S2_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S3_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["Race_RK"] = GP_fp2_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

        GP_fp2_Sectors=GP_fp2_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
        GP_fp2_Sectors=GP_fp2_Sectors.fillna(0)
        GP_fp2_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()
        #get a combined view for fastest drivers in the entire lap, S1, S2, and S3
        Fastest_Lap_fp2=GP_fp2_Sectors[GP_fp2_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_Lap_fp2.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
        Fastest_sector1_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector1_fp2.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
        Fastest_sector2_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector2_fp2.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
        Fastest_sector3_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector3_fp2.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
        Fast_Laps_fp2=Fastest_Lap_fp2.merge(Fastest_sector1_fp2,on=['LapNumber']).merge(Fastest_sector2_fp2,on=['LapNumber']).merge(Fastest_sector3_fp2,on=['LapNumber'])
        Fast_Laps_fp2=Fast_Laps_fp2[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
        Fast_Laps_fp2=Fast_Laps_fp2.reset_index(drop=True)
        Fast_Laps_fp2['color'] = Fast_Laps_fp2['Fastest Lap'].apply(driver_color)
        LapTime_fp2_ordered=Fast_Laps_fp2.sort_values(by=['LapTime (s)'])
        fig_fp2 = go.Figure(go.Table
        (header={"values": LapTime_fp2_ordered.columns},
        cells=dict(
            values=LapTime_fp2_ordered.T.values,
            fill_color=[LapTime_fp2_ordered.color],
            align='center', font=dict(color='white', size=11)
            ))
        )
        fig_fp2.update_layout(
            title="FP2 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi,i),
                title_x=0.5,
            yaxis = dict(tickfont = dict(size=15)),
            xaxis = dict(tickfont = dict(size=15)),
            font=dict(
                family="PT Sans Narrow",
                size=13,
                color="Black"
            ),
            height=780,
            width=1200,
            title_font_family="PT Sans Narrow",
            margin=dict(l=5, r=5, t=35, b=5),
        )
        fig_fp2.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP2/{}/{} {} FP2 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi,year_multi,i),include_plotlyjs='cdn')
    except:
        continue

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/290820071.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [45]:
#Multi GP Plot FP3

In [46]:
for i in race_multi:
    try:
        df_bq_fp3=df_bq2_fp3[(df_bq2_fp3["GP"]==i)&(df_bq2_fp3["Year"]==year_multi)]
        GP_fp3=df_bq_fp3
        GP_fp3["LapNumber"]=GP_fp3["LapNumber"].astype(int)
        GP_fp3=GP_fp3.sort_values(['Driver','LapNumber'])
        GP_fp3["DriverNumber"]=GP_fp3["DriverNumber"].astype(int)
        year=GP_fp3['Year'].iloc[0]
        gp=GP_fp3['GP'].iloc[0]
        #Convert LapTime to Time Delta for plotting on Y Axis
        GP_fp3['LapTime_TD']= pd.to_timedelta(GP_fp3["LapTime"])
        GP_fp3["LapTime"]=GP_fp3['LapTime'].str.split('days ').str[1]
        GP_fp3.loc[:, "LapTime (s)"] = GP_fp3["LapTime_TD"].dt.total_seconds()
        # Fastest Driver in each lap
        GP_fp3['s1_TD']= pd.to_timedelta(GP_fp3["Sector1Time"])
        GP_fp3['s2_TD']= pd.to_timedelta(GP_fp3["Sector2Time"])
        GP_fp3['s3_TD']= pd.to_timedelta(GP_fp3["Sector3Time"])

        GP_fp3.loc[:, "Time S1 (s)"] = GP_fp3["s1_TD"].dt.total_seconds()
        GP_fp3.loc[:, "Time S2 (s)"] = GP_fp3["s2_TD"].dt.total_seconds()
        GP_fp3.loc[:, "Time S3 (s)"] = GP_fp3["s3_TD"].dt.total_seconds()
        GP_fp3_Rk=GP_fp3[GP_fp3["LapTime"]!="NaT"]
        GP_fp3_Rk["LAP_RK"] = GP_fp3_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S1_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S2_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S3_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["Race_RK"] = GP_fp3_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

        GP_fp3_Sectors=GP_fp3_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
        GP_fp3_Sectors=GP_fp3_Sectors.fillna(0)
        #get a combined view for fastest drivers in the entire lap, S1, S2, and S3
        Fastest_Lap_fp3=GP_fp3_Sectors[GP_fp3_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_Lap_fp3.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
        Fastest_sector1_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector1_fp3.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
        Fastest_sector2_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector2_fp3.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
        Fastest_sector3_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector3_fp3.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
        Fast_Laps_fp3=Fastest_Lap_fp3.merge(Fastest_sector1_fp3,on=['LapNumber']).merge(Fastest_sector2_fp3,on=['LapNumber']).merge(Fastest_sector3_fp3,on=['LapNumber'])
        Fast_Laps_fp3=Fast_Laps_fp3[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
        Fast_Laps_fp3=Fast_Laps_fp3.reset_index(drop=True)
        Fast_Laps_fp3['color'] = Fast_Laps_fp3['Fastest Lap'].apply(driver_color)
        LapTime_fp3_ordered=Fast_Laps_fp3.sort_values(by=['LapTime (s)'])

        fig_fp3 = go.Figure(go.Table
        (header={"values": LapTime_fp3_ordered.columns},
        cells=dict(
            values=LapTime_fp3_ordered.T.values,
            fill_color=[LapTime_fp3_ordered.color],
            align='center', font=dict(color='white', size=11)
            ))
        )
        fig_fp3.update_layout(
            title="FP3 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi, i),
                title_x=0.5,
            yaxis = dict(tickfont = dict(size=15)),
            xaxis = dict(tickfont = dict(size=15)),
            font=dict(
                family="PT Sans Narrow",
                size=13,
                color="Black"
            ),
            height=780,
            width=1200,
            title_font_family="PT Sans Narrow",
            margin=dict(l=5, r=5, t=35, b=5),
        )
        fig_fp3.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP3/{}/{} {} FP3 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi, year_multi, i),include_plotlyjs='cdn')
    except:
        continue

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_26512/2753040708.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy