In [1]:
import pandas as pd
import numpy as np
import pandas_gbq
import time
import itertools
import datetime
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import requests
import json
import plotly.graph_objects as go
project_id = "perceptive-ivy-290216"

In [2]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp1_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp1 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [3]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp2_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp2 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

KeyboardInterrupt:

In [ ]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.fp3_lap_time`
"""
project_id = "perceptive-ivy-290216"
df_bq2_fp3 = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [4]:
race="Las Vegas Grand Prix"

In [5]:
# FP1

In [6]:
df_bq_fp1=df_bq2_fp1[(df_bq2_fp1["GP"]==race)&(df_bq2_fp1["Year"]==2025)]
GP_fp1=df_bq_fp1
GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)
GP_fp1=GP_fp1.sort_values(['Driver','LapNumber'])
GP_fp1["DriverNumber"]=GP_fp1["DriverNumber"].astype(int)
year=GP_fp1['Year'].iloc[0]
gp=GP_fp1['GP'].iloc[0]
GP_fp1.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_39916/1916111373.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
184,0 days 00:18:38.189000,ALB,23,NaT,1,1.0,0 days 00:16:54.083000,NaT,NaT,0 days 00:00:36.135000,0 days 00:00:39.757000,NaT,0 days 00:17:58.679000,0 days 00:18:38.315000,167.0,196.0,289.0,285.0,False,MEDIUM,1.0,True,Williams,0 days 00:16:54.083000,2025-11-21 00:31:54.091,1,NaN,False,,False,False,2025,Las Vegas Grand Prix
185,0 days 00:20:20.287000,ALB,23,0 days 00:01:42.098000,2,1.0,NaT,NaT,0 days 00:00:29.466000,0 days 00:00:34.240000,0 days 00:00:38.392000,0 days 00:19:07.655000,0 days 00:19:41.895000,0 days 00:20:20.287000,177.0,200.0,310.0,311.0,True,MEDIUM,2.0,True,Williams,0 days 00:18:38.189000,2025-11-21 00:33:38.197,1,NaN,False,,False,True,2025,Las Vegas Grand Prix
186,0 days 00:22:10.930000,ALB,23,0 days 00:01:50.643000,3,1.0,NaT,0 days 00:22:08.065000,0 days 00:00:28.302000,0 days 00:00:33.526000,0 days 00:00:48.815000,0 days 00:20:48.589000,0 days 00:21:22.115000,0 days 00:22:10.930000,180.0,203.0,NaN,255.0,False,MEDIUM,3.0,True,Williams,0 days 00:20:20.287000,2025-11-21 00:35:20.295,1,NaN,False,,False,False,2025,Las Vegas Grand Prix
187,0 days 00:33:41.270000,ALB,23,NaT,4,2.0,0 days 00:31:59.482000,NaT,NaT,0 days 00:00:34.545000,0 days 00:00:40.528000,NaT,0 days 00:33:01.178000,0 days 00:33:41.669000,173.0,NaN,314.0,219.0,False,MEDIUM,4.0,False,Williams,0 days 00:22:10.930000,2025-11-21 00:37:10.938,12,NaN,False,,False,False,2025,Las Vegas Grand Prix
188,0 days 00:35:18.885000,ALB,23,0 days 00:01:37.615000,5,2.0,NaT,NaT,0 days 00:00:27.637000,0 days 00:00:32.383000,0 days 00:00:37.068000,0 days 00:34:08.907000,0 days 00:34:41.290000,0 days 00:35:18.358000,183.0,204.0,317.0,335.0,True,MEDIUM,5.0,False,Williams,0 days 00:33:41.270000,2025-11-21 00:48:41.278,1,NaN,False,,False,False,2025,Las Vegas Grand Prix

In [7]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp1['LapTime_TD']= pd.to_timedelta(GP_fp1["LapTime"])
GP_fp1["LapTime"]=GP_fp1['LapTime'].str.split('days ').str[1]
GP_fp1.loc[:, "LapTime (s)"] = GP_fp1["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [8]:
GP_fp1['s1_TD']= pd.to_timedelta(GP_fp1["Sector1Time"])
GP_fp1['s2_TD']= pd.to_timedelta(GP_fp1["Sector2Time"])
GP_fp1['s3_TD']= pd.to_timedelta(GP_fp1["Sector3Time"])

GP_fp1.loc[:, "Time S1 (s)"] = GP_fp1["s1_TD"].dt.total_seconds()
GP_fp1.loc[:, "Time S2 (s)"] = GP_fp1["s2_TD"].dt.total_seconds()
GP_fp1.loc[:, "Time S3 (s)"] = GP_fp1["s3_TD"].dt.total_seconds()

In [9]:
GP_fp1_Rk=GP_fp1[GP_fp1["LapTime"]!="NaT"]
GP_fp1_Rk["LAP_RK"] = GP_fp1_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["S1_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["S2_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["S3_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp1_Rk["Race_RK"] = GP_fp1_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [10]:
GP_fp1_Sectors=GP_fp1_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp1_Sectors=GP_fp1_Sectors.fillna(0)
GP_fp1_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
184,ALB,1,0.0,36.135,39.757,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,2.0,1.0
80,ALO,1,0.0,37.870,40.338,0,0.0,SOFT,2025,Las Vegas Grand Prix,0.0,0.0,8.0,4.0
50,ANT,1,0.0,40.036,44.562,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,12.0,17.0
507,BEA,1,0.0,42.067,42.231,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,19.0,12.0
369,BOR,1,0.0,41.657,42.016,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,18.0,10.0

In [11]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3860C6"
    elif driver =="TSU":
        return "#3860C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [12]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp1=GP_fp1_Sectors[GP_fp1_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp1.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp1.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp1.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp1.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp1=Fastest_Lap_fp1.merge(Fastest_sector1_fp1,on=['LapNumber']).merge(Fastest_sector2_fp1,on=['LapNumber']).merge(Fastest_sector3_fp1,on=['LapNumber'])
Fast_Laps_fp1=Fast_Laps_fp1[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp1=Fast_Laps_fp1.reset_index(drop=True)
Fast_Laps_fp1.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Las Vegas Grand Prix,2025,2,00:01:38.686000,98.686,PIA,MEDIUM,28.475,PIA,MEDIUM,33.008,PIA,MEDIUM,37.203,PIA,MEDIUM
1,Las Vegas Grand Prix,2025,3,00:01:38.011000,98.011,VER,MEDIUM,27.912,NOR,MEDIUM,33.061,RUS,MEDIUM,37.005,VER,MEDIUM
2,Las Vegas Grand Prix,2025,4,00:01:37.685000,97.685,PIA,MEDIUM,27.903,PIA,MEDIUM,32.894,PIA,MEDIUM,36.888,PIA,MEDIUM
3,Las Vegas Grand Prix,2025,5,00:01:36.493000,96.493,VER,MEDIUM,27.287,VER,MEDIUM,32.383,ALB,MEDIUM,36.737,VER,MEDIUM
4,Las Vegas Grand Prix,2025,6,00:01:36.758000,96.758,NOR,MEDIUM,27.325,ALO,SOFT,31.833,NOR,MEDIUM,36.719,PIA,MEDIUM

In [13]:
Fast_Laps_fp1['color'] = Fast_Laps_fp1['Fastest Lap'].apply(driver_color)
Fast_Laps_fp1.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Las Vegas Grand Prix,2025,2,00:01:38.686000,98.686,PIA,MEDIUM,28.475,PIA,MEDIUM,33.008,PIA,MEDIUM,37.203,PIA,MEDIUM,#FF8000
1,Las Vegas Grand Prix,2025,3,00:01:38.011000,98.011,VER,MEDIUM,27.912,NOR,MEDIUM,33.061,RUS,MEDIUM,37.005,VER,MEDIUM,#3860C6
2,Las Vegas Grand Prix,2025,4,00:01:37.685000,97.685,PIA,MEDIUM,27.903,PIA,MEDIUM,32.894,PIA,MEDIUM,36.888,PIA,MEDIUM,#FF8000
3,Las Vegas Grand Prix,2025,5,00:01:36.493000,96.493,VER,MEDIUM,27.287,VER,MEDIUM,32.383,ALB,MEDIUM,36.737,VER,MEDIUM,#3860C6
4,Las Vegas Grand Prix,2025,6,00:01:36.758000,96.758,NOR,MEDIUM,27.325,ALO,SOFT,31.833,NOR,MEDIUM,36.719,PIA,MEDIUM,#FF8000

In [14]:
LapTime_fp1_ordered=Fast_Laps_fp1.sort_values(by=['LapTime (s)'])
LapTime_fp1_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
19,Las Vegas Grand Prix,2025,21,00:01:34.802000,94.802,LEC,SOFT,26.748,ALB,SOFT,31.724,LEC,SOFT,36.287,LEC,SOFT,#E80020
14,Las Vegas Grand Prix,2025,16,00:01:34.968000,94.968,ALB,SOFT,26.711,HAM,SOFT,31.761,ALB,SOFT,36.295,ALB,SOFT,#64C4FF
17,Las Vegas Grand Prix,2025,19,00:01:35.071000,95.071,TSU,SOFT,26.704,HAM,SOFT,31.748,LEC,SOFT,36.256,TSU,SOFT,#3860C6
12,Las Vegas Grand Prix,2025,14,00:01:35.109000,95.109,VER,SOFT,26.705,VER,SOFT,32.068,VER,SOFT,36.336,VER,SOFT,#3860C6
21,Las Vegas Grand Prix,2025,23,00:01:35.117000,95.117,TSU,SOFT,26.707,TSU,SOFT,31.860,LAW,SOFT,36.536,TSU,SOFT,#3860C6

In [15]:
LapTime_fp1_ordered.sort_values(by=['Time S1 (s)'])

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
17,Las Vegas Grand Prix,2025,19,00:01:35.071000,95.071,TSU,SOFT,26.704,HAM,SOFT,31.748,LEC,SOFT,36.256,TSU,SOFT,#3860C6
12,Las Vegas Grand Prix,2025,14,00:01:35.109000,95.109,VER,SOFT,26.705,VER,SOFT,32.068,VER,SOFT,36.336,VER,SOFT,#3860C6
21,Las Vegas Grand Prix,2025,23,00:01:35.117000,95.117,TSU,SOFT,26.707,TSU,SOFT,31.860,LAW,SOFT,36.536,TSU,SOFT,#3860C6
14,Las Vegas Grand Prix,2025,16,00:01:34.968000,94.968,ALB,SOFT,26.711,HAM,SOFT,31.761,ALB,SOFT,36.295,ALB,SOFT,#64C4FF
18,Las Vegas Grand Prix,2025,20,00:01:35.460000,95.460,PIA,SOFT,26.729,HAM,SOFT,31.340,ANT,SOFT,36.395,PIA,SOFT,#FF8000
13,Las Vegas Grand Prix,2025,15,00:01:35.281000,95.281,LEC,SOFT,26.747,HAM,SOFT,31.858,LEC,SOFT,36.430,RUS,SOFT,#E80020
19,Las Vegas Grand Prix,2025,21,00:01:34.802000,94.802,LEC,SOFT,26.748,ALB,SOFT,31.724,LEC,SOFT,36.287,LEC,SOFT,#E80020
15,Las Vegas Grand Prix,2025,17,00:01:35.121000,95.121,LEC,SOFT,26.770,LEC,SOFT,31.942,LEC,SOFT,36.409,LEC,SOFT,#E80020
25,Las Vegas Grand Prix,2025,27,00:01:38.020000,98.020,LEC,MEDIUM,26.793,SAI,SOFT,32.726,LEC,MEDIUM,37.204,LEC,MEDIUM,#E80020
16,Las Vegas Grand Prix,2025,18,00:01:35.568000,95.568,ANT,SOFT,26.828,HAM,SOFT,31.886,ANT,SOFT,36.598,ANT,SOFT,#27F4D2
26,Las Vegas Grand Prix,2025,28,00:01:35.299000,95.299,HAD,SOFT,26.859,HAD,SOFT,31.493,HAD,SOFT,36.420,HAD,SOFT,#6692FF
10,Las Vegas Grand Prix,2025,12,00:01:35.561000,95.561,HAM,SOFT,26.912,HAM,SOFT,31.670,SAI,MEDIUM,36.624,HAM,SOFT,#E80020
20,Las Vegas Grand Prix,2025,22,00:01:35.450000,95.450,PIA,SOFT,26.927,PIA,SOFT,32.156,PIA,SOFT,36.367,PIA,SOFT,#FF8000
23,Las Vegas Grand Prix,2025,25,00:01:35.179000,95.179,SAI,SOFT,26.928,SAI,SOFT,31.816,SAI,SOFT,36.435,SAI,SOFT,#64C4FF
27,Las Vegas Grand Prix,2025,29,00:01:53.657000,113.657,SAI,SOFT,26.956,SAI,SOFT,34.259,SAI,SOFT,48.421,LEC,MEDIUM,#64C4FF
9,Las Vegas Grand Prix,2025,11,00:01:35.954000,95.954,LEC,MEDIUM,26.988,LEC,MEDIUM,32.098,LEC,MEDIUM,36.594,ANT,MEDIUM,#E80020
11,Las Vegas Grand Prix,2025,13,00:01:35.699000,95.699,RUS,SOFT,27.048,RUS,SOFT,31.833,GAS,MEDIUM,36.452,RUS,SOFT,#27F4D2
5,Las Vegas Grand Prix,2025,7,00:01:36.043000,96.043,VER,MEDIUM,27.058,VER,MEDIUM,32.297,HAD,MEDIUM,36.605,VER,MEDIUM,#3860C6
7,Las Vegas Grand Prix,2025,9,00:01:35.776000,95.776,VER,MEDIUM,27.149,VER,MEDIUM,31.996,ALO,SOFT,36.466,VER,MEDIUM,#3860C6
8,Las Vegas Grand Prix,2025,10,00:01:36.083000,96.083,RUS,MEDIUM,27.211,SAI,MEDIUM,31.684,RUS,MEDIUM,36.645,RUS,MEDIUM,#27F4D2
3,Las Vegas Grand Prix,2025,5,00:01:36.493000,96.493,VER,MEDIUM,27.287,VER,MEDIUM,32.383,ALB,MEDIUM,36.737,VER,MEDIUM,#3860C6
4,Las Vegas Grand Prix,2025,6,00:01:36.758000,96.758,NOR,MEDIUM,27.325,ALO,SOFT,31.833,NOR,MEDIUM,36.719,PIA,MEDIUM,#FF8000
6,Las Vegas Grand Prix,2025,8,00:01:36.250000,96.250,PIA,MEDIUM,27.335,PIA,MEDIUM,31.718,STR,MEDIUM,36.581,RUS,MEDIUM,#FF8000
22,Las Vegas Grand Prix,2025,24,00:01:37.886000,97.886,PIA,SOFT,27.615,PIA,SOFT,32.562,OCO,SOFT,36.950,PIA,SOFT,#FF8000
24,Las Vegas Grand Prix,2025,26,00:01:37.732000,97.732,LEC,MEDIUM,27.814,LEC,MEDIUM,32.727,LEC,MEDIUM,37.191,LEC,MEDIUM,#E80020
2,Las Vegas Grand Prix,2025,4,00:01:37.685000,97.685,PIA,MEDIUM,27.903,PIA,MEDIUM,32.894,PIA,MEDIUM,36.888,PIA,MEDIUM,#FF8000
1,Las Vegas Grand Prix,2025,3,00:01:38.011000,98.011,VER,MEDIUM,27.912,NOR,MEDIUM,33.061,RUS,MEDIUM,37.005,VER,MEDIUM,#3860C6
0,Las Vegas Grand Prix,2025,2,00:01:38.686000,98.686,PIA,MEDIUM,28.475,PIA,MEDIUM,33.008,PIA,MEDIUM,37.203,PIA,MEDIUM,#FF8000
28,Las Vegas Grand Prix,2025,30,00:01:50.150000,110.150,HAD,SOFT,31.815,HAD,SOFT,33.145,HAD,SOFT,44.633,ANT,MEDIUM,#6692FF
29,Las Vegas Grand Prix,2025,31,00:02:10.312000,130.312,SAI,SOFT,54.743,SAI,SOFT,32.567,SAI,SOFT,42.484,SAI,SOFT,#64C4FF

In [16]:
LapTime_fp1_ordered.sort_values(by=['Time S2 (s)'])

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
18,Las Vegas Grand Prix,2025,20,00:01:35.460000,95.460,PIA,SOFT,26.729,HAM,SOFT,31.340,ANT,SOFT,36.395,PIA,SOFT,#FF8000
26,Las Vegas Grand Prix,2025,28,00:01:35.299000,95.299,HAD,SOFT,26.859,HAD,SOFT,31.493,HAD,SOFT,36.420,HAD,SOFT,#6692FF
10,Las Vegas Grand Prix,2025,12,00:01:35.561000,95.561,HAM,SOFT,26.912,HAM,SOFT,31.670,SAI,MEDIUM,36.624,HAM,SOFT,#E80020
8,Las Vegas Grand Prix,2025,10,00:01:36.083000,96.083,RUS,MEDIUM,27.211,SAI,MEDIUM,31.684,RUS,MEDIUM,36.645,RUS,MEDIUM,#27F4D2
6,Las Vegas Grand Prix,2025,8,00:01:36.250000,96.250,PIA,MEDIUM,27.335,PIA,MEDIUM,31.718,STR,MEDIUM,36.581,RUS,MEDIUM,#FF8000
19,Las Vegas Grand Prix,2025,21,00:01:34.802000,94.802,LEC,SOFT,26.748,ALB,SOFT,31.724,LEC,SOFT,36.287,LEC,SOFT,#E80020
17,Las Vegas Grand Prix,2025,19,00:01:35.071000,95.071,TSU,SOFT,26.704,HAM,SOFT,31.748,LEC,SOFT,36.256,TSU,SOFT,#3860C6
14,Las Vegas Grand Prix,2025,16,00:01:34.968000,94.968,ALB,SOFT,26.711,HAM,SOFT,31.761,ALB,SOFT,36.295,ALB,SOFT,#64C4FF
23,Las Vegas Grand Prix,2025,25,00:01:35.179000,95.179,SAI,SOFT,26.928,SAI,SOFT,31.816,SAI,SOFT,36.435,SAI,SOFT,#64C4FF
4,Las Vegas Grand Prix,2025,6,00:01:36.758000,96.758,NOR,MEDIUM,27.325,ALO,SOFT,31.833,NOR,MEDIUM,36.719,PIA,MEDIUM,#FF8000
11,Las Vegas Grand Prix,2025,13,00:01:35.699000,95.699,RUS,SOFT,27.048,RUS,SOFT,31.833,GAS,MEDIUM,36.452,RUS,SOFT,#27F4D2
13,Las Vegas Grand Prix,2025,15,00:01:35.281000,95.281,LEC,SOFT,26.747,HAM,SOFT,31.858,LEC,SOFT,36.430,RUS,SOFT,#E80020
21,Las Vegas Grand Prix,2025,23,00:01:35.117000,95.117,TSU,SOFT,26.707,TSU,SOFT,31.860,LAW,SOFT,36.536,TSU,SOFT,#3860C6
16,Las Vegas Grand Prix,2025,18,00:01:35.568000,95.568,ANT,SOFT,26.828,HAM,SOFT,31.886,ANT,SOFT,36.598,ANT,SOFT,#27F4D2
15,Las Vegas Grand Prix,2025,17,00:01:35.121000,95.121,LEC,SOFT,26.770,LEC,SOFT,31.942,LEC,SOFT,36.409,LEC,SOFT,#E80020
7,Las Vegas Grand Prix,2025,9,00:01:35.776000,95.776,VER,MEDIUM,27.149,VER,MEDIUM,31.996,ALO,SOFT,36.466,VER,MEDIUM,#3860C6
12,Las Vegas Grand Prix,2025,14,00:01:35.109000,95.109,VER,SOFT,26.705,VER,SOFT,32.068,VER,SOFT,36.336,VER,SOFT,#3860C6
9,Las Vegas Grand Prix,2025,11,00:01:35.954000,95.954,LEC,MEDIUM,26.988,LEC,MEDIUM,32.098,LEC,MEDIUM,36.594,ANT,MEDIUM,#E80020
20,Las Vegas Grand Prix,2025,22,00:01:35.450000,95.450,PIA,SOFT,26.927,PIA,SOFT,32.156,PIA,SOFT,36.367,PIA,SOFT,#FF8000
5,Las Vegas Grand Prix,2025,7,00:01:36.043000,96.043,VER,MEDIUM,27.058,VER,MEDIUM,32.297,HAD,MEDIUM,36.605,VER,MEDIUM,#3860C6
3,Las Vegas Grand Prix,2025,5,00:01:36.493000,96.493,VER,MEDIUM,27.287,VER,MEDIUM,32.383,ALB,MEDIUM,36.737,VER,MEDIUM,#3860C6
22,Las Vegas Grand Prix,2025,24,00:01:37.886000,97.886,PIA,SOFT,27.615,PIA,SOFT,32.562,OCO,SOFT,36.950,PIA,SOFT,#FF8000
29,Las Vegas Grand Prix,2025,31,00:02:10.312000,130.312,SAI,SOFT,54.743,SAI,SOFT,32.567,SAI,SOFT,42.484,SAI,SOFT,#64C4FF
25,Las Vegas Grand Prix,2025,27,00:01:38.020000,98.020,LEC,MEDIUM,26.793,SAI,SOFT,32.726,LEC,MEDIUM,37.204,LEC,MEDIUM,#E80020
24,Las Vegas Grand Prix,2025,26,00:01:37.732000,97.732,LEC,MEDIUM,27.814,LEC,MEDIUM,32.727,LEC,MEDIUM,37.191,LEC,MEDIUM,#E80020
2,Las Vegas Grand Prix,2025,4,00:01:37.685000,97.685,PIA,MEDIUM,27.903,PIA,MEDIUM,32.894,PIA,MEDIUM,36.888,PIA,MEDIUM,#FF8000
0,Las Vegas Grand Prix,2025,2,00:01:38.686000,98.686,PIA,MEDIUM,28.475,PIA,MEDIUM,33.008,PIA,MEDIUM,37.203,PIA,MEDIUM,#FF8000
1,Las Vegas Grand Prix,2025,3,00:01:38.011000,98.011,VER,MEDIUM,27.912,NOR,MEDIUM,33.061,RUS,MEDIUM,37.005,VER,MEDIUM,#3860C6
28,Las Vegas Grand Prix,2025,30,00:01:50.150000,110.150,HAD,SOFT,31.815,HAD,SOFT,33.145,HAD,SOFT,44.633,ANT,MEDIUM,#6692FF
27,Las Vegas Grand Prix,2025,29,00:01:53.657000,113.657,SAI,SOFT,26.956,SAI,SOFT,34.259,SAI,SOFT,48.421,LEC,MEDIUM,#64C4FF

In [17]:
LapTime_fp1_ordered.sort_values(by=['Time S3 (s)'])

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
17,Las Vegas Grand Prix,2025,19,00:01:35.071000,95.071,TSU,SOFT,26.704,HAM,SOFT,31.748,LEC,SOFT,36.256,TSU,SOFT,#3860C6
19,Las Vegas Grand Prix,2025,21,00:01:34.802000,94.802,LEC,SOFT,26.748,ALB,SOFT,31.724,LEC,SOFT,36.287,LEC,SOFT,#E80020
14,Las Vegas Grand Prix,2025,16,00:01:34.968000,94.968,ALB,SOFT,26.711,HAM,SOFT,31.761,ALB,SOFT,36.295,ALB,SOFT,#64C4FF
12,Las Vegas Grand Prix,2025,14,00:01:35.109000,95.109,VER,SOFT,26.705,VER,SOFT,32.068,VER,SOFT,36.336,VER,SOFT,#3860C6
20,Las Vegas Grand Prix,2025,22,00:01:35.450000,95.450,PIA,SOFT,26.927,PIA,SOFT,32.156,PIA,SOFT,36.367,PIA,SOFT,#FF8000
18,Las Vegas Grand Prix,2025,20,00:01:35.460000,95.460,PIA,SOFT,26.729,HAM,SOFT,31.340,ANT,SOFT,36.395,PIA,SOFT,#FF8000
15,Las Vegas Grand Prix,2025,17,00:01:35.121000,95.121,LEC,SOFT,26.770,LEC,SOFT,31.942,LEC,SOFT,36.409,LEC,SOFT,#E80020
26,Las Vegas Grand Prix,2025,28,00:01:35.299000,95.299,HAD,SOFT,26.859,HAD,SOFT,31.493,HAD,SOFT,36.420,HAD,SOFT,#6692FF
13,Las Vegas Grand Prix,2025,15,00:01:35.281000,95.281,LEC,SOFT,26.747,HAM,SOFT,31.858,LEC,SOFT,36.430,RUS,SOFT,#E80020
23,Las Vegas Grand Prix,2025,25,00:01:35.179000,95.179,SAI,SOFT,26.928,SAI,SOFT,31.816,SAI,SOFT,36.435,SAI,SOFT,#64C4FF
11,Las Vegas Grand Prix,2025,13,00:01:35.699000,95.699,RUS,SOFT,27.048,RUS,SOFT,31.833,GAS,MEDIUM,36.452,RUS,SOFT,#27F4D2
7,Las Vegas Grand Prix,2025,9,00:01:35.776000,95.776,VER,MEDIUM,27.149,VER,MEDIUM,31.996,ALO,SOFT,36.466,VER,MEDIUM,#3860C6
21,Las Vegas Grand Prix,2025,23,00:01:35.117000,95.117,TSU,SOFT,26.707,TSU,SOFT,31.860,LAW,SOFT,36.536,TSU,SOFT,#3860C6
6,Las Vegas Grand Prix,2025,8,00:01:36.250000,96.250,PIA,MEDIUM,27.335,PIA,MEDIUM,31.718,STR,MEDIUM,36.581,RUS,MEDIUM,#FF8000
9,Las Vegas Grand Prix,2025,11,00:01:35.954000,95.954,LEC,MEDIUM,26.988,LEC,MEDIUM,32.098,LEC,MEDIUM,36.594,ANT,MEDIUM,#E80020
16,Las Vegas Grand Prix,2025,18,00:01:35.568000,95.568,ANT,SOFT,26.828,HAM,SOFT,31.886,ANT,SOFT,36.598,ANT,SOFT,#27F4D2
5,Las Vegas Grand Prix,2025,7,00:01:36.043000,96.043,VER,MEDIUM,27.058,VER,MEDIUM,32.297,HAD,MEDIUM,36.605,VER,MEDIUM,#3860C6
10,Las Vegas Grand Prix,2025,12,00:01:35.561000,95.561,HAM,SOFT,26.912,HAM,SOFT,31.670,SAI,MEDIUM,36.624,HAM,SOFT,#E80020
8,Las Vegas Grand Prix,2025,10,00:01:36.083000,96.083,RUS,MEDIUM,27.211,SAI,MEDIUM,31.684,RUS,MEDIUM,36.645,RUS,MEDIUM,#27F4D2
4,Las Vegas Grand Prix,2025,6,00:01:36.758000,96.758,NOR,MEDIUM,27.325,ALO,SOFT,31.833,NOR,MEDIUM,36.719,PIA,MEDIUM,#FF8000
3,Las Vegas Grand Prix,2025,5,00:01:36.493000,96.493,VER,MEDIUM,27.287,VER,MEDIUM,32.383,ALB,MEDIUM,36.737,VER,MEDIUM,#3860C6
2,Las Vegas Grand Prix,2025,4,00:01:37.685000,97.685,PIA,MEDIUM,27.903,PIA,MEDIUM,32.894,PIA,MEDIUM,36.888,PIA,MEDIUM,#FF8000
22,Las Vegas Grand Prix,2025,24,00:01:37.886000,97.886,PIA,SOFT,27.615,PIA,SOFT,32.562,OCO,SOFT,36.950,PIA,SOFT,#FF8000
1,Las Vegas Grand Prix,2025,3,00:01:38.011000,98.011,VER,MEDIUM,27.912,NOR,MEDIUM,33.061,RUS,MEDIUM,37.005,VER,MEDIUM,#3860C6
24,Las Vegas Grand Prix,2025,26,00:01:37.732000,97.732,LEC,MEDIUM,27.814,LEC,MEDIUM,32.727,LEC,MEDIUM,37.191,LEC,MEDIUM,#E80020
0,Las Vegas Grand Prix,2025,2,00:01:38.686000,98.686,PIA,MEDIUM,28.475,PIA,MEDIUM,33.008,PIA,MEDIUM,37.203,PIA,MEDIUM,#FF8000
25,Las Vegas Grand Prix,2025,27,00:01:38.020000,98.020,LEC,MEDIUM,26.793,SAI,SOFT,32.726,LEC,MEDIUM,37.204,LEC,MEDIUM,#E80020
29,Las Vegas Grand Prix,2025,31,00:02:10.312000,130.312,SAI,SOFT,54.743,SAI,SOFT,32.567,SAI,SOFT,42.484,SAI,SOFT,#64C4FF
28,Las Vegas Grand Prix,2025,30,00:01:50.150000,110.150,HAD,SOFT,31.815,HAD,SOFT,33.145,HAD,SOFT,44.633,ANT,MEDIUM,#6692FF
27,Las Vegas Grand Prix,2025,29,00:01:53.657000,113.657,SAI,SOFT,26.956,SAI,SOFT,34.259,SAI,SOFT,48.421,LEC,MEDIUM,#64C4FF

In [18]:
import plotly.graph_objects as go

fig_fp1 = go.Figure(go.Table
 (header={"values": LapTime_fp1_ordered.columns},
  cells=dict(
    values=LapTime_fp1_ordered.T.values,
    fill_color=[LapTime_fp1_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp1.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp1_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp1_ordered.loc[LapTime_fp1_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp1_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp1.update_layout(
    title="FP1 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp1.show()

In [19]:
save_year=2025

In [20]:
fig_fp1.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP1/{}/{} {} FP1 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [24]:
# FP2

In [21]:
df_bq_fp2=df_bq2_fp2[(df_bq2_fp2["GP"]==race)&(df_bq2_fp2["Year"]==2025)]
GP_fp2=df_bq_fp2
GP_fp2["LapNumber"]=GP_fp2["LapNumber"].astype(int)
GP_fp2=GP_fp2.sort_values(['Driver','LapNumber'])
GP_fp2["DriverNumber"]=GP_fp2["DriverNumber"].astype(int)
year=GP_fp2['Year'].iloc[0]
gp=GP_fp2['GP'].iloc[0]
GP_fp2.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_37770/2277067741.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
111,0 days 00:23:16.295000,ALB,23,NaT,1,1.0,0 days 00:21:28.222000,NaT,NaT,0 days 00:00:39.510000,0 days 00:00:40.588000,NaT,0 days 00:22:35.961000,0 days 00:23:16.478000,163.0,186.0,305.0,281.0,False,MEDIUM,1.0,True,Williams,0 days 00:21:28.222000,2025-11-21 04:07:34.733,1,NaN,False,,False,False,2025,Las Vegas Grand Prix
112,0 days 00:25:07.751000,ALB,23,0 days 00:01:51.456000,2,1.0,NaT,NaT,0 days 00:00:29.988000,0 days 00:00:36.684000,0 days 00:00:44.784000,0 days 00:23:46.283000,0 days 00:24:22.967000,0 days 00:25:07.751000,166.0,200.0,314.0,227.0,True,MEDIUM,2.0,True,Williams,0 days 00:23:16.295000,2025-11-21 04:09:22.806,1,NaN,False,,False,True,2025,Las Vegas Grand Prix
113,0 days 00:26:44.808000,ALB,23,0 days 00:01:37.057000,3,1.0,NaT,NaT,0 days 00:00:27.331000,0 days 00:00:32.826000,0 days 00:00:36.900000,0 days 00:25:35.082000,0 days 00:26:07.908000,0 days 00:26:44.808000,186.0,207.0,320.0,317.0,True,MEDIUM,3.0,True,Williams,0 days 00:25:07.751000,2025-11-21 04:11:14.262,1,NaN,False,,False,True,2025,Las Vegas Grand Prix
114,0 days 00:28:44.293000,ALB,23,0 days 00:01:59.485000,4,1.0,NaT,NaT,0 days 00:00:39.456000,0 days 00:00:41.989000,0 days 00:00:38.040000,0 days 00:27:24.264000,0 days 00:28:06.253000,0 days 00:28:44.293000,115.0,193.0,320.0,306.0,False,MEDIUM,4.0,True,Williams,0 days 00:26:44.808000,2025-11-21 04:12:51.319,1,NaN,False,,False,True,2025,Las Vegas Grand Prix
115,0 days 00:30:19.722000,ALB,23,0 days 00:01:35.429000,5,1.0,NaT,NaT,0 days 00:00:27.022000,0 days 00:00:32.027000,0 days 00:00:36.380000,0 days 00:29:11.315000,0 days 00:29:43.342000,0 days 00:30:19.722000,186.0,213.0,320.0,339.0,True,MEDIUM,5.0,True,Williams,0 days 00:28:44.293000,2025-11-21 04:14:50.804,12,NaN,False,,False,True,2025,Las Vegas Grand Prix

In [22]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp2['LapTime_TD']= pd.to_timedelta(GP_fp2["LapTime"])
GP_fp2["LapTime"]=GP_fp2['LapTime'].str.split('days ').str[1]
GP_fp2.loc[:, "LapTime (s)"] = GP_fp2["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [23]:
GP_fp2['s1_TD']= pd.to_timedelta(GP_fp2["Sector1Time"])
GP_fp2['s2_TD']= pd.to_timedelta(GP_fp2["Sector2Time"])
GP_fp2['s3_TD']= pd.to_timedelta(GP_fp2["Sector3Time"])

GP_fp2.loc[:, "Time S1 (s)"] = GP_fp2["s1_TD"].dt.total_seconds()
GP_fp2.loc[:, "Time S2 (s)"] = GP_fp2["s2_TD"].dt.total_seconds()
GP_fp2.loc[:, "Time S3 (s)"] = GP_fp2["s3_TD"].dt.total_seconds()

In [24]:
GP_fp2_Rk=GP_fp2[GP_fp2["LapTime"]!="NaT"]
GP_fp2_Rk["LAP_RK"] = GP_fp2_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S1_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S2_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["S3_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp2_Rk["Race_RK"] = GP_fp2_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [25]:
GP_fp2_Sectors=GP_fp2_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp2_Sectors=GP_fp2_Sectors.fillna(0)
GP_fp2_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
111,ALB,1,0.0,39.510,40.588,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,14.0,10.0
51,ALO,1,0.0,35.987,39.360,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,2.0,2.0
34,ANT,1,0.0,40.361,42.554,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,15.0,16.0
297,BEA,1,0.0,39.508,41.523,0,0.0,MEDIUM,2025,Las Vegas Grand Prix,0.0,0.0,13.0,13.0
221,BOR,1,0.0,41.410,40.265,0,0.0,HARD,2025,Las Vegas Grand Prix,0.0,0.0,17.0,9.0

In [26]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp2=GP_fp2_Sectors[GP_fp2_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp2.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp2.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp2.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp2.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp2=Fastest_Lap_fp2.merge(Fastest_sector1_fp2,on=['LapNumber']).merge(Fastest_sector2_fp2,on=['LapNumber']).merge(Fastest_sector3_fp2,on=['LapNumber'])
Fast_Laps_fp2=Fast_Laps_fp2[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp2=Fast_Laps_fp2.reset_index(drop=True)
Fast_Laps_fp2.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Las Vegas Grand Prix,2025,2,00:01:36.288000,96.288,PIA,MEDIUM,27.513,NOR,MEDIUM,32.239,NOR,MEDIUM,36.123,PIA,MEDIUM
1,Las Vegas Grand Prix,2025,3,00:01:34.713000,94.713,NOR,MEDIUM,26.714,NOR,MEDIUM,31.632,NOR,MEDIUM,36.367,NOR,MEDIUM
2,Las Vegas Grand Prix,2025,4,00:01:34.740000,94.740,PIA,MEDIUM,26.869,ALO,MEDIUM,31.699,PIA,MEDIUM,36.095,PIA,MEDIUM
3,Las Vegas Grand Prix,2025,5,00:01:33.943000,93.943,NOR,MEDIUM,26.527,NOR,MEDIUM,31.470,NOR,MEDIUM,35.946,NOR,MEDIUM
4,Las Vegas Grand Prix,2025,6,00:01:34.493000,94.493,PIA,MEDIUM,26.757,PIA,MEDIUM,31.659,PIA,MEDIUM,36.077,PIA,MEDIUM

In [27]:
Fast_Laps_fp2['color'] = Fast_Laps_fp2['Fastest Lap'].apply(driver_color)
Fast_Laps_fp2.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Las Vegas Grand Prix,2025,2,00:01:36.288000,96.288,PIA,MEDIUM,27.513,NOR,MEDIUM,32.239,NOR,MEDIUM,36.123,PIA,MEDIUM,#FF8000
1,Las Vegas Grand Prix,2025,3,00:01:34.713000,94.713,NOR,MEDIUM,26.714,NOR,MEDIUM,31.632,NOR,MEDIUM,36.367,NOR,MEDIUM,#FF8000
2,Las Vegas Grand Prix,2025,4,00:01:34.740000,94.740,PIA,MEDIUM,26.869,ALO,MEDIUM,31.699,PIA,MEDIUM,36.095,PIA,MEDIUM,#FF8000
3,Las Vegas Grand Prix,2025,5,00:01:33.943000,93.943,NOR,MEDIUM,26.527,NOR,MEDIUM,31.470,NOR,MEDIUM,35.946,NOR,MEDIUM,#FF8000
4,Las Vegas Grand Prix,2025,6,00:01:34.493000,94.493,PIA,MEDIUM,26.757,PIA,MEDIUM,31.659,PIA,MEDIUM,36.077,PIA,MEDIUM,#FF8000

In [28]:
LapTime_fp2_ordered=Fast_Laps_fp2.sort_values(by=['LapTime (s)'])
LapTime_fp2_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
8,Las Vegas Grand Prix,2025,10,00:01:33.602000,93.602,NOR,SOFT,26.332,NOR,SOFT,31.225,NOR,SOFT,35.911,LEC,MEDIUM,#FF8000
13,Las Vegas Grand Prix,2025,15,00:01:33.631000,93.631,ANT,SOFT,26.273,HAM,SOFT,31.298,ANT,SOFT,35.908,ANT,SOFT,#27F4D2
12,Las Vegas Grand Prix,2025,14,00:01:33.815000,93.815,LEC,SOFT,26.390,TSU,SOFT,31.431,LEC,SOFT,35.938,LEC,SOFT,#E80020
9,Las Vegas Grand Prix,2025,11,00:01:33.879000,93.879,HUL,SOFT,26.468,RUS,MEDIUM,31.395,HUL,SOFT,35.817,HUL,SOFT,#52e252
11,Las Vegas Grand Prix,2025,13,00:01:33.893000,93.893,HAD,SOFT,26.340,SAI,SOFT,31.354,HAD,SOFT,36.029,HAD,SOFT,#6692FF

In [29]:
import plotly.graph_objects as go
# colors = n_colors('rgb(255, 200, 200)', 'rgb(200, 0, 0)', 9, colortype='rgb')

fig_fp2 = go.Figure(go.Table
 (header={"values": LapTime_fp2_ordered.columns},
  cells=dict(
    values=LapTime_fp2_ordered.T.values,
    fill_color=[LapTime_fp2_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp2.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp2_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp2_ordered.loc[LapTime_fp2_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp2_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp2.update_layout(
    title="FP2 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp2.show()

In [30]:
fig_fp2.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP2/{}/{} {} FP2 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [30]:
# FP3

In [31]:
df_bq_fp3=df_bq2_fp3[(df_bq2_fp3["GP"]==race)&(df_bq2_fp3["Year"]==2025)]
GP_fp3=df_bq_fp3
GP_fp3["LapNumber"]=GP_fp3["LapNumber"].astype(int)
GP_fp3=GP_fp3.sort_values(['Driver','LapNumber'])
GP_fp3["DriverNumber"]=GP_fp3["DriverNumber"].astype(int)
year=GP_fp3['Year'].iloc[0]
gp=GP_fp3['GP'].iloc[0]
GP_fp3.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_37770/2774860751.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
138,0 days 00:24:31.383000,ALB,23,NaT,1,1.0,0 days 00:22:44.841000,NaT,NaT,0 days 00:00:37.842000,0 days 00:00:39.870000,NaT,0 days 00:23:51.753000,0 days 00:24:31.565000,157.0,193.0,284.0,268.0,False,INTERMEDIATE,1.0,True,Williams,0 days 00:22:44.841000,2025-11-22 00:38:26.168,1,NaN,False,,False,False,2025,Las Vegas Grand Prix
139,0 days 00:26:39.718000,ALB,23,0 days 00:02:08.335000,2,1.0,NaT,NaT,0 days 00:00:51.299000,0 days 00:00:38.198000,0 days 00:00:38.838000,0 days 00:25:22.682000,0 days 00:26:00.880000,0 days 00:26:39.718000,140.0,197.0,307.0,282.0,True,INTERMEDIATE,2.0,True,Williams,0 days 00:24:31.383000,2025-11-22 00:40:12.710,12,NaN,False,,False,True,2025,Las Vegas Grand Prix
140,0 days 00:28:26.191000,ALB,23,0 days 00:01:46.473000,3,1.0,NaT,NaT,0 days 00:00:31.199000,0 days 00:00:36.403000,0 days 00:00:38.871000,0 days 00:27:10.917000,0 days 00:27:47.320000,0 days 00:28:26.191000,154.0,195.0,306.0,311.0,True,INTERMEDIATE,3.0,True,Williams,0 days 00:26:39.718000,2025-11-22 00:42:21.045,1,NaN,False,,False,True,2025,Las Vegas Grand Prix
141,0 days 00:30:43.449000,ALB,23,0 days 00:02:17.258000,4,1.0,NaT,NaT,0 days 00:00:47.842000,0 days 00:00:47.450000,0 days 00:00:41.966000,0 days 00:29:14.033000,0 days 00:30:01.483000,0 days 00:30:43.449000,130.0,147.0,312.0,254.0,False,INTERMEDIATE,4.0,True,Williams,0 days 00:28:26.191000,2025-11-22 00:44:07.518,1,NaN,False,,False,True,2025,Las Vegas Grand Prix
142,0 days 00:32:28.477000,ALB,23,0 days 00:01:45.028000,5,1.0,NaT,NaT,0 days 00:00:30.298000,0 days 00:00:36.241000,0 days 00:00:38.489000,0 days 00:31:13.747000,0 days 00:31:49.988000,0 days 00:32:28.477000,160.0,197.0,309.0,316.0,True,INTERMEDIATE,5.0,True,Williams,0 days 00:30:43.449000,2025-11-22 00:46:24.776,1,NaN,False,,False,True,2025,Las Vegas Grand Prix

In [32]:
#Convert LapTime to Time Delta for plotting on Y Axis
GP_fp3['LapTime_TD']= pd.to_timedelta(GP_fp3["LapTime"])
GP_fp3["LapTime"]=GP_fp3['LapTime'].str.split('days ').str[1]
GP_fp3.loc[:, "LapTime (s)"] = GP_fp3["LapTime_TD"].dt.total_seconds()

# Fastest Driver in each lap

In [33]:
GP_fp3['s1_TD']= pd.to_timedelta(GP_fp3["Sector1Time"])
GP_fp3['s2_TD']= pd.to_timedelta(GP_fp3["Sector2Time"])
GP_fp3['s3_TD']= pd.to_timedelta(GP_fp3["Sector3Time"])

GP_fp3.loc[:, "Time S1 (s)"] = GP_fp3["s1_TD"].dt.total_seconds()
GP_fp3.loc[:, "Time S2 (s)"] = GP_fp3["s2_TD"].dt.total_seconds()
GP_fp3.loc[:, "Time S3 (s)"] = GP_fp3["s3_TD"].dt.total_seconds()

In [34]:
GP_fp3_Rk=GP_fp3[GP_fp3["LapTime"]!="NaT"]
GP_fp3_Rk["LAP_RK"] = GP_fp3_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S1_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S2_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["S3_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
GP_fp3_Rk["Race_RK"] = GP_fp3_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

In [35]:
GP_fp3_Sectors=GP_fp3_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
GP_fp3_Sectors=GP_fp3_Sectors.fillna(0)
GP_fp3_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()

,Driver,LapNumber,Time S1 (s),Time S2 (s),Time S3 (s),LapTime,LapTime (s),Compound,Year,GP,LAP_RK,S1_RK,S2_RK,S3_RK
138,ALB,1,0.0,37.842,39.870,0,0.0,INTERMEDIATE,2025,Las Vegas Grand Prix,0.0,0.0,1.0,2.0
64,ALO,1,0.0,42.620,42.905,0,0.0,INTERMEDIATE,2025,Las Vegas Grand Prix,0.0,0.0,15.0,13.0
41,ANT,1,0.0,42.808,46.175,0,0.0,INTERMEDIATE,2025,Las Vegas Grand Prix,0.0,0.0,17.0,16.0
388,BEA,1,0.0,45.356,51.917,0,0.0,INTERMEDIATE,2025,Las Vegas Grand Prix,0.0,0.0,19.0,19.0
283,BOR,1,0.0,47.627,45.328,0,0.0,SOFT,2025,Las Vegas Grand Prix,0.0,0.0,20.0,15.0

In [36]:
#get a combined view for fastest drivers in the entire lap, S1, S2, and S3
Fastest_Lap_fp3=GP_fp3_Sectors[GP_fp3_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_Lap_fp3.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
Fastest_sector1_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector1_fp3.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
Fastest_sector2_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector2_fp3.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
Fastest_sector3_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
Fastest_sector3_fp3.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
Fast_Laps_fp3=Fastest_Lap_fp3.merge(Fastest_sector1_fp3,on=['LapNumber']).merge(Fastest_sector2_fp3,on=['LapNumber']).merge(Fastest_sector3_fp3,on=['LapNumber'])
Fast_Laps_fp3=Fast_Laps_fp3[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
Fast_Laps_fp3=Fast_Laps_fp3.reset_index(drop=True)
Fast_Laps_fp3.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound
0,Las Vegas Grand Prix,2025,2,00:01:43.254000,103.254,GAS,SOFT,30.231,RUS,INTERMEDIATE,35.027,GAS,SOFT,37.671,GAS,SOFT
1,Las Vegas Grand Prix,2025,3,00:01:39.163000,99.163,GAS,SOFT,28.619,GAS,SOFT,33.349,GAS,SOFT,37.133,HUL,SOFT
2,Las Vegas Grand Prix,2025,4,00:01:37.437000,97.437,GAS,SOFT,27.832,GAS,SOFT,32.796,GAS,SOFT,36.773,HUL,SOFT
3,Las Vegas Grand Prix,2025,5,00:01:37.483000,97.483,STR,SOFT,27.894,STR,SOFT,32.847,STR,SOFT,36.742,STR,SOFT
4,Las Vegas Grand Prix,2025,6,00:01:36.650000,96.650,HUL,SOFT,27.492,GAS,SOFT,32.461,HUL,SOFT,36.226,HUL,SOFT

In [37]:
Fast_Laps_fp3['color'] = Fast_Laps_fp3['Fastest Lap'].apply(driver_color)
Fast_Laps_fp3.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
0,Las Vegas Grand Prix,2025,2,00:01:43.254000,103.254,GAS,SOFT,30.231,RUS,INTERMEDIATE,35.027,GAS,SOFT,37.671,GAS,SOFT,#0093cc
1,Las Vegas Grand Prix,2025,3,00:01:39.163000,99.163,GAS,SOFT,28.619,GAS,SOFT,33.349,GAS,SOFT,37.133,HUL,SOFT,#0093cc
2,Las Vegas Grand Prix,2025,4,00:01:37.437000,97.437,GAS,SOFT,27.832,GAS,SOFT,32.796,GAS,SOFT,36.773,HUL,SOFT,#0093cc
3,Las Vegas Grand Prix,2025,5,00:01:37.483000,97.483,STR,SOFT,27.894,STR,SOFT,32.847,STR,SOFT,36.742,STR,SOFT,#229971
4,Las Vegas Grand Prix,2025,6,00:01:36.650000,96.650,HUL,SOFT,27.492,GAS,SOFT,32.461,HUL,SOFT,36.226,HUL,SOFT,#52e252

In [38]:
LapTime_fp3_ordered=Fast_Laps_fp3.sort_values(by=['LapTime (s)'])
LapTime_fp3_ordered.head()

,GP,Year,LapNumber,LapTime,LapTime (s),Fastest Lap,Lap Compound,Time S1 (s),Fastest S1,S1 Compound,Time S2 (s),Fastest S2,S2 Compound,Time S3 (s),Fastest S3,S3 Compound,color
17,Las Vegas Grand Prix,2025,19,00:01:34.054000,94.054,RUS,SOFT,26.816,RUS,SOFT,31.579,RUS,SOFT,35.659,RUS,SOFT,#27F4D2
22,Las Vegas Grand Prix,2025,24,00:01:34.281000,94.281,VER,SOFT,26.828,VER,SOFT,31.785,VER,SOFT,35.668,VER,SOFT,#3860C6
15,Las Vegas Grand Prix,2025,17,00:01:34.875000,94.875,ALB,SOFT,26.954,ALB,SOFT,31.861,RUS,SOFT,35.882,RUS,SOFT,#64C4FF
21,Las Vegas Grand Prix,2025,23,00:01:35.169000,95.169,HAD,SOFT,27.065,HAD,SOFT,32.225,HAD,SOFT,35.879,HAD,SOFT,#6692FF
23,Las Vegas Grand Prix,2025,25,00:01:35.269000,95.269,HAM,SOFT,27.308,HAM,SOFT,32.191,HAM,SOFT,35.770,HAM,SOFT,#E80020

In [39]:
import plotly.graph_objects as go
# colors = n_colors('rgb(255, 200, 200)', 'rgb(200, 0, 0)', 9, colortype='rgb')

fig_fp3 = go.Figure(go.Table
 (header={"values": LapTime_fp3_ordered.columns},
  cells=dict(
    values=LapTime_fp3_ordered.T.values,
    fill_color=[LapTime_fp3_ordered.color],
    align='center', font=dict(color='white', size=11)
    ))
 )

# fig_fp3.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": LapTime_fp3_ordered.T.values
#                                 if c == "All"
#                                 else LapTime_fp3_ordered.loc[LapTime_fp3_ordered["LapNumber"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + LapTime_fp3_ordered["LapNumber"].unique().tolist()
#             ]
#         }
#     ]
# )
fig_fp3.update_layout(
    title="FP3 Fastest Lap and Sector Times Ordered By Lap Times",
        title_x=0.5,
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=13,
        color="Black"
    ),
    height=780,
    width=1200,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig_fp3.show()

In [40]:
fig_fp3.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP3/{}/{} {} FP3 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year,year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi GP Plot FP1

In [40]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3860C6"
    elif driver =="TSU":
        return "#3860C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [41]:
save_year_multi=2025

In [42]:
#2025
race_multi=["Japanese Grand Prix","Bahrain Grand Prix","Saudi Arabian Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Spanish Grand Prix","Canadian Grand Prix","Austrian Grand Prix","British Grand Prix","Belgian Grand Prix","Hungarian Grand Prix","Dutch Grand Prix","Italian Grand Prix","Azerbaijan Grand Prix","Singapore Grand Prix","United States Grand Prix","Mexico City Grand Prix","São Paulo Grand Prix"]
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
# 2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2025
for i in race_multi:
    df_bq_fp1=df_bq2_fp1[(df_bq2_fp1["GP"]==i)&(df_bq2_fp1["Year"]==year_multi)]
    GP_fp1=df_bq_fp1
    GP_fp1["LapNumber"]=GP_fp1["LapNumber"].astype(int)
    GP_fp1=GP_fp1.sort_values(['Driver','LapNumber'])
    GP_fp1["DriverNumber"]=GP_fp1["DriverNumber"].astype(int)
    # year=GP_fp1['Year'].iloc[0]
    # gp=GP_fp1['GP'].iloc[0]
    GP_fp1['LapTime_TD']= pd.to_timedelta(GP_fp1["LapTime"])
    GP_fp1["LapTime"]=GP_fp1['LapTime'].str.split('days ').str[1]
    GP_fp1.loc[:, "LapTime (s)"] = GP_fp1["LapTime_TD"].dt.total_seconds()
    GP_fp1['s1_TD']= pd.to_timedelta(GP_fp1["Sector1Time"])
    GP_fp1['s2_TD']= pd.to_timedelta(GP_fp1["Sector2Time"])
    GP_fp1['s3_TD']= pd.to_timedelta(GP_fp1["Sector3Time"])

    GP_fp1.loc[:, "Time S1 (s)"] = GP_fp1["s1_TD"].dt.total_seconds()
    GP_fp1.loc[:, "Time S2 (s)"] = GP_fp1["s2_TD"].dt.total_seconds()
    GP_fp1.loc[:, "Time S3 (s)"] = GP_fp1["s3_TD"].dt.total_seconds()
    GP_fp1_Rk=GP_fp1[GP_fp1["LapTime"]!="NaT"]
    GP_fp1_Rk["LAP_RK"] = GP_fp1_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S1_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S2_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["S3_RK"] = GP_fp1_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
    GP_fp1_Rk["Race_RK"] = GP_fp1_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)
    GP_fp1_Sectors=GP_fp1_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
    GP_fp1_Sectors=GP_fp1_Sectors.fillna(0)
    Fastest_Lap_fp1=GP_fp1_Sectors[GP_fp1_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_Lap_fp1.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
    Fastest_sector1_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector1_fp1.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
    Fastest_sector2_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector2_fp1.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
    Fastest_sector3_fp1=GP_fp1_Sectors[GP_fp1_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
    Fastest_sector3_fp1.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
    Fast_Laps_fp1=Fastest_Lap_fp1.merge(Fastest_sector1_fp1,on=['LapNumber']).merge(Fastest_sector2_fp1,on=['LapNumber']).merge(Fastest_sector3_fp1,on=['LapNumber'])
    Fast_Laps_fp1=Fast_Laps_fp1[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
    Fast_Laps_fp1=Fast_Laps_fp1.reset_index(drop=True)
    Fast_Laps_fp1['color'] = Fast_Laps_fp1['Fastest Lap'].apply(driver_color)
    LapTime_fp1_ordered=Fast_Laps_fp1.sort_values(by=['LapTime (s)'])
    fig_fp1 = go.Figure(go.Table
    (header={"values": LapTime_fp1_ordered.columns},
    cells=dict(
        values=LapTime_fp1_ordered.T.values,
        fill_color=[LapTime_fp1_ordered.color],
        align='center', font=dict(color='white', size=11)
        ))
    )
    fig_fp1.update_layout(
        title="FP1 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi, i),
            title_x=0.5,
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=13,
            color="Black"
        ),
        height=780,
        width=1200,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig_fp1.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP1/{}/{} {} FP1 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi,year_multi, i),include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/807502903.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [43]:
#Multi GP Plot FP2

In [44]:
for i in race_multi:
    try:
        df_bq_fp2=df_bq2_fp2[(df_bq2_fp2["GP"]==i)&(df_bq2_fp2["Year"]==year_multi)]
        GP_fp2=df_bq_fp2
        GP_fp2["LapNumber"]=GP_fp2["LapNumber"].astype(int)
        GP_fp2=GP_fp2.sort_values(['Driver','LapNumber'])
        GP_fp2["DriverNumber"]=GP_fp2["DriverNumber"].astype(int)
        year=GP_fp2['Year'].iloc[0]
        gp=GP_fp2['GP'].iloc[0]
        #Convert LapTime to Time Delta for plotting on Y Axis
        GP_fp2['LapTime_TD']= pd.to_timedelta(GP_fp2["LapTime"])
        GP_fp2["LapTime"]=GP_fp2['LapTime'].str.split('days ').str[1]
        GP_fp2.loc[:, "LapTime (s)"] = GP_fp2["LapTime_TD"].dt.total_seconds()
        # Fastest Driver in each lap
        GP_fp2['s1_TD']= pd.to_timedelta(GP_fp2["Sector1Time"])
        GP_fp2['s2_TD']= pd.to_timedelta(GP_fp2["Sector2Time"])
        GP_fp2['s3_TD']= pd.to_timedelta(GP_fp2["Sector3Time"])

        GP_fp2.loc[:, "Time S1 (s)"] = GP_fp2["s1_TD"].dt.total_seconds()
        GP_fp2.loc[:, "Time S2 (s)"] = GP_fp2["s2_TD"].dt.total_seconds()
        GP_fp2.loc[:, "Time S3 (s)"] = GP_fp2["s3_TD"].dt.total_seconds()
        GP_fp2_Rk=GP_fp2[GP_fp2["LapTime"]!="NaT"]
        GP_fp2_Rk["LAP_RK"] = GP_fp2_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S1_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S2_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["S3_RK"] = GP_fp2_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
        GP_fp2_Rk["Race_RK"] = GP_fp2_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

        GP_fp2_Sectors=GP_fp2_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
        GP_fp2_Sectors=GP_fp2_Sectors.fillna(0)
        GP_fp2_Sectors.sort_values(by=["LapNumber","S1_RK"]).head()
        #get a combined view for fastest drivers in the entire lap, S1, S2, and S3
        Fastest_Lap_fp2=GP_fp2_Sectors[GP_fp2_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_Lap_fp2.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
        Fastest_sector1_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector1_fp2.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
        Fastest_sector2_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector2_fp2.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
        Fastest_sector3_fp2=GP_fp2_Sectors[GP_fp2_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector3_fp2.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
        Fast_Laps_fp2=Fastest_Lap_fp2.merge(Fastest_sector1_fp2,on=['LapNumber']).merge(Fastest_sector2_fp2,on=['LapNumber']).merge(Fastest_sector3_fp2,on=['LapNumber'])
        Fast_Laps_fp2=Fast_Laps_fp2[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
        Fast_Laps_fp2=Fast_Laps_fp2.reset_index(drop=True)
        Fast_Laps_fp2['color'] = Fast_Laps_fp2['Fastest Lap'].apply(driver_color)
        LapTime_fp2_ordered=Fast_Laps_fp2.sort_values(by=['LapTime (s)'])
        fig_fp2 = go.Figure(go.Table
        (header={"values": LapTime_fp2_ordered.columns},
        cells=dict(
            values=LapTime_fp2_ordered.T.values,
            fill_color=[LapTime_fp2_ordered.color],
            align='center', font=dict(color='white', size=11)
            ))
        )
        fig_fp2.update_layout(
            title="FP2 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi,i),
                title_x=0.5,
            yaxis = dict(tickfont = dict(size=15)),
            xaxis = dict(tickfont = dict(size=15)),
            font=dict(
                family="PT Sans Narrow",
                size=13,
                color="Black"
            ),
            height=780,
            width=1200,
            title_font_family="PT Sans Narrow",
            margin=dict(l=5, r=5, t=35, b=5),
        )
        fig_fp2.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP2/{}/{} {} FP2 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi,year_multi,i),include_plotlyjs='cdn')
    except:
        continue

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/3494421142.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [45]:
#Multi GP Plot FP3

In [46]:
for i in race_multi:
    try:
        df_bq_fp3=df_bq2_fp3[(df_bq2_fp3["GP"]==i)&(df_bq2_fp3["Year"]==year_multi)]
        GP_fp3=df_bq_fp3
        GP_fp3["LapNumber"]=GP_fp3["LapNumber"].astype(int)
        GP_fp3=GP_fp3.sort_values(['Driver','LapNumber'])
        GP_fp3["DriverNumber"]=GP_fp3["DriverNumber"].astype(int)
        year=GP_fp3['Year'].iloc[0]
        gp=GP_fp3['GP'].iloc[0]
        #Convert LapTime to Time Delta for plotting on Y Axis
        GP_fp3['LapTime_TD']= pd.to_timedelta(GP_fp3["LapTime"])
        GP_fp3["LapTime"]=GP_fp3['LapTime'].str.split('days ').str[1]
        GP_fp3.loc[:, "LapTime (s)"] = GP_fp3["LapTime_TD"].dt.total_seconds()
        # Fastest Driver in each lap
        GP_fp3['s1_TD']= pd.to_timedelta(GP_fp3["Sector1Time"])
        GP_fp3['s2_TD']= pd.to_timedelta(GP_fp3["Sector2Time"])
        GP_fp3['s3_TD']= pd.to_timedelta(GP_fp3["Sector3Time"])

        GP_fp3.loc[:, "Time S1 (s)"] = GP_fp3["s1_TD"].dt.total_seconds()
        GP_fp3.loc[:, "Time S2 (s)"] = GP_fp3["s2_TD"].dt.total_seconds()
        GP_fp3.loc[:, "Time S3 (s)"] = GP_fp3["s3_TD"].dt.total_seconds()
        GP_fp3_Rk=GP_fp3[GP_fp3["LapTime"]!="NaT"]
        GP_fp3_Rk["LAP_RK"] = GP_fp3_Rk.groupby("LapNumber")["LapTime (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S1_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S1 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S2_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S2 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["S3_RK"] = GP_fp3_Rk.groupby("LapNumber")["Time S3 (s)"].rank(method="dense", ascending=True)
        GP_fp3_Rk["Race_RK"] = GP_fp3_Rk.groupby("GP")["LapTime (s)"].rank(method="dense", ascending=True)

        GP_fp3_Sectors=GP_fp3_Rk[["Driver","LapNumber","Time S1 (s)","Time S2 (s)","Time S3 (s)","LapTime","LapTime (s)","Compound","Year","GP","LAP_RK","S1_RK","S2_RK","S3_RK"]]
        GP_fp3_Sectors=GP_fp3_Sectors.fillna(0)
        #get a combined view for fastest drivers in the entire lap, S1, S2, and S3
        Fastest_Lap_fp3=GP_fp3_Sectors[GP_fp3_Sectors["LAP_RK"]==1][["GP","Year","LapNumber","LapTime","LapTime (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_Lap_fp3.columns=["GP","Year","LapNumber","LapTime","LapTime (s)","Lap Compound","Fastest Lap"]
        Fastest_sector1_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S1_RK"]==1][["LapNumber","Time S1 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector1_fp3.columns=["LapNumber","Time S1 (s)","S1 Compound","Fastest S1"]
        Fastest_sector2_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S2_RK"]==1][["LapNumber","Time S2 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector2_fp3.columns=["LapNumber","Time S2 (s)","S2 Compound","Fastest S2"]
        Fastest_sector3_fp3=GP_fp3_Sectors[GP_fp3_Sectors["S3_RK"]==1][["LapNumber","Time S3 (s)","Compound","Driver"]].reset_index(drop=True)
        Fastest_sector3_fp3.columns=["LapNumber","Time S3 (s)","S3 Compound","Fastest S3"]
        Fast_Laps_fp3=Fastest_Lap_fp3.merge(Fastest_sector1_fp3,on=['LapNumber']).merge(Fastest_sector2_fp3,on=['LapNumber']).merge(Fastest_sector3_fp3,on=['LapNumber'])
        Fast_Laps_fp3=Fast_Laps_fp3[["GP","Year","LapNumber","LapTime","LapTime (s)","Fastest Lap","Lap Compound","Time S1 (s)","Fastest S1","S1 Compound","Time S2 (s)","Fastest S2","S2 Compound","Time S3 (s)","Fastest S3","S3 Compound"]].sort_values(by=["LapNumber"])
        Fast_Laps_fp3=Fast_Laps_fp3.reset_index(drop=True)
        Fast_Laps_fp3['color'] = Fast_Laps_fp3['Fastest Lap'].apply(driver_color)
        LapTime_fp3_ordered=Fast_Laps_fp3.sort_values(by=['LapTime (s)'])

        fig_fp3 = go.Figure(go.Table
        (header={"values": LapTime_fp3_ordered.columns},
        cells=dict(
            values=LapTime_fp3_ordered.T.values,
            fill_color=[LapTime_fp3_ordered.color],
            align='center', font=dict(color='white', size=11)
            ))
        )
        fig_fp3.update_layout(
            title="FP3 Fastest Lap and Sector Times Ordered By Lap Times For The {} {}".format(year_multi, i),
                title_x=0.5,
            yaxis = dict(tickfont = dict(size=15)),
            xaxis = dict(tickfont = dict(size=15)),
            font=dict(
                family="PT Sans Narrow",
                size=13,
                color="Black"
            ),
            height=780,
            width=1200,
            title_font_family="PT Sans Narrow",
            margin=dict(l=5, r=5, t=35, b=5),
        )
        fig_fp3.write_html("/Users/rdesh723/statpulse-html/plots/Free Practice/FP3/{}/{} {} FP3 Fastest Lap Times and Sectors Ordered by Lap Times.html".format(save_year_multi, year_multi, i),include_plotlyjs='cdn')
    except:
        continue

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_57932/659399502.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy