In [11]:
import pandas as pd
import numpy as np
import itertools
import datetime
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import *
from datetime import datetime, timedelta, date
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [ ]:
#Change the date to the previous day
query = """
SELECT
A.GAME_ID, GAME_DATE, MATCHUP, EVENTNUM, PERIOD, PCTIMESTRING, EVENTMSGTYPE, EVENTMSGACTIONTYPE,
CASE WHEN EVENTMSGTYPE=1 THEN 'Made FG'
     WHEN EVENTMSGTYPE=2 THEN 'Missed FG'
     WHEN EVENTMSGTYPE=3 THEN 'Free Throw Attempts'
     WHEN EVENTMSGTYPE=4 THEN 'Rebound'
     WHEN EVENTMSGTYPE=5 THEN 'Turnover'
     WHEN EVENTMSGTYPE=6 THEN 'Foul'
     WHEN EVENTMSGTYPE=7 THEN 'Violation'
     WHEN EVENTMSGTYPE=8 THEN 'Substitution'
     WHEN EVENTMSGTYPE=9 THEN 'Timeout'
     WHEN EVENTMSGTYPE=10 THEN 'Jump Ball'
     WHEN EVENTMSGTYPE=11 THEN 'Ejection'
     WHEN EVENTMSGTYPE=12 THEN 'Period Begin'
     WHEN EVENTMSGTYPE=13 THEN 'Period End'
     END as Event,
CASE WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=0 THEN 'No Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=1 THEN 'Jump Shot/3PT Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=2 THEN 'RUNNING JUMP SHOT/ 3PT RUNNING JUMP SHOT'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=3 THEN 'Hook Shot/3PT Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=4 THEN 'Tip Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=5 THEN 'Layup/3PT Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=6 THEN 'Driving Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=7 THEN 'Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=8 THEN 'Slam Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=9 THEN 'Driving Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=40 THEN '3PT Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=41 THEN 'Running Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=42 THEN 'Driving Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=43 THEN 'Alley-oop Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=44 THEN 'Reverse Layup/3PT Reverse Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=46 THEN 'Running Jump Shot/3PT Running Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=47 THEN 'Turnaround Jump Shot/3PT Turnaround Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=49 THEN 'Driving Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=50 THEN 'Running Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=51 THEN 'Reverse Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=52 THEN 'Alley-oop Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=54 THEN 'Running Tip Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=56 THEN 'Running Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=57 THEN 'Driving Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=58 THEN 'Turnaround Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=59 THEN 'Finger Roll/3PT Finger Roll'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=60 THEN 'Running Finger Roll'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=61 THEN 'Driving Finger Roll'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=62 THEN 'Turnaround Finger Roll'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=63 THEN 'Fadeaway Jumper/3PT Fadeaway Jumper'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=64 THEN 'Follow up Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=65 THEN 'Jump Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=66 THEN 'Jump Bank Shot/3PT Jump Bank Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=67 THEN 'Hook Bank Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=71 THEN 'Finger Roll Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=72 THEN 'Putback Layup/3PT Putback Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=73 THEN 'Driving Reverse Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=74 THEN 'Running Reverse Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=75 THEN 'Driving Finger Roll Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=76 THEN 'Running Finger Roll Layup'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=77 THEN 'Driving Jump Shot/3PT Driving Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=78 THEN 'Floating Jump Shot/3PT Floating Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=79 THEN 'Pullup Jump Shot/3PT Pullup Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=80 THEN 'Step Back Jump Shot/3PT Step Back Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=81 THEN 'Pullup Bank Shot/3PT Pullup Bank Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=82 THEN 'Driving Bank Shot/3PT Driving Bank Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=83 THEN 'Fadeaway Bank Shot/3PT Fadeaway Bank Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=84 THEN 'Running Bank Shot/3PT Running Bank Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=85 THEN 'Turnaround Bank Shot/3PT Turnaround Bank Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=86 THEN 'Turnaround Fadeaway/3PT Turnaround Fadeaway'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=87 THEN 'Putback Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=88 THEN 'Driving Slam Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=89 THEN 'Reverse Slam Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=90 THEN 'Running Slam Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=91 THEN 'Putback Reverse Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=92 THEN 'Putback Slam Dunk'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=93 THEN 'Driving Bank Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=94 THEN 'Jump Bank Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=95 THEN 'Running Bank Hook Shot/3PT Running Bank Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=96 THEN 'Turnaround Bank Hook Shot/3PT Turnaround Bank Hook Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=97 THEN 'Tip Layup Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=98 THEN 'Cutting Layup Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=99 THEN 'Cutting Finger Roll Layup Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=100 THEN 'Running Alley-oop Layup Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=101 THEN 'Driving Floating Jump Shot/3PT Driving Floating Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=102 THEN 'Driving Floating Bank Jump Shot/3PT Driving Floating Bank Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=103 THEN 'Running Pull/3PT Running Pull'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=104 THEN 'Step Back Bank Jump Shot/3PT Step Back Bank Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=105 THEN 'Turnaround Fadeaway Bank Jump Shot/3PT Turnaround Fadeaway Bank Jump Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=106 THEN 'Running Alley-oop Dunk Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=107 THEN 'Tip Dunk Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=108 THEN 'Cutting Dunk Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=109 THEN 'Driving Reverse Dunk Shot'
     WHEN EVENTMSGTYPE IN (1,2) AND EVENTMSGACTIONTYPE=110 THEN 'Running Reverse Dunk Shot'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=10 THEN 'Free Throw 1 of 1'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=11 THEN 'Free Throw 1 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=12 THEN 'Free Throw 2 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=13 THEN 'Free Throw 1 of 3'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=14 THEN 'Free Throw 2 of 3'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=15 THEN 'Free Throw 3 of 3'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=16 THEN 'Free Throw Technical 1 of 1'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=18 THEN 'Free Throw Flagrant 1 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=19 THEN 'Free Throw Flagrant 2 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=20 THEN 'Free Throw Flagrant 1 of 1'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=21 THEN 'Free Throw Technical 1 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=22 THEN 'Free Throw Technical 2 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=25 THEN 'Free Throw Clear Path 1 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=26 THEN 'Free Throw Clear Path 2 of 2'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=27 THEN 'Free Throw Flagrant 1 of 3'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=28 THEN 'Free Throw Flagrant 2 of 3'
     WHEN EVENTMSGTYPE IN (3) AND EVENTMSGACTIONTYPE=29 THEN 'Free Throw Flagrant 3 of 3'
     WHEN EVENTMSGTYPE IN (4) THEN 'Rebound'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=0 THEN 'Flagrant Foul: No Turnover'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=1 THEN 'Bad Pass TO: Steal'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=2 THEN 'Lost Ball TO: Steal'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=4 THEN 'Traveling TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=6 THEN 'Double Dribble TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=7 THEN 'Discontinue Dribble TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=8 THEN '3 Second Violation TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=9 THEN '5 Second Violation TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=10 THEN '8 Second Violation TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=11 THEN 'Shot Clock TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=12 THEN 'Inbound TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=13 THEN 'Backcourt TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=14 THEN 'Illegal pick TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=15 THEN 'Offensive Goaltending TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=16 THEN 'Isolation Violation TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=17 THEN 'Lane Violation TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=18 THEN 'Jump Ball Violation TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=19 THEN 'Kicked Ball Violation TO '
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=20 THEN 'Illegal Assist TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=21 THEN 'Palming TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=22 THEN 'Post up TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=23 THEN 'Double personal TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=32 THEN 'Opposite basket TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=33 THEN 'Punched ball TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=34 THEN 'Swinging elbows TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=35 THEN 'Basket from below TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=36 THEN 'Illegal Screen'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=37 THEN 'Offensive Foul TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=38 THEN '5 second inbound TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=39 THEN 'Step out of bounds TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=40 THEN 'Out of bounds lost ball TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=41 THEN 'Poss lost ball TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=42 THEN 'Excess Timeout TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=43 THEN 'Player OOB TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=44 THEN 'Too many players TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=45 THEN 'Out of bounds bad pass TO'
     WHEN EVENTMSGTYPE IN (5) AND EVENTMSGACTIONTYPE=52 THEN 'STL TO'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=1 THEN 'Personal Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=2 THEN 'S Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=3 THEN 'L.B. Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=4 THEN 'Offensive Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=5 THEN 'In. Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=6 THEN 'Away from play foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=7 THEN 'Elbow Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=8 THEN 'Punch Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=9 THEN 'C.P. Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=10 THEN 'Double personal Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=11 THEN 'T. Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=12 THEN 'Non-Unsportsmanlike Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=13 THEN 'Hanging Tech Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=14 THEN 'Flagrant Foul Type 1'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=15 THEN 'Flagrant Foul Type 2'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=16 THEN 'Double Technical'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=17 THEN 'Team T. Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=18 THEN 'Team Delay Technical'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=19 THEN 'Taunting '
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=25 THEN 'Excess Timeout Technical'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=26 THEN 'Offensive Charge Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=27 THEN 'Personal Block Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=28 THEN 'Personal Take Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=29 THEN 'Shooting Block Foul'
     WHEN EVENTMSGTYPE IN (6) AND EVENTMSGACTIONTYPE=30 THEN 'Too many Players Foul'
     WHEN EVENTMSGTYPE IN (7) AND EVENTMSGACTIONTYPE=0 THEN 'Violation: No violation'
     WHEN EVENTMSGTYPE IN (7) AND EVENTMSGACTIONTYPE=1 THEN 'Violation: Delay of game '
     WHEN EVENTMSGTYPE IN (7) AND EVENTMSGACTIONTYPE=2 THEN 'Defensive Goaltending'
     WHEN EVENTMSGTYPE IN (7) AND EVENTMSGACTIONTYPE=3 THEN 'Lane Violation'
     WHEN EVENTMSGTYPE IN (7) AND EVENTMSGACTIONTYPE=4 THEN 'Jump Ball Violation'
     WHEN EVENTMSGTYPE IN (7) AND EVENTMSGACTIONTYPE=5 THEN 'Kicked Ball Violation'
     WHEN EVENTMSGTYPE IN (7) AND EVENTMSGACTIONTYPE=6 THEN 'Double Lane Violation'
     WHEN EVENTMSGTYPE IN (8)  THEN 'Substitution'
     WHEN EVENTMSGTYPE IN (9) AND EVENTMSGACTIONTYPE=0 THEN 'Timeout: No Timeout'
     WHEN EVENTMSGTYPE IN (9) AND EVENTMSGACTIONTYPE=1 THEN 'Timeout Regular'
     WHEN EVENTMSGTYPE IN (9) AND EVENTMSGACTIONTYPE=2 THEN 'Timeout Short'
     WHEN EVENTMSGTYPE IN (9) AND EVENTMSGACTIONTYPE=3 THEN 'Timeout official TV'
     WHEN EVENTMSGTYPE IN (9) AND EVENTMSGACTIONTYPE=4 THEN 'Timeout Official'
     WHEN EVENTMSGTYPE IN (9) AND EVENTMSGACTIONTYPE=5 THEN 'Timeout Advance'
     WHEN EVENTMSGTYPE IN (9) AND EVENTMSGACTIONTYPE=7 THEN 'Coach Challenge'
     WHEN EVENTMSGTYPE IN (10) AND EVENTMSGACTIONTYPE=0 THEN 'Jump ball'
     WHEN EVENTMSGTYPE IN (10) AND EVENTMSGACTIONTYPE=1 THEN 'Jump ball CC'
     WHEN EVENTMSGTYPE IN (11) AND EVENTMSGACTIONTYPE=0 THEN 'Ejection: No ejection'
     WHEN EVENTMSGTYPE IN (11) AND EVENTMSGACTIONTYPE=1 THEN 'Ejection: Second Technical'
     WHEN EVENTMSGTYPE IN (11) AND EVENTMSGACTIONTYPE=2 THEN 'Ejection: Second Flagrant Type 1 '
     WHEN EVENTMSGTYPE IN (11) AND EVENTMSGACTIONTYPE=3 THEN 'Ejection: First Flagrant Type 2'
     WHEN EVENTMSGTYPE IN (11) AND EVENTMSGACTIONTYPE=4 THEN 'Ejection: Other'
     WHEN EVENTMSGTYPE IN (12) THEN 'Start of period'
     WHEN EVENTMSGTYPE IN (13) THEN 'End of period'
     ELSE 'No event'
     END as Event_Type,

HOMEDESCRIPTION, NEUTRALDESCRIPTION, VISITORDESCRIPTION, SCORE, SCOREMARGIN, PERSON1TYPE, PLAYER1_ID, PLAYER1_NAME, PLAYER1_TEAM_ID, PLAYER1_TEAM_CITY, PLAYER1_TEAM_NICKNAME, PLAYER1_TEAM_ABBREVIATION, PERSON2TYPE, PLAYER2_ID, PLAYER2_NAME, PLAYER2_TEAM_ID, PLAYER2_TEAM_CITY, PLAYER2_TEAM_NICKNAME, PLAYER2_TEAM_ABBREVIATION, PERSON3TYPE, PLAYER3_ID, PLAYER3_NAME, PLAYER3_TEAM_ID, PLAYER3_TEAM_CITY, PLAYER3_TEAM_NICKNAME, PLAYER3_TEAM_ABBREVIATION, VIDEO_AVAILABLE_FLAG, WCTIMESTRING, A.Season
FROM
`perceptive-ivy-290216.play_by_play.reg_season_22_23` A
INNER JOIN
nba_game_player_team_ids.game_ids_reg_season B
ON A.GAME_ID =B.GAME_ID
-- WHERE A.GAME_ID='0022001010'
AND MATCHUP LIKE '%@ DEN%'
ORDER BY 4"""
project_id = "perceptive-ivy-290216"
df_bq = pd.read_gbq(query=query, project_id=project_id, dialect='standard')

In [ ]:
query2 = """
SELECT TEAM_ABBREVIATION, GAME_ID, GAME_DATE, WL, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS FROM `perceptive-ivy-290216.nba_api_team_boxscore.team_box_96_onwards`
WHERE TEAM_ABBREVIATION="DEN"
AND SEASON='2022-23'
AND MATCHUP LIKE "%DEN vs.%"
"""
project_id = "perceptive-ivy-290216"
result_bq = pd.read_gbq(query=query2, project_id=project_id, dialect='standard')
result_bq.head()

Warning: Total number of columns (22) exceeds max_columns (20). Falling back to pandas display.

,TEAM_ABBREVIATION,GAME_ID,GAME_DATE,WL,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,DEN,0022201147,2023-03-30,L,32,80,0.400,4,28,0.143,20,32,0.625,11,29,40,21,4,5,10,21,88
1,DEN,0022200989,2023-03-08,L,37,88,0.420,15,40,0.375,7,15,0.467,11,33,44,26,5,2,11,16,96
2,DEN,0022201014,2023-03-12,L,45,90,0.500,12,31,0.387,18,24,0.750,15,34,49,27,4,8,15,19,120
3,DEN,0022200362,2022-12-06,L,40,78,0.513,13,32,0.406,22,28,0.786,8,28,36,30,8,4,17,28,115
4,DEN,0022200219,2022-11-16,L,36,82,0.439,14,38,0.368,17,20,0.850,8,34,42,18,3,5,15,25,103

In [2]:
#Change the date to the previous day
query_shooting = """
SELECT
GAME_ID as GAME, PLAYER_NAME, PERIOD PERIOD_LOC, MINUTES_REMAINING, SECONDS_REMAINING, SHOT_TYPE, SHOT_ZONE_BASIC
FROM `perceptive-ivy-290216.nba_api_shooting_location.x_y_location`
WHERE SEASON='2022-23'
# AND GAME_ID='0041500407'
ORDER BY PERIOD, MINUTES_REMAINING DESC, SECONDS_REMAINING DESC
"""
project_id = "perceptive-ivy-290216"
shooting_df = pd.read_gbq(query=query_shooting, project_id=project_id, dialect='standard')
shooting_df.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_13281/3446780254.py:11: FutureWarning: read_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.read_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.read_gbq
  shooting_df = pd.read_gbq(query=query_shooting, project_id=project_id, dialect='standard')

,GAME,PLAYER_NAME,PERIOD_LOC,MINUTES_REMAINING,SECONDS_REMAINING,SHOT_TYPE,SHOT_ZONE_BASIC
0,0022200180,Bobby Portis,1,12,0,2PT Field Goal,Restricted Area
1,0022200524,Buddy Hield,1,11,57,3PT Field Goal,Above the Break 3
2,0022200378,Buddy Hield,1,11,56,2PT Field Goal,Restricted Area
3,0022200472,Alperen Sengun,1,11,56,2PT Field Goal,Restricted Area
4,0022200957,Jaden Ivey,1,11,55,2PT Field Goal,Restricted Area

In [3]:
#Making sure all games are in here
df_bq.GAME_ID.nunique()

NameError: name 'df_bq' is not defined

In [ ]:
game=df_bq

In [ ]:

game=game.replace("TIE",'0')

In [ ]:
game["RK"] = game.groupby("GAME_ID")["EVENTNUM"].rank(method="dense", ascending=True)

In [ ]:
game = game.sort_values(['GAME_ID','EVENTNUM']).reset_index(drop=True)

In [ ]:
#Make the first row of each game id as 0 for score and score margin, otherwise the next game inherits the prior game's score and scoremargin in the next steps due to no delineation
for index, row in game.iterrows():
  if game.loc[index, 'RK']==1.0:
    game.loc[index, 'SCOREMARGIN']=0
    game.loc[index, 'SCORE']='0-0'

In [ ]:

game['SCOREMARGIN'] = game['SCOREMARGIN'].fillna(method='ffill')
game['SCORE'] = game['SCORE'].fillna(method='ffill')
game=game.fillna('No')
game['SCOREMARGIN']=game['SCOREMARGIN'].astype(int)

In [ ]:

game[['MINUTE', 'SECOND']] = game['PCTIMESTRING'].str.split(':', 1, expand=True)
game["MINUTE"]=game["MINUTE"].astype(int)
game["SECOND"]=game["SECOND"].astype(int)
game["SECONDS"]=game["MINUTE"]*60+game["SECOND"]

<ipython-input-14-0c3f1d875fae>:1: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  game[['MINUTE', 'SECOND']] = game['PCTIMESTRING'].str.split(':', 1, expand=True)

In [ ]:
game.sort_values(['GAME_ID', 'PERIOD', 'SECONDS'], ascending=[True, True, False], inplace=True)
game['overall_rank'] = 1
game['overall_rank'] = game.groupby(['GAME_ID'])['overall_rank'].cumsum()
game.head()

Warning: Total number of columns (44) exceeds max_columns (20). Falling back to pandas display.

,GAME_ID,GAME_DATE,MATCHUP,EVENTNUM,PERIOD,PCTIMESTRING,EVENTMSGTYPE,EVENTMSGACTIONTYPE,Event,Event_Type,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG,WCTIMESTRING,Season,RK,MINUTE,SECOND,SECONDS,overall_rank
0,0022200035,2022-10-22,OKC @ DEN,2,1,12:00,12,0,Period Begin,Start of period,No,Start of 1st Period (9:17 PM EST),No,0-0,0,0.0,0,No,No,No,No,No,0,0,No,No,No,No,No,0,0,No,No,No,No,No,0,9:17 PM,2022-23,1.0,12,0,720,1
1,0022200035,2022-10-22,OKC @ DEN,4,1,12:00,10,0,Jump Ball,Jump ball,Jump Ball Jokic vs. Robinson-Earl: Tip to Giddey,No,No,0-0,0,4.0,203999,Nikola Jokic,1610612743.0,Denver,Nuggets,DEN,5,1630526,Jeremiah Robinson-Earl,1610612760.0,Oklahoma City,Thunder,OKC,5,1630581,Josh Giddey,1610612760.0,Oklahoma City,Thunder,OKC,1,9:17 PM,2022-23,2.0,12,0,720,2
2,0022200035,2022-10-22,OKC @ DEN,7,1,11:47,2,1,Missed FG,Jump Shot/3PT Jump Shot,No,No,MISS Dort 24' 3PT Jump Shot,0-0,0,5.0,1629652,Luguentz Dort,1610612760.0,Oklahoma City,Thunder,OKC,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,9:17 PM,2022-23,3.0,11,47,707,3
3,0022200035,2022-10-22,OKC @ DEN,8,1,11:45,4,0,Rebound,Rebound,Murray REBOUND (Off:0 Def:1),No,No,0-0,0,4.0,1627750,Jamal Murray,1610612743.0,Denver,Nuggets,DEN,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,9:17 PM,2022-23,4.0,11,45,705,4
4,0022200035,2022-10-22,OKC @ DEN,9,1,11:40,5,1,Turnover,Bad Pass TO: Steal,Murray Bad Pass Turnover (P1.T1),No,Pokusevski STEAL (1 STL),0-0,0,4.0,1627750,Jamal Murray,1610612743.0,Denver,Nuggets,DEN,5,1630197,Aleksej Pokusevski,1610612760.0,Oklahoma City,Thunder,OKC,0,0,No,No,No,No,No,1,9:17 PM,2022-23,5.0,11,40,700,5

In [ ]:
# game_edited=pd.concat([game,game[['SECONDS']].shift(periods=-1).rename({'SECONDS':'SECONDS_SHIFTED'}, axis=1)], axis=1)
game_edited=pd.concat([game,game[['SECONDS']].diff().rename({'SECONDS':'SECONDS_Diff'}, axis=1)], axis=1)
game_edited=pd.concat([game_edited,game_edited[['SCOREMARGIN']].diff().rename({'SCOREMARGIN':'SCOREMARGIN_Diff'}, axis=1)], axis=1)
game_edited["SECONDS_Diff"]=game_edited["SECONDS_Diff"].abs()
game_edited["SCOREMARGIN_Diff"]=game_edited["SCOREMARGIN_Diff"].abs()
game_edited.tail()

Warning: Total number of columns (46) exceeds max_columns (20). Falling back to pandas display.

,GAME_ID,GAME_DATE,MATCHUP,EVENTNUM,PERIOD,PCTIMESTRING,EVENTMSGTYPE,EVENTMSGACTIONTYPE,Event,Event_Type,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG,WCTIMESTRING,Season,RK,MINUTE,SECOND,SECONDS,overall_rank,SECONDS_Diff,SCOREMARGIN_Diff
18979,0022201227,2023-04-09,SAC @ DEN,620,4,0:33,1,50,Made FG,Running Dunk,No,No,Metu 3' Running Dunk (9 PTS) (Ellis 1 AST),95 - 109,14,5.0,1629002,Chimezie Metu,1610612758.0,Sacramento,Kings,SAC,5,1631165,Keon Ellis,1610612758.0,Sacramento,Kings,SAC,0,0,No,No,No,No,No,1,5:43 PM,2022-23,435.0,0,33,33,435,5.0,2.0
18980,0022201227,2023-04-09,SAC @ DEN,622,4,0:09,5,11,Turnover,Shot Clock TO,NUGGETS Turnover: Shot Clock (T#20),No,No,95 - 109,14,2.0,1610612743,No,No,No,No,No,0,0,No,No,No,No,No,1,0,No,No,No,No,No,0,5:44 PM,2022-23,436.0,0,9,9,436,24.0,0.0
18981,0022201227,2023-04-09,SAC @ DEN,623,4,0:01,2,79,Missed FG,Pullup Jump Shot/3PT Pullup Jump Shot,No,No,MISS Metu 27' 3PT Pullup Jump Shot,95 - 109,14,5.0,1629002,Chimezie Metu,1610612758.0,Sacramento,Kings,SAC,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,5:44 PM,2022-23,437.0,0,1,1,437,8.0,0.0
18982,0022201227,2023-04-09,SAC @ DEN,624,4,0:01,4,0,Rebound,Rebound,No,No,Kings Rebound,95 - 109,14,3.0,1610612758,No,No,No,No,No,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,5:44 PM,2022-23,438.0,0,1,1,438,0.0,0.0
18983,0022201227,2023-04-09,SAC @ DEN,625,4,0:00,13,0,Period End,End of period,No,End of 4th Period (5:44 PM EST),No,95 - 109,14,0.0,0,No,No,No,No,No,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,5:44 PM,2022-23,439.0,0,0,0,439,1.0,0.0

In [ ]:
BLOCK_ALL_GAMES=game_edited
BLOCK_ALL_GAMES=BLOCK_ALL_GAMES[BLOCK_ALL_GAMES["Event_Type"]!="Start of period"]
BLOCK_ALL_GAMES=BLOCK_ALL_GAMES.sort_values(by=["GAME_ID","PERIOD","SECONDS"], ascending=[True, True, False])


BLOCK_1=game_edited[game_edited['GAME_ID'].isin(['0022201227'])]
BLOCK_1=BLOCK_1[BLOCK_1["Event_Type"]!="Start of period"]
BLOCK_1=BLOCK_1.sort_values(by=["GAME_ID","PERIOD","SECONDS"], ascending=[True, True, False])
BLOCK_1.head()

Warning: Total number of columns (46) exceeds max_columns (20). Falling back to pandas display.

,GAME_ID,GAME_DATE,MATCHUP,EVENTNUM,PERIOD,PCTIMESTRING,EVENTMSGTYPE,EVENTMSGACTIONTYPE,Event,Event_Type,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG,WCTIMESTRING,Season,RK,MINUTE,SECOND,SECONDS,overall_rank,SECONDS_Diff,SCOREMARGIN_Diff
18546,0022201227,2023-04-09,SAC @ DEN,4,1,12:00,10,0,Jump Ball,Jump ball,Jump Ball Jordan vs. Sabonis: Tip to Barnes,No,No,0-0,0,4.0,201599,DeAndre Jordan,1610612743.0,Denver,Nuggets,DEN,5,1627734,Domantas Sabonis,1610612758.0,Sacramento,Kings,SAC,5,203084,Harrison Barnes,1610612758.0,Sacramento,Kings,SAC,1,3:41 PM,2022-23,2.0,12,0,720,2,0.0,0.0
18547,0022201227,2023-04-09,SAC @ DEN,7,1,11:39,1,108,Made FG,Cutting Dunk Shot,No,No,Sabonis 3' Cutting Dunk Shot (2 PTS) (Huerter ...,2 - 0,-2,5.0,1627734,Domantas Sabonis,1610612758.0,Sacramento,Kings,SAC,5,1628989,Kevin Huerter,1610612758.0,Sacramento,Kings,SAC,0,0,No,No,No,No,No,1,3:42 PM,2022-23,3.0,11,39,699,3,21.0,2.0
18548,0022201227,2023-04-09,SAC @ DEN,9,1,11:22,1,9,Made FG,Driving Dunk,Braun 2' Driving Dunk (2 PTS) (Jordan 1 AST),No,No,2 - 2,0,4.0,1631128,Christian Braun,1610612743.0,Denver,Nuggets,DEN,4,201599,DeAndre Jordan,1610612743.0,Denver,Nuggets,DEN,0,0,No,No,No,No,No,1,3:42 PM,2022-23,4.0,11,22,682,4,17.0,2.0
18568,0022201227,2023-04-09,SAC @ DEN,41,1,11:15,7,5,Violation,Kicked Ball Violation,Jordan Violation:Kicked Ball (D.Taylor),No,No,14 - 6,-8,4.0,201599,DeAndre Jordan,1610612743.0,Denver,Nuggets,DEN,0,0,No,No,No,No,No,1,0,No,No,No,No,No,0,3:42 PM,2022-23,24.0,11,15,675,5,7.0,8.0
18549,0022201227,2023-04-09,SAC @ DEN,13,1,11:06,2,63,Missed FG,Fadeaway Jumper/3PT Fadeaway Jumper,No,No,MISS Fox 16' Fadeaway Jumper,2 - 2,0,5.0,1628368,De'Aaron Fox,1610612758.0,Sacramento,Kings,SAC,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,3:42 PM,2022-23,5.0,11,6,666,6,9.0,8.0

In [ ]:
#Add a column to check scoremargin and if it is =/>/< than 0
for index,row in BLOCK_1.iterrows():
  if row['SCOREMARGIN']==0:
    BLOCK_1.loc[index,'LEAD_LAG'] = 'ALL'
  elif row['SCOREMARGIN']>0:
    BLOCK_1.loc[index,'LEAD_LAG'] = 'HOME LEAD'
  elif row['SCOREMARGIN']<0:
    BLOCK_1.loc[index,'LEAD_LAG'] = 'HOME DEFICIT'

In [ ]:
BLOCK_1.head()

Warning: Total number of columns (47) exceeds max_columns (20). Falling back to pandas display.

,GAME_ID,GAME_DATE,MATCHUP,EVENTNUM,PERIOD,PCTIMESTRING,EVENTMSGTYPE,EVENTMSGACTIONTYPE,Event,Event_Type,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG,WCTIMESTRING,Season,RK,MINUTE,SECOND,SECONDS,overall_rank,SECONDS_Diff,SCOREMARGIN_Diff,LEAD_LAG
18546,0022201227,2023-04-09,SAC @ DEN,4,1,12:00,10,0,Jump Ball,Jump ball,Jump Ball Jordan vs. Sabonis: Tip to Barnes,No,No,0-0,0,4.0,201599,DeAndre Jordan,1610612743.0,Denver,Nuggets,DEN,5,1627734,Domantas Sabonis,1610612758.0,Sacramento,Kings,SAC,5,203084,Harrison Barnes,1610612758.0,Sacramento,Kings,SAC,1,3:41 PM,2022-23,2.0,12,0,720,2,0.0,0.0,ALL
18547,0022201227,2023-04-09,SAC @ DEN,7,1,11:39,1,108,Made FG,Cutting Dunk Shot,No,No,Sabonis 3' Cutting Dunk Shot (2 PTS) (Huerter ...,2 - 0,-2,5.0,1627734,Domantas Sabonis,1610612758.0,Sacramento,Kings,SAC,5,1628989,Kevin Huerter,1610612758.0,Sacramento,Kings,SAC,0,0,No,No,No,No,No,1,3:42 PM,2022-23,3.0,11,39,699,3,21.0,2.0,HOME DEFICIT
18548,0022201227,2023-04-09,SAC @ DEN,9,1,11:22,1,9,Made FG,Driving Dunk,Braun 2' Driving Dunk (2 PTS) (Jordan 1 AST),No,No,2 - 2,0,4.0,1631128,Christian Braun,1610612743.0,Denver,Nuggets,DEN,4,201599,DeAndre Jordan,1610612743.0,Denver,Nuggets,DEN,0,0,No,No,No,No,No,1,3:42 PM,2022-23,4.0,11,22,682,4,17.0,2.0,ALL
18568,0022201227,2023-04-09,SAC @ DEN,41,1,11:15,7,5,Violation,Kicked Ball Violation,Jordan Violation:Kicked Ball (D.Taylor),No,No,14 - 6,-8,4.0,201599,DeAndre Jordan,1610612743.0,Denver,Nuggets,DEN,0,0,No,No,No,No,No,1,0,No,No,No,No,No,0,3:42 PM,2022-23,24.0,11,15,675,5,7.0,8.0,HOME DEFICIT
18549,0022201227,2023-04-09,SAC @ DEN,13,1,11:06,2,63,Missed FG,Fadeaway Jumper/3PT Fadeaway Jumper,No,No,MISS Fox 16' Fadeaway Jumper,2 - 2,0,5.0,1628368,De'Aaron Fox,1610612758.0,Sacramento,Kings,SAC,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,3:42 PM,2022-23,5.0,11,6,666,6,9.0,8.0,ALL

In [ ]:
#Add a column to check scoremargin and if it is =/>/< than 0
for index,row in BLOCK_ALL_GAMES.iterrows():
  if row['SCOREMARGIN']==0:
    BLOCK_ALL_GAMES.loc[index,'LEAD_LAG'] = 'ALL'
  elif row['SCOREMARGIN']>0:
    BLOCK_ALL_GAMES.loc[index,'LEAD_LAG'] = 'HOME LEAD'
  elif row['SCOREMARGIN']<0:
    BLOCK_ALL_GAMES.loc[index,'LEAD_LAG'] = 'HOME DEFICIT'

In [ ]:
#Add a column to check scoremargin and if it is =/>/< than 0
for index,row in BLOCK_ALL_GAMES.iterrows():
  if ((row['SECONDS']<=720) & (row['SECONDS']>300)):
    BLOCK_ALL_GAMES.loc[index,'CLUTCH'] = '6-12 MIN'
  elif ((row['SECONDS']<=300) & (row['SECONDS']>120)):
    BLOCK_ALL_GAMES.loc[index,'CLUTCH'] = '2-5 MIN'
  elif ((row['SECONDS']<=120)):
    BLOCK_ALL_GAMES.loc[index,'CLUTCH'] = 'LESS THAN 2 MIN'
  # elif ((row['SECONDS']<=120) & (row['SECONDS']>60)):
  #   BLOCK_ALL_GAMES.loc[index,'CLUTCH'] = '1-2 MIN'
  # elif ((row['SECONDS']<=60) & (row['SECONDS']>30)):
  #   BLOCK_ALL_GAMES.loc[index,'CLUTCH'] = '30 SEC-1 MIN'
  # elif ((row['SECONDS']<=30)):
  #   BLOCK_ALL_GAMES.loc[index,'CLUTCH'] = 'LESS THAN 30 SEC'

In [ ]:
#Add a column to check scoremargin and if it is =/>/< than 0
for index,row in BLOCK_ALL_GAMES.iterrows():
  if row['SCOREMARGIN']==0:
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '0'
  elif ((row['SCOREMARGIN']<=5) & (row['SCOREMARGIN']>0)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '<=5'
  elif ((row['SCOREMARGIN']<=10) & (row['SCOREMARGIN']>5)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '6-10'
  elif ((row['SCOREMARGIN']<=20) & (row['SCOREMARGIN']>10)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '11-20'
  elif ((row['SCOREMARGIN']>20)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '>20'

  elif ((row['SCOREMARGIN']>=-5) & (row['SCOREMARGIN']<0)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '<=5'
  elif ((row['SCOREMARGIN']>=-10) & (row['SCOREMARGIN']<-5)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '6-10'
  elif ((row['SCOREMARGIN']>=-20) & (row['SCOREMARGIN']<-10)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '11-20'
  elif ((row['SCOREMARGIN']<-20)):
    BLOCK_ALL_GAMES.loc[index,'MARGIN'] = '>20'

In [10]:
BLOCK_ALL_GAMES=BLOCK_ALL_GAMES.merge(result_bq, how='left', left_on=['GAME_ID','GAME_DATE'], right_on=['GAME_ID','GAME_DATE'])
BLOCK_ALL_GAMES.head()

NameError: name 'BLOCK_ALL_GAMES' is not defined

In [ ]:
BLOCK_ALL_GAMES=BLOCK_ALL_GAMES.merge(shooting_df, how='left', left_on=['GAME_ID','MINUTE','SECOND','PLAYER1_NAME','PERIOD'], right_on=['GAME','MINUTES_REMAINING','SECONDS_REMAINING','PLAYER_NAME','PERIOD_LOC'])

In [ ]:
BLOCK_ALL_GAMES.head()

Warning: Total number of columns (76) exceeds max_columns (20). Falling back to pandas display.

,GAME_ID,GAME_DATE,MATCHUP,EVENTNUM,PERIOD,PCTIMESTRING,EVENTMSGTYPE,EVENTMSGACTIONTYPE,Event,Event_Type,HOMEDESCRIPTION,NEUTRALDESCRIPTION,VISITORDESCRIPTION,SCORE,SCOREMARGIN,PERSON1TYPE,PLAYER1_ID,PLAYER1_NAME,PLAYER1_TEAM_ID,PLAYER1_TEAM_CITY,PLAYER1_TEAM_NICKNAME,PLAYER1_TEAM_ABBREVIATION,PERSON2TYPE,PLAYER2_ID,PLAYER2_NAME,PLAYER2_TEAM_ID,PLAYER2_TEAM_CITY,PLAYER2_TEAM_NICKNAME,PLAYER2_TEAM_ABBREVIATION,PERSON3TYPE,PLAYER3_ID,PLAYER3_NAME,PLAYER3_TEAM_ID,PLAYER3_TEAM_CITY,PLAYER3_TEAM_NICKNAME,PLAYER3_TEAM_ABBREVIATION,VIDEO_AVAILABLE_FLAG,WCTIMESTRING,Season,RK,MINUTE,SECOND,SECONDS,overall_rank,SECONDS_Diff,SCOREMARGIN_Diff,LEAD_LAG,CLUTCH,MARGIN,TEAM_ABBREVIATION,WL,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,GAME,PLAYER_NAME,PERIOD_LOC,MINUTES_REMAINING,SECONDS_REMAINING,SHOT_TYPE,SHOT_ZONE_BASIC
0,0022200035,2022-10-22,OKC @ DEN,4,1,12:00,10,0,Jump Ball,Jump ball,Jump Ball Jokic vs. Robinson-Earl: Tip to Giddey,No,No,0-0,0,4.0,203999,Nikola Jokic,1610612743.0,Denver,Nuggets,DEN,5,1630526,Jeremiah Robinson-Earl,1610612760.0,Oklahoma City,Thunder,OKC,5,1630581,Josh Giddey,1610612760.0,Oklahoma City,Thunder,OKC,1,9:17 PM,2022-23,2.0,12,0,720,2,0.0,0.0,ALL,6-12 MIN,0,DEN,W,42,85,0.494,20,38,0.526,18,31,0.581,9,37,46,33,5,6,18,21,122,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN
1,0022200035,2022-10-22,OKC @ DEN,7,1,11:47,2,1,Missed FG,Jump Shot/3PT Jump Shot,No,No,MISS Dort 24' 3PT Jump Shot,0-0,0,5.0,1629652,Luguentz Dort,1610612760.0,Oklahoma City,Thunder,OKC,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,9:17 PM,2022-23,3.0,11,47,707,3,13.0,0.0,ALL,6-12 MIN,0,DEN,W,42,85,0.494,20,38,0.526,18,31,0.581,9,37,46,33,5,6,18,21,122,0022200035,Luguentz Dort,1,11,47,3PT Field Goal,Left Corner 3
2,0022200035,2022-10-22,OKC @ DEN,8,1,11:45,4,0,Rebound,Rebound,Murray REBOUND (Off:0 Def:1),No,No,0-0,0,4.0,1627750,Jamal Murray,1610612743.0,Denver,Nuggets,DEN,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,9:17 PM,2022-23,4.0,11,45,705,4,2.0,0.0,ALL,6-12 MIN,0,DEN,W,42,85,0.494,20,38,0.526,18,31,0.581,9,37,46,33,5,6,18,21,122,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN
3,0022200035,2022-10-22,OKC @ DEN,9,1,11:40,5,1,Turnover,Bad Pass TO: Steal,Murray Bad Pass Turnover (P1.T1),No,Pokusevski STEAL (1 STL),0-0,0,4.0,1627750,Jamal Murray,1610612743.0,Denver,Nuggets,DEN,5,1630197,Aleksej Pokusevski,1610612760.0,Oklahoma City,Thunder,OKC,0,0,No,No,No,No,No,1,9:17 PM,2022-23,5.0,11,40,700,5,5.0,0.0,ALL,6-12 MIN,0,DEN,W,42,85,0.494,20,38,0.526,18,31,0.581,9,37,46,33,5,6,18,21,122,NaN,NaN,<NA>,<NA>,<NA>,NaN,NaN
4,0022200035,2022-10-22,OKC @ DEN,11,1,11:34,2,103,Missed FG,Running Pull/3PT Running Pull,No,No,MISS Gilgeous-Alexander 26' 3PT Running Pull-U...,0-0,0,5.0,1628983,Shai Gilgeous-Alexander,1610612760.0,Oklahoma City,Thunder,OKC,0,0,No,No,No,No,No,0,0,No,No,No,No,No,1,9:17 PM,2022-23,6.0,11,34,694,6,6.0,0.0,ALL,6-12 MIN,0,DEN,W,42,85,0.494,20,38,0.526,18,31,0.581,9,37,46,33,5,6,18,21,122,0022200035,Shai Gilgeous-Alexander,1,11,34,3PT Field Goal,Above the Break 3

In [ ]:
TEAM='DEN'

In [4]:
#SCORING grouped by period, Lead Lag AND CLUTCH TIME. REMOVING GAME LEVEL GROUPING
############################################################## CHnge team abbr too team in analysis************************************
PTS_LEAD_LAG_CLUTCH_MARGIN=BLOCK_ALL_GAMES[((BLOCK_ALL_GAMES.PLAYER1_NAME!="No") & (BLOCK_ALL_GAMES.Event=="Made FG") & (BLOCK_ALL_GAMES.PLAYER1_TEAM_ABBREVIATION==TEAM))]
PTS_LEAD_LAG_CLUTCH_MARGIN=PTS_LEAD_LAG_CLUTCH_MARGIN.groupby(by=["PLAYER1_TEAM_ABBREVIATION","PERIOD","LEAD_LAG","CLUTCH","MARGIN","SHOT_TYPE","PLAYER1_NAME"])["Event"].count()
PTS_LEAD_LAG_CLUTCH_MARGIN=pd.DataFrame(PTS_LEAD_LAG_CLUTCH_MARGIN)
PTS_LEAD_LAG_CLUTCH_MARGIN.reset_index(inplace=True)
PTS_LEAD_LAG_CLUTCH_MARGIN[((PTS_LEAD_LAG_CLUTCH_MARGIN["PERIOD"].isin([1,2,3,4])) & (PTS_LEAD_LAG_CLUTCH_MARGIN["PLAYER1_NAME"]=='Nikola Jokic'))]

NameError: name 'BLOCK_ALL_GAMES' is not defined

In [5]:
for index,row in PTS_LEAD_LAG_CLUTCH_MARGIN.iterrows():
  if (row['CLUTCH']=="6-12 MIN"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'CLUTCH_RK'] = 1
  elif (row['CLUTCH']=="2-5 MIN"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'CLUTCH_RK'] = 2
  elif (row['CLUTCH']=="LESS THAN 2 MIN"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'CLUTCH_RK'] = 3

for index,row in PTS_LEAD_LAG_CLUTCH_MARGIN.iterrows():
  if (row['MARGIN']=="0"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'MARGIN_RK'] = 3
  elif (row['MARGIN']=="<=5"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'MARGIN_RK'] = 3
  elif (row['MARGIN']=="6-10"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'MARGIN_RK'] = 2
  elif (row['MARGIN']=="11-20"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'MARGIN_RK'] = 1
  elif (row['MARGIN']==">20"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'MARGIN_RK'] = 0.5

for index,row in PTS_LEAD_LAG_CLUTCH_MARGIN.iterrows():
  if (row['SHOT_TYPE']=="2PT Field Goal"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'FG_RK'] = 2
  elif (row['SHOT_TYPE']=="3PT Field Goal"):
    PTS_LEAD_LAG_CLUTCH_MARGIN.loc[index,'FG_RK'] = 3
PTS_LEAD_LAG_CLUTCH_MARGIN

NameError: name 'PTS_LEAD_LAG_CLUTCH_MARGIN' is not defined

In [6]:
#Rebounds grouped by Period
SHOTS_PERCENT=BLOCK_ALL_GAMES[((BLOCK_ALL_GAMES.PLAYER1_NAME!="No") & (BLOCK_ALL_GAMES.Event=="Made FG") & (BLOCK_ALL_GAMES.PLAYER1_TEAM_ABBREVIATION==TEAM))]
SHOTS_PERCENT=SHOTS_PERCENT.groupby(by=["PLAYER1_TEAM_ABBREVIATION","PERIOD","PLAYER1_NAME"])["Event"].count()
SHOTS_PERCENT=pd.DataFrame(SHOTS_PERCENT)
SHOTS_PERCENT.reset_index(inplace=True)
SHOTS_PERCENT['CATEGORY_PERCENT']=SHOTS_PERCENT['Event'] / SHOTS_PERCENT.groupby(['PLAYER1_NAME'])['Event'].transform('sum')*100
SHOTS_PERCENT=SHOTS_PERCENT.round({'CATEGORY_PERCENT': 1})
SHOTS_PERCENT["WEIGHTED"]=SHOTS_PERCENT["Event"]*2*(SHOTS_PERCENT["CATEGORY_PERCENT"]/100)*SHOTS_PERCENT["PERIOD"]
SHOTS_PERCENT["TOTALS"]=SHOTS_PERCENT.groupby(['PLAYER1_NAME'])['WEIGHTED'].transform('sum')
SHOTS_PERCENT["TOTALS1"]=SHOTS_PERCENT["TOTALS"]*SHOTS_PERCENT["PERIOD"]

SHOTS_PERCENT["EVENT_TOTALS"]=SHOTS_PERCENT.groupby(['PLAYER1_NAME'])['TOTALS1'].transform('sum')
# SHOTS_PERCENT["WEIGHTED"].groupby(by=["PLAYER1_NAME"]).sum() / SHOTS_PERCENT["Event"].groupby(by=["PLAYER1_NAME"]).sum()
# SHOTS_PERCENT=SHOTS_PERCENT.groupby(by=["PLAYER1_NAME"])(["WEIGHTED"]/["Event"])
SHOTS_PERCENT

NameError: name 'BLOCK_ALL_GAMES' is not defined

In [7]:
#Rebounds grouped by Period
SHOTS_PERCENT=BLOCK_ALL_GAMES[((BLOCK_ALL_GAMES.PLAYER1_NAME!="No") & (BLOCK_ALL_GAMES.Event=="Made FG") & (BLOCK_ALL_GAMES.PLAYER1_TEAM_ABBREVIATION==TEAM))]
SHOTS_PERCENT=SHOTS_PERCENT.groupby(by=["PLAYER1_TEAM_ABBREVIATION","PERIOD","PLAYER1_NAME"])["Event"].count()
SHOTS_PERCENT=pd.DataFrame(SHOTS_PERCENT)
SHOTS_PERCENT.reset_index(inplace=True)
SHOTS_PERCENT['CATEGORY_PERCENT']=SHOTS_PERCENT['Event'] / SHOTS_PERCENT.groupby(['PLAYER1_NAME'])['Event'].transform('sum')*100
SHOTS_PERCENT=SHOTS_PERCENT.round({'CATEGORY_PERCENT': 1})
# SHOTS_PERCENT["WEIGHTED"].groupby(by=["PLAYER1_NAME"]).sum() / SHOTS_PERCENT["Event"].groupby(by=["PLAYER1_NAME"]).sum()
# SHOTS_PERCENT=SHOTS_PERCENT.groupby(by=["PLAYER1_NAME"])(["WEIGHTED"]/["Event"])
SHOTS_PERCENT

NameError: name 'BLOCK_ALL_GAMES' is not defined

In [8]:
#Rebounds grouped by Period
SHOTS_PERCENT2=BLOCK_ALL_GAMES[((BLOCK_ALL_GAMES.PLAYER1_NAME!="No") & (BLOCK_ALL_GAMES.Event=="Made FG") & (BLOCK_ALL_GAMES.PLAYER1_TEAM_ABBREVIATION==TEAM))]
SHOTS_PERCENT2=SHOTS_PERCENT2.groupby(by=["PLAYER1_TEAM_ABBREVIATION","MARGIN","PLAYER1_NAME"])["Event"].count()
SHOTS_PERCENT2=pd.DataFrame(SHOTS_PERCENT2)
SHOTS_PERCENT2.reset_index(inplace=True)
SHOTS_PERCENT2['CATEGORY_PERCENT']=SHOTS_PERCENT2['Event'] / SHOTS_PERCENT2.groupby(['PLAYER1_NAME'])['Event'].transform('sum')*100
SHOTS_PERCENT2=SHOTS_PERCENT2.round({'CATEGORY_PERCENT': 1})
# SHOTS_PERCENT["WEIGHTED"].groupby(by=["PLAYER1_NAME"]).sum() / SHOTS_PERCENT["Event"].groupby(by=["PLAYER1_NAME"]).sum()
# SHOTS_PERCENT=SHOTS_PERCENT.groupby(by=["PLAYER1_NAME"])(["WEIGHTED"]/["Event"])
SHOTS_PERCENT2

NameError: name 'BLOCK_ALL_GAMES' is not defined

In [9]:
#Rebounds grouped by Period
SHOTS_PERCENT3=BLOCK_ALL_GAMES[((BLOCK_ALL_GAMES.PLAYER1_NAME!="No") & (BLOCK_ALL_GAMES.Event=="Made FG") & (BLOCK_ALL_GAMES.PLAYER1_TEAM_ABBREVIATION==TEAM))]
SHOTS_PERCENT3=SHOTS_PERCENT3.groupby(by=["PLAYER1_TEAM_ABBREVIATION","CLUTCH","PLAYER1_NAME"])["Event"].count()
SHOTS_PERCENT3=pd.DataFrame(SHOTS_PERCENT3)
SHOTS_PERCENT3.reset_index(inplace=True)
SHOTS_PERCENT3['CATEGORY_PERCENT']=SHOTS_PERCENT3['Event'] / SHOTS_PERCENT3.groupby(['PLAYER1_NAME'])['Event'].transform('sum')*100
SHOTS_PERCENT3=SHOTS_PERCENT3.round({'CATEGORY_PERCENT': 1})
# SHOTS_PERCENT["WEIGHTED"].groupby(by=["PLAYER1_NAME"]).sum() / SHOTS_PERCENT["Event"].groupby(by=["PLAYER1_NAME"]).sum()
# SHOTS_PERCENT=SHOTS_PERCENT.groupby(by=["PLAYER1_NAME"])(["WEIGHTED"]/["Event"])
SHOTS_PERCENT3

NameError: name 'BLOCK_ALL_GAMES' is not defined