In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import matplotlib.pyplot as plt
from datetime import *
import pandas_gbq
from datetime import datetime, timedelta, date
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT
A.*,
B.RoundNumber
FROM `perceptive-ivy-290216.f1_api.results_race` A
INNER JOIN
`perceptive-ivy-290216.f1_api.schedules_update` B
ON A.GP=B.EventName AND A.Year=B.Year
# WHERE
# A.Year=2024
# AND B.Year=2024
-- AND
--  A.GP='Qatar Grand Prix'
"""

track2=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [5]:
query3=f"""
SELECT
A.*,
B.RoundNumber
FROM `perceptive-ivy-290216.f1_api.results_sprint` A
INNER JOIN
`perceptive-ivy-290216.f1_api.schedules_update` B
ON A.GP=B.EventName AND A.Year=B.Year
# WHERE
# A.Year=2024
-- AND
-- A.GP='Qatar Grand Prix'
"""
track3=pandas_gbq.read_gbq(query3,project_id,dialect='standard')

Downloading: 100%|██████████|

In [6]:
year=2025

In [7]:
track_race=track2[track2["Year"]==year]
track_sprint=track3[track3["Year"]==year]

In [8]:
points_table=track_race[["RoundNumber","GP","FullName","Points"]]
points_table=points_table.fillna(0)
points_table["Points"]=points_table["Points"].astype(int)
points_table=points_table.sort_values(by=["RoundNumber","FullName"])

In [9]:
points_table.tail()

     RoundNumber                     GP         FullName  Points
166            1  Australian Grand Prix  Nico Hulkenberg       6
170            1  Australian Grand Prix   Oliver Bearman       0
174            1  Australian Grand Prix    Oscar Piastri       2
161            1  Australian Grand Prix     Pierre Gasly       0
168            1  Australian Grand Prix     Yuki Tsunoda       0

In [10]:
points_table_sprint=track_sprint[["RoundNumber","GP","FullName","Points"]]
points_table_sprint["Points"]=points_table_sprint["Points"].astype(int)
points_table_sprint=points_table_sprint.sort_values(by=["RoundNumber","FullName"])

In [11]:
points_table=pd.concat([points_table,points_table_sprint])
# points_table[points_table["GP"]=="British Grand Prix"].sort_values("FullName").head()

In [12]:
races = points_table['GP'].drop_duplicates()
results = points_table.pivot_table(index='FullName', columns='RoundNumber', values='Points', aggfunc='sum')
results.fillna(0)

results['total_points'] = results.sum(axis=1)
results = results.sort_values(by='total_points', ascending=False)
results.drop(columns='total_points', inplace=True)

# Use race name, instead of round no., as column names
results.columns = races
results=results.fillna(0)

In [13]:
fig_pts = px.imshow(
    results,
    text_auto=True,
    aspect='auto',  # Automatically adjust the aspect ratio
    width=1200, height=700,
    # color_continuous_scale=[[0,    'rgb(198, 219, 239)'],  # Blue scale
    #                         [0.25, 'rgb(107, 174, 214)'],
    #                         [0.5,  'rgb(33,  113, 181)'],
    #                         [0.75, 'rgb(8,   81,  156)'],
    #                         [1,    'rgb(8,   48,  107)']],
    labels={'x': 'Race',
            'y': 'FullName',
            'color': 'Points'}       # Change hover texts
)
fig_pts.update_xaxes(title_text='')      # Remove axis titles
fig_pts.update_yaxes(title_text='')
fig_pts.update_yaxes(tickmode='linear')  # Show all ticks, i.e. driver names
fig_pts.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey',
                 showline=False,
                 tickson='boundaries')              # Show horizontal grid only
fig_pts.update_xaxes(showgrid=False, showline=False)    # And remove vertical grid
fig_pts.update_layout(plot_bgcolor='rgba(0,0,0,0)')     # White background
fig_pts.update_layout(coloraxis_showscale=False)        # Remove legend
fig_pts.update_layout(xaxis=dict(side='top'))           # x-axis on top
fig_pts.update_layout(margin=dict(l=0, r=0, b=0, t=0))  # Remove border margins
fig_pts.update_layout(
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=13.5)),
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    xaxis_title="<b>GP</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="BLACK"
    ),
    title_font_family="PT Sans Narrow"
)
fig_pts.show()

In [14]:
save_year=2025

In [15]:
fig_pts.write_html("/Users/rdesh723/statpulse-html/plots/Matrix/{}/Driver and GP Points Matrix for the {} F1 Season.html".format(save_year,year),full_html=False, include_plotlyjs='cdn')

In [16]:
#Position

In [17]:
pos_table=track_race[["RoundNumber","GP","FullName","Position"]]
pos_table=pos_table.fillna(0)
pos_table["Position"]=pos_table["Position"].astype(int)
pos_table=pos_table.sort_values(by=["RoundNumber","FullName"])

In [18]:
pos_table_sprint=track_sprint[["RoundNumber","GP","FullName","Position"]]
pos_table_sprint["Position"]=pos_table_sprint["Position"].astype(int)
pos_table_sprint=pos_table_sprint.sort_values(by=["RoundNumber","FullName"])

In [19]:
races_pos = pos_table['GP'].drop_duplicates()
results_pos = pos_table.pivot_table(index='FullName', columns='RoundNumber', values='Position', aggfunc='sum')

# results['total_points'] = results.sum(axis=1)
# results = results.sort_values(by='total_points', ascending=False)
# results.drop(columns='total_points', inplace=True)

# Use race name, instead of round no., as column names
results_pos.columns = races_pos
results_pos.fillna(0)
results_pos

GP                     Australian Grand Prix
FullName
Alexander Albon                            4
Andrea Kimi Antonelli                      5
Carlos Sainz                              18
Charles Leclerc                            8
Esteban Ocon                              13
Fernando Alonso                           17
Gabriel Bortoleto                         16
George Russell                             3
Isack Hadjar                              20
Jack Doohan                               19
Lance Stroll                               6
Lando Norris                               1
Lewis Hamilton                            10
Liam Lawson                               15
Max Verstappen                             2
Nico Hulkenberg                            7
Oliver Bearman                            14
Oscar Piastri                              9
Pierre Gasly                              11
Yuki Tsunoda                              12

In [20]:
fig_pos = px.imshow(
    results_pos,
    text_auto=True,
    aspect='auto',  # Automatically adjust the aspect ratio
    width=1200, height=700,
    color_continuous_scale=[[0,    'rgb(198, 219, 239)'],  # Blue scale
                            [0.25, 'rgb(107, 174, 214)'],
                            [0.5,  'rgb(33,  113, 181)'],
                            [0.75, 'rgb(8,   81,  156)'],
                            [1,    'rgb(8,   48,  107)']],
    labels={'x': 'Race',
            'y': 'Driver',
            'color': 'Position'}       # Change hover texts
)
fig_pos.update_xaxes(title_text='')      # Remove axis titles
fig_pos.update_yaxes(title_text='')
fig_pos.update_yaxes(tickmode='linear')  # Show all ticks, i.e. driver names
fig_pos.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey',
                 showline=False,
                 tickson='boundaries')              # Show horizontal grid only
fig_pos.update_xaxes(showgrid=False, showline=False)    # And remove vertical grid
fig_pos.update_layout(plot_bgcolor='rgba(0,0,0,0)')     # White background
fig_pos.update_layout(coloraxis_showscale=False)        # Remove legend
fig_pos.update_layout(xaxis=dict(side='top'))           # x-axis on top
fig_pos.update_layout(margin=dict(l=0, r=0, b=0, t=0))  # Remove border margins
fig_pos.update_layout(
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=13.5)),
    xaxis_title="<b>GP</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="BLACK"
    ),
    title_font_family="PT Sans Narrow"
)
fig_pos.show()

In [21]:
fig_pos.write_html("/Users/rdesh723/statpulse-html/plots/Matrix/{}/Driver and Final GP Position Matrix for the {} F1 Season.html".format(save_year,year),full_html=False, include_plotlyjs='cdn')

In [22]:
races_pos_sprint = pos_table_sprint['GP'].drop_duplicates()
results_pos_sprint = pos_table_sprint.pivot_table(index='FullName', columns='RoundNumber', values='Position', aggfunc='sum')

# results['total_points'] = results.sum(axis=1)
# results = results.sort_values(by='total_points', ascending=False)
# results.drop(columns='total_points', inplace=True)

# Use race name, instead of round no., as column names
results_pos_sprint.columns = races_pos_sprint
results_pos_sprint.fillna(0)
results_pos_sprint

Empty DataFrame
Columns: []
Index: []

In [23]:
fig_pos_sprint = px.imshow(
    results_pos_sprint,
    text_auto=True,
    width=1200, height=700,
    aspect='auto',  # Automatically adjust the aspect ratio
    color_continuous_scale=[[0,    'rgb(198, 219, 239)'],  # Blue scale
                            [0.25, 'rgb(107, 174, 214)'],
                            [0.5,  'rgb(33,  113, 181)'],
                            [0.75, 'rgb(8,   81,  156)'],
                            [1,    'rgb(8,   48,  107)']],
    labels={'x': 'Race',
            'y': 'Driver',
            'color': 'Position'}       # Change hover texts
)
fig_pos_sprint.update_xaxes(title_text='')      # Remove axis titles
fig_pos_sprint.update_yaxes(title_text='')
fig_pos_sprint.update_yaxes(tickmode='linear')  # Show all ticks, i.e. driver names
fig_pos_sprint.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey',
                 showline=False,
                 tickson='boundaries')              # Show horizontal grid only
fig_pos_sprint.update_xaxes(showgrid=False, showline=False)    # And remove vertical grid
fig_pos_sprint.update_layout(plot_bgcolor='rgba(0,0,0,0)')     # White background
fig_pos_sprint.update_layout(coloraxis_showscale=False)        # Remove legend
fig_pos_sprint.update_layout(xaxis=dict(side='top'))           # x-axis on top
fig_pos_sprint.update_layout(margin=dict(l=0, r=0, b=0, t=0))  # Remove border margins
fig_pos_sprint.update_layout(
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=13.5)),
    xaxis_title="<b>GP</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="BLACK"
    ),
    title_font_family="PT Sans Narrow"
)
fig_pos_sprint.show()

In [24]:
fig_pos_sprint.write_html("/Users/rdesh723/statpulse-html/plots/Matrix/{}/Driver and Final Sprint Position Matrix for the {} F1 Season.html".format(save_year,year),full_html=False, include_plotlyjs='cdn')

In [25]:
# Grid Position

In [26]:
grid_pos_table=track_race[["RoundNumber","GP","FullName","Position"]]
grid_pos_table=grid_pos_table.fillna(0)
grid_pos_table["Position"]=grid_pos_table["Position"].astype(int)
grid_pos_table=grid_pos_table.sort_values(by=["RoundNumber","FullName"])

In [27]:
grid_pos_table_sprint=track_sprint[["RoundNumber","GP","FullName","Position"]]
grid_pos_table_sprint["Position"]=grid_pos_table_sprint["Position"].astype(int)
grid_pos_table_sprint=grid_pos_table_sprint.sort_values(by=["RoundNumber","FullName"])

In [28]:
races_grid_pos = grid_pos_table['GP'].drop_duplicates()
results_grid_pos = grid_pos_table.pivot_table(index='FullName', columns='RoundNumber', values='Position', aggfunc='sum')

# results['total_points'] = results.sum(axis=1)
# results = results.sort_values(by='total_points', ascending=False)
# results.drop(columns='total_points', inplace=True)

# Use race name, instead of round no., as column names
results_grid_pos.columns = races_grid_pos
results_grid_pos.fillna(0)
results_grid_pos

GP                     Australian Grand Prix
FullName
Alexander Albon                            4
Andrea Kimi Antonelli                      5
Carlos Sainz                              18
Charles Leclerc                            8
Esteban Ocon                              13
Fernando Alonso                           17
Gabriel Bortoleto                         16
George Russell                             3
Isack Hadjar                              20
Jack Doohan                               19
Lance Stroll                               6
Lando Norris                               1
Lewis Hamilton                            10
Liam Lawson                               15
Max Verstappen                             2
Nico Hulkenberg                            7
Oliver Bearman                            14
Oscar Piastri                              9
Pierre Gasly                              11
Yuki Tsunoda                              12

In [29]:
fig_grid_pos = px.imshow(
    results_grid_pos,
    text_auto=True,
    aspect='auto',  # Automatically adjust the aspect ratio
    width=1200, height=700,
    color_continuous_scale=[[0,    'rgb(198, 219, 239)'],  # Blue scale
                            [0.25, 'rgb(107, 174, 214)'],
                            [0.5,  'rgb(33,  113, 181)'],
                            [0.75, 'rgb(8,   81,  156)'],
                            [1,    'rgb(8,   48,  107)']],
    labels={'x': 'Race',
            'y': 'Driver',
            'color': 'Position'}       # Change hover texts
)
fig_grid_pos.update_xaxes(title_text='')      # Remove axis titles
fig_grid_pos.update_yaxes(title_text='')
fig_grid_pos.update_yaxes(tickmode='linear')  # Show all ticks, i.e. driver names
fig_grid_pos.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey',
                 showline=False,
                 tickson='boundaries')              # Show horizontal grid only
fig_grid_pos.update_xaxes(showgrid=False, showline=False)    # And remove vertical grid
fig_grid_pos.update_layout(plot_bgcolor='rgba(0,0,0,0)')     # White background
fig_grid_pos.update_layout(coloraxis_showscale=False)        # Remove legend
fig_grid_pos.update_layout(xaxis=dict(side='top'))           # x-axis on top
fig_grid_pos.update_layout(margin=dict(l=0, r=0, b=0, t=0))  # Remove border margins
fig_grid_pos.update_layout(
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=13.5)),
    xaxis_title="<b>GP</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="BLACK"
    ),
    title_font_family="PT Sans Narrow"
)
fig_grid_pos.show()

In [30]:
fig_grid_pos.write_html("/Users/rdesh723/statpulse-html/plots/Matrix/{}/Driver and Race Grid Position Matrix for the {} F1 Season.html".format(save_year,year),full_html=False, include_plotlyjs='cdn')

In [31]:
races_grid_pos_sprint = grid_pos_table_sprint['GP'].drop_duplicates()
results_grid_pos_sprint = grid_pos_table_sprint.pivot_table(index='FullName', columns='RoundNumber', values='Position', aggfunc='sum')

# results['total_points'] = results.sum(axis=1)
# results = results.sort_values(by='total_points', ascending=False)
# results.drop(columns='total_points', inplace=True)

# Use race name, instead of round no., as column names
results_grid_pos_sprint.columns = races_grid_pos_sprint
results_grid_pos_sprint.fillna(0)
results_grid_pos_sprint

Empty DataFrame
Columns: []
Index: []

In [32]:
fig_grid_sprint_pos = px.imshow(
    results_grid_pos_sprint,
    text_auto=True,
    aspect='auto',  # Automatically adjust the aspect ratio
    width=1200, height=700,
    color_continuous_scale=[[0,    'rgb(198, 219, 239)'],  # Blue scale
                            [0.25, 'rgb(107, 174, 214)'],
                            [0.5,  'rgb(33,  113, 181)'],
                            [0.75, 'rgb(8,   81,  156)'],
                            [1,    'rgb(8,   48,  107)']],
    labels={'x': 'Race',
            'y': 'Driver',
            'color': 'Position'}       # Change hover texts
)
fig_grid_sprint_pos.update_xaxes(title_text='')      # Remove axis titles
fig_grid_sprint_pos.update_yaxes(title_text='')
fig_grid_sprint_pos.update_yaxes(tickmode='linear')  # Show all ticks, i.e. driver names
fig_grid_sprint_pos.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGrey',
                 showline=False,
                 tickson='boundaries')              # Show horizontal grid only
fig_grid_sprint_pos.update_xaxes(showgrid=False, showline=False)    # And remove vertical grid
fig_grid_sprint_pos.update_layout(plot_bgcolor='rgba(0,0,0,0)')     # White background
fig_grid_sprint_pos.update_layout(coloraxis_showscale=False)        # Remove legend
fig_grid_sprint_pos.update_layout(xaxis=dict(side='top'))           # x-axis on top
fig_grid_sprint_pos.update_layout(margin=dict(l=0, r=0, b=0, t=0))  # Remove border margins
fig_grid_sprint_pos.update_layout(
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=13.5)),
    xaxis_title="<b>GP</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
    ),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="BLACK"
    ),
    title_font_family="PT Sans Narrow"
)
fig_grid_sprint_pos.show()

In [33]:
fig_grid_sprint_pos.write_html("/Users/rdesh723/statpulse-html/plots/Matrix/{}/Driver and Sprint Race Grid Position Matrix for the {} F1 Season.html".format(save_year,year),full_html=False, include_plotlyjs='cdn')