In [13]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from PIL import Image
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [14]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [15]:
query2=f"""
SELECT
*
FROM `perceptive-ivy-290216.f1_api.sprint_lap_time`  A
# WHERE A.Year=2024
# AND A.GP="Monaco Grand Prix"
# AND A.DRIVER='HAM'
ORDER BY LapNumber, LapStartTime
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [16]:
track2=track3[(track3["GP"]=='Chinese Grand Prix')&(track3["Year"]==2025)]
track2.head()
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]

In [17]:
track2['LapTime']= pd.to_timedelta(track2["LapTime"])

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_40924/4173085553.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
# track2['LapTime'].dt.total_seconds().min()*1.07
track2=track2[track2['LapNumber']!=1.0]
track2=track2[track2['LapNumber']!=19.0]

In [19]:
# quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.1]
quicklaps=track2
quicklaps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
511,0 days 00:48:25.746000,HAM,44,0 days 00:01:35.399000,2.0,1.0,NaT,NaT,0 days 00:00:25.591000,0 days 00:00:28.731000,0 days 00:00:41.077000,0 days 00:47:16.014000,0 days 00:47:44.745000,0 days 00:48:25.822000,NaN,275.0,260.0,312.0,True,MEDIUM,8.0,False,Ferrari,0 days 00:46:50.347000,2025-03-22 03:05:21.513,1,1.0,False,,False,True,2025,Chinese Grand Prix
512,0 days 00:48:26.863000,VER,1,0 days 00:01:35.745000,2.0,1.0,NaT,NaT,0 days 00:00:25.654000,0 days 00:00:28.886000,0 days 00:00:41.205000,0 days 00:47:16.833000,0 days 00:47:45.719000,0 days 00:48:26.924000,279.0,275.0,261.0,317.0,True,MEDIUM,5.0,False,Red Bull Racing,0 days 00:46:51.118000,2025-03-22 03:05:22.284,1,2.0,False,,False,True,2025,Chinese Grand Prix
513,0 days 00:48:28.523000,PIA,81,0 days 00:01:36.086000,2.0,1.0,NaT,NaT,0 days 00:00:25.510000,0 days 00:00:29.217000,0 days 00:00:41.359000,0 days 00:47:18.038000,0 days 00:47:47.255000,0 days 00:48:28.614000,273.0,275.0,261.0,315.0,True,MEDIUM,6.0,False,McLaren,0 days 00:46:52.437000,2025-03-22 03:05:23.603,1,3.0,False,,False,True,2025,Chinese Grand Prix
515,0 days 00:48:30.092000,RUS,63,0 days 00:01:36.432000,2.0,1.0,NaT,NaT,0 days 00:00:26.032000,0 days 00:00:29.221000,0 days 00:00:41.179000,0 days 00:47:19.692000,0 days 00:47:48.913000,0 days 00:48:30.092000,275.0,272.0,262.0,319.0,True,MEDIUM,10.0,False,Mercedes,0 days 00:46:53.660000,2025-03-22 03:05:24.826,1,4.0,False,,False,True,2025,Chinese Grand Prix
516,0 days 00:48:30.902000,LEC,16,0 days 00:01:36.895000,2.0,1.0,NaT,NaT,0 days 00:00:26.226000,0 days 00:00:29.410000,0 days 00:00:41.259000,0 days 00:47:20.278000,0 days 00:47:49.688000,0 days 00:48:30.947000,284.0,279.0,268.0,337.0,True,MEDIUM,8.0,False,Ferrari,0 days 00:46:54.007000,2025-03-22 03:05:25.173,1,5.0,False,,False,True,2025,Chinese Grand Prix

In [20]:
#Remove Pitstops and Track Status other than Clear to remove slow laps
quicklaps=quicklaps[((quicklaps["PitOutTime"]=='NaT')&(quicklaps["PitInTime"]=='NaT')&(~quicklaps["TrackStatus"].isin(['4','41','5','6','7','124'])))]

In [21]:
transformed_laps = quicklaps.copy()
transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

# order the team from the fastest (lowest median lap time) tp slower
team_order = (
    transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
)
print(team_order)

Index(['PIA', 'HAM', 'VER', 'LEC', 'STR', 'RUS', 'TSU', 'ANT', 'SAI', 'NOR',
       'ALO', 'ALB', 'BEA', 'LAW', 'DOO', 'HAD', 'GAS', 'OCO', 'BOR', 'HUL'],
      dtype='object', name='Driver')

In [22]:
transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
transformed_laps.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,LapTime (s),median
6315,0 days 01:14:59.325000,BOR,5,0 days 00:01:39.642000,18.0,1.0,NaT,NaT,0 days 00:00:26.765000,0 days 00:00:30.220000,0 days 00:00:42.657000,0 days 01:13:46.498000,0 days 01:14:16.718000,0 days 01:14:59.375000,279.0,275.0,269.0,336.0,False,MEDIUM,24.0,False,Kick Sauber,0 days 01:13:19.683000,2025-03-22 03:31:50.849,1,16.0,False,,False,True,2025,Chinese Grand Prix,99.642,98.949
6316,0 days 01:14:59.945000,OCO,31,0 days 00:01:39.736000,18.0,1.0,NaT,NaT,0 days 00:00:26.571000,0 days 00:00:30.557000,0 days 00:00:42.608000,0 days 01:13:46.850000,0 days 01:14:17.407000,0 days 01:15:00.015000,280.0,272.0,269.0,333.0,False,MEDIUM,24.0,False,Haas F1 Team,0 days 01:13:20.209000,2025-03-22 03:31:51.375,1,17.0,False,,False,True,2025,Chinese Grand Prix,99.736,98.871
6317,0 days 01:15:03.515000,HUL,27,0 days 00:01:41.825000,18.0,1.0,NaT,NaT,0 days 00:00:26.406000,0 days 00:00:30.016000,0 days 00:00:45.403000,0 days 01:13:48.148000,0 days 01:14:18.164000,0 days 01:15:03.567000,277.0,270.0,261.0,312.0,False,MEDIUM,24.0,False,Kick Sauber,0 days 01:13:21.690000,2025-03-22 03:31:52.856,1,19.0,False,,False,True,2025,Chinese Grand Prix,101.825,99.068
6318,0 days 01:15:01.655000,DOO,7,0 days 00:01:39.658000,18.0,1.0,NaT,NaT,0 days 00:00:26.474000,0 days 00:00:30.050000,0 days 00:00:43.134000,0 days 01:13:48.574000,0 days 01:14:18.624000,0 days 01:15:01.758000,277.0,275.0,262.0,329.0,False,MEDIUM,24.0,False,Alpine,0 days 01:13:21.997000,2025-03-22 03:31:53.163,1,18.0,False,,False,True,2025,Chinese Grand Prix,99.658,98.609
6319,0 days 01:15:05.634000,SAI,55,0 days 00:01:37.675000,18.0,2.0,NaT,NaT,0 days 00:00:26.115000,0 days 00:00:29.434000,0 days 00:00:42.126000,0 days 01:13:54.126000,0 days 01:14:23.560000,0 days 01:15:05.686000,276.0,276.0,262.0,317.0,False,MEDIUM,13.0,False,Williams,0 days 01:13:27.959000,2025-03-22 03:31:59.125,1,20.0,False,,False,True,2025,Chinese Grand Prix,97.675,97.803

In [ ]:
fig_pace=px.box(
    transformed_laps.sort_values(by=["median","LapNumber"]),
    x="Driver",
    y="LapTime (s)",
    color='Driver',
    template="xgridoff",
    hover_data=["LapNumber","TrackStatus","Position"],
    title="<b>Driver Pace Plot for the {} {} Sprint Race</b>".format(year,gp),
    points='all',
    # palette=team_palette,
    # whiskerprops=dict(color="white"),
    # boxprops=dict(edgecolor="white"),
    # medianprops=dict(color="grey"),
    # capprops=dict(color="white"),
    height=700, width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)
fig_pace.update_traces(opacity=1)
fig_pace.update_layout(
    title_x=0.5,
    hoverlabel=dict(
    bgcolor="white",
    font_size=16,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=50, r=5, t=35, b=50)
)
fig_pace.show()

In [24]:
fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Driver Pace Plots/{}/{} {} Sprint Race Driver Pace Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [25]:
#Get MINIMUM OF THE MEDIAN LAP TIMES

fastest_lap = transformed_laps["median"].min()
transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent']
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
transformed_laps_relative_median=transformed_laps[["Team","Driver","Delta","Delta_Percent","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
transformed_laps_relative_median

                Team Driver  Delta Delta_Percent  Delta_Percent_Abs
513          McLaren    PIA  0.000        100.0%           0.000000
511          Ferrari    HAM  0.021      100.022%           0.021683
512  Red Bull Racing    VER  0.199      100.205%           0.205470
516          Ferrari    LEC  0.437      100.451%           0.451209
520     Aston Martin    STR  0.469      100.484%           0.484249
515         Mercedes    RUS  0.472      100.487%           0.487347
517     Racing Bulls    TSU  0.791      100.817%           0.816718
519         Mercedes    ANT  0.894      100.923%           0.923067
527         Williams    SAI  0.952      100.983%           0.982953
522          McLaren    NOR  1.018      101.051%           1.051099
524     Aston Martin    ALO  1.190      101.229%           1.228691
525         Williams    ALB  1.441      101.488%           1.487852
526     Haas F1 Team    BEA  1.509      101.558%           1.558063
534  Red Bull Racing    LAW  1.656       101.71%           1.709843
533           Alpine    DOO  1.758      101.815%           1.815159
531     Racing Bulls    HAD  1.793      101.851%           1.851297
528           Alpine    GAS  1.818      101.877%           1.877110
532     Haas F1 Team    OCO  2.020      102.086%           2.085678
530      Kick Sauber    BOR  2.098      102.166%           2.166214
535      Kick Sauber    HUL  2.217      102.289%           2.289083

In [26]:
for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta']=0.001

for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']=0.001
        
transformed_laps_relative_median

                Team Driver  Delta Delta_Percent  Delta_Percent_Abs
513          McLaren    PIA  0.001        100.0%           0.001000
511          Ferrari    HAM  0.021      100.022%           0.021683
512  Red Bull Racing    VER  0.199      100.205%           0.205470
516          Ferrari    LEC  0.437      100.451%           0.451209
520     Aston Martin    STR  0.469      100.484%           0.484249
515         Mercedes    RUS  0.472      100.487%           0.487347
517     Racing Bulls    TSU  0.791      100.817%           0.816718
519         Mercedes    ANT  0.894      100.923%           0.923067
527         Williams    SAI  0.952      100.983%           0.982953
522          McLaren    NOR  1.018      101.051%           1.051099
524     Aston Martin    ALO  1.190      101.229%           1.228691
525         Williams    ALB  1.441      101.488%           1.487852
526     Haas F1 Team    BEA  1.509      101.558%           1.558063
534  Red Bull Racing    LAW  1.656       101.71%           1.709843
533           Alpine    DOO  1.758      101.815%           1.815159
531     Racing Bulls    HAD  1.793      101.851%           1.851297
528           Alpine    GAS  1.818      101.877%           1.877110
532     Haas F1 Team    OCO  2.020      102.086%           2.085678
530      Kick Sauber    BOR  2.098      102.166%           2.166214
535      Kick Sauber    HUL  2.217      102.289%           2.289083

In [ ]:
fig_median=px.bar(
    transformed_laps_relative_median,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Median Lap Times) for the {} {} Sprint Race</b>".format(year,gp),
    text="Delta_Percent",
    height=700, 
    width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_median.update_traces(textposition='outside')

fig_median.update_traces(opacity=0.85)

fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta_Percent_Abs'].max()+0.7, 0])

fig_median.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_median.update_xaxes(title_text='')      # Remove axis titles
fig_median.update_yaxes(title_text='Percentage%')

fig_median.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_median.Team, transformed_laps_relative_median.Delta_Percent_Abs, transformed_laps_relative_median.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_median.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig_median.update_layout(
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig_median.show()

In [28]:
fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Median Lap Times/{}/{} {} Sprint Race Driver Median Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [29]:
#Get MINIMUM OF ALL LAP TIMES
transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

fastest_lap_all = transformed_laps["min_all"].min()
transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_All']
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
transformed_laps_relative_min_all=transformed_laps[["Team","Driver","Delta_Min_All","Delta_Percent_All","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
511,Ferrari,HAM,0.000,100.0%,0.000000
512,Red Bull Racing,VER,0.346,100.363%,0.362687
527,Williams,SAI,0.420,100.44%,0.440256
513,McLaren,PIA,0.455,100.477%,0.476944
515,Mercedes,RUS,0.492,100.516%,0.515729
516,Ferrari,LEC,0.856,100.897%,0.897284
519,Mercedes,ANT,0.912,100.956%,0.955985
517,Racing Bulls,TSU,0.989,101.037%,1.036698
520,Aston Martin,STR,1.036,101.086%,1.085965
535,Kick Sauber,HUL,1.130,101.184%,1.184499
522,McLaren,NOR,1.309,101.372%,1.372132
524,Aston Martin,ALO,1.659,101.739%,1.739012
526,Haas F1 Team,BEA,1.736,101.82%,1.819726
534,Red Bull Racing,LAW,1.764,101.849%,1.849076
525,Williams,ALB,1.945,102.039%,2.038805
530,Kick Sauber,BOR,2.076,102.176%,2.176123
528,Alpine,GAS,2.082,102.182%,2.182413
531,Racing Bulls,HAD,2.150,102.254%,2.253692
532,Haas F1 Team,OCO,2.155,102.259%,2.258934
533,Alpine,DOO,2.287,102.397%,2.397300

In [30]:
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
511,Ferrari,HAM,0.001,100.0%,0.001000
512,Red Bull Racing,VER,0.346,100.363%,0.362687
527,Williams,SAI,0.420,100.44%,0.440256
513,McLaren,PIA,0.455,100.477%,0.476944
515,Mercedes,RUS,0.492,100.516%,0.515729
516,Ferrari,LEC,0.856,100.897%,0.897284
519,Mercedes,ANT,0.912,100.956%,0.955985
517,Racing Bulls,TSU,0.989,101.037%,1.036698
520,Aston Martin,STR,1.036,101.086%,1.085965
535,Kick Sauber,HUL,1.130,101.184%,1.184499
522,McLaren,NOR,1.309,101.372%,1.372132
524,Aston Martin,ALO,1.659,101.739%,1.739012
526,Haas F1 Team,BEA,1.736,101.82%,1.819726
534,Red Bull Racing,LAW,1.764,101.849%,1.849076
525,Williams,ALB,1.945,102.039%,2.038805
530,Kick Sauber,BOR,2.076,102.176%,2.176123
528,Alpine,GAS,2.082,102.182%,2.182413
531,Racing Bulls,HAD,2.150,102.254%,2.253692
532,Haas F1 Team,OCO,2.155,102.259%,2.258934
533,Alpine,DOO,2.287,102.397%,2.397300

In [ ]:
fig_min=px.bar(
    transformed_laps_relative_min_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Fastest Lap Times) for the {} {} Sprint Race</b>".format(year,gp),
    text="Delta_Percent_All",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_min.update_traces(textposition='outside')

fig_min.update_traces(opacity=0.85)

fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Percent_Abs'].max()+0.8, 0])

fig_min.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_min.update_xaxes(title_text='')      # Remove axis titles
fig_min.update_yaxes(title_text='Percentage%')

fig_min.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_min_all.Team, transformed_laps_relative_min_all.Delta_Percent_Abs, transformed_laps_relative_min_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_min.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )


fig_min.update_layout(
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=22,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_min.update_yaxes(ticksuffix = "  ")

fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

fig_min.show()

In [32]:
fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Fastest Lap/{}/{} {} Sprint Race Driver Fastest Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [33]:
#Get AVERAGE OF ALL LAP TIMES
transformed_laps['avg_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform(np.mean)

fastest_lap_avg = transformed_laps["avg_all"].min()
transformed_laps['Delta_Avg_All']= transformed_laps["avg_all"] - (fastest_lap_avg)
transformed_laps['Delta_Percent_Avg']= (transformed_laps["avg_all"]/(fastest_lap_avg)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_Avg']
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+100
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].round(3)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].astype(str)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+"%"
transformed_laps_relative_avg_all=transformed_laps[["Team","Driver","Delta_Avg_All","Delta_Percent_Avg","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all.sort_values("Delta_Avg_All")
transformed_laps_relative_avg_all

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_40924/2458230245.py:2: FutureWarning:

The provided callable <function mean at 0x1082eb4c0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
511,Ferrari,HAM,0.000000,100.0%,0.000000
513,McLaren,PIA,0.240882,100.249%,0.248755
515,Mercedes,RUS,0.375118,100.387%,0.387377
516,Ferrari,LEC,0.386824,100.399%,0.399465
512,Red Bull Racing,VER,0.457176,100.472%,0.472118
522,McLaren,NOR,0.929588,100.96%,0.959968
517,Racing Bulls,TSU,0.936000,100.967%,0.966590
519,Mercedes,ANT,0.944647,100.976%,0.975519
527,Williams,SAI,0.948173,100.979%,0.979160
520,Aston Martin,STR,1.040765,101.075%,1.074778
524,Aston Martin,ALO,1.636882,101.69%,1.690378
528,Alpine,GAS,1.726294,101.783%,1.782712
525,Williams,ALB,1.731353,101.788%,1.787936
534,Red Bull Racing,LAW,1.827529,101.887%,1.887255
531,Racing Bulls,HAD,1.866235,101.927%,1.927226
532,Haas F1 Team,OCO,1.982412,102.047%,2.047200
530,Kick Sauber,BOR,1.998412,102.064%,2.063723
526,Haas F1 Team,BEA,2.006235,102.072%,2.071802
535,Kick Sauber,HUL,2.047412,102.114%,2.114324
533,Alpine,DOO,2.053941,102.121%,2.121067

In [34]:
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']=0.001
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']=0.001    
        
transformed_laps_relative_avg_all

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
511,Ferrari,HAM,0.001000,100.0%,0.001000
513,McLaren,PIA,0.240882,100.249%,0.248755
515,Mercedes,RUS,0.375118,100.387%,0.387377
516,Ferrari,LEC,0.386824,100.399%,0.399465
512,Red Bull Racing,VER,0.457176,100.472%,0.472118
522,McLaren,NOR,0.929588,100.96%,0.959968
517,Racing Bulls,TSU,0.936000,100.967%,0.966590
519,Mercedes,ANT,0.944647,100.976%,0.975519
527,Williams,SAI,0.948173,100.979%,0.979160
520,Aston Martin,STR,1.040765,101.075%,1.074778
524,Aston Martin,ALO,1.636882,101.69%,1.690378
528,Alpine,GAS,1.726294,101.783%,1.782712
525,Williams,ALB,1.731353,101.788%,1.787936
534,Red Bull Racing,LAW,1.827529,101.887%,1.887255
531,Racing Bulls,HAD,1.866235,101.927%,1.927226
532,Haas F1 Team,OCO,1.982412,102.047%,2.047200
530,Kick Sauber,BOR,1.998412,102.064%,2.063723
526,Haas F1 Team,BEA,2.006235,102.072%,2.071802
535,Kick Sauber,HUL,2.047412,102.114%,2.114324
533,Alpine,DOO,2.053941,102.121%,2.121067

In [ ]:
fig=px.bar(
    transformed_laps_relative_avg_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Average Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_Avg",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig.update_traces(textposition='outside')

fig.update_traces(opacity=0.85)

fig.update_traces( marker_line_color='white',marker_line_width=1.5)

fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_yaxes(range=[transformed_laps_relative_avg_all['Delta_Percent_Abs'].max()+0.7, 0])

fig.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig.update_xaxes(title_text='')      # Remove axis titles
fig.update_yaxes(title_text='Percentage%')

fig.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_avg_all.Team, transformed_laps_relative_avg_all.Delta_Percent_Abs, transformed_laps_relative_avg_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig.show()

In [36]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Average Lap Times/{}/{} {} Driver Average Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [37]:
#Multi Race Plot

In [38]:
#2024
# race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']
#2022
# race_multi=['Austrian Grand Prix','Emilia Romagna Grand Prix','São Paulo Grand Prix']
#2021
race_multi=['British Grand Prix','Italian Grand Prix','São Paulo Grand Prix']

year_multi=2021
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    track2['LapTime']= pd.to_timedelta(track2["LapTime"])
    track2=track2[track2['LapNumber']!=1.0]
    quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.07]
    transformed_laps = quicklaps.copy()
    transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

    # order the team from the fastest (lowest median lap time) tp slower
    team_order = (
        transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
    )
    print(team_order)
    transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
    transformed_laps.tail()
    fig_pace=px.box(
        transformed_laps.sort_values(by=["median","LapNumber"]),
        x="Driver",
        y="LapTime (s)",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace Plot for the {} {} Sprint Race</b>".format(year_multi,i),
        height=700, width=1200,

    color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )
    fig_pace.update_traces(opacity=1)
    fig_pace.update_layout(
        title_x=0.5,
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow",
        margin=dict(l=50, r=5, t=35, b=50)
    )
    fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Driver Pace Plots/{}/{} {} Sprint Race Driver Pace Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')
    #Get MINIMUM OF THE MEDIAN LAP TIMES

    fastest_lap = transformed_laps["median"].min()
    transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
    transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
    transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent"]].drop_duplicates()
    transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
    transformed_laps_relative_median
    for index, row in transformed_laps_relative_median.iterrows():
        if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
         transformed_laps_relative_median.loc[index, 'Delta']=0.001
    transformed_laps_relative_median
    fig_median=px.bar(
        transformed_laps_relative_median,
        x="Driver",
        y="Delta",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Median Lap Times) for the {} {} Sprint Race</b>".format(year_multi,i),
        text="Delta_Percent",
        height=700, 
        width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_median.update_traces(textposition='outside')

    fig_median.update_traces(opacity=0.85)

    fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta'].max()+0.6, 0])

    fig_median.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_median.update_xaxes(title_text='')      # Remove axis titles
    fig_median.update_yaxes(title_text='')

    fig_median.update_xaxes(
            title_standoff = 75
    )

    fig_median.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

    fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Median Lap Times/{}/{} {} Sprint Race Driver Median Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

    transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

    fastest_lap_all = transformed_laps["min_all"].min()
    transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
    transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
    transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All"]].drop_duplicates()
    transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
    transformed_laps_relative_min_all
    for index, row in transformed_laps_relative_min_all.iterrows():
        if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
         transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    transformed_laps_relative_min_all
    fig_min=px.bar(
        transformed_laps_relative_min_all,
        x="Driver",
        y="Delta_Min_All",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Fastest Lap Times) for the {} {} Sprint Race</b>".format(year_multi,i),
        text="Delta_Percent_All",
        height=700, width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_min.update_traces(textposition='outside')

    fig_min.update_traces(opacity=0.85)

    fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Min_All'].max()+0.5, 0])

    fig_min.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_min.update_xaxes(title_text='')      # Remove axis titles
    fig_min.update_yaxes(title_text='')

    fig_min.update_xaxes(
            title_standoff = 75
    )

    fig_min.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_min.update_yaxes(ticksuffix = "  ")

    fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
    fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Fastest Lap/{}/{} {} Sprint Race Driver Fastest Lap Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_40924/2812607600.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'HAM', 'BOT', 'LEC', 'NOR', 'RIC', 'SAI', 'PER', 'ALO', 'VET',
       'TSU', 'GAS', 'OCO', 'RUS', 'RAI', 'STR', 'LAT', 'GIO', 'MSC', 'MAZ'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_40924/2812607600.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_40924/2812607600.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['BOT', 'VER', 'RIC', 'NOR', 'HAM', 'LEC', 'SAI', 'PER', 'GIO', 'STR',
       'VET', 'ALO', 'OCO', 'RUS', 'LAT', 'TSU', 'MAZ', 'KUB', 'MSC'],
      dtype='object', name='Driver')
Index(['VER', 'BOT', 'HAM', 'SAI', 'PER', 'NOR', 'LEC', 'VET', 'OCO', 'ALO',
       'GAS', 'RIC', 'GIO', 'TSU', 'STR', 'RAI', 'LAT', 'RUS', 'MSC', 'MAZ'],
      dtype='object', name='Driver')