In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT
*
FROM `perceptive-ivy-290216.f1_api.sprint_lap_time`  A
# WHERE A.Year=2024
# AND A.GP="Monaco Grand Prix"
# AND A.DRIVER='HAM'
ORDER BY LapNumber, LapStartTime
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [4]:
track2=track3[(track3["GP"]=='Qatar Grand Prix')&(track3["Year"]==2024)]
track2.head()
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]

In [5]:
track2['LapTime']= pd.to_timedelta(track2["LapTime"])

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_12097/4173085553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track2['LapTime']= pd.to_timedelta(track2["LapTime"])

In [6]:
# track2['LapTime'].dt.total_seconds().min()*1.07
track2=track2[track2['LapNumber']!=1.0]

In [7]:
# quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.1]
quicklaps=track2
quicklaps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
406,0 days 00:47:07.164000,NOR,4,0 days 00:01:25.961000,2.0,1.0,NaT,NaT,0 days 00:00:31.925000,0 days 00:00:29.161000,0 days 00:00:24.875000,0 days 00:46:13.128000,0 days 00:46:42.289000,0 days 00:47:07.164000,243.0,284.0,273.0,289.0,True,MEDIUM,7.0,False,McLaren,0 days 00:45:41.203000,2024-11-30 14:04:55.542,1,1.0,False,,False,True,2024,Qatar Grand Prix
409,0 days 00:47:08.279000,PIA,81,0 days 00:01:25.982000,2.0,1.0,NaT,NaT,0 days 00:00:32.133000,0 days 00:00:29.102000,0 days 00:00:24.747000,0 days 00:46:14.441000,0 days 00:46:43.543000,0 days 00:47:08.290000,239.0,284.0,278.0,294.0,True,MEDIUM,7.0,False,McLaren,0 days 00:45:42.297000,2024-11-30 14:04:56.636,1,2.0,False,,False,True,2024,Qatar Grand Prix
411,0 days 00:47:08.962000,RUS,63,0 days 00:01:26.166000,2.0,1.0,NaT,NaT,0 days 00:00:32.122000,0 days 00:00:29.328000,0 days 00:00:24.716000,0 days 00:46:14.882000,0 days 00:46:44.210000,0 days 00:47:08.926000,243.0,288.0,281.0,295.0,True,MEDIUM,6.0,False,Mercedes,0 days 00:45:42.796000,2024-11-30 14:04:57.135,1,3.0,False,,False,True,2024,Qatar Grand Prix
414,0 days 00:47:10.116000,SAI,55,0 days 00:01:26.295000,2.0,1.0,NaT,NaT,0 days 00:00:32.062000,0 days 00:00:29.359000,0 days 00:00:24.874000,0 days 00:46:15.888000,0 days 00:46:45.247000,0 days 00:47:10.121000,242.0,286.0,278.0,296.0,True,MEDIUM,3.0,False,Ferrari,0 days 00:45:43.821000,2024-11-30 14:04:58.160,1,4.0,False,,False,True,2024,Qatar Grand Prix
416,0 days 00:47:10.929000,HAM,44,0 days 00:01:26.545000,2.0,1.0,NaT,NaT,0 days 00:00:32.450000,0 days 00:00:29.264000,0 days 00:00:24.831000,0 days 00:46:16.825000,0 days 00:46:46.089000,0 days 00:47:10.920000,239.0,287.0,280.0,297.0,True,MEDIUM,8.0,False,Mercedes,0 days 00:45:44.384000,2024-11-30 14:04:58.723,1,5.0,False,,False,True,2024,Qatar Grand Prix

In [8]:
transformed_laps = quicklaps.copy()
transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

# order the team from the fastest (lowest median lap time) tp slower
team_order = (
    transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
)
print(team_order)

Index(['PIA', 'LEC', 'RUS', 'SAI', 'VER', 'NOR', 'HAM', 'GAS', 'HUL', 'MAG',
       'ALO', 'BOT', 'STR', 'ZHO', 'COL', 'PER', 'OCO', 'TSU', 'LAW', 'ALB'],
      dtype='object', name='Driver')

In [ ]:
transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
transformed_laps.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,LapTime (s),median
6205,0 days 01:11:50.884000,LAW,30,0 days 00:01:26.458000,19.0,1.0,NaT,NaT,0 days 00:00:32.090000,0 days 00:00:29.361000,0 days 00:00:25.007000,0 days 01:10:56.514000,0 days 01:11:25.875000,0 days 01:11:50.882000,237.0,285.0,276.0,NaN,False,MEDIUM,26.0,False,RB,0 days 01:10:24.426000,2024-11-30 14:29:38.765,1,16.0,False,,False,True,2024,Qatar Grand Prix,86.458,86.4110
6206,0 days 01:11:51.630000,TSU,22,0 days 00:01:26.115000,19.0,1.0,NaT,NaT,0 days 00:00:31.950000,0 days 00:00:29.169000,0 days 00:00:24.996000,0 days 01:10:57.460000,0 days 01:11:26.629000,0 days 01:11:51.625000,NaN,288.0,279.0,303.0,False,MEDIUM,26.0,False,RB,0 days 01:10:25.515000,2024-11-30 14:29:39.854,1,17.0,False,,False,True,2024,Qatar Grand Prix,86.115,86.3895
6207,0 days 01:11:52.167000,COL,43,0 days 00:01:25.959000,19.0,1.0,NaT,NaT,0 days 00:00:31.871000,0 days 00:00:29.355000,0 days 00:00:24.733000,0 days 01:10:58.095000,0 days 01:11:27.450000,0 days 01:11:52.183000,NaN,286.0,282.0,324.0,False,MEDIUM,15.0,True,Williams,0 days 01:10:26.208000,2024-11-30 14:29:40.547,1,18.0,False,,False,True,2024,Qatar Grand Prix,85.959,86.2020
6208,0 days 01:12:27.964000,ZHO,24,0 days 00:01:25.051000,19.0,2.0,NaT,NaT,0 days 00:00:31.607000,0 days 00:00:28.761000,0 days 00:00:24.683000,0 days 01:11:34.487000,0 days 01:12:03.248000,0 days 01:12:27.931000,245.0,286.0,276.0,286.0,True,MEDIUM,17.0,False,Kick Sauber,0 days 01:11:02.913000,2024-11-30 14:30:17.252,1,19.0,False,,False,True,2024,Qatar Grand Prix,85.051,86.1850
6209,0 days 01:12:30.899000,PER,11,0 days 00:01:24.929000,19.0,2.0,NaT,NaT,0 days 00:00:31.450000,0 days 00:00:28.829000,0 days 00:00:24.650000,0 days 01:11:37.404000,0 days 01:12:06.233000,0 days 01:12:30.883000,241.0,286.0,280.0,296.0,False,MEDIUM,26.0,False,Red Bull Racing,0 days 01:11:05.970000,2024-11-30 14:30:20.309,1,20.0,False,,False,True,2024,Qatar Grand Prix,84.929,86.2450

In [10]:
fig_pace=px.box(
    transformed_laps.sort_values(by=["median","LapNumber"]),
    x="Driver",
    y="LapTime (s)",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace Plot for the {} {} Sprint Race</b>".format(year,gp),
    # palette=team_palette,
    # whiskerprops=dict(color="white"),
    # boxprops=dict(edgecolor="white"),
    # medianprops=dict(color="grey"),
    # capprops=dict(color="white"),
    height=700, width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)
fig_pace.update_traces(opacity=1)
fig_pace.update_layout(
    title_x=0.5,
    hoverlabel=dict(
    bgcolor="white",
    font_size=16,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=50, r=5, t=35, b=50)
)
fig_pace.show()

In [11]:
fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Driver Pace Plots/{}/{} {} Sprint Race Driver Pace Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [12]:
#Get MINIMUM OF THE MEDIAN LAP TIMES

fastest_lap = transformed_laps["median"].min()
transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent']
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
transformed_laps_relative_median

    Driver   Delta Delta_Percent
409    PIA  0.0000        100.0%
420    LEC  0.1695      100.199%
411    RUS  0.2060      100.242%
414    SAI  0.2200      100.259%
430    VER  0.3060       100.36%
406    NOR  0.3290      100.387%
416    HAM  0.3740       100.44%
426    GAS  0.3935      100.463%
423    HUL  0.4030      100.474%
434    MAG  0.4620      100.543%
432    ALO  0.6425      100.755%
436    BOT  0.8075      100.949%
437    STR  0.8345      100.981%
447    ZHO  1.1110      101.306%
460    COL  1.1280      101.326%
464    PER  1.1710      101.376%
438    OCO  1.2950      101.522%
449    TSU  1.3155      101.546%
444    LAW  1.3370      101.572%
440    ALB  1.3485      101.585%

In [13]:
for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta']=0.001

for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']=0.001
        
transformed_laps_relative_median

    Driver   Delta Delta_Percent
409    PIA  0.0010        100.0%
420    LEC  0.1695      100.199%
411    RUS  0.2060      100.242%
414    SAI  0.2200      100.259%
430    VER  0.3060       100.36%
406    NOR  0.3290      100.387%
416    HAM  0.3740       100.44%
426    GAS  0.3935      100.463%
423    HUL  0.4030      100.474%
434    MAG  0.4620      100.543%
432    ALO  0.6425      100.755%
436    BOT  0.8075      100.949%
437    STR  0.8345      100.981%
447    ZHO  1.1110      101.306%
460    COL  1.1280      101.326%
464    PER  1.1710      101.376%
438    OCO  1.2950      101.522%
449    TSU  1.3155      101.546%
444    LAW  1.3370      101.572%
440    ALB  1.3485      101.585%

In [14]:
fig_median=px.bar(
    transformed_laps_relative_median,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Median Lap Times) for the {} {} Sprint Race</b>".format(year,gp),
    text="Delta_Percent",
    height=700, 
    width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_median.update_traces(textposition='outside')

fig_median.update_traces(opacity=0.85)

fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta_Percent_Abs'].max()+0.7, 0])

fig_median.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_median.update_xaxes(title_text='')      # Remove axis titles
fig_median.update_yaxes(title_text='Percentage%')

fig_median.update_xaxes(
        title_standoff = 75
)

fig_median.update_layout(
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig_median.show()

In [15]:
fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Median Lap Times/{}/{} {} Sprint Race Driver Median Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [16]:
#Get MINIMUM OF ALL LAP TIMES
transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

fastest_lap_all = transformed_laps["min_all"].min()
transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_All']
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
transformed_laps_relative_min_all

    Driver  Delta_Min_All Delta_Percent_All
420    LEC          0.000            100.0%
432    ALO          0.358          100.427%
423    HUL          0.361           100.43%
406    NOR          0.406          100.484%
416    HAM          0.414          100.493%
411    RUS          0.457          100.545%
414    SAI          0.482          100.574%
409    PIA          0.531          100.633%
434    MAG          0.645          100.769%
430    VER          0.654          100.779%
464    PER          0.969          101.155%
426    GAS          1.007            101.2%
447    ZHO          1.128          101.344%
437    STR          1.446          101.723%
440    ALB          1.520          101.811%
436    BOT          1.524          101.816%
438    OCO          1.675          101.996%
460    COL          1.676          101.997%
444    LAW          1.839          102.191%
449    TSU          1.915          102.282%

In [17]:
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_min_all

    Driver  Delta_Min_All Delta_Percent_All
420    LEC          0.001            100.0%
432    ALO          0.358          100.427%
423    HUL          0.361           100.43%
406    NOR          0.406          100.484%
416    HAM          0.414          100.493%
411    RUS          0.457          100.545%
414    SAI          0.482          100.574%
409    PIA          0.531          100.633%
434    MAG          0.645          100.769%
430    VER          0.654          100.779%
464    PER          0.969          101.155%
426    GAS          1.007            101.2%
447    ZHO          1.128          101.344%
437    STR          1.446          101.723%
440    ALB          1.520          101.811%
436    BOT          1.524          101.816%
438    OCO          1.675          101.996%
460    COL          1.676          101.997%
444    LAW          1.839          102.191%
449    TSU          1.915          102.282%

In [18]:
fig_min=px.bar(
    transformed_laps_relative_min_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Fastest Lap Times) for the {} {} Sprint Race</b>".format(year,gp),
    text="Delta_Percent_All",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_min.update_traces(textposition='outside')

fig_min.update_traces(opacity=0.85)

fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Percent_Abs'].max()+0.8, 0])

fig_min.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_min.update_xaxes(title_text='')      # Remove axis titles
fig_min.update_yaxes(title_text='Percentage%')

fig_min.update_xaxes(
        title_standoff = 75
)

fig_min.update_layout(
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_min.update_yaxes(ticksuffix = "  ")

fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

fig_min.show()

In [19]:
fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Fastest Lap/{}/{} {} Sprint Race Driver Fastest Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Get AVERAGE OF ALL LAP TIMES
transformed_laps['avg_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform(np.mean)

fastest_lap_avg = transformed_laps["avg_all"].min()
transformed_laps['Delta_Avg_All']= transformed_laps["avg_all"] - (fastest_lap_avg)
transformed_laps['Delta_Percent_Avg']= (transformed_laps["avg_all"]/(fastest_lap_avg)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_Avg']
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+100
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].round(3)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].astype(str)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+"%"
transformed_laps_relative_avg_all=transformed_laps[["Driver","Delta_Avg_All","Delta_Percent_Avg","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all.sort_values("Delta_Avg_All")
transformed_laps_relative_avg_all

In [ ]:
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']=0.001
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']=0.001    
        
transformed_laps_relative_avg_all

In [ ]:
fig=px.bar(
    transformed_laps_relative_avg_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Average Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_Avg",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig.update_traces(textposition='outside')

fig.update_traces(opacity=0.85)

fig.update_traces( marker_line_color='white',marker_line_width=1.5)

fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_yaxes(range=[transformed_laps_relative_avg_all['Delta_Percent_Abs'].max()+0.7, 0])

fig.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig.update_xaxes(title_text='')      # Remove axis titles
fig.update_yaxes(title_text='Percentage%')

fig.update_xaxes(
        title_standoff = 75
)

fig.update_layout(
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig.show()

In [ ]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Average Lap Times/{}/{} {} Driver Average Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi Race Plot

In [7]:
#2024
# race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']
#2022
# race_multi=['Austrian Grand Prix','Emilia Romagna Grand Prix','São Paulo Grand Prix']
#2021
race_multi=['British Grand Prix','Italian Grand Prix','São Paulo Grand Prix']

year_multi=2021
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    track2['LapTime']= pd.to_timedelta(track2["LapTime"])
    track2=track2[track2['LapNumber']!=1.0]
    quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.07]
    transformed_laps = quicklaps.copy()
    transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

    # order the team from the fastest (lowest median lap time) tp slower
    team_order = (
        transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
    )
    print(team_order)
    transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
    transformed_laps.tail()
    fig_pace=px.box(
        transformed_laps.sort_values(by=["median","LapNumber"]),
        x="Driver",
        y="LapTime (s)",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace Plot for the {} {} Sprint Race</b>".format(year_multi,i),
        height=700, width=1200,

    color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )
    fig_pace.update_traces(opacity=1)
    fig_pace.update_layout(
        title_x=0.5,
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow",
        margin=dict(l=50, r=5, t=35, b=50)
    )
    fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Driver Pace Plots/{}/{} {} Sprint Race Driver Pace Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')
    #Get MINIMUM OF THE MEDIAN LAP TIMES

    fastest_lap = transformed_laps["median"].min()
    transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
    transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
    transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent"]].drop_duplicates()
    transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
    transformed_laps_relative_median
    for index, row in transformed_laps_relative_median.iterrows():
        if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
         transformed_laps_relative_median.loc[index, 'Delta']=0.001
    transformed_laps_relative_median
    fig_median=px.bar(
        transformed_laps_relative_median,
        x="Driver",
        y="Delta",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Median Lap Times) for the {} {} Sprint Race</b>".format(year_multi,i),
        text="Delta_Percent",
        height=700, 
        width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_median.update_traces(textposition='outside')

    fig_median.update_traces(opacity=0.85)

    fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta'].max()+0.6, 0])

    fig_median.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_median.update_xaxes(title_text='')      # Remove axis titles
    fig_median.update_yaxes(title_text='')

    fig_median.update_xaxes(
            title_standoff = 75
    )

    fig_median.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

    fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Median Lap Times/{}/{} {} Sprint Race Driver Median Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

    transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

    fastest_lap_all = transformed_laps["min_all"].min()
    transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
    transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
    transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All"]].drop_duplicates()
    transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
    transformed_laps_relative_min_all
    for index, row in transformed_laps_relative_min_all.iterrows():
        if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
         transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    transformed_laps_relative_min_all
    fig_min=px.bar(
        transformed_laps_relative_min_all,
        x="Driver",
        y="Delta_Min_All",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Fastest Lap Times) for the {} {} Sprint Race</b>".format(year_multi,i),
        text="Delta_Percent_All",
        height=700, width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_min.update_traces(textposition='outside')

    fig_min.update_traces(opacity=0.85)

    fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Min_All'].max()+0.5, 0])

    fig_min.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_min.update_xaxes(title_text='')      # Remove axis titles
    fig_min.update_yaxes(title_text='')

    fig_min.update_xaxes(
            title_standoff = 75
    )

    fig_min.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_min.update_yaxes(ticksuffix = "  ")

    fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
    fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Fastest Lap/{}/{} {} Sprint Race Driver Fastest Lap Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_11976/833092992.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_11976/833092992.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'HAM', 'BOT', 'LEC', 'NOR', 'RIC', 'SAI', 'PER', 'ALO', 'VET',
       'TSU', 'GAS', 'OCO', 'RUS', 'RAI', 'STR', 'LAT', 'GIO', 'MSC', 'MAZ'],
      dtype='object', name='Driver')
Index(['BOT', 'VER', 'RIC', 'NOR', 'HAM', 'LEC', 'SAI', 'PER', 'GIO', 'STR',
       'VET', 'ALO', 'OCO', 'RUS', 'LAT', 'TSU', 'MAZ', 'KUB', 'MSC'],
      dtype='object', name='Driver')
Index(['VER', 'BOT', 'HAM', 'SAI', 'PER', 'NOR', 'LEC', 'VET', 'OCO', 'ALO',
       'GAS', 'RIC', 'GIO', 'TSU', 'STR', 'RAI', 'LAT', 'RUS', 'MSC', 'MAZ'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_11976/833092992.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy