In [20]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.sprint_lap_time`
# WHERE YEAR=2024
# AND GP='Saudi Arabian Grand Prix'
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [4]:
query_all_laps=f"""
SELECT * FROM `perceptive-ivy-290216.f1_api.sprint_lap_time`
UNION ALL
SELECT * FROM `perceptive-ivy-290216.f1_api.final_driver_positions_all_sprint`
"""
track_all_laps=pandas_gbq.read_gbq(query_all_laps,project_id,dialect='standard')

Downloading: 100%|██████████|

In [27]:
race="Chinese Grand Prix"

In [28]:
track2=track3[(track3["GP"]==race)&(track3["Year"]==2025)]

In [29]:
#Get Final Pos to order the final plot
track_all_laps_2=track_all_laps[(track_all_laps["GP"]==race)&(track_all_laps["Year"]==2025)]
final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]

In [30]:
final_pos

    Driver  Position
359    GAS      12.0
360    DOO      20.0
361    STR       9.0
362    ALO      10.0
363    RUS       4.0
364    ANT       7.0
365    VER       3.0
366    LAW      14.0
367    BOR      18.0
368    HUL      19.0
369    ALB      11.0
370    SAI      17.0
371    TSU       6.0
372    HAD      13.0
373    BEA      15.0
374    OCO      16.0
375    HAM       1.0
376    LEC       5.0
377    PIA       2.0
378    NOR       8.0

In [31]:
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]
Drivers=(track2['Driver'].unique())

In [32]:
stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
stints = stints.rename(columns={"LapNumber": "StintLength"})
stints.head()

  Driver  Stint Compound  StintLength
0    ALB    1.0   MEDIUM           19
1    ALO    1.0   MEDIUM           19
2    ANT    1.0   MEDIUM           19
3    BEA    1.0   MEDIUM           19
4    BOR    1.0   MEDIUM           19

In [33]:
#Use commented when the bars don't align with final race positions
stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
# stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Stint','Position'])

# stint_with_pos["Total"]=stint_with_pos["Compound"].astype(str)+ " " +stint_with_pos["Stint"].astype(str)
stint_with_pos=stint_with_pos.reset_index(drop=True)
stint_with_pos.head()

  Driver  Stint Compound  StintLength  Position
0    HAM    1.0   MEDIUM           19       1.0
1    PIA    1.0   MEDIUM           19       2.0
2    VER    1.0   MEDIUM           19       3.0
3    RUS    1.0   MEDIUM           19       4.0
4    LEC    1.0   MEDIUM           19       5.0

In [34]:
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(int)
stint_with_pos["Stint"]=stint_with_pos["Stint"].astype(str)
stint_with_pos["LapNumber"]=stint_with_pos.groupby("Driver")["StintLength"].cumsum() #This will give lap number on stint final lap
stint_with_pos["LapNumber_Prior"]=stint_with_pos.groupby("Driver")["LapNumber"].shift(1) #Get prior lap
stint_with_pos=stint_with_pos.fillna(0)
stint_with_pos["Img_Loc"]=(stint_with_pos["LapNumber"]+stint_with_pos["LapNumber_Prior"])/2 #This will make the placement for the image around the center
stint_with_pos.head()

,Driver,Stint,Compound,StintLength,Position,LapNumber,LapNumber_Prior,Img_Loc
0,HAM,1,MEDIUM,19,1.0,19,0.0,9.5
1,PIA,1,MEDIUM,19,2.0,19,0.0,9.5
2,VER,1,MEDIUM,19,3.0,19,0.0,9.5
3,RUS,1,MEDIUM,19,4.0,19,0.0,9.5
4,LEC,1,MEDIUM,19,5.0,19,0.0,9.5

In [35]:
fig=px.bar(
    stint_with_pos,
    y="Driver",
    x='StintLength',
    text="StintLength",
    orientation='h',
    barmode='stack',
    # color='Compound',
    template="simple_white",
    title="<b>Tyre Strategies for the {} {} Sprint Race</b>".format(year,gp),
    height=800, width=1200,
    hover_data=["Position","Stint","Compound","LapNumber"],
    color_discrete_map={
                 "SOFT": "#F91536",
                 "MEDIUM": "#ffdf00 ",
                 "HARD":"#c8c8c8 ",
                 "INTERMEDIATE":"#009E60 ",
                 "WET":"#3671C6"
    }
)
fig.update_layout(
    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    xaxis_title="<b>Lap Number</b>",
    yaxis_title="<b>Driver</b>",
    title_x=0.5,
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)

for x,y,z in zip(stint_with_pos.Img_Loc, stint_with_pos.Compound, stint_with_pos.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==y:
      image=str(png)
      fig.add_layout_image(
          x=x,
          y=z,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=1.5,
          sizey=1.5,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
        yaxis={'categoryorder':'total descending'},  
        hoverlabel=dict(
        bgcolor="Black",
        font_size=20,
        font_family="PT Sans Narrow",

    ),
    margin=dict(l=5, r=5, t=35, b=5),
    )

fig['layout']['yaxis']['autorange'] = "reversed"

fig.update_traces(marker_line_width=3, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

fig.update_yaxes(ticksuffix = "  ")

fig.update_traces(marker_color='#a2a2a2')

fig.show()

In [36]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Tyre Strat/{}/{} {} Sprint Race Tyre Strategies.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi Race Plot

In [8]:
#2024
# race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']
#2022
# race_multi=['Austrian Grand Prix','Emilia Romagna Grand Prix','São Paulo Grand Prix']
#2021
race_multi=['British Grand Prix','Italian Grand Prix','São Paulo Grand Prix']

year_multi=2021
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    track_all_laps_2=track_all_laps[(track_all_laps["GP"]==i)&(track_all_laps["Year"]==year_multi)]
    final_pos=track_all_laps_2[track_all_laps_2["LapNumber"]==track_all_laps_2.LapNumber.max()][["Driver","Position"]]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    Drivers=(track2['Driver'].unique())
    stints = track2[["Driver", "Stint", "Compound", "LapNumber"]]
    stints = stints.groupby(["Driver", "Stint", "Compound"]).count().reset_index()
    stints = stints.rename(columns={"LapNumber": "StintLength"})
    stints.head()
    stint_with_pos=stints.merge(final_pos, left_on=["Driver"],right_on=["Driver"]).sort_values(by=['Position','Stint'])
    stint_with_pos.head()
    fig=px.bar(
        stint_with_pos,
        y="Driver",
        x='StintLength',
        text="StintLength",
        orientation='h',
        barmode='stack',
        color='Compound',
        template="simple_white",
        title="<b>Tyre Strategies for the {} {}</b>".format(year_multi,i),
        height=800, width=1200,
        hover_data=["Position"],
        color_discrete_map={
                    "SOFT": "#F91536",
                    "MEDIUM": "#ffdf00 ",
                    "HARD":"#c8c8c8 ",
                    "INTERMEDIATE":"#009E60 ",
                    "WET":"#3671C6"
        }
    )
    fig.update_layout(
        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),
        xaxis_title="<b>Lap Number</b>",
        yaxis_title="<b>Driver</b>",
        title_x=0.5,
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )

    fig.update_layout(yaxis={'categoryorder':'total descending'},    
            hoverlabel=dict(
            bgcolor="Black",
            font_size=16,
            font_family="PT Sans Narrow"
        ),
        margin=dict(l=5, r=5, t=35, b=5),
        )

    fig['layout']['yaxis']['autorange'] = "reversed"

    fig.update_traces(marker_line_width=1, marker_line_color="WHITE", opacity=0.99, insidetextanchor="middle",textfont_color="White")

    fig.update_yaxes(ticksuffix = "  ")
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Tyre Strat/{}/{} {} Sprint Race Tyre Strategies.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')