In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from PIL import Image
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT
*
FROM `perceptive-ivy-290216.f1_api.sprint_lap_time`  A
# WHERE A.Year=2024
# AND A.GP="Monaco Grand Prix"
# AND A.DRIVER='HAM'
ORDER BY LapNumber, LapStartTime
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [4]:
track2=track3[(track3["GP"]=='Qatar Grand Prix')&(track3["Year"]==2025)]
track2.head()
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]

In [5]:
track2['LapTime']= pd.to_timedelta(track2["LapTime"])

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38215/4173085553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track2['LapTime']= pd.to_timedelta(track2["LapTime"])

In [6]:
# track2['LapTime'].dt.total_seconds().min()*1.07
track2=track2[track2['LapNumber']!=1.0]
track2=track2[track2['LapNumber']!=19.0]

In [7]:
# quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.1]
quicklaps=track2
quicklaps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
660,0 days 00:48:51.615000,PIA,81,0 days 00:01:25.086000,2.0,1.0,NaT,NaT,0 days 00:00:31.501000,0 days 00:00:28.571000,0 days 00:00:25.014000,0 days 00:47:58.065000,0 days 00:48:26.636000,0 days 00:48:51.650000,242.0,288.0,278.0,300.0,True,MEDIUM,7.0,False,McLaren,0 days 00:47:26.529000,2025-11-29 14:05:00.354,1,1.0,False,,False,True,2025,Qatar Grand Prix
663,0 days 00:48:52.888000,RUS,63,0 days 00:01:25.085000,2.0,1.0,NaT,NaT,0 days 00:00:31.518000,0 days 00:00:28.766000,0 days 00:00:24.801000,0 days 00:47:59.341000,0 days 00:48:28.107000,0 days 00:48:52.908000,NaN,289.0,280.0,293.0,True,MEDIUM,8.0,False,Mercedes,0 days 00:47:27.803000,2025-11-29 14:05:01.628,1,2.0,False,,False,True,2025,Qatar Grand Prix
667,0 days 00:48:54.111000,NOR,4,0 days 00:01:25.135000,2.0,2.0,NaT,NaT,0 days 00:00:31.619000,0 days 00:00:28.844000,0 days 00:00:24.672000,0 days 00:48:00.622000,0 days 00:48:29.466000,0 days 00:48:54.138000,241.0,288.0,280.0,305.0,True,HARD,2.0,True,McLaren,0 days 00:47:28.976000,2025-11-29 14:05:02.801,1,3.0,False,,False,True,2025,Qatar Grand Prix
670,0 days 00:48:54.729000,VER,1,0 days 00:01:25.136000,2.0,2.0,NaT,NaT,0 days 00:00:31.491000,0 days 00:00:29.106000,0 days 00:00:24.539000,0 days 00:48:01.109000,0 days 00:48:30.215000,0 days 00:48:54.754000,244.0,287.0,283.0,302.0,True,HARD,2.0,True,Red Bull Racing,0 days 00:47:29.593000,2025-11-29 14:05:03.418,1,4.0,False,,False,True,2025,Qatar Grand Prix
673,0 days 00:48:56.125000,TSU,22,0 days 00:01:25.493000,2.0,2.0,NaT,NaT,0 days 00:00:31.647000,0 days 00:00:28.978000,0 days 00:00:24.868000,0 days 00:48:02.312000,0 days 00:48:31.290000,0 days 00:48:56.158000,241.0,286.0,281.0,298.0,True,HARD,2.0,True,Red Bull Racing,0 days 00:47:30.632000,2025-11-29 14:05:04.457,1,5.0,False,,False,True,2025,Qatar Grand Prix

In [8]:
#Remove Pitstops and Track Status other than Clear to remove slow laps
quicklaps=quicklaps[((quicklaps["PitOutTime"]=='NaT')&(quicklaps["PitInTime"]=='NaT')&(~quicklaps["TrackStatus"].isin(['4','41','5','6','7','124'])))]

In [9]:
transformed_laps = quicklaps.copy()
transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

# order the team from the fastest (lowest median lap time) tp slower
team_order = (
    transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
)
print(team_order)

Index(['PIA', 'RUS', 'NOR', 'VER', 'TSU', 'ANT', 'ALO', 'HAD', 'LEC', 'ALB',
       'SAI', 'BOR', 'LAW', 'OCO', 'BEA', 'HUL', 'STR', 'HAM', 'GAS', 'COL'],
      dtype='object', name='Driver')

In [10]:
transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
transformed_laps.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,LapTime (s),median
7835,0 days 01:12:02.278000,LAW,30,0 days 00:01:25.740000,18.0,1.0,NaT,NaT,0 days 00:00:31.718000,0 days 00:00:29.420000,0 days 00:00:24.602000,0 days 01:11:08.261000,0 days 01:11:37.681000,0 days 01:12:02.283000,239.0,286.0,281.0,310.0,False,MEDIUM,24.0,False,Racing Bulls,0 days 01:10:36.538000,2025-11-29 14:28:10.363,1,14.0,False,,False,True,2025,Qatar Grand Prix,85.740,86.174
7836,0 days 01:12:04.658000,OCO,31,0 days 00:01:26.044000,18.0,1.0,NaT,NaT,0 days 00:00:31.737000,0 days 00:00:29.460000,0 days 00:00:24.847000,0 days 01:11:10.403000,0 days 01:11:39.863000,0 days 01:12:04.710000,235.0,289.0,282.0,308.0,False,MEDIUM,24.0,False,Haas F1 Team,0 days 01:10:38.614000,2025-11-29 14:28:12.439,1,15.0,False,,False,True,2025,Qatar Grand Prix,86.044,86.224
7837,0 days 01:12:05.154000,HUL,27,0 days 00:01:25.701000,18.0,1.0,NaT,NaT,0 days 00:00:31.545000,0 days 00:00:29.489000,0 days 00:00:24.667000,0 days 01:11:11.023000,0 days 01:11:40.512000,0 days 01:12:05.179000,237.0,289.0,286.0,327.0,False,MEDIUM,24.0,False,Kick Sauber,0 days 01:10:39.453000,2025-11-29 14:28:13.278,1,16.0,False,,False,True,2025,Qatar Grand Prix,85.701,86.325
7838,0 days 01:12:09.297000,HAM,44,0 days 00:01:26.785000,18.0,1.0,NaT,NaT,0 days 00:00:31.861000,0 days 00:00:29.806000,0 days 00:00:25.118000,0 days 01:11:14.401000,0 days 01:11:44.207000,0 days 01:12:09.325000,244.0,287.0,281.0,311.0,False,MEDIUM,18.0,True,Ferrari,0 days 01:10:42.512000,2025-11-29 14:28:16.337,1,17.0,False,,False,True,2025,Qatar Grand Prix,86.785,86.506
7843,0 days 01:12:46.189000,STR,18,0 days 00:01:28.611000,18.0,2.0,NaT,NaT,0 days 00:00:33.221000,0 days 00:00:29.930000,0 days 00:00:25.460000,0 days 01:11:50.819000,0 days 01:12:20.749000,0 days 01:12:46.209000,225.0,285.0,279.0,298.0,False,SOFT,15.0,False,Aston Martin,0 days 01:11:17.578000,2025-11-29 14:28:51.403,1,19.0,False,,False,True,2025,Qatar Grand Prix,88.611,86.434

In [11]:
fig_pace=px.box(
    transformed_laps.sort_values(by=["median","LapNumber"]),
    x="Driver",
    y="LapTime (s)",
    color='Driver',
    template="xgridoff",
    hover_data=["LapNumber","TrackStatus","Position"],
    title="<b>Driver Pace Plot for the {} {} Sprint Race</b>".format(year,gp),
    points='all',
    # palette=team_palette,
    # whiskerprops=dict(color="white"),
    # boxprops=dict(edgecolor="white"),
    # medianprops=dict(color="grey"),
    # capprops=dict(color="white"),
    height=700, width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)
fig_pace.update_traces(opacity=1)
fig_pace.update_layout(
    title_x=0.5,
    hoverlabel=dict(
    bgcolor="white",
    font_size=16,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=50, r=5, t=35, b=50)
)
fig_pace.show()

In [12]:
fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Driver Pace Plots/{}/{} {} Sprint Race Driver Pace Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [13]:
#Get MINIMUM OF THE MEDIAN LAP TIMES

fastest_lap = transformed_laps["median"].min()
transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent']
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
transformed_laps_relative_median=transformed_laps[["Team","Driver","Delta","Delta_Percent","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
transformed_laps_relative_median

                Team Driver  Delta Delta_Percent  Delta_Percent_Abs
660          McLaren    PIA  0.000        100.0%           0.000000
663         Mercedes    RUS  0.028      100.033%           0.032980
667          McLaren    NOR  0.068       100.08%           0.080093
670  Red Bull Racing    VER  0.177      100.208%           0.208478
673  Red Bull Racing    TSU  0.389      100.458%           0.458181
678         Mercedes    ANT  0.635      100.748%           0.747930
675     Aston Martin    ALO  0.878      101.034%           1.034146
681     Racing Bulls    HAD  1.041      101.226%           1.226134
685          Ferrari    LEC  1.081      101.273%           1.273248
682         Williams    ALB  1.081      101.273%           1.273248
680         Williams    SAI  1.082      101.274%           1.274426
683      Kick Sauber    BOR  1.231       101.45%           1.449924
686     Racing Bulls    LAW  1.273      101.499%           1.499393
687     Haas F1 Team    OCO  1.323      101.558%           1.558286
684     Haas F1 Team    BEA  1.372      101.616%           1.616000
688      Kick Sauber    HUL  1.424      101.677%           1.677248
689     Aston Martin    STR  1.533      101.806%           1.805632
690          Ferrari    HAM  1.605       101.89%           1.890437
691           Alpine    GAS  1.614      101.901%           1.901038
692           Alpine    COL  1.704      102.007%           2.007043

In [14]:
for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta']=0.001

for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']=0.001
        
transformed_laps_relative_median

                Team Driver  Delta Delta_Percent  Delta_Percent_Abs
660          McLaren    PIA  0.001        100.0%           0.001000
663         Mercedes    RUS  0.028      100.033%           0.032980
667          McLaren    NOR  0.068       100.08%           0.080093
670  Red Bull Racing    VER  0.177      100.208%           0.208478
673  Red Bull Racing    TSU  0.389      100.458%           0.458181
678         Mercedes    ANT  0.635      100.748%           0.747930
675     Aston Martin    ALO  0.878      101.034%           1.034146
681     Racing Bulls    HAD  1.041      101.226%           1.226134
685          Ferrari    LEC  1.081      101.273%           1.273248
682         Williams    ALB  1.081      101.273%           1.273248
680         Williams    SAI  1.082      101.274%           1.274426
683      Kick Sauber    BOR  1.231       101.45%           1.449924
686     Racing Bulls    LAW  1.273      101.499%           1.499393
687     Haas F1 Team    OCO  1.323      101.558%           1.558286
684     Haas F1 Team    BEA  1.372      101.616%           1.616000
688      Kick Sauber    HUL  1.424      101.677%           1.677248
689     Aston Martin    STR  1.533      101.806%           1.805632
690          Ferrari    HAM  1.605       101.89%           1.890437
691           Alpine    GAS  1.614      101.901%           1.901038
692           Alpine    COL  1.704      102.007%           2.007043

In [15]:
fig_median=px.bar(
    transformed_laps_relative_median,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Median Lap Times) for the {} {} Sprint Race</b>".format(year,gp),
    text="Delta_Percent",
    height=700, 
    width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",                
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_median.update_traces(textposition='outside')

fig_median.update_traces(opacity=0.85)

fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta_Percent_Abs'].max()+0.7, 0])

fig_median.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_median.update_xaxes(title_text='')      # Remove axis titles
fig_median.update_yaxes(title_text='Percentage%')

fig_median.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_median.Team, transformed_laps_relative_median.Delta_Percent_Abs, transformed_laps_relative_median.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_median.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig_median.update_layout(
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig_median.show()

In [16]:
fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Median Lap Times/{}/{} {} Sprint Race Driver Median Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [17]:
#Get MINIMUM OF ALL LAP TIMES
transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

fastest_lap_all = transformed_laps["min_all"].min()
transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_All']
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
transformed_laps_relative_min_all=transformed_laps[["Team","Driver","Delta_Min_All","Delta_Percent_All","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
689,Aston Martin,STR,0.000,100.0%,0.000000
660,McLaren,PIA,0.463,100.554%,0.553927
667,McLaren,NOR,0.922,101.103%,1.103069
670,Red Bull Racing,VER,0.956,101.144%,1.143746
663,Mercedes,RUS,0.979,101.171%,1.171263
678,Mercedes,ANT,1.141,101.365%,1.365077
673,Red Bull Racing,TSU,1.231,101.473%,1.472752
681,Racing Bulls,HAD,1.819,102.176%,2.176228
675,Aston Martin,ALO,1.830,102.189%,2.189388
680,Williams,SAI,1.878,102.247%,2.246815
682,Williams,ALB,1.924,102.302%,2.301848
687,Haas F1 Team,OCO,1.970,102.357%,2.356882
684,Haas F1 Team,BEA,2.008,102.402%,2.402345
686,Racing Bulls,LAW,2.035,102.435%,2.434647
685,Ferrari,LEC,2.053,102.456%,2.456182
683,Kick Sauber,BOR,2.078,102.486%,2.486092
688,Kick Sauber,HUL,2.093,102.504%,2.504038
690,Ferrari,HAM,2.197,102.628%,2.628462
692,Alpine,COL,2.293,102.743%,2.743315
691,Alpine,GAS,2.418,102.893%,2.892864

In [18]:
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
689,Aston Martin,STR,0.001,100.0%,0.001000
660,McLaren,PIA,0.463,100.554%,0.553927
667,McLaren,NOR,0.922,101.103%,1.103069
670,Red Bull Racing,VER,0.956,101.144%,1.143746
663,Mercedes,RUS,0.979,101.171%,1.171263
678,Mercedes,ANT,1.141,101.365%,1.365077
673,Red Bull Racing,TSU,1.231,101.473%,1.472752
681,Racing Bulls,HAD,1.819,102.176%,2.176228
675,Aston Martin,ALO,1.830,102.189%,2.189388
680,Williams,SAI,1.878,102.247%,2.246815
682,Williams,ALB,1.924,102.302%,2.301848
687,Haas F1 Team,OCO,1.970,102.357%,2.356882
684,Haas F1 Team,BEA,2.008,102.402%,2.402345
686,Racing Bulls,LAW,2.035,102.435%,2.434647
685,Ferrari,LEC,2.053,102.456%,2.456182
683,Kick Sauber,BOR,2.078,102.486%,2.486092
688,Kick Sauber,HUL,2.093,102.504%,2.504038
690,Ferrari,HAM,2.197,102.628%,2.628462
692,Alpine,COL,2.293,102.743%,2.743315
691,Alpine,GAS,2.418,102.893%,2.892864

In [19]:
fig_min=px.bar(
    transformed_laps_relative_min_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Fastest Lap Times) for the {} {} Sprint Race</b>".format(year,gp),
    text="Delta_Percent_All",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_min.update_traces(textposition='outside')

fig_min.update_traces(opacity=0.85)

fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Percent_Abs'].max()+0.8, 0])

fig_min.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_min.update_xaxes(title_text='')      # Remove axis titles
fig_min.update_yaxes(title_text='Percentage%')

fig_min.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_min_all.Team, transformed_laps_relative_min_all.Delta_Percent_Abs, transformed_laps_relative_min_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_min.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )


fig_min.update_layout(
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=22,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_min.update_yaxes(ticksuffix = "  ")

fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

fig_min.show()

In [20]:
fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Fastest Lap/{}/{} {} Sprint Race Driver Fastest Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [21]:
#Get AVERAGE OF ALL LAP TIMES
transformed_laps['avg_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform(np.mean)

fastest_lap_avg = transformed_laps["avg_all"].min()
transformed_laps['Delta_Avg_All']= transformed_laps["avg_all"] - (fastest_lap_avg)
transformed_laps['Delta_Percent_Avg']= (transformed_laps["avg_all"]/(fastest_lap_avg)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_Avg']
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+100
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].round(3)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].astype(str)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+"%"
transformed_laps_relative_avg_all=transformed_laps[["Team","Driver","Delta_Avg_All","Delta_Percent_Avg","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all.sort_values("Delta_Avg_All")
transformed_laps_relative_avg_all

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38215/2458230245.py:2: FutureWarning:

The provided callable <function mean at 0x110cef4c0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
660,McLaren,PIA,0.000000,100.0%,0.000000
663,Mercedes,RUS,0.108353,100.128%,0.127782
667,McLaren,NOR,0.144529,100.17%,0.170445
670,Red Bull Racing,VER,0.295529,100.349%,0.348521
673,Red Bull Racing,TSU,0.549059,100.648%,0.647511
678,Mercedes,ANT,0.615882,100.726%,0.726316
675,Aston Martin,ALO,1.057941,101.248%,1.247641
680,Williams,SAI,1.108706,101.308%,1.307508
681,Racing Bulls,HAD,1.155176,101.362%,1.362311
682,Williams,ALB,1.156235,101.364%,1.363560
683,Kick Sauber,BOR,1.354765,101.598%,1.597687
684,Haas F1 Team,BEA,1.417471,101.672%,1.671637
685,Ferrari,LEC,1.432529,101.689%,1.689396
686,Racing Bulls,LAW,1.484824,101.751%,1.751067
687,Haas F1 Team,OCO,1.596412,101.883%,1.882664
688,Kick Sauber,HUL,1.607471,101.896%,1.895706
690,Ferrari,HAM,1.808529,102.133%,2.132817
691,Alpine,GAS,1.832180,102.161%,2.160708
692,Alpine,COL,1.966180,102.319%,2.318736
689,Aston Martin,STR,2.239314,102.641%,2.640845

In [22]:
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']=0.001
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']=0.001    
        
transformed_laps_relative_avg_all

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
660,McLaren,PIA,0.001000,100.0%,0.001000
663,Mercedes,RUS,0.108353,100.128%,0.127782
667,McLaren,NOR,0.144529,100.17%,0.170445
670,Red Bull Racing,VER,0.295529,100.349%,0.348521
673,Red Bull Racing,TSU,0.549059,100.648%,0.647511
678,Mercedes,ANT,0.615882,100.726%,0.726316
675,Aston Martin,ALO,1.057941,101.248%,1.247641
680,Williams,SAI,1.108706,101.308%,1.307508
681,Racing Bulls,HAD,1.155176,101.362%,1.362311
682,Williams,ALB,1.156235,101.364%,1.363560
683,Kick Sauber,BOR,1.354765,101.598%,1.597687
684,Haas F1 Team,BEA,1.417471,101.672%,1.671637
685,Ferrari,LEC,1.432529,101.689%,1.689396
686,Racing Bulls,LAW,1.484824,101.751%,1.751067
687,Haas F1 Team,OCO,1.596412,101.883%,1.882664
688,Kick Sauber,HUL,1.607471,101.896%,1.895706
690,Ferrari,HAM,1.808529,102.133%,2.132817
691,Alpine,GAS,1.832180,102.161%,2.160708
692,Alpine,COL,1.966180,102.319%,2.318736
689,Aston Martin,STR,2.239314,102.641%,2.640845

In [23]:
fig=px.bar(
    transformed_laps_relative_avg_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Average Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_Avg",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig.update_traces(textposition='outside')

fig.update_traces(opacity=0.85)

fig.update_traces( marker_line_color='white',marker_line_width=1.5)

fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_yaxes(range=[transformed_laps_relative_avg_all['Delta_Percent_Abs'].max()+2, 0])

fig.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig.update_xaxes(title_text='')      # Remove axis titles
fig.update_yaxes(title_text='Percentage%')

fig.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_avg_all.Team, transformed_laps_relative_avg_all.Delta_Percent_Abs, transformed_laps_relative_avg_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig.add_layout_image(
          x=z,
          y=y+0.9,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    margin=dict(l=60, r=5, t=110, b=30),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig.show()

In [24]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Average Lap Times/{}/{} {} Driver Average Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [25]:
#Multi Race Plot

In [26]:
#2025
race_multi=['Miami Grand Prix','Belgian Grand Prix','United States Grand Prix','São Paulo Grand Prix']
#2024
# race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']
#2022
# race_multi=['Austrian Grand Prix','Emilia Romagna Grand Prix','São Paulo Grand Prix']
#2021
# race_multi=['British Grand Prix','Italian Grand Prix','São Paulo Grand Prix']

year_multi=2025
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    track2['LapTime']= pd.to_timedelta(track2["LapTime"])
    track2=track2[track2['LapNumber']!=1.0]
    quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.07]
    transformed_laps = quicklaps.copy()
    transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

    # order the team from the fastest (lowest median lap time) tp slower
    team_order = (
        transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
    )
    print(team_order)
    transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
    transformed_laps.tail()
    fig_pace=px.box(
        transformed_laps.sort_values(by=["median","LapNumber"]),
        x="Driver",
        y="LapTime (s)",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace Plot for the {} {} Sprint Race</b>".format(year_multi,i),
        height=700, width=1200,

    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
            }
    )
    fig_pace.update_traces(opacity=1)
    fig_pace.update_layout(
        title_x=0.5,
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow",
        margin=dict(l=50, r=5, t=35, b=50)
    )
    fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Driver Pace Plots/{}/{} {} Sprint Race Driver Pace Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')
    #Get MINIMUM OF THE MEDIAN LAP TIMES

    fastest_lap = transformed_laps["median"].min()
    transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
    transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
    transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent"]].drop_duplicates()
    transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
    transformed_laps_relative_median
    for index, row in transformed_laps_relative_median.iterrows():
        if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
         transformed_laps_relative_median.loc[index, 'Delta']=0.001
    transformed_laps_relative_median
    fig_median=px.bar(
        transformed_laps_relative_median,
        x="Driver",
        y="Delta",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Median Lap Times) for the {} {} Sprint Race</b>".format(year_multi,i),
        text="Delta_Percent",
        height=700, 
        width=1200,
        color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
            }
    )

    fig_median.update_traces(textposition='outside')

    fig_median.update_traces(opacity=0.85)

    fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta'].max()+0.6, 0])

    fig_median.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_median.update_xaxes(title_text='')      # Remove axis titles
    fig_median.update_yaxes(title_text='')

    fig_median.update_xaxes(
            title_standoff = 75
    )

    fig_median.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

    fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Median Lap Times/{}/{} {} Sprint Race Driver Median Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

    transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

    fastest_lap_all = transformed_laps["min_all"].min()
    transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
    transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
    transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All"]].drop_duplicates()
    transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
    transformed_laps_relative_min_all
    for index, row in transformed_laps_relative_min_all.iterrows():
        if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
         transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    transformed_laps_relative_min_all
    fig_min=px.bar(
        transformed_laps_relative_min_all,
        x="Driver",
        y="Delta_Min_All",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Fastest Lap Times) for the {} {} Sprint Race</b>".format(year_multi,i),
        text="Delta_Percent_All",
        height=700, width=1200,
        color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
            }
    )

    fig_min.update_traces(textposition='outside')

    fig_min.update_traces(opacity=0.85)

    fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Min_All'].max()+0.5, 0])

    fig_min.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_min.update_xaxes(title_text='')      # Remove axis titles
    fig_min.update_yaxes(title_text='')

    fig_min.update_xaxes(
            title_standoff = 75
    )

    fig_min.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_min.update_yaxes(ticksuffix = "  ")

    fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
    fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Driver Pace/Fastest Lap/{}/{} {} Sprint Race Driver Fastest Lap Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38215/1125699223.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38215/1125699223.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['PIA', 'NOR', 'VER', 'RUS', 'HAM', 'ANT', 'ALO', 'ALB', 'LAW', 'STR',
       'GAS', 'HAD', 'OCO', 'SAI', 'TSU', 'HUL', 'BEA', 'BOR', 'DOO'],
      dtype='object', name='Driver')
Index(['VER', 'NOR', 'PIA', 'LEC', 'OCO', 'SAI', 'HAD', 'BEA', 'BOR', 'LAW',
       'TSU', 'STR', 'GAS', 'RUS', 'ALO', 'ALB', 'HAM', 'ANT', 'HUL', 'COL'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38215/1125699223.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38215/1125699223.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'RUS', 'LEC', 'SAI', 'HAM', 'ALB', 'TSU', 'BEA', 'ANT', 'LAW',
       'STR', 'GAS', 'HUL', 'OCO', 'HAD', 'BOR', 'COL'],
      dtype='object', name='Driver')
Index(['NOR', 'ANT', 'VER', 'RUS', 'PIA', 'LEC', 'HAM', 'ALO', 'GAS', 'STR',
       'HUL', 'COL', 'BEA', 'BOR', 'ALB', 'OCO', 'HAD', 'SAI', 'LAW', 'TSU'],
      dtype='object', name='Driver')