In [1]:
import pandas as pd
import numpy as np
import time
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import requests
import json
project_id = "perceptive-ivy-290216"

In [2]:
# Race

In [3]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_race`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_race = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [4]:
racing='Australian Grand Prix'

In [5]:
df_bq_race=df_bq2_race[(df_bq2_race["GP"]==racing)&(df_bq2_race["Year"]==2025)]
GP_race=df_bq_race
GP_race["DriverNumber"]=GP_race["DriverNumber"].astype(int)
year_race=GP_race['Year'].iloc[0]
gp_race=GP_race['GP'].iloc[0]
GP_race.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3239/756652593.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GP_race["DriverNumber"]=GP_race["DriverNumber"].astype(int)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
26148,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,https://media.formula1.com/d_driver_fallback_i...,,19.0,R,14.0,NaT,NaT,NaT,NaT,Retired,0.0,2025,Australian Grand Prix
26155,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,11.0,11,9.0,NaT,NaT,NaT,0 days 00:00:26.502000,Finished,0.0,2025,Australian Grand Prix
26161,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,17.0,R,12.0,NaT,NaT,NaT,NaT,Retired,0.0,2025,Australian Grand Prix
26171,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,6.0,6,13.0,NaT,NaT,NaT,0 days 00:00:17.413000,Finished,8.0,2025,Australian Grand Prix
26192,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,8.0,8,7.0,NaT,NaT,NaT,0 days 00:00:19.826000,Finished,4.0,2025,Australian Grand Prix

In [6]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="LAW":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [7]:
GP_race['Color'] = GP_race['Abbreviation'].apply(driver_color)
GP_race.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3239/1190466171.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GP_race['Color'] = GP_race['Abbreviation'].apply(driver_color)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
26148,7,J DOOHAN,DOO,doohan,Alpine,0093CC,alpine,Jack,Doohan,Jack Doohan,https://media.formula1.com/d_driver_fallback_i...,,19.0,R,14.0,NaT,NaT,NaT,NaT,Retired,0.0,2025,Australian Grand Prix,#0093cc
26155,10,P GASLY,GAS,gasly,Alpine,0093CC,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,11.0,11,9.0,NaT,NaT,NaT,0 days 00:00:26.502000,Finished,0.0,2025,Australian Grand Prix,#0093cc
26161,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,17.0,R,12.0,NaT,NaT,NaT,NaT,Retired,0.0,2025,Australian Grand Prix,#229971
26171,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,6.0,6,13.0,NaT,NaT,NaT,0 days 00:00:17.413000,Finished,8.0,2025,Australian Grand Prix,#229971
26192,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,8.0,8,7.0,NaT,NaT,NaT,0 days 00:00:19.826000,Finished,4.0,2025,Australian Grand Prix,#E80020

In [8]:
Fast_Laps_Race=GP_race[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])

In [9]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_Race.columns},
  cells=dict(
    values=Fast_Laps_Race.T.values,
    fill_color=[Fast_Laps_Race.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )

# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Race Results".format(year_race,gp_race),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=15,
        color="Black"
    ),
    height=1000,
    width=1000,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [10]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Results/{}/{} {} Race Results.html".format(year_race,year_race,gp_race),full_html=False, include_plotlyjs='cdn')

In [11]:
#Multi Race Plot

In [12]:
#2024
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="COL":
        return '#64C4FF'    
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    else:
        return '#3860C6'

In [12]:
#2020
def driver_color(driver):
    if driver =="AIT":
        return "#0082fa"
    elif driver =="ALB":
        return '#1E41FF'
    elif driver =="BOT":
        return '#00D2BE'
    elif driver =="FIT":
        return '#787878'
    elif driver =="GAS":
        return '#2B4562'
    elif driver =="GIO":
        return '#9B0000'
    elif driver =="GRO":
        return '#787878'
    elif driver =="HAM":
        return '#00D2BE'
    elif driver =="HUL":
        return '#F596C8'
    elif driver =="KVY":
        return '#2B4562'
    elif driver =="LAT":
        return '#0082fa'
    elif driver =="LEC":
        return '#DC0000'
    elif driver =="MAG":
        return '#787878'
    elif driver =="NOR":
        return '#FF8700'
    elif driver =="OCO":
        return '#ffc600'
    elif driver =="PER":
        return '#F596C8'
    elif driver =="RAI":
        return '#9B0000'
    elif driver =="RIC":
        return '#ffc600'
    elif driver =="RUS":
        return '#0082fa'
    elif driver =="SAI":
        return '#FF8700'
    elif driver =="STR":
        return '#F596C8'
    elif driver =="VER":
        return '#1E41FF'
    elif driver =="VET":
        return '#DC0000'
    else:
        return '#3860C6'

In [13]:
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2020
for i in race_multi:
    df_bq_race=df_bq2_race[(df_bq2_race["GP"]==i)&(df_bq2_race["Year"]==year_multi)]
    GP_race=df_bq_race
    GP_race["DriverNumber"]=GP_race["DriverNumber"].astype(int)
    year_race=GP_race['Year'].iloc[0]
    gp_race=GP_race['GP'].iloc[0]
    GP_race['Color'] = GP_race['Abbreviation'].apply(driver_color)
    Fast_Laps_Race=GP_race[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])
    import plotly.graph_objects as go

    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_Race.columns},
    cells=dict(
        values=Fast_Laps_Race.T.values,
        fill_color=[Fast_Laps_Race.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )
    fig.update_layout(
        title="{} {} Race Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),
        font=dict(
            family="PT Sans Narrow",
            size=15,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Results/{}/{} {} Race Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:16: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_3572/354092314.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
# Qualy

In [11]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_qualifying`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_qualy = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [12]:
df_bq_qualy=df_bq2_qualy[(df_bq2_qualy["GP"]==racing)&(df_bq2_qualy["Year"]==2025)]
GP_qualy=df_bq_qualy
# GP["LapNumber"]=GP["LapNumber"].astype(int)
# GP=GP.sort_values(['Driver','LapNumber'])
GP_qualy["DriverNumber"]=GP_qualy["DriverNumber"].astype(int)
year_qualy=GP_qualy['Year'].iloc[0]
gp_qualy=GP_qualy['GP'].iloc[0]
GP_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_1635/5941125.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
161,10,P GASLY,GAS,,Alpine,0093CC,,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,9.0,,NaN,0 days 00:01:16.328000,0 days 00:01:16.112000,0 days 00:01:15.980000,NaT,,NaN,2025,Australian Grand Prix
162,7,J DOOHAN,DOO,,Alpine,0093CC,,Jack,Doohan,Jack Doohan,https://media.formula1.com/d_driver_fallback_i...,,14.0,,NaN,0 days 00:01:16.315000,0 days 00:01:16.863000,NaT,NaT,,NaN,2025,Australian Grand Prix
163,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,12.0,,NaN,0 days 00:01:16.288000,0 days 00:01:16.453000,NaT,NaT,,NaN,2025,Australian Grand Prix
164,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,13.0,,NaN,0 days 00:01:16.369000,0 days 00:01:16.483000,NaT,NaT,,NaN,2025,Australian Grand Prix
165,63,G RUSSELL,RUS,,Mercedes,27F4D2,,George,Russell,George Russell,https://media.formula1.com/d_driver_fallback_i...,,4.0,,NaN,0 days 00:01:15.971000,0 days 00:01:15.798000,0 days 00:01:15.546000,NaT,,NaN,2025,Australian Grand Prix

In [13]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="LAW":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [14]:
GP_qualy['Color'] = GP_qualy['Abbreviation'].apply(driver_color)
GP_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_1635/1606116537.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
161,10,P GASLY,GAS,,Alpine,0093CC,,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,9.0,,NaN,0 days 00:01:16.328000,0 days 00:01:16.112000,0 days 00:01:15.980000,NaT,,NaN,2025,Australian Grand Prix,#0093cc
162,7,J DOOHAN,DOO,,Alpine,0093CC,,Jack,Doohan,Jack Doohan,https://media.formula1.com/d_driver_fallback_i...,,14.0,,NaN,0 days 00:01:16.315000,0 days 00:01:16.863000,NaT,NaT,,NaN,2025,Australian Grand Prix,#0093cc
163,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,12.0,,NaN,0 days 00:01:16.288000,0 days 00:01:16.453000,NaT,NaT,,NaN,2025,Australian Grand Prix,#229971
164,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,13.0,,NaN,0 days 00:01:16.369000,0 days 00:01:16.483000,NaT,NaT,,NaN,2025,Australian Grand Prix,#229971
165,63,G RUSSELL,RUS,,Mercedes,27F4D2,,George,Russell,George Russell,https://media.formula1.com/d_driver_fallback_i...,,4.0,,NaN,0 days 00:01:15.971000,0 days 00:01:15.798000,0 days 00:01:15.546000,NaT,,NaN,2025,Australian Grand Prix,#27F4D2

In [15]:
Fast_Laps_Qualy=GP_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])

In [16]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_Qualy.columns},
  cells=dict(
    values=Fast_Laps_Qualy.T.values,
    fill_color=[Fast_Laps_Qualy.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )

# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Qualifying Results".format(year_qualy,gp_qualy),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    height=1000,
    width=1000,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [17]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Qualy Results/{}/{} {} Qualifying Results.html".format(year_qualy,year_qualy,gp_qualy),full_html=False, include_plotlyjs='cdn')

In [22]:
#Multi Race Plot

In [28]:
#2024
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="COL":
        return '#64C4FF'    
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    else:
        return '#3860C6'

In [30]:
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2020
for i in race_multi:

    df_bq_qualy=df_bq2_qualy[(df_bq2_qualy["GP"]==i)&(df_bq2_qualy["Year"]==year_multi)]
    GP_qualy=df_bq_qualy
    GP_qualy["DriverNumber"]=GP_qualy["DriverNumber"].astype(int)
    year_qualy=GP_qualy['Year'].iloc[0]
    gp_qualy=GP_qualy['GP'].iloc[0]
    GP_qualy['Color'] = GP_qualy['Abbreviation'].apply(driver_color)
    GP_qualy.head()
    Fast_Laps_Qualy=GP_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])
    import plotly.graph_objects as go

    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_Qualy.columns},
    cells=dict(
        values=Fast_Laps_Qualy.T.values,
        fill_color=[Fast_Laps_Qualy.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )

    fig.update_layout(
        title="{} {} Qualifying Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Qualy Results/{}/{} {} Qualifying Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/2942302736.py:20: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Sprint Race

In [19]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_sprint`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_sprint = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [20]:
racing_sprint='Qatar Grand Prix'

In [21]:
df_bq_sprint=df_bq2_sprint[(df_bq2_sprint["GP"]==racing_sprint)&(df_bq2_sprint["Year"]==2024)]
GP_sprint=df_bq_sprint
GP_sprint["DriverNumber"]=GP_sprint["DriverNumber"].astype(int)
year_sprint=GP_sprint['Year'].iloc[0]
gp_sprint=GP_sprint['GP'].iloc[0]
GP_sprint.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_12613/268647073.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
0,10,P GASLY,GAS,gasly,Alpine,0093cc,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,FRA,9.0,9,8.0,NaT,NaT,NaT,0 days 00:00:14.513000,Finished,0.0,2024,Qatar Grand Prix
1,31,E OCON,OCO,ocon,Alpine,0093cc,alpine,Esteban,Ocon,Esteban Ocon,https://media.formula1.com/d_driver_fallback_i...,FRA,14.0,14,17.0,NaT,NaT,NaT,0 days 00:00:30.379000,Finished,0.0,2024,Qatar Grand Prix
2,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,ESP,11.0,11,11.0,NaT,NaT,NaT,0 days 00:00:19.204000,Finished,0.0,2024,Qatar Grand Prix
3,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,CAN,13.0,13,14.0,NaT,NaT,NaT,0 days 00:00:24.421000,Finished,0.0,2024,Qatar Grand Prix
4,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,https://media.formula1.com/d_driver_fallback_i...,GBR,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:00.410000,Finished,6.0,2024,Qatar Grand Prix

In [22]:
#2024
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="BEA":
        return '#B6BABD'    
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="COL":
        return '#64C4FF'    
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    elif driver =="LAW":
        return '#6692FF'        
    else:
        return '#3860C6'

In [23]:
GP_sprint['Color'] = GP_sprint['Abbreviation'].apply(driver_color)
GP_sprint.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_12613/4122059520.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
0,10,P GASLY,GAS,gasly,Alpine,0093cc,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,FRA,9.0,9,8.0,NaT,NaT,NaT,0 days 00:00:14.513000,Finished,0.0,2024,Qatar Grand Prix,#0093cc
1,31,E OCON,OCO,ocon,Alpine,0093cc,alpine,Esteban,Ocon,Esteban Ocon,https://media.formula1.com/d_driver_fallback_i...,FRA,14.0,14,17.0,NaT,NaT,NaT,0 days 00:00:30.379000,Finished,0.0,2024,Qatar Grand Prix,#0093cc
2,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,ESP,11.0,11,11.0,NaT,NaT,NaT,0 days 00:00:19.204000,Finished,0.0,2024,Qatar Grand Prix,#229971
3,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,CAN,13.0,13,14.0,NaT,NaT,NaT,0 days 00:00:24.421000,Finished,0.0,2024,Qatar Grand Prix,#229971
4,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,https://media.formula1.com/d_driver_fallback_i...,GBR,3.0,3,2.0,NaT,NaT,NaT,0 days 00:00:00.410000,Finished,6.0,2024,Qatar Grand Prix,#27F4D2

In [24]:
Fast_Laps_sprint=GP_sprint[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])

In [25]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_sprint.columns},
  cells=dict(
    values=Fast_Laps_sprint.T.values,
    fill_color=[Fast_Laps_sprint.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )


# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Sprint Race Results".format(year_sprint,gp_sprint),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    height=1000,
    width=1050,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [26]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Results/{}/{} {} Sprint Race Results.html".format(year_sprint,year_sprint,gp_sprint),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi GP Plot

In [37]:
#2024
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="COL":
        return '#64C4FF'    
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    else:
        return '#3860C6'

In [38]:
#2024
race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']
#2022
# race_multi=['Austrian Grand Prix','Emilia Romagna Grand Prix','São Paulo Grand Prix']
#2021
# race_multi=['British Grand Prix','Italian Grand Prix','São Paulo Grand Prix']

year_multi=2024
for i in race_multi:
    df_bq_sprint=df_bq2_sprint[(df_bq2_sprint["GP"]==i)&(df_bq2_sprint["Year"]==year_multi)]
    GP_sprint=df_bq_sprint
    GP_sprint["DriverNumber"]=GP_sprint["DriverNumber"].astype(int)
    year_sprint=GP_sprint['Year'].iloc[0]
    gp_sprint=GP_sprint['GP'].iloc[0]
    GP_sprint['Color'] = GP_sprint['Abbreviation'].apply(driver_color)
    Fast_Laps_sprint=GP_sprint[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])
    import plotly.graph_objects as go

    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_sprint.columns},
    cells=dict(
        values=Fast_Laps_sprint.T.values,
        fill_color=[Fast_Laps_sprint.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )
    fig.update_layout(
        title="{} {} Sprint Race Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Results/{}/{} {} Sprint Race Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [26]:
# Sprint Qualy

In [27]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_sprint_qualifying`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_sprint_qualy = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [28]:
df_bq_sprint_qualy=df_bq2_sprint_qualy[(df_bq2_sprint_qualy["GP"]==racing_sprint)&(df_bq2_sprint_qualy["Year"]==2024)]
GP_sprint_qualy=df_bq_sprint_qualy
# GP["LapNumber"]=GP["LapNumber"].astype(int)
# GP=GP.sort_values(['Driver','LapNumber'])
GP_sprint_qualy["DriverNumber"]=GP_sprint_qualy["DriverNumber"].astype(int)
year_sprint_qualy=GP_sprint_qualy['Year'].iloc[0]
gp_sprint_qualy=GP_sprint_qualy['GP'].iloc[0]
GP_sprint_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_12613/2992934816.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
220,10,P GASLY,GAS,,Alpine,0093cc,,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,FRA,8.0,,NaN,0 days 00:01:22.586000,0 days 00:01:22.352000,0 days 00:01:21.978000,NaT,,NaN,2024,Qatar Grand Prix
221,31,E OCON,OCO,,Alpine,0093cc,,Esteban,Ocon,Esteban Ocon,https://media.formula1.com/d_driver_fallback_i...,FRA,18.0,,NaN,0 days 00:01:22.906000,NaT,NaT,NaT,,NaN,2024,Qatar Grand Prix
222,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,ESP,11.0,,NaN,0 days 00:01:22.499000,0 days 00:01:22.433000,NaT,NaT,,NaN,2024,Qatar Grand Prix
223,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,CAN,14.0,,NaN,0 days 00:01:22.522000,0 days 00:01:22.599000,NaT,NaT,,NaN,2024,Qatar Grand Prix
224,63,G RUSSELL,RUS,,Mercedes,27F4D2,,George,Russell,George Russell,https://media.formula1.com/d_driver_fallback_i...,GBR,2.0,,NaN,0 days 00:01:22.021000,0 days 00:01:21.488000,0 days 00:01:21.075000,NaT,,NaN,2024,Qatar Grand Prix

In [29]:
#2024
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="BEA":
        return '#B6BABD'    
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="COL":
        return '#64C4FF'    
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    elif driver =="LAW":
        return '#6692FF'
    else:
        return '#3860C6'

In [30]:
GP_sprint_qualy['Color'] = GP_sprint_qualy['Abbreviation'].apply(driver_color)
GP_sprint_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_12613/948559039.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
220,10,P GASLY,GAS,,Alpine,0093cc,,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,FRA,8.0,,NaN,0 days 00:01:22.586000,0 days 00:01:22.352000,0 days 00:01:21.978000,NaT,,NaN,2024,Qatar Grand Prix,#0093cc
221,31,E OCON,OCO,,Alpine,0093cc,,Esteban,Ocon,Esteban Ocon,https://media.formula1.com/d_driver_fallback_i...,FRA,18.0,,NaN,0 days 00:01:22.906000,NaT,NaT,NaT,,NaN,2024,Qatar Grand Prix,#0093cc
222,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,ESP,11.0,,NaN,0 days 00:01:22.499000,0 days 00:01:22.433000,NaT,NaT,,NaN,2024,Qatar Grand Prix,#229971
223,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,CAN,14.0,,NaN,0 days 00:01:22.522000,0 days 00:01:22.599000,NaT,NaT,,NaN,2024,Qatar Grand Prix,#229971
224,63,G RUSSELL,RUS,,Mercedes,27F4D2,,George,Russell,George Russell,https://media.formula1.com/d_driver_fallback_i...,GBR,2.0,,NaN,0 days 00:01:22.021000,0 days 00:01:21.488000,0 days 00:01:21.075000,NaT,,NaN,2024,Qatar Grand Prix,#27F4D2

In [31]:
Fast_Laps_sprint_qualy=GP_sprint_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])

In [32]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_sprint_qualy.columns},
  cells=dict(
    values=Fast_Laps_sprint_qualy.T.values,
    fill_color=[Fast_Laps_sprint_qualy.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )

# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Sprint Qualifying Results".format(year_sprint_qualy,gp_sprint_qualy),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    height=1000,
    width=1050,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [33]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Qualy Results/{}/{} {} Sprint Qualifying Results.html".format(year_sprint_qualy,year_sprint_qualy,gp_sprint_qualy),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi GP Plot

In [45]:
#2024
def driver_color(driver):
    if driver =="VER":
        return "#3860C6"
    elif driver =="PER":
        return '#3860C6'
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    elif driver =="LEC":
        return '#E80020'
    elif driver =="SAI":
        return '#E80020'
    elif driver =="HAM":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="OCO":
        return '#0093cc'
    elif driver =="MAG":
        return '#B6BABD'
    elif driver =="HUL":
        return '#B6BABD'
    elif driver =="ZHO":
        return '#52e252'
    elif driver =="BOT":
        return '#52e252'
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAR":
        return '#64C4FF'
    elif driver =="COL":
        return '#64C4FF'    
    elif driver =="TSU":
        return '#6692FF'
    elif driver =="RIC":
        return '#6692FF'
    else:
        return '#3860C6'

In [46]:
#2024
race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']

year_multi=2024
for i in race_multi:
    df_bq_sprint_qualy=df_bq2_sprint_qualy[(df_bq2_sprint_qualy["GP"]==i)&(df_bq2_sprint_qualy["Year"]==year_multi)]
    GP_sprint_qualy=df_bq_sprint_qualy
    GP_sprint_qualy["DriverNumber"]=GP_sprint_qualy["DriverNumber"].astype(int)
    year_sprint_qualy=GP_sprint_qualy['Year'].iloc[0]
    gp_sprint_qualy=GP_sprint_qualy['GP'].iloc[0]
    GP_sprint_qualy['Color'] = GP_sprint_qualy['Abbreviation'].apply(driver_color)
    Fast_Laps_sprint_qualy=GP_sprint_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])
    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_sprint_qualy.columns},
    cells=dict(
        values=Fast_Laps_sprint_qualy.T.values,
        fill_color=[Fast_Laps_sprint_qualy.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )

    fig.update_layout(
        title="{} {} Sprint Qualifying Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Qualy Results/{}/{} {} Sprint Qualifying Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3101608197.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3101608197.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3101608197.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3101608197.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3101608197.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3101608197.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy