In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT
*
FROM `perceptive-ivy-290216.f1_api.race_lap_time`  A
# WHERE A.Year=2024
# AND A.GP="Monaco Grand Prix"
# AND A.DRIVER='HAM'
ORDER BY LapNumber, LapStartTime
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [4]:
track2=track3[(track3["GP"]=='Australian Grand Prix')&(track3["Year"]==2025)]
track2.head()
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]

In [5]:
track2['LapTime']= pd.to_timedelta(track2["LapTime"])

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6011/4173085553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track2['LapTime']= pd.to_timedelta(track2["LapTime"])

In [6]:
# track2['LapTime'].dt.total_seconds().min()*1.07
track2=track2[track2['LapNumber']!=1.0]

In [7]:
# quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.1]
quicklaps=track2
quicklaps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
22073,0 days 01:15:47.663000,NOR,4,NaT,2.0,1.0,NaT,0 days 01:15:36.644000,0 days 00:00:58.907000,0 days 00:00:38.076000,0 days 00:01:12.905000,0 days 01:13:56.774000,0 days 01:14:34.847000,0 days 01:15:47.721000,68.0,223.0,NaN,242.0,False,INTERMEDIATE,2.0,True,McLaren,0 days 01:12:57.726000,NaT,4,1.0,False,,False,False,2025,Australian Grand Prix
22074,0 days 01:15:49.358000,VER,1,NaT,2.0,1.0,NaT,0 days 01:15:38.205000,0 days 00:00:58.141000,0 days 00:00:37.976000,0 days 00:01:13.205000,0 days 01:13:58.233000,0 days 01:14:36.257000,0 days 01:15:49.446000,66.0,222.0,NaN,210.0,False,INTERMEDIATE,2.0,True,Red Bull Racing,0 days 01:13:00.002000,NaT,4,2.0,False,,False,False,2025,Australian Grand Prix
22075,0 days 01:15:50.986000,PIA,81,NaT,2.0,1.0,NaT,0 days 01:15:40.060000,0 days 00:00:58.462000,0 days 00:00:37.621000,0 days 00:01:13.460000,0 days 01:14:00.139000,0 days 01:14:37.662000,0 days 01:15:51.065000,67.0,197.0,NaN,191.0,False,INTERMEDIATE,2.0,True,McLaren,0 days 01:13:01.467000,NaT,4,3.0,False,,False,False,2025,Australian Grand Prix
22076,0 days 01:15:53.439000,RUS,63,NaT,2.0,1.0,NaT,0 days 01:15:41.818000,0 days 00:00:57.443000,0 days 00:00:36.070000,0 days 00:01:14.613000,0 days 01:14:02.911000,0 days 01:14:38.887000,0 days 01:15:53.515000,65.0,219.0,NaN,181.0,False,INTERMEDIATE,2.0,True,Mercedes,0 days 01:13:05.317000,NaT,4,4.0,False,,False,False,2025,Australian Grand Prix
22077,0 days 01:15:56.324000,LEC,16,NaT,2.0,1.0,NaT,0 days 01:15:44.366000,0 days 00:00:55.101000,0 days 00:00:36.092000,0 days 00:01:16.040000,0 days 01:14:04.519000,0 days 01:14:40.314000,0 days 01:15:56.518000,67.0,200.0,NaN,218.0,False,INTERMEDIATE,2.0,True,Ferrari,0 days 01:13:09.163000,NaT,4,5.0,False,,False,False,2025,Australian Grand Prix

In [8]:
#Remove Pitstops and Track Status other than Clear to remove slow laps
quicklaps=quicklaps[((quicklaps["PitOutTime"]=='NaT')&(quicklaps["PitInTime"]=='NaT')&(~quicklaps["TrackStatus"].isin(['4','41','5','6','7','124'])))]

In [9]:
transformed_laps = quicklaps.copy()
transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

# order the team from the fastest (lowest median lap time) tp slower
team_order = (
    transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
)
print(team_order)

Index(['NOR', 'PIA', 'VER', 'RUS', 'ANT', 'LEC', 'ALB', 'TSU', 'HAM', 'GAS',
       'STR', 'ALO', 'HUL', 'BOR', 'BEA', 'LAW', 'OCO'],
      dtype='object', name='Driver')

In [10]:
transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
transformed_laps.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,LapTime (s),median
547017,0 days 02:53:27.318000,PIA,81,0 days 00:01:29.517000,57.0,6.0,NaT,NaT,0 days 00:00:31.475000,0 days 00:00:18.119000,0 days 00:00:39.923000,0 days 02:52:29.355000,0 days 02:52:47.474000,0 days 02:53:27.397000,NaN,319.0,302.0,296.0,False,INTERMEDIATE,13.0,True,McLaren,0 days 02:51:57.801000,NaT,1,9.0,False,,False,True,2025,Australian Grand Prix,89.517,90.0970
547019,0 days 02:53:33.398000,GAS,10,0 days 00:01:31.312000,57.0,6.0,NaT,NaT,0 days 00:00:31.774000,0 days 00:00:19.075000,0 days 00:00:40.463000,0 days 02:52:33.919000,0 days 02:52:52.994000,0 days 02:53:33.457000,264.0,291.0,285.0,269.0,False,INTERMEDIATE,11.0,True,Alpine,0 days 02:52:02.086000,NaT,1,11.0,False,,False,True,2025,Australian Grand Prix,91.312,92.3270
547020,0 days 02:53:36.816000,TSU,22,0 days 00:01:31.511000,57.0,6.0,NaT,NaT,0 days 00:00:31.959000,0 days 00:00:19.035000,0 days 00:00:40.517000,0 days 02:52:37.318000,0 days 02:52:56.353000,0 days 02:53:36.870000,273.0,301.0,287.0,282.0,False,INTERMEDIATE,10.0,True,Racing Bulls,0 days 02:52:05.305000,NaT,1,12.0,False,,False,True,2025,Australian Grand Prix,91.511,92.0725
547022,0 days 02:53:40.059000,OCO,31,0 days 00:01:30.924000,57.0,6.0,NaT,NaT,0 days 00:00:32.076000,0 days 00:00:19.022000,0 days 00:00:39.826000,0 days 02:52:41.265000,0 days 02:53:00.287000,0 days 02:53:40.113000,266.0,294.0,285.0,278.0,False,INTERMEDIATE,11.0,True,Haas F1 Team,0 days 02:52:09.135000,NaT,1,13.0,False,,False,True,2025,Australian Grand Prix,90.924,93.5535
547024,0 days 02:53:47.250000,BEA,87,0 days 00:01:30.553000,57.0,7.0,NaT,NaT,0 days 00:00:31.384000,0 days 00:00:19.175000,0 days 00:00:39.994000,0 days 02:52:48.144000,0 days 02:53:07.319000,0 days 02:53:47.313000,265.0,288.0,286.0,282.0,False,INTERMEDIATE,13.0,True,Haas F1 Team,0 days 02:52:16.697000,NaT,1,14.0,False,,False,True,2025,Australian Grand Prix,90.553,93.3685

In [11]:
fig_pace=px.box(
    transformed_laps.sort_values(by=["median","LapNumber"]),
    x="Driver",
    y="LapTime (s)",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace Plot for the {} {}</b>".format(year,gp),
    # palette=team_palette,
    # whiskerprops=dict(color="white"),
    # boxprops=dict(edgecolor="white"),
    # medianprops=dict(color="grey"),
    # capprops=dict(color="white"),
    height=700, width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)
fig_pace.update_traces(opacity=1)
fig_pace.update_layout(
    title_x=0.5,
    hoverlabel=dict(
    bgcolor="white",
    font_size=16,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=50, r=5, t=35, b=50)
)
fig_pace.show()

In [12]:
fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Driver Pace Plots/{}/{} {} Driver Pace Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [55]:
#Get MINIMUM OF THE MEDIAN LAP TIMES

fastest_lap = transformed_laps["median"].min()
transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent']
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(2)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
transformed_laps_relative_median

      Driver   Delta Delta_Percent  Delta_Percent_Abs
87308    NOR  0.0000        100.0%           0.000000
87310    PIA  0.1450       100.16%           0.161197
87309    VER  0.7105       100.79%           0.789866
87311    RUS  1.1260       101.25%           1.251779
87320    ANT  1.3570       101.51%           1.508582
87312    LEC  1.4580       101.62%           1.620864
87314    ALB  2.0245       102.25%           2.250645
87313    TSU  2.1205       102.36%           2.357368
87315    HAM  2.2580       102.51%           2.510228
87316    GAS  2.3750       102.64%           2.640297
87318    STR  2.4195       102.69%           2.689768
87317    ALO  2.5690       102.86%           2.855968
87319    HUL  2.6650       102.96%           2.962691
87321    BOR  3.3760       103.75%           3.753113
87324    BEA  3.4165        103.8%           3.798137
87323    LAW  3.5475       103.94%           3.943770
87322    OCO  3.6015        104.0%           4.003802

In [56]:
for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta']=0.001

for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_median

      Driver   Delta Delta_Percent  Delta_Percent_Abs
87308    NOR  0.0010        100.0%           0.001000
87310    PIA  0.1450       100.16%           0.161197
87309    VER  0.7105       100.79%           0.789866
87311    RUS  1.1260       101.25%           1.251779
87320    ANT  1.3570       101.51%           1.508582
87312    LEC  1.4580       101.62%           1.620864
87314    ALB  2.0245       102.25%           2.250645
87313    TSU  2.1205       102.36%           2.357368
87315    HAM  2.2580       102.51%           2.510228
87316    GAS  2.3750       102.64%           2.640297
87318    STR  2.4195       102.69%           2.689768
87317    ALO  2.5690       102.86%           2.855968
87319    HUL  2.6650       102.96%           2.962691
87321    BOR  3.3760       103.75%           3.753113
87324    BEA  3.4165        103.8%           3.798137
87323    LAW  3.5475       103.94%           3.943770
87322    OCO  3.6015        104.0%           4.003802

In [57]:
fig_median=px.bar(
    transformed_laps_relative_median,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Median Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent",
    height=700, 
    width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_median.update_traces(textposition='outside')

fig_median.update_traces(opacity=0.85)

fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta_Percent_Abs'].max()+0.7, 0])

fig_median.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_median.update_xaxes(title_text='')      # Remove axis titles
fig_median.update_yaxes(title_text='Percentage%')

fig_median.update_xaxes(
        title_standoff = 75
)

fig_median.update_layout(
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

# fig_median.update_yaxes(visible=False)

fig_median.show()

In [58]:
fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Median Lap Times/{}/{} {} Driver Median Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [59]:
#Get MINIMUM OF ALL LAP TIMES
transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

fastest_lap_all = transformed_laps["min_all"].min()
transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_All']
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
transformed_laps_relative_min_all

      Driver  Delta_Min_All Delta_Percent_All  Delta_Percent_Abs
87308    NOR          0.000            100.0%           0.000000
87323    LAW          0.803          100.977%           0.977278
87309    VER          0.914          101.112%           1.112369
87310    PIA          1.075          101.308%           1.308311
87321    BOR          2.025          102.464%           2.464493
87313    TSU          2.027          102.467%           2.466927
87315    HAM          2.051          102.496%           2.496136
87314    ALB          2.430          102.957%           2.957392
87320    ANT          2.734          103.327%           3.327370
87316    GAS          2.853          103.472%           3.472197
87311    RUS          2.898          103.527%           3.526963
87319    HUL          3.076          103.744%           3.743595
87312    LEC          3.104          103.778%           3.777672
87318    STR          3.371          104.103%           4.102620
87322    OCO          4.597          105.595%           5.594703
87324    BEA          5.436          106.616%           6.615795
87317    ALO          6.652          108.096%           8.095708

In [60]:
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001

for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_min_all

      Driver  Delta_Min_All Delta_Percent_All  Delta_Percent_Abs
87308    NOR          0.001            100.0%           0.001000
87323    LAW          0.803          100.977%           0.977278
87309    VER          0.914          101.112%           1.112369
87310    PIA          1.075          101.308%           1.308311
87321    BOR          2.025          102.464%           2.464493
87313    TSU          2.027          102.467%           2.466927
87315    HAM          2.051          102.496%           2.496136
87314    ALB          2.430          102.957%           2.957392
87320    ANT          2.734          103.327%           3.327370
87316    GAS          2.853          103.472%           3.472197
87311    RUS          2.898          103.527%           3.526963
87319    HUL          3.076          103.744%           3.743595
87312    LEC          3.104          103.778%           3.777672
87318    STR          3.371          104.103%           4.102620
87322    OCO          4.597          105.595%           5.594703
87324    BEA          5.436          106.616%           6.615795
87317    ALO          6.652          108.096%           8.095708

In [61]:
fig_min=px.bar(
    transformed_laps_relative_min_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Fastest Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_All",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_min.update_traces(textposition='outside')

fig_min.update_traces(opacity=0.85)

fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Percent_Abs'].max()+0.7, 0])

fig_min.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_min.update_xaxes(title_text='')      # Remove axis titles
fig_min.update_yaxes(title_text='Percentage%')

fig_min.update_xaxes(
        title_standoff = 75
)

fig_min.update_layout(
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_min.update_yaxes(ticksuffix = "  ")

fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

fig_min.show()

In [62]:
fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Fastest Lap/{}/{} {} Driver Fastest Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [63]:
#Get AVERAGE OF ALL LAP TIMES
transformed_laps['avg_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform(np.mean)

fastest_lap_avg = transformed_laps["avg_all"].min()
transformed_laps['Delta_Avg_All']= transformed_laps["avg_all"] - (fastest_lap_avg)
transformed_laps['Delta_Percent_Avg']= (transformed_laps["avg_all"]/(fastest_lap_avg)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_Avg']
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+100
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].round(3)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].astype(str)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+"%"
transformed_laps_relative_avg_all=transformed_laps[["Driver","Delta_Avg_All","Delta_Percent_Avg","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all.sort_values("Delta_Avg_All")
transformed_laps_relative_avg_all

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6011/3671659905.py:2: FutureWarning:

The provided callable <function mean at 0x10665b560> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

      Driver  Delta_Avg_All Delta_Percent_Avg  Delta_Percent_Abs
87308    NOR       0.000000            100.0%           0.000000
87310    PIA       0.432925          100.482%           0.482167
87309    VER       0.527321          100.587%           0.587299
87311    RUS       1.286131          101.432%           1.432417
87312    LEC       1.916932          102.135%           2.134966
87320    ANT       1.946925          102.168%           2.168371
87314    ALB       2.059690          102.294%           2.293962
87315    HAM       2.315348          102.579%           2.578699
87316    GAS       2.352886          102.621%           2.620506
87318    STR       2.536690          102.825%           2.825216
87313    TSU       2.604515          102.901%           2.900756
87317    ALO       2.714863          103.024%           3.023655
87319    HUL       2.740749          103.052%           3.052485
87321    BOR       2.905617          103.236%           3.236106
87323    LAW       3.253310          103.623%           3.623345
87324    BEA       4.156719           104.63%           4.629510
87322    OCO       4.509015          105.022%           5.021876

In [64]:
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']=0.001
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']=0.001    
transformed_laps_relative_avg_all

      Driver  Delta_Avg_All Delta_Percent_Avg  Delta_Percent_Abs
87308    NOR       0.001000            100.0%           0.001000
87310    PIA       0.432925          100.482%           0.482167
87309    VER       0.527321          100.587%           0.587299
87311    RUS       1.286131          101.432%           1.432417
87312    LEC       1.916932          102.135%           2.134966
87320    ANT       1.946925          102.168%           2.168371
87314    ALB       2.059690          102.294%           2.293962
87315    HAM       2.315348          102.579%           2.578699
87316    GAS       2.352886          102.621%           2.620506
87318    STR       2.536690          102.825%           2.825216
87313    TSU       2.604515          102.901%           2.900756
87317    ALO       2.714863          103.024%           3.023655
87319    HUL       2.740749          103.052%           3.052485
87321    BOR       2.905617          103.236%           3.236106
87323    LAW       3.253310          103.623%           3.623345
87324    BEA       4.156719           104.63%           4.629510
87322    OCO       4.509015          105.022%           5.021876

In [65]:
fig=px.bar(
    transformed_laps_relative_avg_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Average Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_Avg",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "LAW": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "TSU": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig.update_traces(textposition='outside')

fig.update_traces(opacity=0.85)

fig.update_traces( marker_line_color='white',marker_line_width=1.5)

fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_yaxes(range=[transformed_laps_relative_avg_all['Delta_Percent_Abs'].max()+0.8, 0])


# fig.update_yaxes(range=[3.5, 0])

fig.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig.update_xaxes(title_text='')      # Remove axis titles
fig.update_yaxes(title_text='Percentage%')

fig.update_xaxes(
        title_standoff = 75
)

fig.update_layout(
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig.show()

In [66]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Average Lap Times/{}/{} {} Driver Average Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [38]:
#Multi Race Plot

In [12]:
#2024
race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2024
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    track2['LapTime']= pd.to_timedelta(track2["LapTime"])
    track2=track2[track2['LapNumber']!=1.0]
    quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.07]
    transformed_laps = quicklaps.copy()
    transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

    # order the team from the fastest (lowest median lap time) tp slower
    team_order = (
        transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
    )
    print(team_order)
    transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
    transformed_laps.tail()
    fig_pace=px.box(
        transformed_laps.sort_values(by=["median","LapNumber"]),
        x="Driver",
        y="LapTime (s)",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace Plot for the {} {}</b>".format(year_multi,i),
        height=700, width=1200,

    color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )
    fig_pace.update_traces(opacity=1)
    fig_pace.update_layout(
        title_x=0.5,
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow",
        margin=dict(l=50, r=5, t=35, b=50)
    )
    fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Driver Pace Plots/{}/{} {} Driver Pace Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')
    #Get MINIMUM OF THE MEDIAN LAP TIMES

    fastest_lap = transformed_laps["median"].min()
    transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
    transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
    transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent"]].drop_duplicates()
    transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
    transformed_laps_relative_median
    for index, row in transformed_laps_relative_median.iterrows():
        if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
         transformed_laps_relative_median.loc[index, 'Delta']=0.001
    transformed_laps_relative_median
    fig_median=px.bar(
        transformed_laps_relative_median,
        x="Driver",
        y="Delta",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Median Lap Times) for the {} {}</b>".format(year_multi,i),
        text="Delta_Percent",
        height=700, 
        width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_median.update_traces(textposition='outside')

    fig_median.update_traces(opacity=0.85)

    fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta'].max()+0.6, 0])

    fig_median.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_median.update_xaxes(title_text='')      # Remove axis titles
    fig_median.update_yaxes(title_text='')

    fig_median.update_xaxes(
            title_standoff = 75
    )

    fig_median.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

    fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Median Lap Times/{}/{} {} Driver Median Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

    transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

    fastest_lap_all = transformed_laps["min_all"].min()
    transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
    transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
    transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All"]].drop_duplicates()
    transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
    transformed_laps_relative_min_all
    for index, row in transformed_laps_relative_min_all.iterrows():
        if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
         transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    transformed_laps_relative_min_all
    fig_min=px.bar(
        transformed_laps_relative_min_all,
        x="Driver",
        y="Delta_Min_All",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Fastest Lap Times) for the {} {}</b>".format(year_multi,i),
        text="Delta_Percent_All",
        height=700, width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_min.update_traces(textposition='outside')

    fig_min.update_traces(opacity=0.85)

    fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Min_All'].max()+0.5, 0])

    fig_min.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_min.update_xaxes(title_text='')      # Remove axis titles
    fig_min.update_yaxes(title_text='')

    fig_min.update_xaxes(
            title_standoff = 75
    )

    fig_min.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_min.update_yaxes(ticksuffix = "  ")

    fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
    fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Fastest Lap/{}/{} {} Driver Fastest Lap Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'SAI', 'PER', 'RUS', 'NOR', 'HAM', 'PIA', 'LEC', 'SAR', 'HUL',
       'STR', 'ALO', 'ZHO', 'GAS', 'TSU', 'MAG', 'RIC', 'OCO', 'BOT', 'ALB'],
      dtype='object', name='Driver')
Index(['VER', 'PER', 'LEC', 'NOR', 'PIA', 'HAM', 'RUS', 'ALO', 'BEA', 'HUL',
       'ZHO', 'MAG', 'ALB', 'OCO', 'SAR', 'TSU', 'BOT', 'RIC', 'STR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['SAI', 'NOR', 'LEC', 'PER', 'PIA', 'RUS', 'ALO', 'HUL', 'BOT', 'OCO',
       'STR', 'TSU', 'ALB', 'RIC', 'ZHO', 'GAS', 'MAG', 'HAM', 'VER'],
      dtype='object', name='Driver')
Index(['NOR', 'VER', 'LEC', 'PER', 'HAM', 'RUS', 'SAI', 'PIA', 'ALO', 'TSU',
       'STR', 'SAR', 'OCO', 'BOT', 'MAG', 'HUL', 'GAS', 'ZHO'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'PER', 'NOR', 'LEC', 'SAI', 'ALO', 'RUS', 'GAS', 'STR', 'PIA',
       'HAM', 'HUL', 'OCO', 'ZHO', 'ALB', 'SAR', 'MAG', 'BOT', 'TSU', 'RIC'],
      dtype='object', name='Driver')
Index(['NOR', 'LEC', 'VER', 'PER', 'SAI', 'PIA', 'HAM', 'RUS', 'HUL', 'MAG',
       'TSU', 'GAS', 'OCO', 'BOT', 'ALO', 'STR', 'ALB', 'ZHO', 'RIC', 'SAR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'NOR', 'LEC', 'PIA', 'SAI', 'RUS', 'HAM', 'ALB', 'PER', 'TSU',
       'RIC', 'STR', 'GAS', 'HUL', 'ALO', 'BOT', 'OCO', 'MAG', 'ZHO', 'SAR'],
      dtype='object', name='Driver')
Index(['SAR', 'VER', 'HAM', 'NOR', 'RUS', 'SAI', 'TSU', 'PIA', 'LEC', 'STR',
       'ALB', 'GAS', 'BOT', 'ZHO', 'RIC', 'ALO'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'NOR', 'HAM', 'RUS', 'PIA', 'ALO', 'MAG', 'STR', 'HUL', 'RIC',
       'GAS', 'TSU', 'OCO', 'BOT', 'ZHO', 'PER', 'SAI', 'ALB'],
      dtype='object', name='Driver')
Index(['LEC', 'NOR', 'PER', 'VER', 'PIA', 'RUS', 'HAM', 'SAI', 'GAS', 'OCO',
       'TSU', 'HUL', 'ALO', 'ZHO', 'RIC', 'MAG', 'BOT', 'ALB', 'STR', 'SAR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'RUS', 'NOR', 'SAI', 'LEC', 'PIA', 'HAM', 'PER', 'HUL', 'GAS',
       'MAG', 'ZHO', 'RIC', 'OCO', 'TSU', 'STR', 'ALO', 'ALB', 'BOT', 'SAR'],
      dtype='object', name='Driver')
Index(['HAM', 'NOR', 'RUS', 'PIA', 'VER', 'SAI', 'LEC', 'STR', 'HUL', 'ALO',
       'ZHO', 'PER', 'TSU', 'ALB', 'MAG', 'SAR', 'RIC', 'OCO', 'BOT'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['RUS', 'LEC', 'PER', 'HAM', 'PIA', 'NOR', 'VER', 'SAI', 'ALO', 'RIC',
       'HUL', 'STR', 'TSU', 'OCO', 'ALB', 'SAR', 'ZHO', 'MAG', 'BOT', 'GAS'],
      dtype='object', name='Driver')
Index(['HAM', 'RUS', 'LEC', 'NOR', 'PIA', 'VER', 'PER', 'SAI', 'RIC', 'SAR',
       'ALB', 'ALO', 'TSU', 'OCO', 'MAG', 'STR', 'GAS', 'BOT', 'HUL'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy