In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from PIL import Image

# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT
*
FROM `perceptive-ivy-290216.f1_api.race_lap_time`  A
# WHERE A.Year=2024
# AND A.GP="Monaco Grand Prix"
# AND A.DRIVER='HAM'
ORDER BY LapNumber, LapStartTime
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [6]:
track2=track3[(track3["GP"]=='Las Vegas Grand Prix')&(track3["Year"]==2025)]
track2.head()
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]

In [7]:
track2['LapTime']= pd.to_timedelta(track2["LapTime"])

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_40055/4173085553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track2['LapTime']= pd.to_timedelta(track2["LapTime"])

In [8]:
# track2['LapTime'].dt.total_seconds().min()*1.07
track2=track2[track2['LapNumber']!=1.0]

In [9]:
# quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.1]
quicklaps=track2
quicklaps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
21671,0 days 01:01:11.581000,VER,1,0 days 00:01:47.622000,2.0,1.0,NaT,NaT,0 days 00:00:28.482000,0 days 00:00:32.633000,0 days 00:00:46.507000,0 days 00:59:52.455000,0 days 01:00:25.088000,0 days 01:01:11.595000,NaN,NaN,201.0,126.0,True,MEDIUM,2.0,True,Red Bull Racing,0 days 00:59:23.959000,NaT,216,1.0,False,,False,False,2025,Las Vegas Grand Prix
21678,0 days 01:01:14.223000,RUS,63,0 days 00:01:49.251000,2.0,1.0,NaT,NaT,0 days 00:00:28.833000,0 days 00:00:32.961000,0 days 00:00:47.457000,0 days 00:59:53.813000,0 days 01:00:26.774000,0 days 01:01:14.231000,179.0,NaN,227.0,97.0,True,MEDIUM,2.0,True,Mercedes,0 days 00:59:24.972000,NaT,126,2.0,False,,False,False,2025,Las Vegas Grand Prix
21687,0 days 01:01:16.118000,NOR,4,0 days 00:01:50.056000,2.0,1.0,NaT,NaT,0 days 00:00:29.185000,0 days 00:00:32.908000,0 days 00:00:47.963000,0 days 00:59:55.249000,0 days 01:00:28.157000,0 days 01:01:16.120000,177.0,NaN,206.0,97.0,True,MEDIUM,2.0,True,McLaren,0 days 00:59:26.062000,NaT,126,3.0,False,,False,False,2025,Las Vegas Grand Prix
21689,0 days 01:01:17.145000,SAI,55,0 days 00:01:50.424000,2.0,1.0,NaT,NaT,0 days 00:00:29.126000,0 days 00:00:33.294000,0 days 00:00:48.004000,0 days 00:59:55.860000,0 days 01:00:29.154000,0 days 01:01:17.158000,173.0,NaN,248.0,65.0,True,MEDIUM,2.0,True,Williams,0 days 00:59:26.721000,NaT,126,4.0,False,,False,False,2025,Las Vegas Grand Prix
21692,0 days 01:01:19.030000,HAD,6,0 days 00:01:51.673000,2.0,1.0,NaT,NaT,0 days 00:00:29.155000,0 days 00:00:33.256000,0 days 00:00:49.262000,0 days 00:59:56.512000,0 days 01:00:29.768000,0 days 01:01:19.030000,174.0,NaN,276.0,90.0,True,MEDIUM,2.0,True,Racing Bulls,0 days 00:59:27.357000,NaT,126,5.0,False,,False,False,2025,Las Vegas Grand Prix

In [10]:
#Remove Pitstops and Track Status other than Clear to remove slow laps
# quicklaps=quicklaps[((quicklaps["PitOutTime"]=='NaT')&(quicklaps["PitInTime"]=='NaT')&(~quicklaps["TrackStatus"].isin(['4','41','5','6','7','124'])))]

quicklaps=quicklaps[(~quicklaps["TrackStatus"].isin(['4','41','5','6','7','124']))]

In [11]:
transformed_laps = quicklaps.copy()
transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

# order the team from the fastest (lowest median lap time) tp slower
team_order = (
    transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
)
print(team_order)

Index(['VER', 'PIA', 'LEC', 'SAI', 'RUS', 'ANT', 'NOR', 'HAD', 'HAM', 'HUL',
       'TSU', 'BEA', 'OCO', 'ALB', 'LAW', 'GAS', 'ALO', 'COL', 'BOR'],
      dtype='object', name='Driver')

In [12]:
transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
transformed_laps.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,LapTime (s),median
518582,0 days 02:19:50.961000,OCO,31,0 days 00:01:34.734000,50.0,2.0,NaT,NaT,0 days 00:00:27.152000,0 days 00:00:31.623000,0 days 00:00:35.959000,0 days 02:18:43.395000,0 days 02:19:15.018000,0 days 02:19:50.977000,NaN,NaN,320.0,341.0,False,HARD,23.0,True,Haas F1 Team,0 days 02:18:16.227000,NaT,1,11.0,False,,False,True,2025,Las Vegas Grand Prix,94.734,96.710
518599,0 days 02:20:00.875000,BEA,87,0 days 00:01:34.519000,50.0,2.0,NaT,NaT,0 days 00:00:26.907000,0 days 00:00:31.529000,0 days 00:00:36.083000,0 days 02:18:53.282000,0 days 02:19:24.811000,0 days 02:20:00.894000,184.0,NaN,319.0,334.0,True,HARD,33.0,True,Haas F1 Team,0 days 02:18:26.356000,NaT,1,12.0,False,,False,True,2025,Las Vegas Grand Prix,94.519,96.646
518620,0 days 02:20:15.634000,ALO,14,0 days 00:01:38.065000,50.0,2.0,NaT,NaT,0 days 00:00:27.515000,0 days 00:00:33.095000,0 days 00:00:37.455000,0 days 02:19:05.107000,0 days 02:19:38.202000,0 days 02:20:15.657000,182.0,NaN,279.0,278.0,False,HARD,34.0,True,Aston Martin,0 days 02:18:37.569000,NaT,1,13.0,False,,False,True,2025,Las Vegas Grand Prix,98.065,97.079
518624,0 days 02:20:17.300000,TSU,22,0 days 00:01:35.176000,50.0,3.0,NaT,NaT,0 days 00:00:27.079000,0 days 00:00:31.963000,0 days 00:00:36.134000,0 days 02:19:09.219000,0 days 02:19:41.182000,0 days 02:20:17.316000,183.0,NaN,325.0,334.0,False,MEDIUM,24.0,False,Red Bull Racing,0 days 02:18:42.124000,NaT,1,14.0,False,,False,True,2025,Las Vegas Grand Prix,95.176,96.642
518636,0 days 02:20:22.028000,GAS,10,0 days 00:01:35.730000,50.0,2.0,NaT,NaT,0 days 00:00:27.381000,0 days 00:00:31.954000,0 days 00:00:36.395000,0 days 02:19:13.697000,0 days 02:19:45.651000,0 days 02:20:22.046000,NaN,NaN,317.0,322.0,False,HARD,48.0,True,Alpine,0 days 02:18:46.298000,NaT,1,15.0,False,,False,True,2025,Las Vegas Grand Prix,95.730,97.019

In [13]:
fig_pace=px.box(
    transformed_laps.sort_values(by=["median","LapNumber"]),
    x="Driver",
    y="LapTime (s)",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace Plot for the {} {}</b>".format(year,gp),
    # palette=team_palette,
    # whiskerprops=dict(color="white"),
    # boxprops=dict(edgecolor="white"),
    # medianprops=dict(color="grey"),
    # capprops=dict(color="white"),
    height=700, width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)
fig_pace.update_traces(opacity=1)
fig_pace.update_layout(
    title_x=0.5,
    hoverlabel=dict(
    bgcolor="white",
    font_size=16,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=50, r=5, t=35, b=50)
)
fig_pace.show()

In [14]:
fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Driver Pace Plots/{}/{} {} Driver Pace Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [15]:
#Get MINIMUM OF THE MEDIAN LAP TIMES

fastest_lap = transformed_laps["median"].min()
transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent']
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(2)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
transformed_laps_relative_median=transformed_laps[["Team", "Driver","Delta","Delta_Percent","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
transformed_laps_relative_median

                  Team Driver   Delta Delta_Percent  Delta_Percent_Abs
21671  Red Bull Racing    VER  0.0000        100.0%           0.000000
21695          McLaren    PIA  0.1195       100.13%           0.125260
21702          Ferrari    LEC  0.1395       100.15%           0.146224
21689         Williams    SAI  0.2245       100.24%           0.235321
21678         Mercedes    RUS  0.2375       100.25%           0.248948
21711         Mercedes    ANT  0.2935       100.31%           0.307647
21687          McLaren    NOR  0.3315       100.35%           0.347479
21692     Racing Bulls    HAD  0.3725       100.39%           0.390455
21710          Ferrari    HAM  0.6725        100.7%           0.704916
21706      Kick Sauber    HUL  0.8175       100.86%           0.856905
21720  Red Bull Racing    TSU  1.2405        101.3%           1.300294
21699     Haas F1 Team    BEA  1.2445        101.3%           1.304487
21709     Haas F1 Team    OCO  1.3085       101.37%           1.371572
21713         Williams    ALB  1.4470       101.52%           1.516748
21694     Racing Bulls    LAW  1.5625       101.64%           1.637815
21718           Alpine    GAS  1.6175        101.7%           1.695466
21704     Aston Martin    ALO  1.6775       101.76%           1.758358
21715           Alpine    COL  1.9955       102.09%           2.091686
21730      Kick Sauber    BOR     NaN          nan%                NaN

In [16]:
for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta']=0.001

for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_median

                  Team Driver   Delta Delta_Percent  Delta_Percent_Abs
21671  Red Bull Racing    VER  0.0010        100.0%           0.001000
21695          McLaren    PIA  0.1195       100.13%           0.125260
21702          Ferrari    LEC  0.1395       100.15%           0.146224
21689         Williams    SAI  0.2245       100.24%           0.235321
21678         Mercedes    RUS  0.2375       100.25%           0.248948
21711         Mercedes    ANT  0.2935       100.31%           0.307647
21687          McLaren    NOR  0.3315       100.35%           0.347479
21692     Racing Bulls    HAD  0.3725       100.39%           0.390455
21710          Ferrari    HAM  0.6725        100.7%           0.704916
21706      Kick Sauber    HUL  0.8175       100.86%           0.856905
21720  Red Bull Racing    TSU  1.2405        101.3%           1.300294
21699     Haas F1 Team    BEA  1.2445        101.3%           1.304487
21709     Haas F1 Team    OCO  1.3085       101.37%           1.371572
21713         Williams    ALB  1.4470       101.52%           1.516748
21694     Racing Bulls    LAW  1.5625       101.64%           1.637815
21718           Alpine    GAS  1.6175        101.7%           1.695466
21704     Aston Martin    ALO  1.6775       101.76%           1.758358
21715           Alpine    COL  1.9955       102.09%           2.091686
21730      Kick Sauber    BOR     NaN          nan%                NaN

In [19]:
fig_median=px.bar(
    transformed_laps_relative_median,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Median Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent",
    height=700, 
    width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_median.update_traces(textposition='outside')

fig_median.update_traces(opacity=0.85)

fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta_Percent_Abs'].max()+1, 0])

fig_median.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_median.update_xaxes(title_text='')      # Remove axis titles
fig_median.update_yaxes(title_text='Percentage%')

fig_median.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_median.Team, transformed_laps_relative_median.Delta_Percent_Abs, transformed_laps_relative_median.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_median.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig_median.update_layout(
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

# fig_median.update_yaxes(visible=False)

fig_median.show()

In [38]:
fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Median Lap Times/{}/{} {} Driver Median Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [21]:
#Get MINIMUM OF ALL LAP TIMES
transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

fastest_lap_all = transformed_laps["min_all"].min()
transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_All']
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
transformed_laps_relative_min_all=transformed_laps[["Team","Driver","Delta_Min_All","Delta_Percent_All","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
21671,Red Bull Racing,VER,0.000,100.0%,0.000000
21687,McLaren,NOR,0.600,100.643%,0.642639
21711,Mercedes,ANT,0.633,100.678%,0.677984
21695,McLaren,PIA,0.721,100.772%,0.772238
21702,Ferrari,LEC,0.939,101.006%,1.005730
21689,Williams,SAI,1.131,101.211%,1.211375
21699,Haas F1 Team,BEA,1.154,101.236%,1.236009
21710,Ferrari,HAM,1.188,101.272%,1.272425
21709,Haas F1 Team,OCO,1.192,101.277%,1.276710
21706,Kick Sauber,HUL,1.227,101.314%,1.314197
21678,Mercedes,RUS,1.227,101.314%,1.314197
21692,Racing Bulls,HAD,1.255,101.344%,1.344187
21694,Racing Bulls,LAW,1.472,101.577%,1.576608
21720,Red Bull Racing,TSU,1.602,101.716%,1.715846
21713,Williams,ALB,1.819,101.948%,1.948268
21704,Aston Martin,ALO,2.264,102.425%,2.424892
21718,Alpine,GAS,2.309,102.473%,2.473089
21715,Alpine,COL,2.415,102.587%,2.586622
21730,Kick Sauber,BOR,NaN,nan%,NaN

In [22]:
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001

for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
21671,Red Bull Racing,VER,0.001,100.0%,0.001000
21687,McLaren,NOR,0.600,100.643%,0.642639
21711,Mercedes,ANT,0.633,100.678%,0.677984
21695,McLaren,PIA,0.721,100.772%,0.772238
21702,Ferrari,LEC,0.939,101.006%,1.005730
21689,Williams,SAI,1.131,101.211%,1.211375
21699,Haas F1 Team,BEA,1.154,101.236%,1.236009
21710,Ferrari,HAM,1.188,101.272%,1.272425
21709,Haas F1 Team,OCO,1.192,101.277%,1.276710
21706,Kick Sauber,HUL,1.227,101.314%,1.314197
21678,Mercedes,RUS,1.227,101.314%,1.314197
21692,Racing Bulls,HAD,1.255,101.344%,1.344187
21694,Racing Bulls,LAW,1.472,101.577%,1.576608
21720,Red Bull Racing,TSU,1.602,101.716%,1.715846
21713,Williams,ALB,1.819,101.948%,1.948268
21704,Aston Martin,ALO,2.264,102.425%,2.424892
21718,Alpine,GAS,2.309,102.473%,2.473089
21715,Alpine,COL,2.415,102.587%,2.586622
21730,Kick Sauber,BOR,NaN,nan%,NaN

In [32]:
fig_min=px.bar(
    transformed_laps_relative_min_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Fastest Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_All",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_min.update_traces(textposition='outside')

fig_min.update_traces(opacity=0.85)

fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Percent_Abs'].max()+0.7, 0])

fig_min.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_min.update_xaxes(title_text='')      # Remove axis titles
fig_min.update_yaxes(title_text='Percentage%')

fig_min.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_min_all.Team, transformed_laps_relative_min_all.Delta_Percent_Abs, transformed_laps_relative_min_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_min.add_layout_image(
          x=z,
          y=y+0.4,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig_min.update_layout(
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_min.update_yaxes(ticksuffix = "  ")

fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

fig_min.show()

In [33]:
fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Fastest Lap/{}/{} {} Driver Fastest Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [34]:
#Get AVERAGE OF ALL LAP TIMES
transformed_laps['avg_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform(np.mean)

fastest_lap_avg = transformed_laps["avg_all"].min()
transformed_laps['Delta_Avg_All']= transformed_laps["avg_all"] - (fastest_lap_avg)
transformed_laps['Delta_Percent_Avg']= (transformed_laps["avg_all"]/(fastest_lap_avg)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_Avg']
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+100
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].round(3)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].astype(str)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+"%"
transformed_laps_relative_avg_all=transformed_laps[["Team","Driver","Delta_Avg_All","Delta_Percent_Avg","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all.sort_values("Delta_Avg_All")
transformed_laps_relative_avg_all

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_40055/2458230245.py:2: FutureWarning:

The provided callable <function mean at 0x1085ef560> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
21671,Red Bull Racing,VER,0.000000,100.0%,0.000000
21711,Mercedes,ANT,1.092217,101.132%,1.131628
21687,McLaren,NOR,1.135809,101.177%,1.176793
21678,Mercedes,RUS,1.215299,101.259%,1.259151
21695,McLaren,PIA,1.223503,101.268%,1.267651
21702,Ferrari,LEC,1.253156,101.298%,1.298374
21689,Williams,SAI,1.411809,101.463%,1.462752
21692,Racing Bulls,HAD,1.609707,101.668%,1.667790
21706,Kick Sauber,HUL,1.657360,101.717%,1.717163
21710,Ferrari,HAM,1.802523,101.868%,1.867564
21709,Haas F1 Team,OCO,1.834972,101.901%,1.901184
21699,Haas F1 Team,BEA,2.084095,102.159%,2.159295
21720,Red Bull Racing,TSU,2.211319,102.291%,2.291111
21718,Alpine,GAS,2.352013,102.437%,2.436881
21704,Aston Martin,ALO,2.360727,102.446%,2.445910
21694,Racing Bulls,LAW,2.765479,102.865%,2.865266
21715,Alpine,COL,2.777875,102.878%,2.878109
21713,Williams,ALB,5.130646,105.316%,5.315775
21730,Kick Sauber,BOR,NaN,nan%,NaN

In [26]:
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']=0.001
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']=0.001    
transformed_laps_relative_avg_all

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
21671,Red Bull Racing,VER,0.001000,100.0%,0.001000
21711,Mercedes,ANT,1.092217,101.132%,1.131628
21687,McLaren,NOR,1.135809,101.177%,1.176793
21678,Mercedes,RUS,1.215299,101.259%,1.259151
21695,McLaren,PIA,1.223503,101.268%,1.267651
21702,Ferrari,LEC,1.253156,101.298%,1.298374
21689,Williams,SAI,1.411809,101.463%,1.462752
21692,Racing Bulls,HAD,1.609707,101.668%,1.667790
21706,Kick Sauber,HUL,1.657360,101.717%,1.717163
21710,Ferrari,HAM,1.802523,101.868%,1.867564
21709,Haas F1 Team,OCO,1.834972,101.901%,1.901184
21699,Haas F1 Team,BEA,2.084095,102.159%,2.159295
21720,Red Bull Racing,TSU,2.211319,102.291%,2.291111
21718,Alpine,GAS,2.352013,102.437%,2.436881
21704,Aston Martin,ALO,2.360727,102.446%,2.445910
21694,Racing Bulls,LAW,2.765479,102.865%,2.865266
21715,Alpine,COL,2.777875,102.878%,2.878109
21713,Williams,ALB,5.130646,105.316%,5.315775
21730,Kick Sauber,BOR,NaN,nan%,NaN

In [27]:
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all[transformed_laps_relative_avg_all["Driver"]!="ALO"]

In [30]:
fig=px.bar(
    transformed_laps_relative_avg_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Average Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_Avg",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig.update_traces(textposition='outside')

fig.update_traces(opacity=0.85)

fig.update_traces( marker_line_color='white',marker_line_width=1.5)

fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_yaxes(range=[transformed_laps_relative_avg_all['Delta_Percent_Abs'].max()+0.8, 0])


# fig.update_yaxes(range=[3.5, 0])

fig.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig.update_xaxes(title_text='')      # Remove axis titles
fig.update_yaxes(title_text='Percentage%')

fig.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_avg_all.Team, transformed_laps_relative_avg_all.Delta_Percent_Abs, transformed_laps_relative_avg_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig.add_layout_image(
          x=z,
          y=y+0.5,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig.show()

In [31]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Average Lap Times/{}/{} {} Driver Average Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [38]:
#Multi Race Plot

In [21]:
#2025
race_multi=["Japanese Grand Prix","Bahrain Grand Prix","Saudi Arabian Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Spanish Grand Prix","Canadian Grand Prix","Austrian Grand Prix","British Grand Prix","Belgian Grand Prix","Hungarian Grand Prix","Dutch Grand Prix","Italian Grand Prix","Azerbaijan Grand Prix","Singapore Grand Prix","United States Grand Prix","Mexico City Grand Prix","São Paulo Grand Prix"]
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2025
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    track2['LapTime']= pd.to_timedelta(track2["LapTime"])
    track2=track2[track2['LapNumber']!=1.0]
    quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.07]
    transformed_laps = quicklaps.copy()
    transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

    # order the team from the fastest (lowest median lap time) tp slower
    team_order = (
        transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
    )
    print(team_order)
    transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
    transformed_laps.tail()
    fig_pace=px.box(
        transformed_laps.sort_values(by=["median","LapNumber"]),
        x="Driver",
        y="LapTime (s)",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace Plot for the {} {}</b>".format(year_multi,i),
        height=700, width=1200,

    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
            }
    )
    fig_pace.update_traces(opacity=1)
    fig_pace.update_layout(
        title_x=0.5,
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow",
        margin=dict(l=50, r=5, t=35, b=50)
    )
    fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Driver Pace Plots/{}/{} {} Driver Pace Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')
    #Get MINIMUM OF THE MEDIAN LAP TIMES

    fastest_lap = transformed_laps["median"].min()
    transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
    transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
    transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent"]].drop_duplicates()
    transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
    transformed_laps_relative_median
    for index, row in transformed_laps_relative_median.iterrows():
        if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
         transformed_laps_relative_median.loc[index, 'Delta']=0.001
    transformed_laps_relative_median
    fig_median=px.bar(
        transformed_laps_relative_median,
        x="Driver",
        y="Delta",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Median Lap Times) for the {} {}</b>".format(year_multi,i),
        text="Delta_Percent",
        height=700, 
        width=1200,
        color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
            }
    )

    fig_median.update_traces(textposition='outside')

    fig_median.update_traces(opacity=0.85)

    fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta'].max()+0.6, 0])

    fig_median.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_median.update_xaxes(title_text='')      # Remove axis titles
    fig_median.update_yaxes(title_text='')

    fig_median.update_xaxes(
            title_standoff = 75
    )

    fig_median.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

    fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Median Lap Times/{}/{} {} Driver Median Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

    transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

    fastest_lap_all = transformed_laps["min_all"].min()
    transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
    transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
    transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All"]].drop_duplicates()
    transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
    transformed_laps_relative_min_all
    for index, row in transformed_laps_relative_min_all.iterrows():
        if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
         transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    transformed_laps_relative_min_all
    fig_min=px.bar(
        transformed_laps_relative_min_all,
        x="Driver",
        y="Delta_Min_All",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Fastest Lap Times) for the {} {}</b>".format(year_multi,i),
        text="Delta_Percent_All",
        height=700, width=1200,
        color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "COL": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
            }
    )

    fig_min.update_traces(textposition='outside')

    fig_min.update_traces(opacity=0.85)

    fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Min_All'].max()+0.5, 0])

    fig_min.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_min.update_xaxes(title_text='')      # Remove axis titles
    fig_min.update_yaxes(title_text='')

    fig_min.update_xaxes(
            title_standoff = 75
    )

    fig_min.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_min.update_yaxes(ticksuffix = "  ")

    fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
    fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Fastest Lap/{}/{} {} Driver Fastest Lap Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['NOR', 'PIA', 'LEC', 'VER', 'RUS', 'ALO', 'GAS', 'TSU', 'ANT', 'HAM',
       'ALB', 'HAD', 'BEA', 'HUL', 'DOO', 'BOR', 'STR', 'OCO', 'LAW', 'SAI'],
      dtype='object', name='Driver')
Index(['PIA', 'LEC', 'NOR', 'RUS', 'HAM', 'VER', 'GAS', 'OCO', 'ANT', 'TSU',
       'DOO', 'ALB', 'BEA', 'ALO', 'HAD', 'SAI', 'HUL', 'LAW', 'STR', 'BOR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['PIA', 'VER', 'NOR', 'LEC', 'ANT', 'HAM', 'RUS', 'ALB', 'SAI', 'ALO',
       'BEA', 'LAW', 'HAD', 'HUL', 'OCO', 'STR', 'BOR', 'DOO'],
      dtype='object', name='Driver')
Index(['PIA', 'RUS', 'NOR', 'ALB', 'SAI', 'VER', 'TSU', 'HAD', 'ANT', 'OCO',
       'HAM', 'LEC', 'STR', 'GAS', 'ALO', 'HUL', 'BOR', 'BEA', 'LAW'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['PIA', 'NOR', 'LEC', 'VER', 'RUS', 'SAI', 'GAS', 'HAM', 'ALB', 'HAD',
       'BOR', 'LAW', 'ALO', 'BEA', 'STR', 'ANT', 'COL', 'TSU', 'HUL', 'OCO'],
      dtype='object', name='Driver')
Index(['PIA', 'NOR', 'LEC', 'VER', 'HAM', 'RUS', 'SAI', 'ALB', 'LAW', 'ALO',
       'BOR', 'BEA', 'HAD', 'STR', 'OCO', 'ANT', 'COL', 'HUL', 'TSU', 'GAS'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['RUS', 'VER', 'HUL', 'LEC', 'ALO', 'PIA', 'NOR', 'LAW', 'OCO', 'BOR',
       'TSU', 'COL', 'GAS', 'HAM', 'BEA', 'ALB', 'SAI', 'ANT', 'HAD'],
      dtype='object', name='Driver')
Index(['ANT', 'NOR', 'RUS', 'PIA', 'LEC', 'VER', 'HAM', 'ALO', 'STR', 'HUL',
       'BEA', 'OCO', 'SAI', 'ALB', 'HAD', 'TSU', 'COL', 'BOR', 'GAS', 'LAW'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['PIA', 'NOR', 'LEC', 'HAM', 'RUS', 'LAW', 'OCO', 'TSU', 'BOR', 'HUL',
       'COL', 'ALO', 'STR', 'GAS', 'BEA', 'ALB', 'HAD'],
      dtype='object', name='Driver')
Index(['NOR', 'ALB', 'PIA', 'OCO', 'HAM', 'ALO', 'VER', 'LEC', 'SAI', 'HUL',
       'RUS', 'GAS', 'TSU', 'BEA', 'STR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['NOR', 'PIA', 'VER', 'LEC', 'SAI', 'HAM', 'RUS', 'ALB', 'LAW', 'COL',
       'BOR', 'OCO', 'ANT', 'GAS', 'BEA', 'ALO', 'TSU', 'STR', 'HUL', 'HAD'],
      dtype='object', name='Driver')
Index(['NOR', 'PIA', 'RUS', 'LEC', 'VER', 'COL', 'HUL', 'ANT', 'ALO', 'HAD',
       'STR', 'TSU', 'ALB', 'SAI', 'BOR', 'OCO', 'LAW', 'HAM', 'GAS', 'BEA'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['PIA', 'NOR', 'VER', 'HAD', 'ANT', 'LEC', 'RUS', 'ALB', 'LAW', 'SAI',
       'STR', 'ALO', 'HAM', 'BEA', 'COL', 'TSU', 'OCO', 'GAS', 'BOR', 'HUL'],
      dtype='object', name='Driver')
Index(['VER', 'PIA', 'NOR', 'LEC', 'RUS', 'BEA', 'HAM', 'BOR', 'ANT', 'ALB',
       'HAD', 'LAW', 'SAI', 'OCO', 'STR', 'TSU', 'GAS', 'COL', 'ALO'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'ANT', 'RUS', 'NOR', 'LEC', 'SAI', 'LAW', 'ALB', 'TSU', 'HAM',
       'HAD', 'ALO', 'BOR', 'COL', 'BEA', 'OCO', 'HUL', 'STR', 'GAS'],
      dtype='object', name='Driver')
Index(['HAM', 'VER', 'RUS', 'NOR', 'PIA', 'ANT', 'LEC', 'ALO', 'BEA', 'TSU',
       'HAD', 'HUL', 'SAI', 'ALB', 'OCO', 'COL', 'LAW', 'GAS', 'BOR', 'STR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['LEC', 'VER', 'NOR', 'HAM', 'ANT', 'OCO', 'PIA', 'TSU', 'RUS', 'ALB',
       'STR', 'HUL', 'BEA', 'ALO', 'SAI', 'BOR', 'LAW', 'HAD', 'GAS', 'COL'],
      dtype='object', name='Driver')
Index(['NOR', 'HAM', 'LEC', 'PIA', 'RUS', 'BEA', 'ANT', 'STR', 'OCO', 'VER',
       'SAI', 'TSU', 'HAD', 'ALO', 'BOR', 'ALB', 'GAS', 'HUL', 'COL', 'LAW'],
      dtype='object', name='Driver')
Index(['VER', 'RUS', 'PIA', 'ANT', 'NOR', 'BEA', 'COL', 'ALO', 'HAD', 'GAS',
       'STR', 'TSU', 'SAI', 'ALB', 'OCO', 'HUL', 'LAW', 'HAM'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58016/234251604.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy