In [1]:
import pandas as pd
import numpy as np
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from PIL import Image

# %load_ext google.colab.data_table
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
project_id = "perceptive-ivy-290216"

# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 100)

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
query2=f"""
SELECT
*
FROM `perceptive-ivy-290216.f1_api.race_lap_time`  A
# WHERE A.Year=2024
# AND A.GP="Monaco Grand Prix"
# AND A.DRIVER='HAM'
ORDER BY LapNumber, LapStartTime
"""
track3=pandas_gbq.read_gbq(query2,project_id,dialect='standard')

Downloading: 100%|██████████|

In [4]:
track2=track3[(track3["GP"]=='Japanese Grand Prix')&(track3["Year"]==2025)]
track2.head()
year=track2['Year'].iloc[0]
gp=track2['GP'].iloc[0]

In [5]:
track2['LapTime']= pd.to_timedelta(track2["LapTime"])

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_62423/4173085553.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  track2['LapTime']= pd.to_timedelta(track2["LapTime"])

In [6]:
# track2['LapTime'].dt.total_seconds().min()*1.07
track2=track2[track2['LapNumber']!=1.0]

In [7]:
# quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.1]
quicklaps=track2
quicklaps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP
20831,0 days 00:59:15.596000,VER,1,0 days 00:01:33.943000,2.0,1.0,NaT,NaT,0 days 00:00:33.894000,0 days 00:00:42.026000,0 days 00:00:18.023000,0 days 00:58:15.547000,0 days 00:58:57.573000,0 days 00:59:15.596000,279.0,296.0,262.0,295.0,True,MEDIUM,2.0,True,Red Bull Racing,0 days 00:57:41.653000,NaT,1,1.0,False,,False,True,2025,Japanese Grand Prix
20832,0 days 00:59:16.636000,NOR,4,0 days 00:01:33.947000,2.0,1.0,NaT,NaT,0 days 00:00:33.809000,0 days 00:00:42.049000,0 days 00:00:18.089000,0 days 00:58:16.522000,0 days 00:58:58.571000,0 days 00:59:16.660000,NaN,298.0,266.0,295.0,True,MEDIUM,2.0,True,McLaren,0 days 00:57:42.689000,NaT,1,2.0,False,,False,True,2025,Japanese Grand Prix
20833,0 days 00:59:17.494000,PIA,81,0 days 00:01:34.084000,2.0,1.0,NaT,NaT,0 days 00:00:33.936000,0 days 00:00:41.858000,0 days 00:00:18.290000,0 days 00:58:17.364000,0 days 00:58:59.222000,0 days 00:59:17.512000,283.0,300.0,266.0,289.0,True,MEDIUM,2.0,True,McLaren,0 days 00:57:43.410000,NaT,1,3.0,False,,False,True,2025,Japanese Grand Prix
20834,0 days 00:59:18.420000,LEC,16,0 days 00:01:34.121000,2.0,1.0,NaT,NaT,0 days 00:00:34.083000,0 days 00:00:42.034000,0 days 00:00:18.004000,0 days 00:58:18.405000,0 days 00:59:00.439000,0 days 00:59:18.443000,277.0,300.0,264.0,295.0,True,MEDIUM,2.0,True,Ferrari,0 days 00:57:44.299000,NaT,1,4.0,False,,False,True,2025,Japanese Grand Prix
20835,0 days 00:59:19.104000,RUS,63,0 days 00:01:34.191000,2.0,1.0,NaT,NaT,0 days 00:00:33.985000,0 days 00:00:42.155000,0 days 00:00:18.051000,0 days 00:58:18.921000,0 days 00:59:01.076000,0 days 00:59:19.127000,281.0,303.0,269.0,300.0,True,MEDIUM,2.0,True,Mercedes,0 days 00:57:44.913000,NaT,1,5.0,False,,False,True,2025,Japanese Grand Prix

In [8]:
#Remove Pitstops and Track Status other than Clear to remove slow laps
# quicklaps=quicklaps[((quicklaps["PitOutTime"]=='NaT')&(quicklaps["PitInTime"]=='NaT')&(~quicklaps["TrackStatus"].isin(['4','41','5','6','7','124'])))]

quicklaps=quicklaps[(~quicklaps["TrackStatus"].isin(['4','41','5','6','7','124']))]

In [9]:
transformed_laps = quicklaps.copy()
transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

# order the team from the fastest (lowest median lap time) tp slower
team_order = (
    transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
)
print(team_order)

Index(['NOR', 'PIA', 'VER', 'LEC', 'RUS', 'ALO', 'GAS', 'TSU', 'ANT', 'HAM',
       'BEA', 'HAD', 'ALB', 'DOO', 'HUL', 'STR', 'OCO', 'BOR', 'LAW', 'SAI'],
      dtype='object', name='Driver')

In [10]:
transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
transformed_laps.tail()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,Year,GP,LapTime (s),median
523914,0 days 02:19:35.225000,DOO,7,0 days 00:01:32.960000,53.0,2.0,NaT,NaT,0 days 00:00:32.418000,0 days 00:00:42.387000,0 days 00:00:18.155000,0 days 02:18:34.708000,0 days 02:19:17.095000,0 days 02:19:35.250000,280.0,302.0,266.0,301.0,False,HARD,38.0,True,Alpine,0 days 02:18:02.265000,NaT,1,15.0,False,,False,True,2025,Japanese Grand Prix,92.960,93.4690
523915,0 days 02:19:35.868000,HUL,27,0 days 00:01:32.804000,53.0,2.0,NaT,NaT,0 days 00:00:31.989000,0 days 00:00:42.701000,0 days 00:00:18.114000,0 days 02:18:35.069000,0 days 02:19:17.770000,0 days 02:19:35.884000,NaN,305.0,268.0,305.0,False,HARD,31.0,True,Kick Sauber,0 days 02:18:03.064000,NaT,1,16.0,False,,False,True,2025,Japanese Grand Prix,92.804,93.4845
523916,0 days 02:19:36.645000,LAW,30,0 days 00:01:33.243000,53.0,2.0,NaT,NaT,0 days 00:00:32.517000,0 days 00:00:42.254000,0 days 00:00:18.472000,0 days 02:18:35.953000,0 days 02:19:18.207000,0 days 02:19:36.679000,288.0,308.0,266.0,307.0,False,SOFT,20.0,False,Racing Bulls,0 days 02:18:03.402000,NaT,1,17.0,False,,False,True,2025,Japanese Grand Prix,93.243,94.2650
523917,0 days 02:19:37.349000,OCO,31,0 days 00:01:33.106000,53.0,2.0,NaT,NaT,0 days 00:00:32.229000,0 days 00:00:42.548000,0 days 00:00:18.329000,0 days 02:18:36.451000,0 days 02:19:18.999000,0 days 02:19:37.328000,283.0,304.0,272.0,304.0,False,MEDIUM,21.0,True,Haas F1 Team,0 days 02:18:04.243000,NaT,1,18.0,False,,False,True,2025,Japanese Grand Prix,93.106,94.1630
523918,0 days 02:19:37.808000,BOR,5,0 days 00:01:32.949000,53.0,2.0,NaT,NaT,0 days 00:00:32,0 days 00:00:42.550000,0 days 00:00:18.399000,0 days 02:18:36.853000,0 days 02:19:19.403000,0 days 02:19:37.802000,286.0,309.0,269.0,307.0,False,MEDIUM,22.0,True,Kick Sauber,0 days 02:18:04.859000,NaT,1,19.0,False,,False,True,2025,Japanese Grand Prix,92.949,94.1640

In [11]:
fig_pace=px.box(
    transformed_laps.sort_values(by=["median","LapNumber"]),
    x="Driver",
    y="LapTime (s)",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace Plot for the {} {}</b>".format(year,gp),
    # palette=team_palette,
    # whiskerprops=dict(color="white"),
    # boxprops=dict(edgecolor="white"),
    # medianprops=dict(color="grey"),
    # capprops=dict(color="white"),
    height=700, width=1200,

color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)
fig_pace.update_traces(opacity=1)
fig_pace.update_layout(
    title_x=0.5,
    hoverlabel=dict(
    bgcolor="white",
    font_size=16,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    title_font_family="PT Sans Narrow",
    margin=dict(l=50, r=5, t=35, b=50)
)
fig_pace.show()

In [12]:
fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Driver Pace Plots/{}/{} {} Driver Pace Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [13]:
#Get MINIMUM OF THE MEDIAN LAP TIMES

fastest_lap = transformed_laps["median"].min()
transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent']
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(2)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
transformed_laps_relative_median=transformed_laps[["Team", "Driver","Delta","Delta_Percent","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
transformed_laps_relative_median

                  Team Driver   Delta Delta_Percent  Delta_Percent_Abs
20832          McLaren    NOR  0.0000        100.0%           0.000000
20833          McLaren    PIA  0.0765       100.08%           0.082966
20831  Red Bull Racing    VER  0.1900       100.21%           0.206058
20834          Ferrari    LEC  0.2005       100.22%           0.217446
20835         Mercedes    RUS  0.2425       100.26%           0.262995
20842     Aston Martin    ALO  0.7940       100.86%           0.861106
20844           Alpine    GAS  0.8495       100.92%           0.921297
20845  Red Bull Racing    TSU  0.8735       100.95%           0.947325
20836         Mercedes    ANT  0.9295       101.01%           1.008058
20839          Ferrari    HAM  1.0025       101.09%           1.087228
20841     Haas F1 Team    BEA  1.1680       101.27%           1.266715
20837     Racing Bulls    HAD  1.2310       101.34%           1.335040
20840         Williams    ALB  1.2540       101.36%           1.359984
20851           Alpine    DOO  1.2620       101.37%           1.368660
20847      Kick Sauber    HUL  1.2775       101.39%           1.385470
20853     Aston Martin    STR  1.9100       102.07%           2.071426
20850     Haas F1 Team    OCO  1.9560       102.12%           2.121314
20854      Kick Sauber    BOR  1.9570       102.12%           2.122399
20846     Racing Bulls    LAW  2.0580       102.23%           2.231935
20848         Williams    SAI  2.2130        102.4%           2.400035

In [14]:
for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta']=0.001

for index, row in transformed_laps_relative_median.iterrows():
  if transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_median.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_median

                  Team Driver   Delta Delta_Percent  Delta_Percent_Abs
20832          McLaren    NOR  0.0010        100.0%           0.001000
20833          McLaren    PIA  0.0765       100.08%           0.082966
20831  Red Bull Racing    VER  0.1900       100.21%           0.206058
20834          Ferrari    LEC  0.2005       100.22%           0.217446
20835         Mercedes    RUS  0.2425       100.26%           0.262995
20842     Aston Martin    ALO  0.7940       100.86%           0.861106
20844           Alpine    GAS  0.8495       100.92%           0.921297
20845  Red Bull Racing    TSU  0.8735       100.95%           0.947325
20836         Mercedes    ANT  0.9295       101.01%           1.008058
20839          Ferrari    HAM  1.0025       101.09%           1.087228
20841     Haas F1 Team    BEA  1.1680       101.27%           1.266715
20837     Racing Bulls    HAD  1.2310       101.34%           1.335040
20840         Williams    ALB  1.2540       101.36%           1.359984
20851           Alpine    DOO  1.2620       101.37%           1.368660
20847      Kick Sauber    HUL  1.2775       101.39%           1.385470
20853     Aston Martin    STR  1.9100       102.07%           2.071426
20850     Haas F1 Team    OCO  1.9560       102.12%           2.121314
20854      Kick Sauber    BOR  1.9570       102.12%           2.122399
20846     Racing Bulls    LAW  2.0580       102.23%           2.231935
20848         Williams    SAI  2.2130        102.4%           2.400035

In [15]:
fig_median=px.bar(
    transformed_laps_relative_median,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Median Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent",
    height=700, 
    width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_median.update_traces(textposition='outside')

fig_median.update_traces(opacity=0.85)

fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta_Percent_Abs'].max()+0.7, 0])

fig_median.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_median.update_xaxes(title_text='')      # Remove axis titles
fig_median.update_yaxes(title_text='Percentage%')

fig_median.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_median.Team, transformed_laps_relative_median.Delta_Percent_Abs, transformed_laps_relative_median.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_median.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig_median.update_layout(
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

# fig_median.update_yaxes(visible=False)

fig_median.show()

In [16]:
fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Median Lap Times/{}/{} {} Driver Median Plot.html".format(year,year,gp),full_html=False, include_plotlyjs='cdn')

In [17]:
#Get MINIMUM OF ALL LAP TIMES
transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

fastest_lap_all = transformed_laps["min_all"].min()
transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_All']
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
transformed_laps_relative_min_all=transformed_laps[["Team","Driver","Delta_Min_All","Delta_Percent_All","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
20836,Mercedes,ANT,0.000,100.0%,0.000000
20833,McLaren,PIA,0.074,100.081%,0.081350
20831,Red Bull Racing,VER,0.076,100.084%,0.083549
20848,Williams,SAI,0.141,100.155%,0.155005
20832,McLaren,NOR,0.151,100.166%,0.165998
20840,Williams,ALB,0.160,100.176%,0.175892
20837,Racing Bulls,HAD,0.352,100.387%,0.386962
20835,Mercedes,RUS,0.392,100.431%,0.430935
20839,Ferrari,HAM,0.441,100.485%,0.484802
20834,Ferrari,LEC,0.504,100.554%,0.554059
20842,Aston Martin,ALO,0.805,100.885%,0.884956
20844,Alpine,GAS,0.855,100.94%,0.939922
20845,Red Bull Racing,TSU,0.906,100.996%,0.995987
20850,Haas F1 Team,OCO,1.002,101.102%,1.101523
20841,Haas F1 Team,BEA,1.041,101.144%,1.144396
20854,Kick Sauber,BOR,1.069,101.175%,1.175177
20846,Racing Bulls,LAW,1.078,101.185%,1.185071
20853,Aston Martin,STR,1.087,101.195%,1.194965
20847,Kick Sauber,HUL,1.607,101.767%,1.766614
20851,Alpine,DOO,1.720,101.891%,1.890837

In [18]:
for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001

for index, row in transformed_laps_relative_min_all.iterrows():
  if transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_min_all.loc[index, 'Delta_Percent_Abs']=0.001

transformed_laps_relative_min_all

,Team,Driver,Delta_Min_All,Delta_Percent_All,Delta_Percent_Abs
20836,Mercedes,ANT,0.001,100.0%,0.001000
20833,McLaren,PIA,0.074,100.081%,0.081350
20831,Red Bull Racing,VER,0.076,100.084%,0.083549
20848,Williams,SAI,0.141,100.155%,0.155005
20832,McLaren,NOR,0.151,100.166%,0.165998
20840,Williams,ALB,0.160,100.176%,0.175892
20837,Racing Bulls,HAD,0.352,100.387%,0.386962
20835,Mercedes,RUS,0.392,100.431%,0.430935
20839,Ferrari,HAM,0.441,100.485%,0.484802
20834,Ferrari,LEC,0.504,100.554%,0.554059
20842,Aston Martin,ALO,0.805,100.885%,0.884956
20844,Alpine,GAS,0.855,100.94%,0.939922
20845,Red Bull Racing,TSU,0.906,100.996%,0.995987
20850,Haas F1 Team,OCO,1.002,101.102%,1.101523
20841,Haas F1 Team,BEA,1.041,101.144%,1.144396
20854,Kick Sauber,BOR,1.069,101.175%,1.175177
20846,Racing Bulls,LAW,1.078,101.185%,1.185071
20853,Aston Martin,STR,1.087,101.195%,1.194965
20847,Kick Sauber,HUL,1.607,101.767%,1.766614
20851,Alpine,DOO,1.720,101.891%,1.890837

In [19]:
fig_min=px.bar(
    transformed_laps_relative_min_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Fastest Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_All",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig_min.update_traces(textposition='outside')

fig_min.update_traces(opacity=0.85)

fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Percent_Abs'].max()+0.7, 0])

fig_min.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig_min.update_xaxes(title_text='')      # Remove axis titles
fig_min.update_yaxes(title_text='Percentage%')

fig_min.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_min_all.Team, transformed_laps_relative_min_all.Delta_Percent_Abs, transformed_laps_relative_min_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig_min.add_layout_image(
          x=z,
          y=y+0.4,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig_min.update_layout(
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig_min.update_yaxes(ticksuffix = "  ")

fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

fig_min.show()

In [20]:
fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Fastest Lap/{}/{} {} Driver Fastest Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [21]:
#Get AVERAGE OF ALL LAP TIMES
transformed_laps['avg_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform(np.mean)

fastest_lap_avg = transformed_laps["avg_all"].min()
transformed_laps['Delta_Avg_All']= transformed_laps["avg_all"] - (fastest_lap_avg)
transformed_laps['Delta_Percent_Avg']= (transformed_laps["avg_all"]/(fastest_lap_avg)-1)*100
transformed_laps['Delta_Percent_Abs']=transformed_laps['Delta_Percent_Avg']
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+100
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].round(3)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg'].astype(str)
transformed_laps['Delta_Percent_Avg']=transformed_laps['Delta_Percent_Avg']+"%"
transformed_laps_relative_avg_all=transformed_laps[["Team","Driver","Delta_Avg_All","Delta_Percent_Avg","Delta_Percent_Abs"]].drop_duplicates()
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all.sort_values("Delta_Avg_All")
transformed_laps_relative_avg_all

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_62423/2458230245.py:2: FutureWarning:

The provided callable <function mean at 0x1081eb560> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
20831,Red Bull Racing,VER,0.000000,100.0%,0.000000
20833,McLaren,PIA,0.007154,100.008%,0.007698
20832,McLaren,NOR,0.007442,100.008%,0.008009
20834,Ferrari,LEC,0.258673,100.278%,0.278358
20835,Mercedes,RUS,0.271192,100.292%,0.291830
20836,Mercedes,ANT,0.277519,100.299%,0.298639
20839,Ferrari,HAM,0.454385,100.489%,0.488964
20837,Racing Bulls,HAD,0.614135,100.661%,0.660871
20840,Williams,ALB,0.659731,100.71%,0.709937
20841,Haas F1 Team,BEA,0.922673,100.993%,0.992890
20842,Aston Martin,ALO,0.961731,101.035%,1.034920
20845,Red Bull Racing,TSU,0.966615,101.04%,1.040176
20844,Alpine,GAS,1.046538,101.126%,1.126182
20848,Williams,SAI,1.243231,101.338%,1.337842
20851,Alpine,DOO,1.360327,101.464%,1.463850
20854,Kick Sauber,BOR,1.379462,101.484%,1.484441
20847,Kick Sauber,HUL,1.400462,101.507%,1.507039
20850,Haas F1 Team,OCO,1.411538,101.519%,1.518959
20846,Racing Bulls,LAW,1.423000,101.531%,1.531292
20853,Aston Martin,STR,1.852530,101.994%,1.993510

In [22]:
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Avg_All']=0.001
for index, row in transformed_laps_relative_avg_all.iterrows():
  if transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']==0.0:
    transformed_laps_relative_avg_all.loc[index, 'Delta_Percent_Abs']=0.001    
transformed_laps_relative_avg_all

,Team,Driver,Delta_Avg_All,Delta_Percent_Avg,Delta_Percent_Abs
20831,Red Bull Racing,VER,0.001000,100.0%,0.001000
20833,McLaren,PIA,0.007154,100.008%,0.007698
20832,McLaren,NOR,0.007442,100.008%,0.008009
20834,Ferrari,LEC,0.258673,100.278%,0.278358
20835,Mercedes,RUS,0.271192,100.292%,0.291830
20836,Mercedes,ANT,0.277519,100.299%,0.298639
20839,Ferrari,HAM,0.454385,100.489%,0.488964
20837,Racing Bulls,HAD,0.614135,100.661%,0.660871
20840,Williams,ALB,0.659731,100.71%,0.709937
20841,Haas F1 Team,BEA,0.922673,100.993%,0.992890
20842,Aston Martin,ALO,0.961731,101.035%,1.034920
20845,Red Bull Racing,TSU,0.966615,101.04%,1.040176
20844,Alpine,GAS,1.046538,101.126%,1.126182
20848,Williams,SAI,1.243231,101.338%,1.337842
20851,Alpine,DOO,1.360327,101.464%,1.463850
20854,Kick Sauber,BOR,1.379462,101.484%,1.484441
20847,Kick Sauber,HUL,1.400462,101.507%,1.507039
20850,Haas F1 Team,OCO,1.411538,101.519%,1.518959
20846,Racing Bulls,LAW,1.423000,101.531%,1.531292
20853,Aston Martin,STR,1.852530,101.994%,1.993510

In [23]:
transformed_laps_relative_avg_all=transformed_laps_relative_avg_all[transformed_laps_relative_avg_all["Driver"]!="ALO"]

In [24]:
fig=px.bar(
    transformed_laps_relative_avg_all,
    x="Driver",
    y="Delta_Percent_Abs",
    color='Driver',
    template="xgridoff",
    title="<b>Driver Pace (Average Lap Times) for the {} {}</b>".format(year,gp),
    text="Delta_Percent_Avg",
    height=700, width=1200,
    color_discrete_map={
                 "VER": "#3671C6",
                 "TSU": "#3671C6",
                 "LEC": "#E80020",
                 "HAM": "#E80020",
                 "NOR": "#FF8000",
                 "PIA": "#FF8000",
                 "RUS": "#27F4D2",
                 "ANT": "#27F4D2",
                 "GAS": "#0093CC",
                 "DOO": "#0093CC",
                 "ALO": "#229971",
                 "STR": "#229971",
                 "SAI": "#64C4FF",
                 "ALB": "#64C4FF",
                 "HUL": "#52e252",
                 "BOR": "#52e252",
                 "LAW": "#6692FF",
                 "HAD": "#6692FF",
                 "OCO": "#B6BABD",
                 "BEA": "#B6BABD"
          }
)

fig.update_traces(textposition='outside')

fig.update_traces(opacity=0.85)

fig.update_traces( marker_line_color='white',marker_line_width=1.5)

fig.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

fig.update_yaxes(range=[transformed_laps_relative_avg_all['Delta_Percent_Abs'].max()+0.8, 0])


# fig.update_yaxes(range=[3.5, 0])

fig.update_layout(
    xaxis={'side': 'top'},
    yaxis={'side': 'left'}
)

fig.update_xaxes(title_text='')      # Remove axis titles
fig.update_yaxes(title_text='Percentage%')

fig.update_xaxes(
        title_standoff = 75
)

for x,y,z in zip(transformed_laps_relative_avg_all.Team, transformed_laps_relative_avg_all.Delta_Percent_Abs, transformed_laps_relative_avg_all.Driver):
  for png in (Path(Path.cwd()).parents[0].joinpath("F1_LOGOS").glob("*.png")):
    if str.split(str.split(str(png),".")[0],"/")[6]==x:
      image=str(png)
      fig.add_layout_image(
          x=z,
          y=y+0.3,
          source=Image.open(image),
          xref="x",
          yref="y",
          sizex=0.9,
          sizey=0.9,
          xanchor="center",
          yanchor="middle",
      )

fig.update_layout(
    hoverlabel=dict(
    bgcolor="white",
    font_size=20,
    font_family="PT Sans Narrow"
    ),
    title_x=0.5,
    margin=dict(l=100, r=5, t=110, b=30),
    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=16,
        color="Black"
    ),
    title_font_family="PT Sans Narrow"
)
fig.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
fig.show()

In [25]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Average Lap Times/{}/{} {} Driver Average Lap Plot.html".format(year, year,gp),full_html=False, include_plotlyjs='cdn')

In [38]:
#Multi Race Plot

In [12]:
#2024
race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Pre-Season Testing","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2024
for i in race_multi:
    track2=track3[(track3["GP"]==i)&(track3["Year"]==year_multi)]
    year=track2['Year'].iloc[0]
    gp=track2['GP'].iloc[0]
    track2['LapTime']= pd.to_timedelta(track2["LapTime"])
    track2=track2[track2['LapNumber']!=1.0]
    quicklaps=track2[track2["LapTime"]<track2['LapTime'].min()*1.07]
    transformed_laps = quicklaps.copy()
    transformed_laps.loc[:, "LapTime (s)"] = quicklaps["LapTime"].dt.total_seconds()

    # order the team from the fastest (lowest median lap time) tp slower
    team_order = (
        transformed_laps[["Driver", "LapTime (s)"]].groupby("Driver").median()["LapTime (s)"].sort_values().index
    )
    print(team_order)
    transformed_laps['median'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('median')
    transformed_laps.tail()
    fig_pace=px.box(
        transformed_laps.sort_values(by=["median","LapNumber"]),
        x="Driver",
        y="LapTime (s)",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace Plot for the {} {}</b>".format(year_multi,i),
        height=700, width=1200,

    color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )
    fig_pace.update_traces(opacity=1)
    fig_pace.update_layout(
        title_x=0.5,
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        title_font_family="PT Sans Narrow",
        margin=dict(l=50, r=5, t=35, b=50)
    )
    fig_pace.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Driver Pace Plots/{}/{} {} Driver Pace Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')
    #Get MINIMUM OF THE MEDIAN LAP TIMES

    fastest_lap = transformed_laps["median"].min()
    transformed_laps['Delta']= transformed_laps["median"] - (fastest_lap)
    transformed_laps['Delta_Percent']= (transformed_laps["median"]/(fastest_lap)-1)*100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+100
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].round(3)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent'].astype(str)
    transformed_laps['Delta_Percent']=transformed_laps['Delta_Percent']+"%"
    transformed_laps_relative_median=transformed_laps[["Driver","Delta","Delta_Percent"]].drop_duplicates()
    transformed_laps_relative_median=transformed_laps_relative_median.sort_values("Delta")
    transformed_laps_relative_median
    for index, row in transformed_laps_relative_median.iterrows():
        if transformed_laps_relative_median.loc[index, 'Delta']==0.0:
         transformed_laps_relative_median.loc[index, 'Delta']=0.001
    transformed_laps_relative_median
    fig_median=px.bar(
        transformed_laps_relative_median,
        x="Driver",
        y="Delta",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Median Lap Times) for the {} {}</b>".format(year_multi,i),
        text="Delta_Percent",
        height=700, 
        width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_median.update_traces(textposition='outside')

    fig_median.update_traces(opacity=0.85)

    fig_median.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_median.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_median.update_yaxes(range=[transformed_laps_relative_median['Delta'].max()+0.6, 0])

    fig_median.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_median.update_xaxes(title_text='')      # Remove axis titles
    fig_median.update_yaxes(title_text='')

    fig_median.update_xaxes(
            title_standoff = 75
    )

    fig_median.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_median.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)

    fig_median.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Median Lap Times/{}/{} {} Driver Median Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

    transformed_laps['min_all'] = transformed_laps['LapTime (s)'].groupby(transformed_laps['Driver']).transform('min')

    fastest_lap_all = transformed_laps["min_all"].min()
    transformed_laps['Delta_Min_All']= transformed_laps["min_all"] - (fastest_lap_all)
    transformed_laps['Delta_Percent_All']= (transformed_laps["min_all"]/(fastest_lap_all)-1)*100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+100
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].round(3)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All'].astype(str)
    transformed_laps['Delta_Percent_All']=transformed_laps['Delta_Percent_All']+"%"
    transformed_laps_relative_min_all=transformed_laps[["Driver","Delta_Min_All","Delta_Percent_All"]].drop_duplicates()
    transformed_laps_relative_min_all=transformed_laps_relative_min_all.sort_values("Delta_Min_All")
    transformed_laps_relative_min_all
    for index, row in transformed_laps_relative_min_all.iterrows():
        if transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']==0.0:
         transformed_laps_relative_min_all.loc[index, 'Delta_Min_All']=0.001
    transformed_laps_relative_min_all
    fig_min=px.bar(
        transformed_laps_relative_min_all,
        x="Driver",
        y="Delta_Min_All",
        color='Driver',
        template="xgridoff",
        title="<b>Driver Pace (Fastest Lap Times) for the {} {}</b>".format(year_multi,i),
        text="Delta_Percent_All",
        height=700, width=1200,
        color_discrete_map={
                 "ALB": "#64C4FF",
                 "ALO": "#229971",
                 "BOT": "#52e252",
                 "COL": "#37BEDD",
                 "GAS": "#0093cc",
                 "HAM": "#27F4D2",
                 "HUL": "#B6BABD",
                 "LEC": "#E80020",
                 "MAG": "#B6BABD",
                 "NOR": "#FF8000",
                 "OCO": "#0093cc",
                 "PER": "#3671C6",
                 "PIA": "#FF8000",
                 "RIC": "#6692FF",
                 "RUS": "#27F4D2",
                 "SAI": "#E80020",
                 "SAR": "#37BEDD",
                 "STR": "#229971",
                 "TSU": "#6692FF",
                 "VER": "#3671C6",
                 "ZHO": "#52e252"
            }
    )

    fig_min.update_traces(textposition='outside')

    fig_min.update_traces(opacity=0.85)

    fig_min.update_traces( marker_line_color='white',marker_line_width=1.5)

    fig_min.update_yaxes(tickangle = -90,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_xaxes(tickangle = -0,tickprefix="<b>",ticksuffix ="</b><br>")

    fig_min.update_yaxes(range=[transformed_laps_relative_min_all['Delta_Min_All'].max()+0.5, 0])

    fig_min.update_layout(
        xaxis={'side': 'top'},
        yaxis={'side': 'left'}
    )

    fig_min.update_xaxes(title_text='')      # Remove axis titles
    fig_min.update_yaxes(title_text='')

    fig_min.update_xaxes(
            title_standoff = 75
    )

    fig_min.update_layout(
        title_x=0.5,
        margin=dict(l=60, r=5, t=110, b=30),
        hoverlabel=dict(
        bgcolor="white",
        font_size=16,
        font_family="PT Sans Narrow"
        ),
        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=12,
            color="Black"
        ),
        title_font_family="PT Sans Narrow"
    )
    fig_min.update_yaxes(ticksuffix = "  ")

    fig_min.update_traces( marker_line_color='Black',marker_line_width=0.1, opacity=0.99)
    fig_min.write_html("/Users/rdesh723/statpulse-html/plots/Race Driver Pace/Fastest Lap/{}/{} {} Driver Fastest Lap Plot.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'SAI', 'PER', 'RUS', 'NOR', 'HAM', 'PIA', 'LEC', 'SAR', 'HUL',
       'STR', 'ALO', 'ZHO', 'GAS', 'TSU', 'MAG', 'RIC', 'OCO', 'BOT', 'ALB'],
      dtype='object', name='Driver')
Index(['VER', 'PER', 'LEC', 'NOR', 'PIA', 'HAM', 'RUS', 'ALO', 'BEA', 'HUL',
       'ZHO', 'MAG', 'ALB', 'OCO', 'SAR', 'TSU', 'BOT', 'RIC', 'STR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['SAI', 'NOR', 'LEC', 'PER', 'PIA', 'RUS', 'ALO', 'HUL', 'BOT', 'OCO',
       'STR', 'TSU', 'ALB', 'RIC', 'ZHO', 'GAS', 'MAG', 'HAM', 'VER'],
      dtype='object', name='Driver')
Index(['NOR', 'VER', 'LEC', 'PER', 'HAM', 'RUS', 'SAI', 'PIA', 'ALO', 'TSU',
       'STR', 'SAR', 'OCO', 'BOT', 'MAG', 'HUL', 'GAS', 'ZHO'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'PER', 'NOR', 'LEC', 'SAI', 'ALO', 'RUS', 'GAS', 'STR', 'PIA',
       'HAM', 'HUL', 'OCO', 'ZHO', 'ALB', 'SAR', 'MAG', 'BOT', 'TSU', 'RIC'],
      dtype='object', name='Driver')
Index(['NOR', 'LEC', 'VER', 'PER', 'SAI', 'PIA', 'HAM', 'RUS', 'HUL', 'MAG',
       'TSU', 'GAS', 'OCO', 'BOT', 'ALO', 'STR', 'ALB', 'ZHO', 'RIC', 'SAR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'NOR', 'LEC', 'PIA', 'SAI', 'RUS', 'HAM', 'ALB', 'PER', 'TSU',
       'RIC', 'STR', 'GAS', 'HUL', 'ALO', 'BOT', 'OCO', 'MAG', 'ZHO', 'SAR'],
      dtype='object', name='Driver')
Index(['SAR', 'VER', 'HAM', 'NOR', 'RUS', 'SAI', 'TSU', 'PIA', 'LEC', 'STR',
       'ALB', 'GAS', 'BOT', 'ZHO', 'RIC', 'ALO'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'NOR', 'HAM', 'RUS', 'PIA', 'ALO', 'MAG', 'STR', 'HUL', 'RIC',
       'GAS', 'TSU', 'OCO', 'BOT', 'ZHO', 'PER', 'SAI', 'ALB'],
      dtype='object', name='Driver')
Index(['LEC', 'NOR', 'PER', 'VER', 'PIA', 'RUS', 'HAM', 'SAI', 'GAS', 'OCO',
       'TSU', 'HUL', 'ALO', 'ZHO', 'RIC', 'MAG', 'BOT', 'ALB', 'STR', 'SAR'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['VER', 'RUS', 'NOR', 'SAI', 'LEC', 'PIA', 'HAM', 'PER', 'HUL', 'GAS',
       'MAG', 'ZHO', 'RIC', 'OCO', 'TSU', 'STR', 'ALO', 'ALB', 'BOT', 'SAR'],
      dtype='object', name='Driver')
Index(['HAM', 'NOR', 'RUS', 'PIA', 'VER', 'SAI', 'LEC', 'STR', 'HUL', 'ALO',
       'ZHO', 'PER', 'TSU', 'ALB', 'MAG', 'SAR', 'RIC', 'OCO', 'BOT'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Index(['RUS', 'LEC', 'PER', 'HAM', 'PIA', 'NOR', 'VER', 'SAI', 'ALO', 'RIC',
       'HUL', 'STR', 'TSU', 'OCO', 'ALB', 'SAR', 'ZHO', 'MAG', 'BOT', 'GAS'],
      dtype='object', name='Driver')
Index(['HAM', 'RUS', 'LEC', 'NOR', 'PIA', 'VER', 'PER', 'SAI', 'RIC', 'SAR',
       'ALB', 'ALO', 'TSU', 'OCO', 'MAG', 'STR', 'GAS', 'BOT', 'HUL'],
      dtype='object', name='Driver')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_7730/647462274.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy