In [1]:
import pandas as pd
import numpy as np
import time
import itertools
import datetime
import pandas_gbq
import matplotlib.pyplot as plt
from datetime import *
from datetime import datetime, timedelta, date
from pathlib import Path
from zipfile import ZipFile
import urllib
from PIL import Image
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
# Standard plotly imports
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import requests
import json
project_id = "perceptive-ivy-290216"

In [2]:
# Race

In [3]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_race`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_race = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [37]:
racing='Qatar Grand Prix'

In [38]:
df_bq_race=df_bq2_race[(df_bq2_race["GP"]==racing)&(df_bq2_race["Year"]==2025)]
GP_race=df_bq_race
GP_race["DriverNumber"]=GP_race["DriverNumber"].astype(int)
year_race=GP_race['Year'].iloc[0]
gp_race=GP_race['GP'].iloc[0]
GP_race.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/756652593.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
1,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,None,,14.0,14,20.0,NaT,NaT,NaT,0 days 00:00:03.283000,Lapped,0.0,2025,Qatar Grand Prix
3,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,16.0,16,9.0,NaT,NaT,NaT,0 days 00:00:04.941000,Lapped,0.0,2025,Qatar Grand Prix
5,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,7.0,7,8.0,NaT,NaT,NaT,0 days 00:00:54.045000,Finished,6.0,2025,Qatar Grand Prix
7,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,17.0,17,18.0,NaT,NaT,NaT,NaT,Retired,0.0,2025,Qatar Grand Prix
9,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,https://media.formula1.com/d_driver_fallback_i...,,12.0,12,17.0,NaT,NaT,NaT,0 days 00:01:17.730000,Finished,0.0,2025,Qatar Grand Prix

In [39]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="TSU":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [40]:
GP_race['Color'] = GP_race['Abbreviation'].apply(driver_color)
GP_race.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/1190466171.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
1,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,None,,14.0,14,20.0,NaT,NaT,NaT,0 days 00:00:03.283000,Lapped,0.0,2025,Qatar Grand Prix,#0093cc
3,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,16.0,16,9.0,NaT,NaT,NaT,0 days 00:00:04.941000,Lapped,0.0,2025,Qatar Grand Prix,#0093cc
5,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,7.0,7,8.0,NaT,NaT,NaT,0 days 00:00:54.045000,Finished,6.0,2025,Qatar Grand Prix,#229971
7,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,17.0,17,18.0,NaT,NaT,NaT,NaT,Retired,0.0,2025,Qatar Grand Prix,#229971
9,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,https://media.formula1.com/d_driver_fallback_i...,,12.0,12,17.0,NaT,NaT,NaT,0 days 00:01:17.730000,Finished,0.0,2025,Qatar Grand Prix,#E80020

In [41]:
Fast_Laps_Race=GP_race[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])

In [47]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_Race.columns},
  cells=dict(
    values=Fast_Laps_Race.T.values,
    fill_color=[Fast_Laps_Race.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )

# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Race Results".format(year_race,gp_race),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=20)),
    xaxis = dict(tickfont = dict(size=20)),
    font=dict(
        family="PT Sans Narrow",
        size=15,
        color="Black"
    ),
    height=1000,
    width=950,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [48]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Results/{}/{} {} Race Results.html".format(year_race,year_race,gp_race),full_html=False, include_plotlyjs='cdn')

In [14]:
#Multi Race Plot

In [12]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="TSU":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [13]:
#2025
race_multi=["Japanese Grand Prix","Bahrain Grand Prix","Saudi Arabian Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Spanish Grand Prix","Canadian Grand Prix","Austrian Grand Prix","British Grand Prix","Belgian Grand Prix","Hungarian Grand Prix","Dutch Grand Prix","Italian Grand Prix","Azerbaijan Grand Prix","Singapore Grand Prix","United States Grand Prix","Mexico City Grand Prix","São Paulo Grand Prix"]
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2025
for i in race_multi:
    df_bq_race=df_bq2_race[(df_bq2_race["GP"]==i)&(df_bq2_race["Year"]==year_multi)]
    GP_race=df_bq_race
    GP_race["DriverNumber"]=GP_race["DriverNumber"].astype(int)
    year_race=GP_race['Year'].iloc[0]
    gp_race=GP_race['GP'].iloc[0]
    GP_race['Color'] = GP_race['Abbreviation'].apply(driver_color)
    Fast_Laps_Race=GP_race[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])
    import plotly.graph_objects as go

    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_Race.columns},
    cells=dict(
        values=Fast_Laps_Race.T.values,
        fill_color=[Fast_Laps_Race.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )
    fig.update_layout(
        title="{} {} Race Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=20)),
        xaxis = dict(tickfont = dict(size=20)),
        font=dict(
            family="PT Sans Narrow",
            size=15,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Race Results/{}/{} {} Race Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/2403931755.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
# Qualy

In [49]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_qualifying`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_qualy = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [50]:
df_bq_qualy=df_bq2_qualy[(df_bq2_qualy["GP"]==racing)&(df_bq2_qualy["Year"]==2025)]
GP_qualy=df_bq_qualy
# GP["LapNumber"]=GP["LapNumber"].astype(int)
# GP=GP.sort_values(['Driver','LapNumber'])
GP_qualy["DriverNumber"]=GP_qualy["DriverNumber"].astype(int)
year_qualy=GP_qualy['Year'].iloc[0]
gp_qualy=GP_qualy['GP'].iloc[0]
GP_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/5941125.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
1,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,9.0,,NaN,0 days 00:01:20.681000,0 days 00:01:20.324000,0 days 00:01:20.477000,NaT,,NaN,2025,Qatar Grand Prix
3,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,None,,20.0,,NaN,0 days 00:01:21.137000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix
5,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,8.0,,NaN,0 days 00:01:20.598000,0 days 00:01:20.219000,0 days 00:01:20.418000,NaT,,NaN,2025,Qatar Grand Prix
7,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,19.0,,NaN,0 days 00:01:21.058000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix
9,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,10.0,,NaN,0 days 00:01:20.564000,0 days 00:01:20.343000,0 days 00:01:20.561000,NaT,,NaN,2025,Qatar Grand Prix

In [51]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="TSU":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [52]:
GP_qualy['Color'] = GP_qualy['Abbreviation'].apply(driver_color)
GP_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/1606116537.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
1,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,9.0,,NaN,0 days 00:01:20.681000,0 days 00:01:20.324000,0 days 00:01:20.477000,NaT,,NaN,2025,Qatar Grand Prix,#0093cc
3,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,None,,20.0,,NaN,0 days 00:01:21.137000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix,#0093cc
5,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,8.0,,NaN,0 days 00:01:20.598000,0 days 00:01:20.219000,0 days 00:01:20.418000,NaT,,NaN,2025,Qatar Grand Prix,#229971
7,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,19.0,,NaN,0 days 00:01:21.058000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix,#229971
9,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,10.0,,NaN,0 days 00:01:20.564000,0 days 00:01:20.343000,0 days 00:01:20.561000,NaT,,NaN,2025,Qatar Grand Prix,#E80020

In [53]:
Fast_Laps_Qualy=GP_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])

In [54]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_Qualy.columns},
  cells=dict(
    values=Fast_Laps_Qualy.T.values,
    fill_color=[Fast_Laps_Qualy.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )

# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Qualifying Results".format(year_qualy,gp_qualy),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    height=1000,
    width=1000,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [55]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Qualy Results/{}/{} {} Qualifying Results.html".format(year_qualy,year_qualy,gp_qualy),full_html=False, include_plotlyjs='cdn')

In [22]:
#Multi Race Plot

In [20]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3860C6"
    elif driver =="TSU":
        return "#3860C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [21]:
#2025
race_multi=["Japanese Grand Prix","Bahrain Grand Prix","Saudi Arabian Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Spanish Grand Prix","Canadian Grand Prix","Austrian Grand Prix","British Grand Prix","Belgian Grand Prix","Hungarian Grand Prix","Dutch Grand Prix","Italian Grand Prix","Azerbaijan Grand Prix","Singapore Grand Prix","United States Grand Prix","Mexico City Grand Prix","São Paulo Grand Prix"]
#2024
# race_multi=["Bahrain Grand Prix", "Saudi Arabian Grand Prix", "Australian Grand Prix", "Japanese Grand Prix","Chinese Grand Prix","Miami Grand Prix","Emilia Romagna Grand Prix","Monaco Grand Prix","Canadian Grand Prix","Spanish Grand Prix","Austrian Grand Prix","British Grand Prix","Hungarian Grand Prix","Belgian Grand Prix"]
#2023
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Las Vegas Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Qatar Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2022
# race_multi=["Abu Dhabi Grand Prix","Australian Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Canadian Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Japanese Grand Prix","Mexico City Grand Prix","Miami Grand Prix","Monaco Grand Prix","Saudi Arabian Grand Prix","Singapore Grand Prix","Spanish Grand Prix","São Paulo Grand Prix","United States Grand Prix"]
#2021
# race_multi=["Abu Dhabi Grand Prix","Austrian Grand Prix","Azerbaijan Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Dutch Grand Prix","Emilia Romagna Grand Prix","French Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Mexico City Grand Prix","Monaco Grand Prix","Portuguese Grand Prix","Qatar Grand Prix","Russian Grand Prix","Saudi Arabian Grand Prix","Spanish Grand Prix","Styrian Grand Prix","São Paulo Grand Prix","Turkish Grand Prix","United States Grand Prix"]
#2020
# race_multi=["70th Anniversary Grand Prix","Abu Dhabi Grand Prix","Austrian Grand Prix","Bahrain Grand Prix","Belgian Grand Prix","British Grand Prix","Eifel Grand Prix","Emilia Romagna Grand Prix","Hungarian Grand Prix","Italian Grand Prix","Portuguese Grand Prix","Russian Grand Prix","Sakhir Grand Prix","Spanish Grand Prix","Styrian Grand Prix","Turkish Grand Prix","Tuscan Grand Prix"]

year_multi=2025
for i in race_multi:

    df_bq_qualy=df_bq2_qualy[(df_bq2_qualy["GP"]==i)&(df_bq2_qualy["Year"]==year_multi)]
    GP_qualy=df_bq_qualy
    GP_qualy["DriverNumber"]=GP_qualy["DriverNumber"].astype(int)
    year_qualy=GP_qualy['Year'].iloc[0]
    gp_qualy=GP_qualy['GP'].iloc[0]
    GP_qualy['Color'] = GP_qualy['Abbreviation'].apply(driver_color)
    GP_qualy.head()
    Fast_Laps_Qualy=GP_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])
    import plotly.graph_objects as go

    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_Qualy.columns},
    cells=dict(
        values=Fast_Laps_Qualy.T.values,
        fill_color=[Fast_Laps_Qualy.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )

    fig.update_layout(
        title="{} {} Qualifying Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Qualy Results/{}/{} {} Qualifying Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:19: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/3831585235.py:22: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [16]:
#Sprint Race

In [18]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_sprint`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_sprint = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [23]:
racing_sprint='Qatar Grand Prix'

In [24]:
df_bq_sprint=df_bq2_sprint[(df_bq2_sprint["GP"]==racing_sprint)&(df_bq2_sprint["Year"]==2025)]
GP_sprint=df_bq_sprint
GP_sprint["DriverNumber"]=GP_sprint["DriverNumber"].astype(int)
year_sprint=GP_sprint['Year'].iloc[0]
gp_sprint=GP_sprint['GP'].iloc[0]
GP_sprint.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/3853191153.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
0,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,18.0,18,19.0,NaT,NaT,NaT,0 days 00:01:09.534000,Finished,0.0,2025,Qatar Grand Prix
1,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,None,,20.0,20,20.0,NaT,NaT,NaT,0 days 00:01:20.804000,Finished,0.0,2025,Qatar Grand Prix
2,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,7.0,7,4.0,NaT,NaT,NaT,0 days 00:00:24.556000,Finished,2.0,2025,Qatar Grand Prix
3,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,19.0,19,17.0,NaT,NaT,NaT,0 days 00:01:17.960000,Finished,0.0,2025,Qatar Grand Prix
4,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,13.0,13,9.0,NaT,NaT,NaT,0 days 00:00:35.182000,Finished,0.0,2025,Qatar Grand Prix

In [25]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="TSU":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [26]:
GP_sprint['Color'] = GP_sprint['Abbreviation'].apply(driver_color)
GP_sprint.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/4122059520.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
0,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,18.0,18,19.0,NaT,NaT,NaT,0 days 00:01:09.534000,Finished,0.0,2025,Qatar Grand Prix,#0093cc
1,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,None,,20.0,20,20.0,NaT,NaT,NaT,0 days 00:01:20.804000,Finished,0.0,2025,Qatar Grand Prix,#0093cc
2,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,7.0,7,4.0,NaT,NaT,NaT,0 days 00:00:24.556000,Finished,2.0,2025,Qatar Grand Prix,#229971
3,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,19.0,19,17.0,NaT,NaT,NaT,0 days 00:01:17.960000,Finished,0.0,2025,Qatar Grand Prix,#229971
4,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,13.0,13,9.0,NaT,NaT,NaT,0 days 00:00:35.182000,Finished,0.0,2025,Qatar Grand Prix,#E80020

In [27]:
Fast_Laps_sprint=GP_sprint[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])

In [28]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_sprint.columns},
  cells=dict(
    values=Fast_Laps_sprint.T.values,
    fill_color=[Fast_Laps_sprint.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )


# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Sprint Race Results".format(year_sprint,gp_sprint),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    height=1000,
    width=1050,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [29]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Results/{}/{} {} Sprint Race Results.html".format(year_sprint,year_sprint,gp_sprint),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi GP Plot

In [ ]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3860C6"
    elif driver =="TSU":
        return "#3860C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [ ]:
#2024
# race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']
#2022
# race_multi=['Austrian Grand Prix','Emilia Romagna Grand Prix','São Paulo Grand Prix']
#2021
# race_multi=['British Grand Prix','Italian Grand Prix','São Paulo Grand Prix']

year_multi=2025
for i in race_multi:
    df_bq_sprint=df_bq2_sprint[(df_bq2_sprint["GP"]==i)&(df_bq2_sprint["Year"]==year_multi)]
    GP_sprint=df_bq_sprint
    GP_sprint["DriverNumber"]=GP_sprint["DriverNumber"].astype(int)
    year_sprint=GP_sprint['Year'].iloc[0]
    gp_sprint=GP_sprint['GP'].iloc[0]
    GP_sprint['Color'] = GP_sprint['Abbreviation'].apply(driver_color)
    Fast_Laps_sprint=GP_sprint[["Year","GP",'TeamName','FullName','GridPosition','Position','ClassifiedPosition','Status','Time','Points','Color']].sort_values(by=['Position'])
    import plotly.graph_objects as go

    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_sprint.columns},
    cells=dict(
        values=Fast_Laps_sprint.T.values,
        fill_color=[Fast_Laps_sprint.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )
    fig.update_layout(
        title="{} {} Sprint Race Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Race Results/{}/{} {} Sprint Race Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:14: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_6889/3287626911.py:17: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [26]:
# Sprint Qualy

In [30]:
#Change the date to the previous day
query = """
SELECT
*
FROM
`perceptive-ivy-290216.f1_api.results_sprint_qualifying`
# WHERE Year=2024 AND GP="Austrian Grand Prix"
"""
project_id = "perceptive-ivy-290216"
df_bq2_sprint_qualy = pandas_gbq.read_gbq(query, project_id=project_id, dialect='standard')

Downloading: 100%|██████████|

In [31]:
df_bq_sprint_qualy=df_bq2_sprint_qualy[(df_bq2_sprint_qualy["GP"]==racing_sprint)&(df_bq2_sprint_qualy["Year"]==2025)]
GP_sprint_qualy=df_bq_sprint_qualy
# GP["LapNumber"]=GP["LapNumber"].astype(int)
# GP=GP.sort_values(['Driver','LapNumber'])
GP_sprint_qualy["DriverNumber"]=GP_sprint_qualy["DriverNumber"].astype(int)
year_sprint_qualy=GP_sprint_qualy['Year'].iloc[0]
gp_sprint_qualy=GP_sprint_qualy['GP'].iloc[0]
GP_sprint_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/3441572808.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP
0,10,P GASLY,GAS,,Alpine,00A1E8,,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,19.0,,NaN,0 days 00:01:22.112000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix
1,43,F COLAPINTO,COL,,Alpine,00A1E8,,Franco,Colapinto,Franco Colapinto,None,,20.0,,NaN,0 days 00:01:22.364000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix
2,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,4.0,,NaN,0 days 00:01:21.276000,0 days 00:01:21.272000,0 days 00:01:20.450000,NaT,,NaN,2025,Qatar Grand Prix
3,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,16.0,,NaN,0 days 00:01:21.807000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix
4,16,C LECLERC,LEC,,Ferrari,ED1131,,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,9.0,,NaN,0 days 00:01:21.636000,0 days 00:01:21.190000,0 days 00:01:20.622000,NaT,,NaN,2025,Qatar Grand Prix

In [32]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="TSU":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [33]:
GP_sprint_qualy['Color'] = GP_sprint_qualy['Abbreviation'].apply(driver_color)
GP_sprint_qualy.head()

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_38469/948559039.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,HeadshotUrl,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Year,GP,Color
0,10,P GASLY,GAS,,Alpine,00A1E8,,Pierre,Gasly,Pierre Gasly,https://media.formula1.com/d_driver_fallback_i...,,19.0,,NaN,0 days 00:01:22.112000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix,#0093cc
1,43,F COLAPINTO,COL,,Alpine,00A1E8,,Franco,Colapinto,Franco Colapinto,None,,20.0,,NaN,0 days 00:01:22.364000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix,#0093cc
2,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,https://media.formula1.com/d_driver_fallback_i...,,4.0,,NaN,0 days 00:01:21.276000,0 days 00:01:21.272000,0 days 00:01:20.450000,NaT,,NaN,2025,Qatar Grand Prix,#229971
3,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,https://media.formula1.com/d_driver_fallback_i...,,16.0,,NaN,0 days 00:01:21.807000,NaT,NaT,NaT,,NaN,2025,Qatar Grand Prix,#229971
4,16,C LECLERC,LEC,,Ferrari,ED1131,,Charles,Leclerc,Charles Leclerc,https://media.formula1.com/d_driver_fallback_i...,,9.0,,NaN,0 days 00:01:21.636000,0 days 00:01:21.190000,0 days 00:01:20.622000,NaT,,NaN,2025,Qatar Grand Prix,#E80020

In [34]:
Fast_Laps_sprint_qualy=GP_sprint_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])

In [35]:
import plotly.graph_objects as go

fig = go.Figure(go.Table
 (header={"values": Fast_Laps_sprint_qualy.columns},
  cells=dict(
    values=Fast_Laps_sprint_qualy.T.values,
    fill_color=[Fast_Laps_sprint_qualy.Color],
    align='center', font=dict(color='white', size=12)
    ))
 )

# fig.update_layout(
#     updatemenus=[
#         {
#             "buttons": [
#                 {
#                     "label": c,
#                     "method": "update",
#                     "args": [
#                         {
#                             "cells": {
#                                 "values": Fast_Laps.T.values
#                                 if c == "All"
#                                 else Fast_Laps.loc[Fast_Laps["TeamName"].eq(c)].T.values
#                             }
#                         }
#                     ],
#                 }
#                 for c in ["All"] + Fast_Laps["TeamName"].unique().tolist()
#             ]
#         }
#     ]
# )

fig.update_layout(
    title="{} {} Sprint Qualifying Results".format(year_sprint_qualy,gp_sprint_qualy),
        title_x=0.5,
        # template="plotly_dark",

    yaxis = dict(tickfont = dict(size=15)),
    xaxis = dict(tickfont = dict(size=15)),
    font=dict(
        family="PT Sans Narrow",
        size=14,
        color="Black"
    ),
    height=1000,
    width=1050,
    title_font_family="PT Sans Narrow",
    margin=dict(l=5, r=5, t=35, b=5),
)

fig.show()

In [36]:
fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Qualy Results/{}/{} {} Sprint Qualifying Results.html".format(year_sprint_qualy,year_sprint_qualy,gp_sprint_qualy),full_html=False, include_plotlyjs='cdn')

In [ ]:
#Multi GP Plot

In [60]:
#2025
def driver_color(driver):
    #RED BULL
    if driver =="VER":
        return "#3671C6"
    elif driver =="TSU":
        return "#3671C6"       
    #MCLAREN
    elif driver =="NOR":
        return '#FF8000'
    elif driver =="PIA":
        return '#FF8000'
    #FERRARI
    elif driver =="LEC":
        return '#E80020'
    elif driver =="HAM":
        return '#E80020'
    elif driver =="ZHO":
        return '#E80020'    
    #MERCEDES
    elif driver =="ANT":
        return '#27F4D2'
    elif driver =="RUS":
        return '#27F4D2'
    elif driver =="BOT":
        return '#27F4D2'    
    #ASTON
    elif driver =="ALO":
        return '#229971'
    elif driver =="STR":
        return '#229971'
    #ALPINE
    elif driver =="GAS":
        return '#0093cc'
    elif driver =="DOO":
        return '#0093cc'
    elif driver =="COL":
        return '#0093cc'
    #HAAS
    elif driver =="BEA":
        return '#B6BABD'
    elif driver =="OCO":
        return '#B6BABD'
    #SAUBER
    elif driver =="HUL":
        return '#52e252'
    elif driver =="BOR":
        return '#52e252'
    #WILLIAMS
    elif driver =="ALB":
        return '#64C4FF'
    elif driver =="SAI":
        return '#64C4FF'
    #RACING BULLS   
    elif driver =="LAW":
        return '#6692FF'
    elif driver =="HAD":
        return '#6692FF'   
    else:
        return '#3860C6'

In [61]:
#2025
race_multi=['Miami Grand Prix','Belgian Grand Prix','United States Grand Prix','São Paulo Grand Prix']
#2024
# race_multi=['Austrian Grand Prix','Miami Grand Prix','Chinese Grand Prix']
#2023
# race_multi=['Austrian Grand Prix','Azerbaijan Grand Prix','Belgian Grand Prix','Qatar Grand Prix','São Paulo Grand Prix','United States Grand Prix']

year_multi=2025
for i in race_multi:
    df_bq_sprint_qualy=df_bq2_sprint_qualy[(df_bq2_sprint_qualy["GP"]==i)&(df_bq2_sprint_qualy["Year"]==year_multi)]
    GP_sprint_qualy=df_bq_sprint_qualy
    GP_sprint_qualy["DriverNumber"]=GP_sprint_qualy["DriverNumber"].astype(int)
    year_sprint_qualy=GP_sprint_qualy['Year'].iloc[0]
    gp_sprint_qualy=GP_sprint_qualy['GP'].iloc[0]
    GP_sprint_qualy['Color'] = GP_sprint_qualy['Abbreviation'].apply(driver_color)
    Fast_Laps_sprint_qualy=GP_sprint_qualy[["Year","GP",'TeamName','FullName','Q1','Q2','Q3','Position','Color']].sort_values(by=['Position'])
    fig = go.Figure(go.Table
    (header={"values": Fast_Laps_sprint_qualy.columns},
    cells=dict(
        values=Fast_Laps_sprint_qualy.T.values,
        fill_color=[Fast_Laps_sprint_qualy.Color],
        align='center', font=dict(color='white', size=12)
        ))
    )

    fig.update_layout(
        title="{} {} Sprint Qualifying Results".format(year_multi,i),
            title_x=0.5,
            # template="plotly_dark",

        yaxis = dict(tickfont = dict(size=15)),
        xaxis = dict(tickfont = dict(size=15)),
        font=dict(
            family="PT Sans Narrow",
            size=14,
            color="Black"
        ),
        height=1000,
        width=1050,
        title_font_family="PT Sans Narrow",
        margin=dict(l=5, r=5, t=35, b=5),
    )
    fig.write_html("/Users/rdesh723/statpulse-html/plots/Sprint Qualy Results/{}/{} {} Sprint Qualifying Results.html".format(year_multi,year_multi,i),full_html=False, include_plotlyjs='cdn')

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:12: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/var/folders/x_/b65sxrpx6737wtqnt0ctv71w0000gn/T/ipykernel_58008/1216862801.py:15: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy